### ISSUE TITLE
Bar - Line graph - Need help.

### ISSUE THREAD

**Issue by blacknlight** [gitbrent/PptxGenJS#100]
I am trying to create Bar - line graph using 2 different Data set for same period, but I am getting different Y axis values. Is it possible to create such graph? If yes, then How to create such Bar - line Graph?

**Comment by gitbrent** [comment]
Hi @blacknlight ,

The library doesn't support any kind of mixed-graph output - only what is shown in the `examples/pptxgenjs-demo.html` demo.

**Comment by blacknlight** [comment]
Thanks for the help.

But I tried giving same X and Y co-ordinates to bar and line graph, so now I am getting mixed graph. And it  was working partially. Y-axis series was broken by different interval. But then after playing with it for some time, I changed "c:gapWidth" value in PPTxGen.js file and set it manually to a fixed value and voila.. I got what I wanted.

**Comment by gitbrent** [comment]
@blacknlight ,

That's an awesome way to create a mixed graph - overlay them. :-)

Sorry to hear you had to edit the code though - using the `barGapWidthPct` [chart option](https://github.com/gitbrent/PptxGenJS#chart-data-options) wouldn't work?

**Comment by blacknlight** [comment]
@gitbrent 

barGapWidthPct is used to define the width of the bars in bar graph. What I wanted was to split the series on Y axis in similar manner. e.g. I was applying two different data sets for Bar and line graph. So Bar graph was starting lets say at 500 and Y axis values were like 500, 600, 700 and For line graph it was starting at 500 that was correct but Y axis series for Line graph was like 500, 750, 1000. So to adjust the same Y axis series, I had to use "c:gapWidth" property.
