### ISSUE TITLE
Slide Master, vertical alignment of SlideNumber element

### ISSUE THREAD

**Issue by kramsram** [gitbrent/PptxGenJS#1000]
```javascript
let slideNumber = {
	color: FOOTER_FONT_COLOR,
	x: WIDE_SLIDE_WIDTH - SLIDE_NUMBER_WIDTH,
	y: SLIDE_FOOTER_TOP,
	w: SLIDE_NUMBER_WIDTH,
	h: SLIDE_NUMBER_HEIGHT,
	fontFace: SLIDE_FONT_FACE,
	fontSize: BODY_FONT_SIZE,
	valign: "bottom",
	align: "right",
};
```
I have the above for the slideNumber in my slide master definition. All the attributes work except for the valign attribute. The slide number is always "top" aligned. Cannot get it to align t the middle.

What am I missing? or could this be a bug in the slideNumber element?

**Comment by gitbrent** [comment]
@kramsram - thanks for reporting this.

The `valign` prop was not working. It'll be fixed in the next release.
