### ISSUE TITLE
html转成幻灯片后，添加图片报错 ERROR: addImage() requires either 'data' or 'path' parameter!

### ISSUE THREAD

**Issue by nicehive** [gitbrent/PptxGenJS#1001]

**Comment by gitbrent** [comment]
Please review documentation and demos:

# [Image API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-images/)

# [Image Demo](https://gitbrent.github.io/PptxGenJS/demo/browser/index.html#images)
