### ISSUE TITLE
Am I using the file compression correctly?

### ISSUE THREAD

**Issue by COLTstreet** [gitbrent/PptxGenJS#1009]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.8.0     ]

I'm generating a deck that has a lot of very busy data tables, and the deck is 113 slides. After saving the file out into File Explorer, the size is about 91kb. I saw there was a compression option but it doesn't seem to do anything when I set the flag to true, because the size of the file doesn't change. I'm just wondering if I'm doing something wrong?

This is the code I'm using to write the file out and add compression.

`
pres.writeFile({ fileName: 'Small-Store-PPT', compression: true });
`

Thank you for your feedback!

**Comment by gitbrent** [comment]
Looks correct to me, perhaps compression benefits aren't applicable to your particular data?
