### ISSUE TITLE
Vertical line chart

### ISSUE THREAD

**Issue by Shankar000536** [gitbrent/PptxGenJS#101]
Hi,

Is there any way to create the Vertical line chart? If yes how can i create.

Thanks,
Shankar

**Comment by gitbrent** [comment]
Hi @Shankar000536 ,

No, there is no option to create a vertical line chart per se.

You can try both minMax/maxMin values for the `catAxisOrientation` and `valAxisOrientation` options to see if that will "turn" the lines the way you'd like...
