### ISSUE TITLE
hyperlink not work when opened at wps

### ISSUE THREAD

**Issue by lifuzhao100** [gitbrent/PptxGenJS#1014]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   ^3.8.0   ]

Please specify what version(s) of PowerPoint you are targeting: [   wps@latest   ]

### Expected / Desired Behavior / Question
hyperlink not work when opened at wps(wps is a Chinese version of MS Office),so should pptxgenjs be compatible with wps?btw:It works well at MS Office
 

### Observed Behavior
I read slide.xml generated by wps, found that when adding hyperlink, <a:hlinkClick> tag should have an action attribute and its value should be ppaction://hlinkfile
```javascript
else if (opts.hyperlink.url) {
  //runProps += '<a:uFill>'+ genXmlColorSelection('0000FF') +'</a:uFill>'; // Breaks PPT2010! (Issue#74)
  runProps += "<a:hlinkClick r:id=\"rId" + opts.hyperlink._rId + "\" invalidUrl=\"\" action=\"\" tgtFrame=\"\" tooltip=\"" + (opts.hyperlink.tooltip ? encodeXmlEntities(opts.hyperlink.tooltip) : '') + "\" history=\"1\" highlightClick=\"0\" endSnd=\"0\"" + (opts.color ? '>' : '/>');
}
```

**Comment by gitbrent** [comment]
What is WPS are how did you come across this as a solution? I only found 36 references on the entire web for "ppaction://hlinkfile"...
