### ISSUE TITLE
Ability to specify Chart Area fill color 

### ISSUE THREAD

**Issue by hvstaden** [gitbrent/PptxGenJS#1015]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

pptxgenjs: [3.8.0]
PowerPoint: [2108]

### Expected / Desired Behavior / Question
At present, the `IChartPropsBase `interface contains property `fill`, which sets the Plot Area background color of a chart.

**It would be great if the Chart Area fill color could be specified (hope I'm not missing something obvious).**

Visually what I mean by the above:

**Left Image**: At present you can specify the Plot Area fill color, but not the Chart Area fill color.
**Right Image**: Example of chart with Chart Area fill color set.

![image](https://user-images.githubusercontent.com/92735933/137753011-40bb1adb-4300-4ced-bcaf-acb209133a08.png)

**Comment by CharlesMoone** [comment]
what's going on with this feature?
i also need this ability

**Comment by CharlesMoone** [comment]
maybe can use sharp or image instead it.

**Comment by CharlesMoone** [comment]
https://github.com/gitbrent/PptxGenJS/blob/master/demos/modules/demo_chart.mjs#L183
like this. use `slide.addText(".", { x: 0.5, y: 3.8, w: 6.0, h: 3.5, fill: { color: "F1F1F1" }, color: "F1F1F1" });`

**Comment by gitbrent** [comment]
FYI: Allowing this prop to specify Plot Area or Chart Area will be a breaking change

**Comment by gitbrent** [comment]
Starting with v3.11.0 - new syntax for Plot Area and Chart Area

```javascript
let chartProps1 = {
    chartArea: { fill: { color: "F1F1F1" } },
    plotArea: { fill: { color: "F1C1C1" } },
};

let chartProps2 = {
    chartArea: { border: { pt: "2", color: "FF0000" }, fill: { color: "F1F1F1", transparency: 50 } },
    plotArea: { border: { pt: "2", color: "FF0000" }, fill: { color: "F1C1C1", transparency: 50 } },
};
```

![Screen Shot 2022-05-15 at 16 13 37](https://user-images.githubusercontent.com/7218970/168494056-a4050f3c-80f1-4697-8445-61fa0e61ce44.png)

**Comment by gitbrent** [comment]
Thanks for the request @hvstaden and thanks @CharlesMoone for the reminder

**Comment by hvstaden** [comment]
Perfect, thanks a lot!

**Comment by katiehuang1221** [comment]
Hi! Thank you for the new feature! I've installed pptextgenjs@3.11.0, but my chart still has blank background even with chartArea/plotArea specified. I can't figure out why...I'm using the example code in React
`let optsChartLine2 = {
          x: 7,
          y: 0.6,
          w: "45%",
          h: 3,
          plotArea: { fill: { color: "D1E1F1" } },
      
          chartColors: ["0088CC", "99FFCC"],
          chartColorsOpacity: 25,
          valAxisLabelRotate: 5,
          dataBorder: { pt: 2, color: "FFFFFF" },
          showValue: false,
          barGrouping: "stacked",
        };
        slide4.addChart(pres.ChartType.area, arrDataTimeline2ser, optsChartLine2);`

**Comment by artemkov** [comment]
Hello, 
can you also add transparency and line style for border 

![image](https://user-images.githubusercontent.com/23265462/204895772-cc1baef2-6ffb-466f-aff4-f2caf176ebaa.png)
