### ISSUE TITLE
Cant able to fetch value of rich text area with dynamic formatting in the pptx file

### ISSUE THREAD

**Issue by mohammedadnanalam** [gitbrent/PptxGenJS#1018]
Hi @gitbrent 

i was using your library for fetching data from salesforce object and creating pptx file, i hit road blocker when i tried to show rich text area which is store in html format in backend. When i am calling that field and adding in master slide, the content is showing but the formatting is not visible with it.

I have attached image for reference. Hoping your reply as soon as possible.

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/89831860/138824544-bfb4b7cd-2e37-4d47-93d9-761791f7e802.png)

**Comment by gitbrent** [comment]
The library doesn't auto-convert HTML to powerpoint formatting, you need to do that yourself.
