### ISSUE TITLE
Adding charts and media together is causing a pptx error, and repair is needed.

### ISSUE THREAD

**Issue by mvecsernyes** [gitbrent/PptxGenJS#1020]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.9.0-beta     ]

Please specify what version(s) of PowerPoint you are targeting: [     PowerPoint 2016    ]

### Expected / Desired Behavior / Question
*addChart and addMedia(video type) can be used together without repairing the generated file*

### Observed Behavior
*I have not looked into, but when I use addMedia (video type) and addChart() together PowerPoint needs to repair it*

### Steps to Reproduce
Add the following line to demos/node/demo.js and run `node demo.js`
```
	slide.addChart(pptx.ChartType.bar3d, [
			{
				name: 'Income',
				labels: ['2005', '2006', '2007', '2008', '2009'],
				values: [23.5, 26.2, 30.1, 29.5, 24.6]
			},
			{
				name: 'Expense',
				labels: ['2005', '2006', '2007', '2008', '2009'],
				values: [18.1, 22.8, 23.9, 25.1, 25]
			}
		], {x: 1, y: 3, w: 4, h: 3});
			 
	slide.addMedia({type: "video", path: "video.mp4"});
```

**Comment by gitbrent** [comment]
Thanks for reporting this issue @mvecsernyes !

The code was creating duplicate ref-ID's for charts and media. Fixed in v3.10.0.

```javascript
let pptx = new PptxGenJS();
let slide = pptx.addSlide();

slide.addChart(
    pptx.ChartType.bar3d,
    [
        {
            name: "Income",
            labels: ["2005", "2006", "2007", "2008", "2009"],
            values: [23.5, 26.2, 30.1, 29.5, 24.6],
        },
        {
            name: "Expense",
            labels: ["2005", "2006", "2007", "2008", "2009"],
            values: [18.1, 22.8, 23.9, 25.1, 25],
        },
    ],
    { x: 1, y: 3, w: 4, h: 3 }
);

slide.addMedia({ type: "video", path: "video.mp4" });

slide.addImage({ x: 4.4, y: 1.05, w: 1.2, h: 1.2, path: "https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@latest/demos/common/images/trippy.gif", altText: "this is a gif" });

pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```

![Screen Shot 2022-02-26 at 13 06 12](https://user-images.githubusercontent.com/7218970/155855990-cdd2ec0a-6f88-4d11-930b-2f1abb47699e.png)
