### ISSUE TITLE
ReferenceError: JSZip is not defined

### ISSUE THREAD

**Issue by JorgeKunrath** [gitbrent/PptxGenJS#1026]
I'm getting this error when running a app in React (windows machine)

![image](https://user-images.githubusercontent.com/54911848/140536081-fae7ae37-f845-435b-a3f3-26c4600cc01d.png)

I see that this was an issue in the past #638 , but I'm running it in 3.8.0, so should be working I guess

I was able to run the project again by importing the `jszip` everywhere I was importing `pptxgenjs`, but this seems as a workaround to me, so I'm letting you'll know just in case we have a proper fix for that.

----

### Category
- Enhancement
- Bug

### Version

Please specify what version of the library you are using: [  ^3.8.0  ]

Please specify what version(s) of PowerPoint you are targeting: [  I actually don't know. This was used in one part of the project that I have no knowledge, but was affecting the loading of the screen even outside there.  ]

**Comment by gitbrent** [comment]
Thanks for the details. I'm not sure there's any other way to design the library other than to import everywhere as you said...
