### ISSUE TITLE
How to get x,y axis of pixel value in PPT while viewing?

### ISSUE THREAD

**Issue by bannarisoftwares** [gitbrent/PptxGenJS#1029]
We can add textbox,images by using x,y values. How to get x,y axis of pixel value in PPT while viewing. Like if we click by using mouse someplace on PPT, is it possible to get x,y value of the mouse?

**Comment by gitbrent** [comment]
No, you cannot click to find a location in the PPT app. 

You can find this information by placing an object on a slide in PowerPoint, then viewing its `x` `y` location props.

![Screen Shot 2021-11-13 at 12 03 06](https://user-images.githubusercontent.com/7218970/141654352-5369c606-1877-4fd9-a4a0-f02e85d6ef5e.png)
