### ISSUE TITLE
[QUESTION] How to center a image?

### ISSUE THREAD

**Issue by cheb60** [gitbrent/PptxGenJS#1033]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.8

Please specify what version(s) of PowerPoint you are targeting: 2019 or greater

### Expected / Desired Behavior / Question
I first created a fresh instance of PptxGenJS. After that I added a regular slide. In this slide I want to add an image. The documentation says that I can assign x coordinates to an image. When I set this to 50% the image is aligned from the upper left corner. Can this be calculated from the center of the image?

### Steps to Reproduce
```
// 1. Create a new Presentation
let presentation = new PptxGenJS()

// LAYOUT
presentation.layout = 'LAYOUT_16x9'

// SLIDE 1
let firstSlide = presentation.addSlide()

firstSlide.addImage({
    path: 'https://via.placeholder.com/800',
    w: '3.1',
    h: '3.1',
    x: '50%'
})

presentation.writeFile().then(() => {
    console.log('Powerpoint successfully saved!')
}).catch(error => {
    console.log('There was an error while saving your presentation: ', error.getError())
})
```

I hope to hear from you soon.

**Comment by ReimaFrgos** [comment]
The `x` value is based in the left of the image, not the centre of the image. For this specific case, to place the image in the centre you would need:
```
firstSlide.addImage({
    path: 'https://via.placeholder.com/800',
    w: 3.1,
    h: 3.1,
    x: 3.45
})
```
Formula is:
`(slideWidth - imageWidth) / 2`

**Comment by cheb60** [comment]
Hi ReimaFrgos,

Thank you for giving me your solution. Do you know if there is any way we can change x value based on the center of the image?

Hope to hear from u soon. Thanks!

**Comment by ReimaFrgos** [comment]
@cheb60 positioning is always based on the upper left point of the image, so you will need to use the formula in `x`. You can also do for `y` to get vertical centered.

Your slide dimensions will be constant for you're whole deck, so these can just be declared once.

```
const slideWidth = 10;
const slideHeight = 5.63;
let imageWidth = 3.1;
let imageHeight = 3.1;

firstSlide.addImage({
    path: 'https://via.placeholder.com/800',
    w: imageWidth,
    h: imageHeight,
    x: (slideWidth - imageWidth) / 2,
    y: (slideHeight - imageHeight) / 2
})
```

**Comment by gitbrent** [comment]
Thanks @ReimaFrgos
