### ISSUE TITLE
pptx.shapes method is not working for pptxgenjs verion 3.8.0 and 3.5.0

### ISSUE THREAD

**Issue by kanika1323** [gitbrent/PptxGenJS#1034]
Hi Team,

i am using pptxgenjs version 3.8.0  and i am trying to do below functionality-

1)html to ppt is not working (please provide detail example).
2)i am trying to add shape with text for that  i am using pptx.shapes where it shapes is not recognize by the ppt library.

Could you please help  me out.

**Comment by gitbrent** [comment]
Please see /demos for working examples.

**Comment by kanika1323** [comment]
Your working example is not supporting 3.8.0

**Comment by kanika1323** [comment]
can you please provide me the one example of html to ppt
