### ISSUE TITLE
Add a 'line spacing' option to addText()

### ISSUE THREAD

**Issue by eddyclock** [gitbrent/PptxGenJS#104]
Hi,
May I check if line spacing can be added in the slide.addText? I go though the documentation and cannot find this option.
Thanks in advance.
Eddy

**Comment by eddyclock** [comment]
Hi,
I just modified below code ( as I didn't use Bullet , no conflict found)
It works and thanks .
-----------------------------------------------------------------
_if ( textObj.options.line_spacing ) {
                    strXmlLineSpacing = '<a:lnSpc><a:spcPts val="' + textObj.options.line_spacing + '00"/></a:lnSpc>';
				}
				// OPTION: indent
				if ( textObj.options.indentLevel > 0 ) paragraphPropXml += ' lvl="' + textObj.options.indentLevel + '"';
				paraPropXmlCore = paragraphPropXml;

				// OPTION: bullet
				// NOTE: OOXML uses the unicode character set for Bullets
				// EX: Unicode Character 'BULLET' (U+2022) ==> '<a:buChar char="&#x2022;"/>'
				if ( typeof textObj.options.bullet === 'object' ) {
					if ( textObj.options.bullet.type ) {
						if ( textObj.options.bullet.type.toString().toLowerCase() == "number" ) {
							paragraphPropXml += ' marL="342900" indent="-342900"';
							strXmlBullet = '<a:buSzPct val="100000"/><a:buFont typeface="+mj-lt"/><a:buAutoNum type="arabicPeriod"/>';
						}
					}
					else if ( textObj.options.bullet.code ) {
						var bulletCode = '&#x'+ textObj.options.bullet.code +';';

						// Check value for hex-ness (s/b 4 char hex)
						if ( /^[0-9A-Fa-f]{4}$/.test(textObj.options.bullet.code) == false ) {
							console.warn('Warning: `bullet.code should be a 4-digit hex code (ex: 22AB)`!');
							bulletCode = BULLET_TYPES['DEFAULT'];
						}

						paragraphPropXml += ' marL="342900" indent="-342900"';
						strXmlBullet = '<a:buSzPct val="100000"/><a:buChar char="'+ bulletCode +'"/>';
					}
				}
				// DEPRECATED: old bool value (FIXME:Drop in 2.0)
				else if ( textObj.options.bullet == true ) {
					paragraphPropXml += ' marL="228600" indent="-228600"';
					strXmlBullet = '<a:buSzPct val="100000"/><a:buChar char="'+ BULLET_TYPES['DEFAULT'] +'"/>';
				}

				// Close Paragraph-Properties --------------------
				paragraphPropXml += '>'+ strXmlBullet + strXmlLineSpacing + '</a:pPr>';_

**Comment by gitbrent** [comment]
Hi @eddyclock ,

Thanks for the suggestion and the sample code.

Line spacing is now available for text paragraphs and bullets using `lineSpacing`.  The README and examples have been updated as well.

![screen shot 2017-07-06 at 22 29 50](https://user-images.githubusercontent.com/7218970/27942574-89cd6f46-629d-11e7-8509-b621c3a79ed1.png)

**Comment by eddyclock** [comment]
Thanks
