### ISSUE TITLE
Is it possible to use an `id` for a slide in a `hyperlink`?

### ISSUE THREAD

**Issue by peckomingo** [gitbrent/PptxGenJS#1045]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
pptxgenjs: [3.8.0]
PowerPoint: [PowerPoint for Microsoft 365, Version 2110]

### Question
Is it possible to give an `id` to an individual slide (for example when calling `addSlide`) and then linking to it via `hyperlink` instead of using the slide number?

**On creation of slide use an id:**
`const mySlide = presentation.addSlide({ id: 'my-slide-id' });`

**In another Slide, link to the slide via the given id:**
`myOverviewSlide.addText(text: "Goto My Slide", options: { hyperlink: { slide: 'my-special-slide-id' }});`

**Comment by gitbrent** [comment]
The argument for `HyperlinkProps` `slide` at present is simply the slide number.

This seems like a complicated method compared to simple providing the slide #...

**Comment by gitbrent** [comment]
Closing as this issue does not meet the 80/20 criteria for inclusion.
