### ISSUE TITLE
[QUESTION] How to add multiple slides?

### ISSUE THREAD

**Issue by gengituser** [gitbrent/PptxGenJS#1046]
There is the simplest code to create a single slide:

// STEP 1: Create a new Presentation
let pptx = new PptxGenJS();

// STEP 2: Add a new Slide to the Presentation
let slide = pptx.addSlide();

// STEP 3: Add any objects to the Slide (charts, tables, shapes, images, etc.)
slide.addText(
  'BONJOUR - CIAO - GUTEN TAG - HELLO - HOLA - NAMASTE - OLÀ - ZDRAS-TVUY-TE - こんにちは - 你好',
  { x:0.0, y:0.25, w:'100%', h:1.5, align:'center', fontSize:24, color:'0088CC', fill:{ color:'F1F1F1' } }
);

// STEP 4: Send the PPTX Presentation to the user, using your choice of file name
pptx.writeFile({ fileName: 'PptxGenJs-Basic-Slide-Demo' });

Could you please give me the simplest code to create multiple slides?

**Comment by gengituser** [comment]
> There is the simplest code to create a single slide:
> 
> // STEP 1: Create a new Presentation let pptx = new PptxGenJS();
> 
> // STEP 2: Add a new Slide to the Presentation let slide = pptx.addSlide();
> 
> // STEP 3: Add any objects to the Slide (charts, tables, shapes, images, etc.) slide.addText( 'BONJOUR - CIAO - GUTEN TAG - HELLO - HOLA - NAMASTE - OLÀ - ZDRAS-TVUY-TE - こんにちは - 你好', { x:0.0, y:0.25, w:'100%', h:1.5, align:'center', fontSize:24, color:'0088CC', fill:{ color:'F1F1F1' } } );
> 
> // STEP 4: Send the PPTX Presentation to the user, using your choice of file name pptx.writeFile({ fileName: 'PptxGenJs-Basic-Slide-Demo' });
> 
> Could you please give me the easiest code to create multiple slides?

**Comment by gitbrent** [comment]
Please see /demos for examples.
