### ISSUE TITLE
PptxGenJS does not support/included in gulp wiredep and bower

### ISSUE THREAD

**Issue by ayandasgupta** [gitbrent/PptxGenJS#105]
Sir,
I am using this library in my project. But the gulp wiredep is not picking up this particular library while building the lib-XXX.js file. Probable reason is it does not have the bower.json file in it. Can you please help on this? Thanks in advance.

**Comment by gitbrent** [comment]
Hi @ayandasgupta ,

Thanks to the efforts of @santi-git in Issue #107, there is now bower support and a `bower.json` manifest file.

**Comment by ayandasgupta** [comment]
Thanks Gitbrent. Still when I am doing npm install at my local machine it is downloading the previous version 1.4.0 only. Can you please suggest whether there is some additional change needed for getting this latest version? Thanks in advance.
