### ISSUE TITLE
How to get current page of created slide or how create table of content?

### ISSUE THREAD

**Issue by Ciabas** [gitbrent/PptxGenJS#1050]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.9.0]

Please specify what version(s) of PowerPoint you are targeting: [not_related]

### Expected / Desired Behavior / Question
How to build a slider with table of content?
On version 3.1.1 I was using `.number` but after bumping to 3.9.0 I have a problem.
Somehow I need to get page number from created slide. 
Is there any other good solution (API?) to create table of content?

### Observed Behavior
Long time ago there was a function `getPageNumber()` (https://github.com/gitbrent/PptxGenJS/issues/353)
Version 3.1.1 returned a number ```
const slide = pptx.addSlide('Page number');
return slide.number;```.
On version 3.3.0 `.number` was changed/renamed.
Apparently on 3.9.0 there is an attribute `slide._slideNum` but using TS there is no clean approach to get it. TS documentation suggest `.slideNumber` but it's not supported by the code. 

### Steps to Reproduce
V 3.2.1 https://codesandbox.io/s/pptxgenjs-page-number-3-2-1-hqew7?file=/src/App.js
V 3.9.0 https://codesandbox.io/s/pptxgenjs-page-number-3-9-0-2n9js?file=/src/App.js

**Comment by gitbrent** [comment]
The ability to retrieve the slide number was removed as it did not seem useful. It also conflicted with the newer property for the Slide Number prop (`SlideNumberProps`) used to set slide number on the slide.

As the developer, you can track how many slides have been returned.

**Comment by mstudio** [comment]
If anyone else needs to know the slide number after adding tables with `autoPage: true`, you can access it with `slide._slideNum`. The only downside is that you'll need to add another slide after the table to access it. See: https://github.com/gitbrent/PptxGenJS/discussions/1149#discussioncomment-3416290
