### ISSUE TITLE
underline doesn't work in table when update to V3.9.0

### ISSUE THREAD

**Issue by hhq365** [gitbrent/PptxGenJS#1052]
let pptx = new PptxGenJS();
    let slide =pptx.addSlide();
		
		var arrTabRows = [
			[
				{ text: 'White', options: { fill: { color: '6699CC' }, color:'FFFFFF' } },
				{ text: 'Yellow', options: { fill: { color: '99AACC' }, color: 'FFFFAA' } },
				{ text: 'Pink', options: { fill: { color: 'AACCFF' }, color: 'E140FE' } }
			],
			[
				{ text: '12pt', options: { fill: { color: 'FF0000' }, fontSize: 12 } },
				{ text: '20pt', options: { fill: { color: '00FF00' }, fontSize: 20 } },
				{ text: '28pt', options: { fill: { color: '0000FF' }, fontSize: 28 } }
			],
			[
				{ text: 'Bold', options: { fill: { color: '003366' }, bold: true } },
				{ text: 'Underline', options: { fill: { color: '336699' }, underline: true } },
				{ text: '10pt Pad', options: { fill: { color: '6699CC' }, margin: 10 } }
			]
		];
    
		slide.addTable(
			arrTabRows, { x:6.0, y:1.1, w:7.0, rowH:0.75, fill:{color:'F7F7F7'}, color:'FFFFFF', fontSize:16, valign:'center', align:'center', border:{pt:'1', color:'FFFFFF'} }
		);

    pptx.writeFile();
    
    
    
![image](https://user-images.githubusercontent.com/6645976/149505218-aa6ff194-c032-450f-8ad0-61a254c7081d.png)

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher,  i found your project very interesting,  would like to contribute to your project , if u can guide me how to contribute to your open source project i will try solving this issue. I would be really great if u can assign me this issue 🙂

**Comment by hhq365** [comment]
Maybe it's api fault.
This way is workable:
options:{underline: { style:"sng"}}

**Comment by gitbrent** [comment]
Thanks @hhq365 - i've updated the table demo code

**Comment by abdessamadpas** [comment]
> Maybe it's api fault. This way is workable: options:{underline: { style:"sng"}}

that's work for me , thank u so much , so for :
table :
  underline = { style:"sng"};
for normal text:
  underline =true;
