### ISSUE TITLE
Opacity for text element

### ISSUE THREAD

**Issue by ibrahimovfuad** [gitbrent/PptxGenJS#1054]
Hello! I use the latest version of Pptxgenjs and I've faced with problem when I can't pass opacity for whole text element. Is there any option to pass opacity settings? Didn't found anything abt opacity in docs. 

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.9.0

**Comment by gitbrent** [comment]
This ability to set text transparency does not exist yet, i've marked this issue as an enhancement request.

![Screen Shot 2022-02-24 at 19 05 50](https://user-images.githubusercontent.com/7218970/155634185-bc5cb0ce-04a1-4c1f-b299-39bf1ea9a4c7.png)

**Comment by gitbrent** [comment]
Thanks for the suggestion @ibrahimovfuad 

This feature will be available in v3.10.0

![Screen Shot 2022-04-10 at 15 48 22](https://user-images.githubusercontent.com/7218970/162639168-f3ec0895-c462-4afb-9982-cfedb74802a0.png)

![Screen Shot 2022-04-10 at 15 46 57](https://user-images.githubusercontent.com/7218970/162639115-ec3e4c40-1bf2-422b-a059-2b57e90e1770.png)
