### ISSUE TITLE
err TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by ninas880025** [gitbrent/PptxGenJS#106]
Hi I met this error when using addTable. Below is my code:

![image 116](https://user-images.githubusercontent.com/13866745/27375022-6bcb3dd8-56a0-11e7-9a9f-f674135c35a2.png)
This is 'tab':
<img width="234" alt="image 115" src="https://user-images.githubusercontent.com/13866745/27375126-c3f0012e-56a0-11e7-9def-e637f068028d.png">
all the options object is 'options': { fill: '6f9fc9' }

and I got this error:
![image 114](https://user-images.githubusercontent.com/13866745/27375205-0150427c-56a1-11e7-9dc7-0f61d4bd7d2b.png)

I couldn't figure it out. Please help me. thanks!

**Comment by gitbrent** [comment]
Hi @ninas880025 ,

Thanks for reporting this, and extra thanks for the stack trace! 👍 

Those few `undefined` entries are likely the cause.

I've updated the code to avoid this error, so please verify if you can.

**Comment by ninas880025** [comment]
ok thanks! I use npm to install pptxgenjs so now I can renpm install right?

**Comment by ninas880025** [comment]
Hello, 
I dowloaded new version (1.6.0) and then I found this error:
'Cannot read property 'opts' of undefined '
I didn't change my code, just download it and run.
![image 117](https://user-images.githubusercontent.com/13866745/27524368-f4d999c0-5a66-11e7-9cab-3b123ea91760.png)

can you help me with this? thanks!

**Comment by gitbrent** [comment]
Hi @ninas880025 ,

Thanks for the feedback!

I've fixed the issue above and found another place where `null`/`undefined` values would cause errors and fixed that as well.

Please let me know how the newest version works.

**Comment by ninas880025** [comment]
Hi, the newest version works! thanks so much!

**Comment by ninas880025** [comment]
Hi Sorry, 
Could you help me to push this version to npm install? Cause my project need to use npm install to grab this version. thank you so much!!!
