### ISSUE TITLE
Hi, On a slide created using pptxgenJS, the dynamic tables are overflowing to the right. I used autoPage: true and it does not seem to add the newly created tables to the next slide. Please help! TIA

### ISSUE THREAD

**Issue by gitcodepin** [gitbrent/PptxGenJS#1069]

**Comment by gitbrent** [comment]
Please see the many working examples under `/demos`, online, and in the API Docs.

### [Demo](https://gitbrent.github.io/PptxGenJS/demo/browser/index.html#html2pptx)

### [Docs](https://gitbrent.github.io/PptxGenJS/docs/api-tables/#table-auto-paging)

**Comment by gitcodepin** [comment]
Thanks for your reply. I checked Docs page, it says auto-paging will create new slides as **table rows overflow**, doing the magical work for you.
But my issue is dynamic tables overflowing to the right of the slide.
autoPage: true is not working for columnar overflow to next slide.
It works for row overflow to next slide.
Please help.

**Comment by gitcodepin** [comment]
![image](https://user-images.githubusercontent.com/98481460/155461606-207e23d8-01ab-404e-ad87-5257fded923e.png)

**Comment by gitcodepin** [comment]
> Please see the many working examples under `/demos`, online, and in the API Docs.
> 
> ### [Demo](https://gitbrent.github.io/PptxGenJS/demo/browser/index.html#html2pptx)
> ### [Docs](https://gitbrent.github.io/PptxGenJS/docs/api-tables/#table-auto-paging)

Hi, Does autoPage: true work in this scenario?
