### ISSUE TITLE
[QUESTION]how to using the placeholder to generation chart template

### ISSUE THREAD

**Issue by lin-fy** [gitbrent/PptxGenJS#1078]
Can write a few more placeholder type of demo?THX

**Comment by gitbrent** [comment]
A demo of a chart placeholder is already available:

https://gitbrent.github.io/PptxGenJS/demo/browser/index.html#templates

![Screen Shot 2022-05-01 at 14 23 32](https://user-images.githubusercontent.com/7218970/166161403-abe2cbe4-edc5-41fc-960d-461534cb753a.png)
