### ISSUE TITLE
How to covert Html to ppt 

### ISSUE THREAD

**Issue by Kanika2313** [gitbrent/PptxGenJS#1080]
Hi Team,

Can we convert direct html into ppt using pptxgenjs.

Sample-><ul><li>Home</li><li>About</li></ul>

**Comment by gitbrent** [comment]
[Documentation and Demos](https://gitbrent.github.io/PptxGenJS/html2pptx/)

**Comment by Kanika2313** [comment]
This is only for table i have html which is having div ,ul ,li so how can i convert that?

**Comment by gitbrent** [comment]
Either convert your data into an HTML table or use `addTable` to manually add rows & columns.

**Comment by Kanika2313** [comment]
Can you please tell why you are not recommending plugin "html2pptxgenjs" https://github.com/it-beyondit/html2pptxgenjs?msclkid=48db1f54ae8b11ecac726f17e0706ff4 .
we tried this plugin this is working fine for us but in IE browser it is not supporting could you please help me to out for the same.
