### ISSUE TITLE
Not able to add Bullets for multi-line text in the table cell

### ISSUE THREAD

**Issue by abhishekpani** [gitbrent/PptxGenJS#1084]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    /* PptxGenJS 3.9.0 @ 2021-12-11T18:00:42.652Z */     ]

Please specify what version(s) of PowerPoint you are targeting: [    v16.58 (mac)     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Should be able to add Bullets for multi-line text in the table cell

### Observed Behavior
<img width="1179" alt="Screenshot 2022-03-25 at 3 52 12 PM" src="https://user-images.githubusercontent.com/81961718/160103095-f281e68d-bd73-44ea-bf89-4cbbcaad252e.png">

### Steps to Reproduce
Code snippet

rows.push([{
      text: "Line 1\nLine 2\nLine 3",
      options: {
        color: "000000",
        fill: "ffffff",
        breakLine: true,
        align: "left",
        colspan: 1,
        bullet: {
            type: "number"
        },
        fontFace: "Century Gothic",
        fontSize: 9
    }
}]);

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by gitbrent** [comment]
Don't use `breakLine`. Follow the code provided in table demos.

```javascript
let arrCell4 = [{ text: "Numbers\nNumbers\nNumbers", options: { color: "0088cc", bullet: { type: "number" } } }];
```

![Screen Shot 2022-03-27 at 12 32 46](https://user-images.githubusercontent.com/7218970/160293431-7e140311-0bdf-4e96-9abf-769df46f71a1.png)

**Comment by abhishekpani** [comment]
Used below code snippet but still facing the issue. Please help me in resolving this issue

rows.push([{
text: "Line 1\nLine 2\nLine 3",
options: options: { color: "0088cc", bullet: { type: "number" } }
}]);

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/81961718/160347121-88de9466-961c-4525-88c0-c07d5aec0b32.png">

**Comment by willsgh** [comment]
Facing the same issue. It appears related to having spaces in the separate lines of text.

text: "Line 1\nLine 2\nLine 3" : will produce the issues
text: "Line1\nLine2\nLine3": will not

**Comment by willsgh** [comment]
Your code snippet should be

rows.push( { text: [{text: "Line 1\nLine 2\nLine 3", options: { color: "0088cc", bullet: { type: "number" } } }]  });

This will produce the desired result for multi text lines where there are no spaces, as in the provided example.

If you have spaces in the text lines, then you get a very different result.
