### ISSUE TITLE
[QUESTION]Can I set the color of strike just like underline property?

### ISSUE THREAD

**Issue by hhq365** [gitbrent/PptxGenJS#1086]
![image](https://user-images.githubusercontent.com/6645976/160340818-b4b1df9a-60bf-469a-bc54-a2dfdcf51b79.png)

I found strike must be type of string in text element,Could you make it to support set color?

**Comment by gitbrent** [comment]
Does this option exist in the PowerPoint UI?

**Comment by reviewher** [comment]
It does not.  Strikethrough always uses the same color as the font.

<img width="556" alt="osxppt" src="https://user-images.githubusercontent.com/24845478/165224332-68791100-3b12-4938-9e4b-648a36573230.png">

**Comment by gitbrent** [comment]
Closing as this is not a feature PPT supports.
