### ISSUE TITLE
Autopage new slide issue

### ISSUE THREAD

**Issue by tallajobmails** [gitbrent/PptxGenJS#1089]
Hi [Brent Ely](https://github.com/gitbrent),
We are facing the same issue like below when we use the Auto page. The data is misplacing in the different column in a new slide. We are using "pptxgenjs": "^3.9.0" version. 
Please help
Thank you
-tkk

## First Slide
![image](https://user-images.githubusercontent.com/100961957/160649732-62f7d4f4-cf01-4766-a584-9d7467271da1.png)

## Second Slide 
![image](https://user-images.githubusercontent.com/32456839/40076417-d52a76b4-584c-11e8-8a65-c1f701ec82b2.png)

_Originally posted by @dwright-novetta in https://github.com/gitbrent/PptxGenJS/issues/331#issuecomment-389269249_

**Comment by Reen90** [comment]
I encounter the same problem.

**Comment by gitbrent** [comment]
You're reporting an issue not using our issue template, providing no code, and re-using others screen caps.

Re-open a new issue and include all necessary information if you still have problems.
