### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Jbnado** [gitbrent/PptxGenJS#1091]
Image is rotating in 90° deg in ppxt.

### Category
- [ ] Enhancement.
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^3.9.0]

Please specify what version(s) of PowerPoint you are targeting: [PP 2016]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected
The image should be in vertical.

### Observed Behavior
The image is appearing in Power Point horizontally.

### Steps to Reproduce
I'm just using this code to put the image. I already saw the image in base 64 and it's in vertical.
slide
            .addImage({
                data: `image/${foto.type};base64,${base64[0].base64}`, x: '10%', y: '20%',
                sizing: { type: 'contain', w: 4, h: 4 }
            });
I can send the link to see the image, but base64 is too large to paste here!

**Comment by gitbrent** [comment]
The `addImage` method is unit tested, so your issue is with the image itself.

Convert the base64 to an actual image using a webapp and check its rotation etc.

**Comment by Jbnado** [comment]
I saw that when image height is bigger than image width the image in ppxt is rotated, I think its some code of library, I don't remember more :/

**Comment by gitbrent** [comment]
I'm not seeing that behavior:

```javascript
let pptx = new PptxGenJS();
let slide = pptx.addSlide();
slide.addImage({ x: 1.13, y: 1.1, w: 1.25, h: 1.73, path: "https://upload.wikimedia.org/wikipedia/commons/9/9e/125x173.png" });
pptx.writeFile({ fileName: 'PptxGenJS-test.pptx' });
```

![Screen Shot 2022-05-01 at 11 54 41](https://user-images.githubusercontent.com/7218970/166156082-9ca33de6-db37-4e0c-91b5-b3eee8a525f4.png)

If you ever come across a reproducible example, please let me know.

**Comment by Jbnado** [comment]
I can't show the code more because it was in my last job, so I can't access it anymore. But I was using base64 and size: contain.
I was saving my images in Google, and Google send me the base64. I saw if Google was doing the rotate, but wasn't. So I get the base64, used image.decode(), then get the width and height and always the height was higher then width I rotate in 90 degrees.
