### ISSUE TITLE
[QUESTION] Fail to add local images in vue

### ISSUE THREAD

**Issue by flyiiiiii** [gitbrent/PptxGenJS#1092]
Halo, thanks for developing such a good plugin. However, I get puzzled when I add images.

### Category

- [x] Question

### Version

Please specify what version of the library you are using: [3.9.0]

Please specify what version(s) of PowerPoint you are targeting: [ PPTX 2016 ]

### Question
I use PptxGenJS in vue .When I use 'addImage'  API, I succeed in adding a remote URL but failed in adding a local URL. 
How could I  solve the problem? Or did I put the pictures in the wrong folders？ I tried lots of paths but still couldn't export local images to PPTX.
 
Looking forward to your reply.

**Comment by gitbrent** [comment]
The node demo can read images from a local directory, so this is likely a Vue problem.

**Comment by arslan-butt** [comment]
I'm facing the same issue using `Image by data`
