### ISSUE TITLE
transparency doesn't work in table cell

### ISSUE THREAD

**Issue by pipipi-pikachu** [gitbrent/PptxGenJS#1095]
Hi, I found it when using the latest version (3.9.0).

My config:

![image](https://user-images.githubusercontent.com/22936489/162613437-ff9baa11-0c12-433d-bf15-46e7bc35e9c2.png)

Different transparency, but got the same result:

![image](https://user-images.githubusercontent.com/22936489/162613494-380b0f21-0312-4ea7-849d-e261c2e0bf8c.png)

I don't know what oneself do is right or wrong.

Thanks for the library!

**Comment by gitbrent** [comment]
Thanks for reporting this issue @pipipi-pikachu 

The table `fill` property was using a legacy method to create Shading which did not support `transparency`.

```javascript
let pptx = new PptxGenJS();
let slide = pptx.addSlide();

slide.addTable([[{ text: "no transparency" }]], { x: 1, y: 2, w: 3, h: 2, fontSize: 24, fill: { color: "FF0000" } });
slide.addTable([[{ text: "transparency:50" }]], { x: 5, y: 2, w: 3, h: 2, fontSize: 24, fill: { color: "FF0000", transparency: 50 } });

pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```

![Screen Shot 2022-04-10 at 13 41 56](https://user-images.githubusercontent.com/7218970/162634669-4baff9cb-3aee-45d6-a895-16b2ac2f13f6.png)
