### ISSUE TITLE
[QUESTION] Failed to run PptxGenJS in [vite2+vue3] environment

### ISSUE THREAD

**Issue by wwwwhhhzzzccc** [gitbrent/PptxGenJS#1101]
when in import pptxgenjs in vue3, it can not works! how to fix it?

vite2+vue3:  
1\npm create vite@latest
2\choose vue3
3\cd 
4\npm install
5\npm run dev

.........
vscode show errors:
```javascript
X [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "https". 
The package may have incorrect main/module/exports specified in its package.json: 
Failed to resolve entry for package "https". 
The package may have incorrect main/module/exports specified in its package.json.
```

chrome explorer show errors:
```javascript
GET http://localhost:3000/node_modules/.vite/deps/vue.js?v=90163449 net::ERR_ABORTED 504 (Gateway Timeout)
```

my code is:
```vue
<template>
    <div></div>
</template>

<script setup>
// npm install pptxgenjs --save
import pptxgen from "pptxgenjs";

// 1. Create a Presentation
let pres = new pptxgen();

// 2. Add a Slide to the presentation
let slide = pres.addSlide();

// 3. Add 1+ objects (Tables, Shapes, etc.) to the Slide
slide.addText("Hello World from PptxGenJS...", {
    x: 1.5,
    y: 1.5,
    color: "363636",
    fill: { color: "F1F1F1" },
    align: pres.AlignH.center,
});

// 4. Save the Presentation
pres.writeFile({ fileName: "Sample Presentation.pptx" });

</script>

<style>
</style>
```

**Comment by wwwwhhhzzzccc** [comment]
anybody help me????

**Comment by gitbrent** [comment]
This is not a support forum. Also, you've answered your question. The `https` package is missing.

Check the web for a working example using Vue and/or study some to understand node app dependencies.

**Comment by huang1275** [comment]
I have the same problem。There is no solution

**Comment by huang1275** [comment]
![image](https://user-images.githubusercontent.com/110529379/185560940-5c456c66-7e3d-484d-92a9-ddb92a19c639.png)

**Comment by profispojka** [comment]
Couldnt this be a problem with the package? (https://github.com/vitejs/vite/issues/7725) @gitbrent I have https installed and still have the problem.

**Comment by gitbrent** [comment]
Vite/Vue shouldn't be trying to load `https` for a non-node app.

The packge.json file used in our builds excludes certain packages for this reason. Is there a simiilar setting in Vue?

https://github.com/gitbrent/PptxGenJS/blob/25461e5236e4407f72162df97f52d283594a327f/package.json#L26-L33
