### ISSUE TITLE
This image cannot be displayed - Microsoft old version (eg: 2019)

### ISSUE THREAD

**Issue by lova-bc** [gitbrent/PptxGenJS#1105]
### Discussed in https://github.com/gitbrent/PptxGenJS/discussions/1104

<div type='discussions-op-text'>

<sup>Originally posted by **lova-bc** May  3, 2022</sup>
Do you have any ideas to fix image display errors on old version of Microsoft PowerPoint, ex: 2019 version.
`This image cannot be displayed`
<img width="86" alt="Capture d’écran 2022-05-03 à 15 30 43" src="https://user-images.githubusercontent.com/44864112/166453162-0dcf09b5-0de3-4c54-b066-fecae21913ee.png">

</div>

**Comment by gitbrent** [comment]
> Do you have any ideas to fix image display errors

Not likely without any sample code, xml output or information about version, etc.
