### ISSUE TITLE
The array values is repeating when autopage is true

### ISSUE THREAD

**Issue by RatiSethi** [gitbrent/PptxGenJS#1106]
Using pptxgenjs version 3.9
The ppt generated from pptxjenjs is showing repetition of content in table  when the autopage property is set to true, please find the below code used:
private testTable = () => {

    let pres = new pptxgen();

    pres.defineSlideMaster({
      title: "MASTER_SLIDE",
      background: { color: "FFFFFF" },
      objects: [
        {
          text: {
            text: "CONEXTS", options: {
              x: 0.4,
              y: 5.3,
              w: "90%",
              color: "C6C6C6",
              //fill: { color: "F1F1F1" },
              align: pres.AlignH.left,
              autoFit: true,
              fontSize: 10,
              fontFace: "Arial (Body)"
            }
          }
        },
      ]
    });
    let slide = pres.addSlide({ masterName: "MASTER_SLIDE" });

    let rows = [];
    let rightBorder = [{ color: '#D8D8D8' }, { color: '#D8D8D8' }, { color: '#ffffff' }, { color: '#D8D8D8' }];
    let leftBorder = [{ color: '#D8D8D8' }, { color: '#D8D8D8' }, { color: '#D8D8D8' }, { color: '#D8D8D8' }];

    rows.push([
      {
        text: "Column 1",
        options: { fontSize: 10, bold: true, fill: '#E74A21', color: '#FFFFFF', border: rightBorder, padding: [5, 5, 5, 5], align: "center", fontFace: "Arial (Body)" }
      },
      {
        text: "Column 2",
        options: { fontSize: 10, bold: true, fill: '#E74A21', color: '#FFFFFF', border: rightBorder, padding: [5, 5, 5, 5], align: "center", fontFace: "Arial (Body)" }
      }
    ]);

    for (let i = 0; i < 4; i++) {

      rows.push([
        {
          text: "Label 1" + i,
          options: { fontSize: 9, bold: false, fill: '#f6d0cc', color: '#000000', border: leftBorder, padding: [5, 5, 5, 5], fontFace: "Arial (Body)" }
        },
        {
          text: [
            { text: 'ROW HEADER : ', options: { bold: true } },
            { text: "Label 2" + i, options: { bold: false, breakLine: true } },
          ],
          options: { fontSize: 10, bold: false, fill: '#f6d0cc', color: '#000000', border: leftBorder, padding: [5, 5, 5, 5], fontFace: "Arial (Body)" }
        },
      ]);
    }
    slide.addTable(rows, { autoPage: true, });

    pres.writeFile({ fileName: "test.pptx" });
  }

**Comment by gitbrent** [comment]
You'll have to more specific and provide output examples.

Working examples are found in [/demos](https://github.com/gitbrent/PptxGenJS/tree/master/demos)

[Online demo](https://github.com/gitbrent/PptxGenJS/tree/master/demos) has lots of auto-paging that does not exhibit what you're describing.
