### ISSUE TITLE
Issue with Angular 13.2.5 project

### ISSUE THREAD

**Issue by anil957** [gitbrent/PptxGenJS#1107]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question delete this section.*

I am using pptxgenjx 3.10.0 in my angular 13.2.5 project the pptx.writeFile() method is not working , when debug and check in the console no error iam getting , please help to me solve this problem

**Comment by gitbrent** [comment]
This is something you'll need to work on yourself as this isn't a bug of any kind. Integrating into Angular is like using nay other node-based library.

Perhaps the react-demo provided can give you some guidance.
