### ISSUE TITLE
Dynamic shape width?

### ISSUE THREAD

**Issue by kurtismash** [gitbrent/PptxGenJS#111]
Hi,
I am using this library to generate a hierarchal chart in PowerPoint using rectangles and text. I am looking for a way to set the width of a shape to the width the text object within will require. 

For example; a rectangle containing "Foo Bar" will scale to the width of all 7 characters, whereas "Foo" will produce a smaller rectangle with the same height.

I have looked through the API and am unable to find a call that will allow for the width to be calculated beforehand. 

Any suggestions to remedy this issue would be appreciated.

**Comment by gitbrent** [comment]
Hi @kurtismash ,

There's an `autoFit` option but it only adjusts the height as needed.  Mimicking PowerPoint's ability to fit a shape to width based upon text is not something i've managed to do yet.  AFAIK the PPTX file produced has already has its `w` value determined - there's no option that performs that upon rendering - so it's not easily reverse engineered.

**Comment by kurtismash** [comment]
Thank-you for the response. I had a look at the XML from a pptx and saw that it's already determined. I've got round this by using a div and getting the width from that, but it's very approximate.
