### ISSUE TITLE
Does IE11 Support still exist?

### ISSUE THREAD

**Issue by matthew-davis** [gitbrent/PptxGenJS#1113]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.10.0 (latest) ]

Please specify what version(s) of PowerPoint you are targeting: [ PowerPoint 2007 and up ]

### Expected / Desired Behavior / Question
I would expect that Pptxgenjs works with the IE11 browser. It appears that the current documentation lists IE11 support.

### Observed Behavior
If you navigate to: https://gitbrent.github.io/PptxGenJS/demos/ with an IE11 browser and attempt to use any demo it will fail. The failure is silent with nothing listed in the console.

### Steps to Reproduce
Navigate to https://gitbrent.github.io/PptxGenJS/demos/ with an IE11 browser and attempt to use the Live Demo by clicking on the button titled "Run Live Demo" At this point nothing happens, no console logged errors or otherwise.

**Comment by gitbrent** [comment]
@matthew-davis - IE11 support was generally dropped in [v3.6.0](https://github.com/gitbrent/PptxGenJS/releases/tag/v3.6.0)

The demo uses modern javascript and modules so there's no way to support IE11 anymore, however, the library itself still works though (using the bundle or polyfills).

**Comment by gitbrent** [comment]
NOTE: Added an IE11 note to [Wiki page](https://github.com/gitbrent/PptxGenJS/wiki)
