### ISSUE TITLE
SVG Base64 - Unable to load image

### ISSUE THREAD

**Issue by matthew-davis** [gitbrent/PptxGenJS#1114]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 3.10.0 ]
Please specify what version(s) of PowerPoint you are targeting: [ PowerPoint 2007 and up ]

### Expected / Desired Behavior / Question
I've passed an SVG as Base64 to slide.addImage({ data: svgData }) and I would expect that to render, however it doesn't.

### Observed Behavior
After passing in my Base64 SVG as data I receive an error: "ERROR! Unable to load image (image.onerror): data:image/svg+xml;base64,PHN..." I've gone on to confirm that the Base64 data really does render the SVG I want and there isn't any issues in its encoding. I've then gone on to test this with a different Base64 SVG, namely yours that you use in the demos. You've defined it in demos/modules/media.mjs and that data does work.

I did notice that in the returned error there the listing of the Base64 data had "png" appened onto it and wondered if there was something attempting to convert the svg into a png and failing. It turns out that in gen-media.ts there is a function: createSvgPngPreview that does just that and this is also where the Unable to load image error originates. My best guess right now is that my SVG data is too large (it's roughly 40kb in size) and failing this process somewhere along the way. 

Can you tell me if there is something limiting size of Base64 SVG data? 

Would I do better to convert my SVG into a PNG on my side and then send it as "image/png;base64"?

### Steps to Reproduce
I'm generating a powerpoint file with this basic code: https://gist.github.com/matthew-davis/f5f5e74cfdc639e1628e1297d07674be
Then the Base64 SVG data I'm using is in this gist: https://gist.github.com/matthew-davis/c9970d0becad7725a66af171a2bc1683

**Comment by gitbrent** [comment]
@matthew-davis - the demo includes use of a base64 SVG, so i'll have to see what's different in this case.

The `demo_image.mjs` image demo uses this format:
```javascript
export const SVG_BASE64 = "data:image/svg+xml;base64A...="
```

**Comment by nbrendler** [comment]
Ran into the same issue. Works fine in Chrome, but fails in FF. I believe this is running afoul of this bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=700533

Firefox will report the dimensions of your SVG as 0/0, so it bombs [here.](https://github.com/gitbrent/PptxGenJS/blob/master/src/gen-media.ts#L134)  The `png` at the end of the base64 data is a red herring because it uses `path` instead of `data` in the error message.

If you fix your SVG using one of the workarounds described in the bug, _before creating the data URI_, then it works. I added this util function to my export code:
```
function fixSvgDimensions(svg) {
	// Workaround for FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=700533
	svg.width.baseVal.valueAsString = svg.width.baseVal.value.toString();
	svg.height.baseVal.valueAsString = svg.height.baseVal.value.toString();
}
```

**Comment by gitbrent** [comment]
Thanks @nbrendler ! 

@matthew-davis - if this issue is indeed limited to Firefox, then i'll close this issue.

**Comment by matthew-davis** [comment]
Yep, go for closing the issue.

**Comment by Abhishek-KB01** [comment]
Hey, 
I am facing the same issue but on chrome as well. the data seems large and png is appended at the end in the error. Any pointers on how to move forward?
