### ISSUE TITLE
Unable to create vertical lines with addShape()

### ISSUE THREAD

**Issue by kurtismash** [gitbrent/PptxGenJS#112]
When creating a line with the option w:0, the produced line has a width of 1 in the outputted file.

Looking at dist/pptxgen.js, the h option fixes this for horizontal lines. But no fix is present for vertical lines, as can be seen.
````
options.w         = ( options.w || 1.0 );
options.h         = ( options.h || (shape.name == 'line' ? 0 : 1.0) );
````

**Comment by gitbrent** [comment]
Hi @kurtismash ,

Use the `LINE` shape for a line, then rotate it as needed.  The `w` setting will determine how long the line is.

```javascript
// Vertical line
slide.addShape(pptx.shapes.LINE, { x:1.5, y:1.5, w:2.5, rotate:(360-90) }); 
```
![screen shot 2017-06-28 at 21 04 00](https://user-images.githubusercontent.com/7218970/27668233-741b7016-5c45-11e7-8135-f9aae44a6bce.png)

**Comment by kurtismash** [comment]
Thankyou, this is fine.

Out of interest, why is it this way and not as below for both methods (in dist/pptxgen.js)?
```
options.w         = ( options.w || (shape.name == 'line' ? 0 : 1.0) );
options.h         = ( options.h || (shape.name == 'line' ? 0 : 1.0) );
```

**Comment by kurtismash** [comment]
Also, to note that the line rotates around it's centre point and not the XY position it is given.
