### ISSUE TITLE
[BUG] PowerPoint found a problem with content in xxxx.pptx.

### ISSUE THREAD

**Issue by Becavalier** [gitbrent/PptxGenJS#1124]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [**3.10.0**]

Please specify what version(s) of PowerPoint you are targeting: [**16.62 (Mac)**]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

> PowerPoint found a problem with content in test(9).pptx.
PowerPoint can attempt to repair the presentation.

Please refer to: https://codepen.io/becavalier/pen/abqMaXM

The "repair" seems to be working fine on Mac but not on Windows.

Thank you for your feedback!

**Comment by gitbrent** [comment]
Hi @Becavalier - I'm happy to report that this issue is resolved in the upcoming v3.11 release.

**Comment by gitbrent** [comment]
Not too long. You're welcome to take the current build and replace the contents of your node-modules folder if needed.
