### ISSUE TITLE
Add charts to Masters/Templates?

### ISSUE THREAD

**Issue by yipiha** [gitbrent/PptxGenJS#114]
Hi,

Can I define charts in my masters? If yes, how (do you have a sample please)?
Also if I understood correctly it's not possible to use existing PPTX as template but do you think a tool/function could be created that extract the masters from an existing PPTX file?

Thanks a lot - your plugin is way easier than other I tried.

**Comment by gitbrent** [comment]
Hi @yipiha ,

Thanks for suggesting a new feature.  You can now add charts to master slides as well as images, etc.  Try it out and let me know what you think.

```javascript
TITLE_SLIDE: {
  title:  'Corporate Presentation Title Slide',
  objects: [
    { 'line':  { x: 3.5, y:1.00, w:6.00, line:'0088CC', line_size:5 } },
    { 'chart': { type:'PIE', data:[{labels:['R','G','B'], values:[10,10,5]}], opts:{x:0.25, y:0.25, w:3, h:3} } },
    { 'rect':  { x: 0.0, y:5.30, w:'100%', h:0.75, fill:'F1F1F1' } },
    { 'image': { x:11.3, y:6.40, w:1.67, h:0.75, data:pptxgenjsLogoSml } }
  ]
},
```
