### ISSUE TITLE
Is there a limit for the number of lines in a line chart?

### ISSUE THREAD

**Issue by honzukka** [gitbrent/PptxGenJS#1141]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.10.0

Please specify what version(s) of PowerPoint you are targeting: Office 2019, version 16.63.1

Please specify what web browser you are using: Google Chrome, latest version

### Expected / Desired Behavior / Question
When creating a chart with 26 (and more) lines, I would like to be able to open PowerPoint, click the chart, then `Chart Design` -> `Edit data in Excel` and see the underlying data open in an Excel spreadsheet.

### Observed Behavior
This works great for charts that have up to 25 lines, but from 26 upwards I get an error:

<img width="254" alt="Screenshot 2022-08-03 at 12 40 28" src="https://user-images.githubusercontent.com/24512922/182577356-65563189-6afc-48a5-8702-70bbed830d7c.png">

Moreover, only the first 25 lines are drawn into the chart.

### Steps to Reproduce
Here is a snippet that reproduces the issue:

```
const testData = Array(26)
    .fill(0)
    .map((_, i) => ({ name: `line${i}`, labels: ['A', 'B', 'C'], values: [i, i, i] }))

const presentation = new pptxgen()
const slide = presentation.addSlide()
slide.addChart(presentation.ChartType.line, testData)
presentation.writeFile({ fileName: 'test.pptx' })
```

**Comment by gitbrent** [comment]
This is fixed via Issue #1076 (release v3.11.0)
