### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading "labels')

### ISSUE THREAD

**Issue by tminus0ne** [gitbrent/PptxGenJS#1142]
Hello! 

We had this issue last week. Version is 3.8.0.
Maybe it's a bit niche, because we can no longer reproduce it.

<img width="559" alt="Screenshot 2022-08-04 at 10 42 23 AM" src="https://user-images.githubusercontent.com/70655247/182793421-ba9d9154-d914-4f1b-bf1d-52a468e84470.png">

Looks quite similar to these two issues: https://github.com/gitbrent/PptxGenJS/issues/17 https://github.com/gitbrent/PptxGenJS/issues/106

**Comment by gitbrent** [comment]
This issue is likely resolved via v3.11.0.

**Comment by tminus0ne** [comment]
Okay, will test. Thanks!
