### ISSUE TITLE
PPT Save on Remote Server

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#115]
Hello,
How to save PPT on remote server folder path using javascript/ HTML? 
It would be really helpful for me.
Thanks in advance.

-- Shrikant bhongade
shri.bhongade@gmail.com

**Comment by gitbrent** [comment]
Hi @shrikantbhongade,

If you're looking to have a webpage write a file onto a server - like, "Click here to have Report.pptx created on farm01.mycomp.com/output" - then you'd need to engineer a solution like using node.js and express to create a URL to visit (Issue #35), generated the file on the web server, then you could ssh etc. to move it around - even to a remote server.

**Comment by shrikantbhongade** [comment]
Hi,
I want to save PPT on SharePoint/ Dynamics CRM while generating. I have converted PPTX object to embedded/ blob/ binary but when I go to download the file and open PPT then it shows the REPAIR message and actual data is not displaying while I have appended at the time of PPT creation.

Thanks In Advance
Shrikant
