### ISSUE TITLE
[BUG] PowerPoint shows the "repair" dialog when adding an SVG image to a slide master

### ISSUE THREAD

**Issue by BenHall-1** [gitbrent/PptxGenJS#1150]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the following template to ensure we have the details to help.

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/) to see if your question is already addressed there.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.11.0 ]

Please specify what version(s) of PowerPoint you are targeting: [ 16.64 ]

Please specify what web browser you are using: [ N/A (NodeJS) ]

### Expected / Desired Behavior / Question
Expected behaviour would be to not see any repair message when opening the PowerPoint Presentation

### Observed Behavior
When adding an SVG to a slide master, it produces a Repair message on opening.

### Steps to Reproduce

```js
let pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE";

pptx.defineSlideMaster({
    title: "REPORT_PAGE",
    objects: [
        // Company Logo
        {
            image: {
                x: 0.25, 
                y: 0.25, 
                w: 2, 
                h: 0.4,
                path: "img/logo.svg",
            },
        },
    ],
})

let testSlide = pptx.addSlide({ masterName: 'REPORT_PAGE' });
```

**Comment by mjkstudios** [comment]
I can confirm this is still an issue with the latest 3.11.0 build. Is anyone looking into this?

**Comment by mjkstudios** [comment]
Thank you @gitbrent for taking the time to look at this issue. I've read through a few other issues in this repo and can tell that these "repair" problems are a pain.

This is a related (closed) issue: https://github.com/gitbrent/PptxGenJS/issues/522

**Comment by gitbrent** [comment]
@BenHall-1 @mjkstudios - this issue has been resolved and will ship in v3.12.

Thanks for reporting this!

**Comment by mjkstudios** [comment]
Thanks, @gitbrent! Is there an estimated date for when this will be published to npm?

**Comment by gitbrent** [comment]
@mjkstudios - I'm going to start releasing beta versions going forward, starting with this one.

Use `npm install pptxgenjs@beta` to get the latest build with these changes and all others in the CHANGELOG.
