### ISSUE TITLE
[FEATURE] Set default fontFace in masters

### ISSUE THREAD

**Issue by matt88120** [gitbrent/PptxGenJS#1158]
It would be great if a default FontFace can be define for the whole PPTX. 
He's there a way to do that ?

**Comment by matt88120** [comment]
I suppose not :)

**Comment by matt88120** [comment]
@gitbrent To clarify, is it possible to define a default FontFace in masters, so "Calibri" will not be used as default when editing PPTX further in Powerpoint or Keynote.

**Comment by gitbrent** [comment]
Documentation updated for new properties: [Presentation Options](https://gitbrent.github.io/PptxGenJS/docs/usage-pres-options/#default-font)
