### ISSUE TITLE
[QUESTION] transfer HTML to pptx?

### ISSUE THREAD

**Issue by TonyYanOnFire** [gitbrent/PptxGenJS#1166]
Hi there.

I have created a  html report page with some pptx-like elements. They have texts, images and echarts instances (charts that rendered as canvas or svg). Is there a magic method to simply transfer thoese elements/doms to a pptx, in which you can edit everything just like a plain one, like html2canvas?

Any suggetions or comments are welcome 😁

**Comment by cutemurphy2022** [comment]
no
