### ISSUE TITLE
Could you help to push the latest version of PptxGenJS to npm ?

### ISSUE THREAD

**Issue by ninas880025** [gitbrent/PptxGenJS#117]
Hello, 
As title, could you help to push the latest version to npm? Cause my project use npm install to grab PptxGenJS. 
This is the issue I asked before, I will have to use this version. 
[err TypeError: Cannot read property 'text' of undefined](https://github.com/gitbrent/PptxGenJS/issues/106)

thank you.

**Comment by gitbrent** [comment]
Version 1.6.0 is on NPM.
