### ISSUE TITLE
can it support multi axis pptx

### ISSUE THREAD

**Issue by MyronKing123456** [gitbrent/PptxGenJS#118]
hello man ,I want to build a pptx with two axes,how can i do to realize it

**Comment by gitbrent** [comment]
Hi @MyronKing123456 ,

I'm not sure what you're asking for... a chart of some kind?

**Comment by MyronKing123456** [comment]
well, if i have two series of data, No1:[1,2,3,4]  No2:[1000,2000,3000,4000], if they share just one value axis,the chart will be terrible,so ,i need a sub axis to represent it ,i just want to know if it's possible

**Comment by gitbrent** [comment]
Hi @MyronKing123456 ,

No, Charts can only have one axis.

However, I did have another user who created a cleaver work-around.  He used low opacity and place one chart on top of another...

**Comment by MyronKing123456** [comment]
Well,I got it ,Thanks very much~
