### ISSUE TITLE
[BUG] {strike: false} generates a strike-through

### ISSUE THREAD

**Issue by kracas** [gitbrent/PptxGenJS#1189]
### Issue Category

- Bug

### Product Versions

- 3.11.0

### Desired & Observed Behavior

The following code generates a strike-through style:
`slide.addText('Some text', { strike: false })`

I think it should only generate a strike-through if:
` { strike: 'sngStrike' }` or `{ strike: 'dblStrike' }`

**Comment by gitbrent** [comment]
Logic is wrong: https://github.com/gitbrent/PptxGenJS/blob/b57cd176845d2969195ec2c3d48d01c724055bfb/src/gen-xml.ts#L978

**Comment by gitbrent** [comment]
The code provided does not generate a strikethrough. Perhaps the affected code was already fixed during development of 3.12.

Thanks for reporting the issue.
