### ISSUE TITLE
Library modifies provided export options

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#119]
Hi Brent,
Please find following code which exports **line** to PPTX.
(One line has width: **0** and another has **1** )

```
// Create a new Presentation
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');

// Add a Slide, then add objects
var slide = pptx.addNewSlide();

slide.addShape(pptx.shapes.LINE,      { x:1, y:1, w:0, h:5, line:'FF0000', line_size:1 });
slide.addShape(pptx.shapes.LINE,      { x:3, y:1, w:1, h:5, line:'FF0000', line_size:1 });

// Export Presentation
pptx.save('Demo-Shapes');
```

![image](https://user-images.githubusercontent.com/17859100/28563934-2b3bde2a-7145-11e7-809d-b7e46378dc23.png)

which gets converted like this:

![image](https://user-images.githubusercontent.com/17859100/28564069-76a42818-7145-11e7-86f5-e367a2bd3960.png)

Observations:
when **w** is **0** , it gets modified to **1** automatically.

Could you please fix this soon?

Thanks & Regards,
Sangram

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

Please use 'lineSize' to set the line width, not 'w'. Setting the width to zero is by design.

**Comment by sangramjagtap** [comment]
Hi @gitbrent ,
Would be great if you can share code for adding a vertical line.

**Comment by gitbrent** [comment]
Lines can be rotated 360 degrees - see the examples folder for code.
