### ISSUE TITLE
Format text as a superscript in a table cell

### ISSUE THREAD

**Issue by aranard** [gitbrent/PptxGenJS#120]
I'm looking for a way to create text with a superscript within a table cell in my PowerPoint file. This would look something like `Text^Superscript` (where the text `Superscript` should appear above the baseline of `Text`).

Is there currently a way to do this, and if not, is this something that might be added as an enhancement in the future?

Other than this small need, I've had great success with the configuration options available for generating a table. Thanks for the library!

**Comment by gitbrent** [comment]
Hi @aranard ,

Thanks for the feature request.  I've added `subscript` and `superscript` support in the lastest version.  Try it out and let me know what you think.

```javascript
slide.addText(
  [
    { text:'Sub'},
    { text:'Subscript', options:{ subscript:true } },
    { text:' // Super'},
    { text:'Superscript', options:{ superscript:true } }
  ],
  { x:1, y:10 }
);
```
![screen shot 2017-07-31 at 20 53 58](https://user-images.githubusercontent.com/7218970/28805964-f7a6df40-7632-11e7-89ed-ddce669287cb.png)

**Comment by aranard** [comment]
@gitbrent, this looks great! Thanks for the quick resolution. When do you expect this latest version will be published to npm?

**Comment by gitbrent** [comment]
Hi @aranard

I'm just trying to close out Issue #122, then i'll push a new version.
