### ISSUE TITLE
bug: doesn't handle image exif.orientation

### ISSUE THREAD

**Issue by pzhang25** [gitbrent/PptxGenJS#1207]
Hi, I am using #3.11.0, I add an image with exif.orientation=6. It should adjust the image to make it right, but it does. I have attached the pptx. Here is [my git link](https://github.com/pzhang25/pptxjs)
[react-demo.pptx](https://github.com/gitbrent/PptxGenJS/files/10349295/react-demo.pptx)

Thanks for the great product.

**Comment by gitbrent** [comment]
If you're expecting the images added to presentations to honor exif attributes, that's not how this library or OOXML works. You'll need to use the API provided to set scaling, orientation, etc.

See the demos for examples.
