### ISSUE TITLE
Add new line character to list item with shift+enter

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#121]
Hi @gitbrent ,

How to add multiple lines of text to one bullet point?

Example:
![image](https://user-images.githubusercontent.com/17859100/28672458-73621ef8-72fd-11e7-8768-329d1fa82711.png)

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

I'm not sure i've ever created a test case for this.  Have you tried various combinations using `\n` `\r`, a mix, etc?

**Comment by sangramjagtap** [comment]
Yes. I tried many combinations but it always leads to new bullet point

**Comment by shrikantbhongade** [comment]
I am facing the same issue.

**Comment by muftaye** [comment]
I see this was closed.  Was this ever resolved?  I am having the same problem, can't find a way to shift+enter with bullets.  I tried a workaround hoping the inset option would mimic it, but inset doesn't seem to work either.
