### ISSUE TITLE
Converting Html to PPT

### ISSUE THREAD

**Issue by GurpreetkaitCode** [gitbrent/PptxGenJS#1211]
## Question
 Is there any way I can convert HTML as it is in pptx format? For example: If my HTML file contains a heading, paragraph, ul, etc.. can I convert HTML in the same format as we see on the browser.

I went through this converter [https://products.aspose.app/words/conversion/html-to-ppt](url) and it converts as it is, you can check by converting your HTML file. So, can we achieve that result?

!! Thanks in advance 

### Product Versions

Library version: 3.11.0
PowerPoint: PowerPoint 2007
Chrome Browser

**Comment by gitbrent** [comment]
You'll have to write that type of code yourself, there's no built-in functionality to replicate HTML pages.
