### ISSUE TITLE
Insert Attachment

### ISSUE THREAD

**Issue by liuxiansong-ones** [gitbrent/PptxGenJS#1212]
Is it supported to insert attachments? How to operate

**Comment by liuxiansong-ones** [comment]
Is it supported to insert attachments? How to operate

**Comment by gitbrent** [comment]
Can you be more specific, or provide an example?

**Comment by liuxiansong-ones** [comment]
doc、docx、ppt、zip

**Comment by liuxiansong-ones** [comment]
> Can you be more specific, or provide an example?

doc、docx、ppt、zip

**Comment by gitbrent** [comment]
Ah, okay, thanks for the clarification.

This doesn't appear to pass the "majority of users want this" test, plus it would be a pain to support all possible scenarios (attached from filesystem (node) or browser, etc.) so this isn't something we'll look to add.
