### ISSUE TITLE
[BUG|FEATURE]Can you convert such html to ppt?

### ISSUE THREAD

**Issue by nissansz** [gitbrent/PptxGenJS#1229]
We appreciate your feedback - to help the team understand your needs please complete the following template to ensure we have the details to help.

### Submission Guidelines

- **If you are not using the latest release, please update and see if the issue is resolved before submitting an issue**
- General questions or high-level topics should be posted in [Discussions](https://github.com/gitbrent/PptxGenJS/discussions)
- Please browse the online [Documentation](https://gitbrent.github.io/PptxGenJS/) to see if your question is already addressed there

### Issue Category

- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Product Versions

- Please specify what version of the library you are using......: [        ]
- Please specify what version(s) of PowerPoint you are targeting: [        ]
- Please specify what web browser you are using.................: [        ]

### Steps to Reproduce

Can you convert such html to ppt?
[0011.zip](https://github.com/gitbrent/PptxGenJS/files/10991930/0011.zip)

**Comment by gitbrent** [comment]
The only HTML-to-PowerPoint functionality that exists is for tables. See more [here](https://gitbrent.github.io/PptxGenJS/html2pptx/).

**Comment by nissansz** [comment]
Any methods to convert js animation / transition back to ppt?
