### ISSUE TITLE
Rendering of PPTX on screen

### ISSUE THREAD

**Issue by RobPasMue** [gitbrent/PptxGenJS#1230]
Hi everybody! This is my first issue in this repo 😄 

I've been playing around with this tool! I must say it's really good! Let me put a bit of context to what I am doing. I'm in process of creating a React app in which I have a side-by-side distribution of a code editor and a potential previewer. My intention is to get something similar to https://github.com/wyozi/react-pptx but by using directly PptxGenJs instead of react-pptx. I'm struggling to get a potential previewer... Is there a way to get that implemented?

I started from https://gitbrent.github.io/PptxGenJS/demo/react/index.html.. my next point would be to get that previewer up. Do you know if there is any way I can get a similar output [to the right side of this viewer](https://wyozi.github.io/react-pptx/)?

Thanks in advance! And great work with this library

**Comment by gitbrent** [comment]
Hi @RobPasMue 

This is more of a discussion than an issue, and i'm also not sure what this library can do for you. You're basically reproducing the functionality of M365 online (turning PPTX and/or code into HTML) while this library produces XML documents.

**Comment by RobPasMue** [comment]
Sure, sounds reasonable. Thanks @gitbrent. Feel free to close this issue or move it to the discussions section. I will try find a different way to achieve my goal

I was just wondering if PptxGenJS had some internal capabilities for doing this. It'd be a great feature, though I understand the limitations. Thanks again for your answer!
