### ISSUE TITLE
PPT Save on Remote Server-updated

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#125]
Hi,
I want to save PPT on SharePoint/ Dynamics CRM while generating. I have converted PPTX object to embedded/ blob/ binary but when I go to download the file and open PPT then it shows the REPAIR message and actual data is not displaying while I have appended at the time of PPT creation.

Thanks In Advance
Shrikant
shri.bhongade@gmail.com

**Comment by gitbrent** [comment]
Hi @shrikantbhongade ,

I can only support the library itself, so i'm afraid assisting with solutions like this are outside my scope.
