### ISSUE TITLE
Need Axis Label Format Code

### ISSUE THREAD

**Issue by clubajax** [gitbrent/PptxGenJS#127]
We can apply percentages to values with the MS format code (#%), but we can't do this to the tick values - this leaves the data types looking mismatched.

**Comment by clubajax** [comment]
PR added for this feature.

**Comment by gitbrent** [comment]
PR = Issue #129 

@clubajax ,

Do you have test cases for the new `axisLabelFormatCode` and `majorUnit ` options?

**Comment by clubajax** [comment]
Use cases or test cases? I did not see any tests in the repo, and wouldn't know how to write them for a PPTX.

**Comment by gitbrent** [comment]
Hi @clubajax ,

What i'm looking for is how to implement what you've provided.  What formats does `axisLabelFormatCode` take?

**Comment by clubajax** [comment]
The same as the dataLabelFormatCode. I'll add to the PR and update the README.

**Comment by gitbrent** [comment]
Resolved with Issue #132 

Thanks!
