### ISSUE TITLE
Insecure ppt

### ISSUE THREAD

**Issue by furstenheim** [gitbrent/PptxGenJS#131]
Hi,
I'm creating a ppt with the library, the format looks great but there is a warning saying that the ppt is insecure. Is it possible to avoid that? Maybe restricting the funcionalities
![pasted image at 2017_08_08 04_31 pm](https://user-images.githubusercontent.com/8070719/29076956-4377bfe6-7c57-11e7-9bc8-edb94f39507a.png)

**Comment by gitbrent** [comment]
Hi @furstenheim .

As far as I know, this is shown for any document that is generated/sourced from the web.  There's no functionality to restrict or anything like that - a PPT presentation is just a zipped collection of XML files.

If you find any more information about this, please let me know.
