### ISSUE TITLE
[FEATURE]How to use PptxGenJS to import an existing PPT file and save all the slides as pictures?

### ISSUE THREAD

**Issue by fml077** [gitbrent/PptxGenJS#1314]
How to use PptxGenJS to import an existing PPT file and save all the slides as pictures?
or any other library  can realize this feature?

**Comment by adarsharegmi** [comment]
.

**Comment by yassinrais** [comment]
🆙

**Comment by gitbrent** [comment]
This library strictly produces PowerPoints, it does not import or parse existing presentations.
