### ISSUE TITLE
Add height, width options to slide numbers

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#133]
![image](https://user-images.githubusercontent.com/17859100/29116820-bac04222-7d19-11e7-8ba3-b1fcb6be77c2.png)

https://github.com/gitbrent/PptxGenJS#slide-number-options

Default width assigned to slide numbers is insufficient for 3 digit slide number. (99+)
PFA screenshot above.

Would be great if we can add custom height,width as per requirement.

**Comment by gitbrent** [comment]
Thanks for the issue @sangramjagtap 

I've increased the width of the numbers object.  I'm not going to add w/h for it yet to keep it simple for clients.
