### ISSUE TITLE
How to convert PPTX object to base64

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#134]
Hi,
How to convert pptx object to base64?
			
Thanks
Shrikant
shri.bhongade@gmail.com

**Comment by gitbrent** [comment]
Hi @shrikantbhongade ,

It depends on how you're using the library.  Client-browser wise, there's only the binary PPTX file produced at save.

Node options include:

- Use [streaming](https://github.com/gitbrent/PptxGenJS#nodejs-1)
- Use a Node library to covert the stream

**Comment by shrikantbhongade** [comment]
Hello,

I am getting error on below line
**const express = require('express');**
Thanks,
Shrikant
