### ISSUE TITLE
Shapes for a front-end usage

### ISSUE THREAD

**Issue by spamforhope** [gitbrent/PptxGenJS#137]
You have unreachable code for a front-end usage of this module:

`
if ( NODEJS ) {
var gObjPptxMasters = require('../dist/pptxgen.masters.js');
var gObjPptxShapes  = require('../dist/pptxgen.shapes.js');
}
`

So if we don't use NodeJS to generate PPT we cannot use all possible shapes (for ex. shapes.OVAL, etc.)

I've fixed this by comment out this IF statement in your code, but it's bad behaviour

**Comment by gitbrent** [comment]
Hi @spamforhope ,

Those 2 global vars are meant to be unreachable by web clients as the libraries should be included using the standard approach of `<script>`...

The `pptxgen.masters.js` file declares its variable first:
```javascript
var gObjPptxMasters = {
	TITLE_SLIDE: {
[...]
```

What front end are you using?

**Comment by abumphy** [comment]
I had the same problem. I used Vue. For the time being, I comment out this if statement.

**Comment by gitbrent** [comment]
Thanks for bringing this up.  This could stand to be improved.

Re-opening so these vars can be declared in our newer node and angular/react detection methods.

**Comment by gitbrent** [comment]
Hi All,

The newest code just checked in should resolve this issue, making the Colors and Shapes libraries available to front-end applications.

Appreciate everyone's feedback!
