### ISSUE TITLE
Error while calling Nodejs-demo.js

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#139]
Hello,

I am getting error on below line
const express = require('express');

app.get('/', function(req, res) {
		res.writeHead(200, { 'Content-disposition':'attachment;filename='+strFilename, 'Content-Length':data.length });
		res.end(new Buffer(data, 'binary'));
	});

I am also getting an error on **"app.get"**  is that 
**Uncaught (in promise) ReferenceError: app is not defined**
Thanks,
Shrikant

**Comment by shrikantbhongade** [comment]
Hello,
One more question is regarding saveCallback(filename, data) is that which data, I will need to pass in the second variable. Please confirm.

**Comment by gitbrent** [comment]
@shrikantbhongade ,

You're missing `express`.  Install it using NPM.

`saveCallback()` `data` is the data returned - its using for streaming.
See the `nodejs-demo.js` STEP 3 for many examples of saving files.
