### ISSUE TITLE
nested table issues

### ISSUE THREAD

**Issue by forrahul123** [gitbrent/PptxGenJS#14]
Hi,

I have  got nested html  table.  while generating  the ppt it  is not getting generated. it aways goes into error mode.

please do help me resolve the issues.

**Comment by gitbrent** [comment]
Can you provide some sample HTML that could be used for testing?

**Comment by forrahul123** [comment]
[OnePagerTemplate.zip](https://github.com/gitbrent/PptxGenJS/files/650679/OnePagerTemplate.zip)

**Comment by forrahul123** [comment]
HI, 

I have added the html template file which has the nested table.

**Comment by gitbrent** [comment]
Hi,

Thanks for opening an issue.

As far as I can tell, PowerPoint does not support nested tables, so I cannot implement a fix for this.

Testing with your complex table did show where the table selectors were not selective enough and would cause excessive looping, so something good did come out of this. :-)
