### ISSUE TITLE
Chart question about rows/columns

### ISSUE THREAD

**Issue by kyrrigle** [gitbrent/PptxGenJS#145]
Hi Brent,

I have a need to plot time series with a relatively small number of series (10 or so) but with a potentially large number of data points (by day for the last 90 days for example).   

Some problems I've encountered- 

1. Cannot have nulls in the data values.  I've got a [patch](https://github.com/lexalytics/PptxGenJS/tree/bugfix/allow-null-values) for this that seems to work.

2. Currently no support for proper dates for the data labels.   PPT/XLS supports this and seems like a straight forward change (`<c:numRef>` instead of `<c:strRef>`)

3.  When I look inside the Excel sheet I see the data is modeled with the series as rows and the data points as columns.   Near as I can tell this will substantially limit how many data points I can have, right?

For example, here's what I get when I open up the Excel sheet of one of the sample line charts:

_ | Q1 | Q2|  Q3|  Q4
-- | -- | -- | -- | --
Red |22 | 11 | 18  |15
Amb |18 | 19|  32 | 19
Grn| 50 | 71 | 5  | 13
Unk| 7|   7|   3|   3

It would seem that instead the series should be columns with the rows holding the data points:

_ |    Red |Amb| Grn| Unk
-- | -- | -- | -- | --
Q1 | 22 | 18 | 50 | 7
Q2  |11  |19 | 71 | 7
Q3  |18 | 32|  5 |  3
Q4  |15|  19  |13|  3

This is also the structure you get by default if on a blank PPT slide you insert a new line chart:

_ |    Series 1 |   Series 2 |   Series 3
-- | -- | -- | -- 
Category 1 | 4.3 |2.4| 2
Category 2 | 2.5| 4.4| 2
Category 3 | 3.5 |1.8| 3
Category 4 | 4.5 |2.8| 5

Before I dig in to patching for this I was curious if there was a reason you went the way you did and if you had any suggestions on how to architect the change?

Thanks!

Matt

**Comment by kyrrigle** [comment]
So I started looking at the code and [this comment](https://github.com/gitbrent/PptxGenJS/blob/8e882ce45e0ea388d42564278a29116e9ed1fb7a/dist/pptxgen.js#L340) seems to suggest that the intention was to rows for labels.

When I put that data into a test and open the Excel sheet I see the opposite.

_ | Jan-17 | Feb-17 | Mar-17 | Apr-17 | May-17
-- | -- | -- | -- | -- | -- 
Red | 11 | 13  | 14 | 15 | 16
Amb |22 | 6  | 7  | 8  | 9
Grn | 33 | 32|  42|  53 | 63

I've put a pull request in with a change for this. #149

**Comment by gitbrent** [comment]
Hi @kyrrigle ,

**Regarding Point 3**:
The last time i generated data using that layout, the chart axises flipped as well, so i kept it as is.

Either way, embedded data chart and Excel worksheet should be more than capable of handling hundreds of rows and columns.

If you encounter an issue with data, let me know.

**Comment by kyrrigle** [comment]
Hmm.  I suppose it is true that you can have 16K columns (which I know now because I just looked it up).   Have a look at the PR I put in, I still think it is valuable for the date line charts.  I suppose we could walk back just the row/col swap but not sure it is worth it?

Also just realizing that I will need a scatter (XY) to represent date charts over smaller time periods (line charts only support points at a day resolution).   Looking at the chart.xml it doesn't look that different from line charts...

**Comment by gitbrent** [comment]
I believe we've got everything mentioned here done or in flight, aside from the reversed data, so i'm closing this for now.

**Comment by gitbrent** [comment]
Hi @kyrrigle ,

I finally figured out what was going with the series as columns instead of rows issue, and it's all working correctly now!

Issue #202 has landed and correctly sets the Data Series as columns and correctly defines the Chart Data Range:

![screen shot 2017-09-26 at 22 54 04](https://user-images.githubusercontent.com/7218970/30895477-26ae8a7c-a310-11e7-8ac5-4fb39ea8627a.png)
