### ISSUE TITLE
colW can't function

### ISSUE THREAD

**Issue by ninas880025** [gitbrent/PptxGenJS#15]
I used the colW property according to document to set each width of column but it failed to work.
There are 7 columns in my table and I set colW like this:

var tabOpts = {x:0.5, y:0.73, cx:9.0, rowH:0.25, colW:[0.65, 3.25, 0.65, 0.65, 0.65, 1.3, 0.65]};

**Comment by gitbrent** [comment]
Thanks for reporting this!  It's fixed as of now.

The `addTable()` method was merely checking the second option object for `colW`, which really made me question the design of the method itself.  It was not well though out and would easily lend itself to issues like this.

Therefore, I've updated the API (and the docs) to use a single `{OPTIONS}` object that consolidates all the table options like all the other Slide methods.

Example:
```javascript
var tabOpts = { x:1, y:1, colW:[0.65, 3.25, 0.65, 0.65, 0.65, 1.3, 0.65] };
slide.addTable( [1,2,3,4,5,6,7], tabOpts );
```

**Comment by ninas880025** [comment]
Okay thank you so much!

sherry

2016-12-17 5:22 GMT+08:00 Brent Ely <notifications@github.com>:
