### ISSUE TITLE
Multi Type Charts

### ISSUE THREAD

**Issue by clubajax** [gitbrent/PptxGenJS#150]
I'm working on multi-types, for example, Stacked Bars with a Line over it. I have a first working prototype done.

Passing the parameters will be a little odd in order to keep it back compatible. Here is a snippet, from which you can give feedback:

```
var regionData = [
	{
		name: 'Bottom',
		labels: ['April', 'May', 'June', 'July', 'August'],
		values: [.17, .26, .53, .10, .4]
	},
	{
		name: 'Middle',
		labels: ['April', 'May', 'June', 'July', 'August'],
		values: [.05, .04, .02, .03, .15]
	},
	{
		name: 'Top',
		labels: ['April', 'May', 'June', 'July', 'August'],
		values: [.01, .02, .25, .35, .2]
	},
	{
		name: 'Current',
		labels: ['April', 'May', 'June', 'July', 'August'],
		values: [.05, .04, .02, .03, .15]
	}
];

var chartTypes = [
	{
		type: pptx.charts.BAR,
		data: ['Bottom', 'Middle', 'Top'],
		options: {
			barGrouping: 'stacked'
		}
	}, {
		type: pptx.charts.LINE,
		data: ['Current'],
		options: {
			barGrouping: 'standard'
		}
	}
];
slide.addChart(chartTypes, regionData, optsChartBar2);
```

**Comment by david23zhu** [comment]
Hi @clubajax, is it possible to have a secondary value axis for the line chart? That would be nice. Nevertheless what you have done is already a great change! Thanks!

**Comment by gitbrent** [comment]
Hi @clubajax 

Multi-type/Mixed charts would be a great addition to the library.

Compatibility-wise, i'd just change `addChart` to look for an array of objects as the first argument so we don't have to conform to the argument order being used presently.

What do you think of this - it's familiar for current users, and easy to iterate over while building the charts:

```javascript
var arrCharts = [
    {
        type: pptx.charts.LINE,
        data: [
            {
                name: 'Bottom',
                labels: ['April', 'May', 'June', 'July', 'August'],
                values: [.17, .26, .53, .10, .4]
            },
            {
                name: 'Middle',
                labels: ['April', 'May', 'June', 'July', 'August'],
                values: [.05, .04, .02, .03, .15]
            },
            {
                name: 'Top',
                labels: ['April', 'May', 'June', 'July', 'August'],
                values: [.01, .02, .25, .35, .2]
            }
        ],
        options: {
            barGrouping: 'stacked'
        }
    },
    {
        type: pptx.charts.BAR,
        data: [
            {
                labels: ['April', 'May', 'June', 'July', 'August'],
                values: [.05, .04, .02, .03, .15]
            },
        ],
        options: {
            barGrouping: 'stacked'
        }
    }
];

slide.addChart(arrCharts, optsChartBar2);
```

Lastly, it should be easier to add a second values axis for @david23zhu using this format.

**Comment by clubajax** [comment]
Okay, I'll look into doing it this way.

**Comment by jpala** [comment]
Wonderful. Which release will this feature be available in?

**Comment by clubajax** [comment]
PR has landed: https://github.com/gitbrent/PptxGenJS/pull/163

**Comment by jpala** [comment]
in 1.7.0, I see only one addChart method with 3 params and the first parm isn't an array. Don't see any overloaded method with 2 params.
slideObj.addChart = function ( inType, inData, inOpt ) {

Am I missing something?

**Comment by clubajax** [comment]
The method is the same. Overloaded arguments maybe is the term? Line 3123 - https://github.com/gitbrent/PptxGenJS/pull/163/files#diff-8f2b0af8f6c33661903dd083ef26c699R3123

**Comment by jpala** [comment]
Looks like 1.7.0 is missing this code. What I see in the diff is different from the code in 1.7.0 distribution file.

1.7.0 has the following implementation from addChart

		slideObj.addChart = function ( inType, inData, inOpt ) {
			var intRels = 1;
			var options = ( inOpt && typeof inOpt === 'object' ? inOpt : {} );

			function correctGridLineOptions(glOpts) {
				if ( !glOpts || glOpts === 'none' ) return;
				if ( glOpts.size !== undefined && (isNaN(Number(glOpts.size)) || glOpts.size <= 0) ) {
					console.warn('Warning: chart.gridLine.size must be greater than 0.');
					delete glOpts.size; // delete prop to used defaults
				}
				if ( glOpts.style && ['solid', 'dash', 'dot'].indexOf(glOpts.style) < 0 ) {
					console.warn('Warning: chart.gridLine.style options: `solid`, `dash`, `dot`.');
					delete glOpts.style;
				}
			}

**Comment by clubajax** [comment]
We need to try to communicate better, since we are only able to pass back one message a day. Makes for a very slow thread...

- It seems like you are looking to merge into 1.7 and not into master? Are those not in sync?
- My last PR was merged to master
- It might help to have a Committer's Guide. I expect this library to get very popular, very soon, now that charts are implemented.

**Comment by gitbrent** [comment]
Multi-type charts are now in the master branch!

Thanks for all the hard work @clubajax !

**Comment by mark-gss** [comment]
Why I cannot make this work? =(
