### ISSUE TITLE
PPT as Axios response- Download as an attachment on browser

### ISSUE THREAD

**Issue by RupaliPatwa** [gitbrent/PptxGenJS#155]
Hi,
I am getting ppt generated as Axios response and I want to download this ppt on browser How do I do it?

I have following flow for generating PPT
1.Create PPT on node js side with require('pptxgenjs');return the pptx variable as a return type
2.The generated PPT is now available as axios response.How do I download this ppt response as browser attachement
Code snippet:
axios
            .post("/downloadPPT", {
              data: data
            })
            .then(function(response) {
//How to download ppt coming as response on browser as attachment.
}

**Comment by gitbrent** [comment]
Hi @RupaliPatwa ,

I'm not familiar with Axios, so I cannot provide much assistance.
