### ISSUE TITLE
Add Graph Legend Customization

### ISSUE THREAD

**Issue by amgault** [gitbrent/PptxGenJS#156]
Could you add the option to customize the font size and color of the graph legend?

**Comment by gitbrent** [comment]
Hi @amgault ,

If you'd like to submit a patch for it, that'd be fine.  Otherwise, it wasn't on my immediate development roadmap.

**Comment by clubajax** [comment]
I have a PR that covers this: https://github.com/gitbrent/PptxGenJS/pull/165

**Comment by gitbrent** [comment]
Patch/Issue #165 has landed.  Issue resolved.

Thanks @amgault and @clubajax .
