### ISSUE TITLE
Export to PPTX does not work on safari browser 

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#158]
Configuration needed:
Browser: Safari
OS: Mac OS Sierra/ OS X

Try "RUN EXAMPLE CODE" from https://gitbrent.github.io/PptxGenJS/

Receiving error: "failed to load resource:  frame load interrupted" consistently.

**Comment by gitbrent** [comment]
@sangramjagtap ,

The library works fine in Safari.  It looks like maybe you're trying to load the file from GitHub...?

Download the library and run the file locally:
`file:///Users/brent/Documents/GitHub/PptxGenJS/examples/pptxgenjs-demo.html`

Or upload it to a webserver and call it from there.

**Comment by sangramjagtap** [comment]
I've tried running file locally,  but couldn't get through.

Then I tried examples given on above mentioned URL.

In both cases safari encountered same error.

**Comment by gitbrent** [comment]
Debugging JavaScript code/libraries starts with the Web Inspector window.  Try checking to ensure everything loaded, check paths, look in the Console for errors, etc...

Here's Safari showing all the JS scripts loaded:

![screen shot 2017-08-22 at 21 51 13](https://user-images.githubusercontent.com/7218970/29596755-3293967c-8784-11e7-9855-b895e14c6ac3.png)
