### ISSUE TITLE
Suggestion about table = no border

### ISSUE THREAD

**Issue by eddyclock** [gitbrent/PptxGenJS#169]
Dear PPTx Team,

Just my small input about this

`if ( cellOpts.border && typeof cellOpts.border === 'string' ) {
								if (cellOpts.border == 'noborder'){
									var intW = 0;
									var strClr = '<a:noFill/>';
									var strAttr = '<a:prstDash val="';
									strAttr += "solid";
									strAttr += '"/><a:round/><a:headEnd type="none" w="med" len="med"/><a:tailEnd type="none" w="med" len="med"/>';
									// *** IMPORTANT! *** LRTB order matters! (Reorder a line below to watch the borders go wonky in MS-PPT-2013!!)
									strXml += '<a:lnL w="'+ intW +'" cap="flat" cmpd="sng" algn="ctr">'+ strClr + strAttr +'</a:lnL>';
									strXml += '<a:lnR w="'+ intW +'" cap="flat" cmpd="sng" algn="ctr">'+ strClr + strAttr +'</a:lnR>';
									strXml += '<a:lnT w="'+ intW +'" cap="flat" cmpd="sng" algn="ctr">'+ strClr + strAttr +'</a:lnT>';
									strXml += '<a:lnB w="'+ intW +'" cap="flat" cmpd="sng" algn="ctr">'+ strClr + strAttr +'</a:lnB>';
								}else{
								strXml += '  <a:lnL w="'+ ONEPT +'" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:srgbClr val="'+ cellOpts.border +'"/></a:solidFill></a:lnL>';
								strXml += '  <a:lnR w="'+ ONEPT +'" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:srgbClr val="'+ cellOpts.border +'"/></a:solidFill></a:lnR>';
								strXml += '  <a:lnT w="'+ ONEPT +'" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:srgbClr val="'+ cellOpts.border +'"/></a:solidFill></a:lnT>';
								strXml += '  <a:lnB w="'+ ONEPT +'" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:srgbClr val="'+ cellOpts.border +'"/></a:solidFill></a:lnB>';
								}
							}`

Thanks,
Eddy Kwok

**Comment by gitbrent** [comment]
Hi @eddyclock ,

Thanks for the issue.

You can create a table without borders by passing a `pt` value of `0`.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addTable( ['cell 1','cell 2'], { x:1, y:1, w:3 }, { border:{pt:0} } );
pptx.save('PptxGenJS-TableNoBorder');
```

I see where this is undocumented, so i'll get it added shortly!

**Comment by eddyclock** [comment]
HI @gitbrent 
I have tried this code before and after your post and no luck in office2010/2013/win7eng / the code for no border is <a:noFill/>.
Just my small input.
Eddy Kwok

**Comment by gitbrent** [comment]
Ah, quite right!  I've added this feature and updated the docs.

`border:'none'` will remove borders

PowerPoint now recognizes the table as having no borders:

![screen shot 2017-09-06 at 23 58 48](https://user-images.githubusercontent.com/7218970/30146905-65e742c0-9360-11e7-9155-2c02facb7a8c.png)

**Comment by eddyclock** [comment]
hi @gitbrent .
That greats and super thanks,
I really love this PptxGenJS and thanks for your genius work.
Eddy Kwok

**Comment by gitbrent** [comment]
Thanks @eddyclock !

**Comment by skgattani** [comment]
Hi,
Is it possible to give border to a cell on only one side like left side border for a specific cell?

Thanks,
