### ISSUE TITLE
Add new 'lang' text option to enable Chinese Word font_face to take effect

### ISSUE THREAD

**Issue by eddyclock** [gitbrent/PptxGenJS#174]
Hi @gitbrent ,

I have added some text with Chinese word "你好" with Chinese font_face = 微軟正黑體 but the chinese cannot reflect correctly.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
//chinese word with chinese font
slide.addText('你好',  { x:0.5, y:1, w:3, font_size:500 , font_face:'微軟正黑體'});
pptx.save('PptxGenJS-ChineseWord-Font-微軟正黑體');
```
![image](https://user-images.githubusercontent.com/1147530/30146473-e1a416bc-93ca-11e7-9ca5-47c77135c90d.png)

I tried to add new option with "zh-tw"

```javascript
if (opts.lang == "zh-TW"){
	startInfo = '<a:rPr lang="zh-TW" altLang="en-US" ';
}else{
	startInfo = '<a:rPr lang="en-US" ';
}
startInfo += ( opts.bold      ? ' b="1"' : '' );
startInfo += ( opts.font_size ? ' sz="'+ Math.round(opts.font_size) +'0"' : '' ); 
startInfo += ( opts.italic    ? ' i="1"' : '' );
startInfo += ( opts.underline || opts.hyperlink ? ' u="sng"' : '' );
// not doc in API yet: startInfo += ( opts.char_spacing ? ' spc="' + (text_info.char_spacing * 100) + '" kern="0"' : '' ); // IMPORTANT: Also disable kerning; otherwise text won't actually expand
startInfo += ' dirty="0" smtClean="0">';
// Color and Font are children of <a:rPr>, so add them now before closing the runProperties tag
if ( opts.color || opts.lang) {
	if ( opts.color ) startInfo += genXmlColorSelection( opts.color );
	if ( opts.font_face ) {
		startInfo += '<a:latin typeface="' + opts.font_face + '" pitchFamily="34" ';
		if (opts.lang == "zh-TW"){
			startInfo += 'charset="0"/><a:ea typeface="' + opts.font_face + '" pitchFamily="34" charset="-120"/>';
		}
		else{
			startInfo += 'charset="0"/><a:cs typeface="' + opts.font_face + '" pitchFamily="34" charset="0"/>';
		}
	}
}
```

Just my small input.
Eddy Kwok

**Comment by gitbrent** [comment]
Hi @eddyclock ,

I've checked in changes to add a new `lang` option - see if it works correctly now.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
//chinese word with chinese font
slide.addText('你好',  { x:0.5, y:1, w:3, font_size:50 , font_face:'微軟正黑體', lang:'zh-TW' });
pptx.save('PptxGenJS-ChineseWord-Font-微軟正黑體');
```
![screen shot 2017-09-07 at 22 38 13](https://user-images.githubusercontent.com/7218970/30195280-1960da88-941e-11e7-94db-04c5a4ac7e84.png)

**Comment by eddyclock** [comment]
HI @gitbrent 

Sorry for long waiting.

It is not correct. I have tried to generate XML file from PowerPoint.

if lang = "zh-TW", I found that there are some key factors as below:

<a:rPr lang="zh-TW" altLang="en-US" ....>
<a:**cs** typeface ... **charset="0"**> ...change to <a:**ea** ... **charset="-120"**>

Hope this can help.
Regards,
Eddy Kwok

**Comment by gitbrent** [comment]
Hi @eddyclock ,

Thanks for letting me know.  Both 'ea' and 'cs' are set to charset="-120" now.

**Comment by LawlietNot** [comment]
Hi @gitbrent ,
I found a bug
if set text lang="zh-CN",  use office 2007 open fail ,prompt repair and then blank page.
if 2010
![image](https://user-images.githubusercontent.com/6241768/33598130-9a5fc0aa-d9dc-11e7-8674-19c2398d1dd4.png)

I do not know pptx xml,so i tried to modify the xml for
```
<a:latin charset="-122" pitchFamily="34" typeface="微软雅黑"/>
	<a:ea charset="-122" pitchFamily="34" typeface="微软雅黑"/>
	<a:cs charset="-120" pitchFamily="34" typeface="微软雅黑"/>
```
Is this possible only for Simplified Chinese.

**Comment by gitbrent** [comment]
Hi @LawlietNot,

I've re-ordered the one place where cs was before ea.  Let me know if this fixes the issue.

**Comment by eddyclock** [comment]
Hi @LawlietNot 
It is fixed and thanks for your help.
Eddy
