### ISSUE TITLE
Negative Chart Values throwing error

### ISSUE THREAD

**Issue by shaunvdp** [gitbrent/PptxGenJS#175]
Hi All...

Thanks to the creator of this brilliant piece of software... I have come across an issue that I wanted to point out, maybe someone came up with a solution for it. 

This works great:
var dataChartBar = [
  {
    name  : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [26, 53, 100, 75]
  }
but as soon as I insert a negative value into the array an error is thrown: 'Cannot read property 'length' of undefined' ... 

var dataChartBar = [
  {
    name  : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [-26, 53, 100, 75]
  }

has anyone come across this and found a solution to it? your help will be greatly appreciated...

many thanks...

**Comment by gitbrent** [comment]
Hi @shaunvdp ,

This issue must be somewhere else in your code.  Negative numbers work fine in charts:

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var dataChartBar = [{
    name : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [-26, 53, 100, 75]
}];

slide.addChart( pptx.charts.BAR, dataChartBar, {} );

pptx.save('PptxGenJS-NegChart');
```
![screen shot 2017-09-07 at 23 10 30](https://user-images.githubusercontent.com/7218970/30195834-e0c34a7c-9421-11e7-90c8-30ee43db7399.png)

**Comment by shaunvdp** [comment]
ah... thanks  so much for the quick response... I stripped the code out and it seems to be working... looks like it was the build up of the attributes that was breaking it as soon as there is a negative value given... will post back as soon as I have more information.

**Comment by gitbrent** [comment]
Hi @shaunvdp ,

What an awesome twist - you turned a non-error into an actual error.  Thanks!  :-)

Supplying `chartColors` without `invertedColors` was causing an issue.  The fix is checked in now.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var dataChartBar = [{
    name : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [-26, 53, 100, 75]
}];

slide.addChart( pptx.charts.BAR, dataChartBar, {chartColors: ['2F469C','2F469C']} );
pptx.save('PptxGenJS-NegChart');
```
![screen shot 2017-09-08 at 20 22 03](https://user-images.githubusercontent.com/7218970/30235883-4c5d3ef2-94d4-11e7-8b6f-b410b27c6bae.png)

**Comment by shaunvdp** [comment]
ah ha! thanks so much... will download the newest build. :)

**Comment by shaunvdp** [comment]
Hi... Me Again... Just tested the new release and noticed that when supplying 2 colors as per your code, the two colors get alternated between the bars (for example if I supply [red,white] the bars will be red, white, red, white, red, white... instead of one being assigned to positive and one being assigned to negative.

**Comment by gitbrent** [comment]
Use the `invertedColors` option to pass colors for negative numbers.

Correct, passing two colors is asking the system to use two alternating colors - just use one color if you want only 1 across all bars.  There's tons of examples in `examples/pptxgenjs-demo.html`

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var dataChartBar = [{
    name : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [-26, 53, 100, 75]
}];

slide.addChart(
  pptx.charts.BAR,
  dataChartBar,
  {
    chartColors: ['2F469C'],
    invertedColors: ['CC8800']
  }
);
pptx.save('PptxGenJS-NegChart');
```
![screen shot 2017-09-11 at 19 56 28](https://user-images.githubusercontent.com/7218970/30303123-631cecf6-972b-11e7-9e6d-e1cbff517ffc.png)

**Comment by shaunvdp** [comment]
Thanks so much... I didn't and still don't see invertedColors anywhere in the documentation... thanks for pointing it out. ;)

**Comment by shaunvdp** [comment]
I actually found it is this issue: https://github.com/gitbrent/PptxGenJS/pull/140

but you do not mention it is any of the examples or documentation for usage...

**Comment by gitbrent** [comment]
Whoops!!

Added to README now.  Thanks.
