### ISSUE TITLE
Ability to import existing PPTX file

### ISSUE THREAD

**Issue by tjrueter** [gitbrent/PptxGenJS#179]
I've been using this library and it's working great.  One feature that would help me a lot is the ability to  pull in an existing PPTX file and add its slides to the presentation.  This way I could have dynamic slides I generate with the library, as well as static slides I pull in from an existing file, and then save the whole thing as a combined presentation file.

**Comment by gitbrent** [comment]
Hi @tjrueter ,

I do not have any plans to add the ability to open/import existing presentations.

There may be tools to perform PPTX merging.
