### ISSUE TITLE
Not able to set x and y position of table while using  "addSlidesForTable" method to add table on slide.

### ISSUE THREAD

**Issue by priyaraskar** [gitbrent/PptxGenJS#18]
Hi,

I am trying to add html table on slide, with addSlidesForTable method.
I followed your instructions and tried to add the table along with custom master layout.
But I am not able to set this html table's 'x' and 'y' positions as it is overlapping my master layout texts.
Can you please help me in how to set these positions?
![capture](https://cloud.githubusercontent.com/assets/24734651/21455862/b6162112-c949-11e6-8b5e-75353aeedf8a.PNG)

**Comment by gitbrent** [comment]
It turns out that I never added any options for table size or placement when using `addSlidesForTable`... :-)

- The method now accepts `x`, `y`, `w`, and `h` options for sizing and placement of the table(s) created
- Documentation has been updated as well

Thanks for your feedback!

**Comment by priyaraskar** [comment]
Thanks for the help @gitbrent , it worked.

Now I need to set y positions of Page Numbers.
I am using 'LAYOUT_WIDE' layout for slides.
but when i set **isNumbered : true**, it is showing page number middle of the slide.
like this: 
![image](https://cloud.githubusercontent.com/assets/24734651/22061137/a42748aa-dd99-11e6-87be-4f53e466b0ba.png)

I need its y position to be at slide's bottom.
Can you please help me with this.

**Comment by gitbrent** [comment]
Sure, that's something i've been meaning to add anyway.

Please open a new Issue and add your screencap and comment from above and i'll work on it.
