### ISSUE TITLE
Generated pptx won't open in PowerPoint 2007 due to rowspan

### ISSUE THREAD

**Issue by CameronOC** [gitbrent/PptxGenJS#180]
I'm attempting to use this powerpoint generation, but I'm running into an issue using powerpoint reader 2007. The application cannot open the file. I can easily open this is Powerpoint 2016, but on my pc I'm having issues getting the powerpoint project to be able to even open the application. If You could assist me that would be marvelous!

**Comment by gitbrent** [comment]
Hi @CameronOC ,

I'm going to need more information to be able to help.

It is every single PPT?  Even the simple hello world text one?

**Comment by CameronOC** [comment]
No, I should test it out more with eliminating other factors, I have a very large single slide I am adding to with that has a title, and 4 tables on it. I have not tried the hello world item as of yet.

**Comment by CameronOC** [comment]
Hey, again sorry about the delay, I further investigated the problem and I'm having issues with the images I'm adding, with the addImage function both of the images I have cause it to not be able to be read by powerpoint 2007, however if I used powerpoint 2016 there are no issues. I'm using the addImage function with a base64encoded image, 

- slide.addImage({data: 'image/png;base64,' + base64Image, x: 6.5, y: .9, w:width, h:height});)

and another image that is stored local to the project.

 Once removed I had one more issue with a table with complex rows. For some reason, this is actually causing the powerpoint slide to fail. It has a row with an object with a custom column span. This is the only difference between the other tables I've created. 

These 2 images and 1 column span cause failure in powerpoint 2007. Do you have any advice?

**Comment by gitbrent** [comment]
Are there any errors or warnings in the console?

Can i see the output of the demo images slide?
`examples/pptxgenjs-demo.html#tab3`

![screen shot 2017-09-11 at 19 48 36](https://user-images.githubusercontent.com/7218970/30302949-50e853d2-972a-11e7-89a6-c73426d6b86c.png)

**Comment by CameronOC** [comment]
Hey @gitbrent, there are no errors in the console on powerpoint generation and save. I am attempting to run use your html example. I'm cloned and opened the example doc and was greaed with this image 
![image](https://user-images.githubusercontent.com/8887643/30555957-11a40426-9c5e-11e7-98aa-6617e56b9a9e.png)

**Comment by CameronOC** [comment]
I open this time with the allow file access from file flag
![image](https://user-images.githubusercontent.com/8887643/30572079-83c1d410-9ca0-11e7-8edd-3b5b2590df94.png)

**Comment by gitbrent** [comment]
Well, that looks okay...  (Are you using PPT 2016?)

What pages give you errors in 2007?  My guess is that it's isolated to a certain object type or types.

**Comment by CameronOC** [comment]
![image](https://user-images.githubusercontent.com/8887643/30573410-9845df1e-9ca8-11e7-93b1-8d319ca37661.png)
This is the error I get

**Comment by CameronOC** [comment]
When I use Office 2007

**Comment by gitbrent** [comment]
Even with the base-bones export?

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addText( 'Hi world', { x:0.0, y:0.25, w:3, h:1, fill:'F1F1F1' } );
pptx.save('PptxGenJs-Basic-Slide-Demo');
```

**Comment by CameronOC** [comment]
Instead of powerpoint viewer I used powerpoint 2007 and can now see the images just fine. I however am still having issues opening any slides with my own images. So I'll use your test images for now and see if there is an issue with my images by chance.

**Comment by CameronOC** [comment]
Here is my code for the table:
let rowz = [];
    rowz.push([
        { text: 'FINANCIALS', options: {color: 'ffffff', fill: '999999', align: 'center', colspan: 6, font_size: 6}}
    ]);
    rowz.push([
        { text: ' ', options: {fill: 'ffffff', color: '000000', align: 'center', font_size: 6}},
        { text: 'Test', options: {fill: 'ffffff', color:'000000', align: 'center',  font_size: 6}},
        { text: 'Test', options: {fill: 'ffffff', color:'000000', align: 'center',  font_size: 6}},
        { text: 'Test', options: {fill: 'ffffff', color:'000000', align: 'center',  font_size: 6}},
        { text: 'Test', options: {fill: 'ffffff', color:'000000', align: 'center',rowspan: 2, colspan: 2,  font_size: 6}}
    ]);
    rowz.push([
        { text: 'Test', options: {fill: 'ffffff', color: '000000', align: 'center',  font_size: 6}},
        { text: 'Test', options: {fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: {fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: {fill: '4286f4', align: 'center', font_size: 6}},
    ]);
    rowz.push([
        { text: ' ', options: {fill: 'cccccc', color: '000000', font_size: 6}},
        { text: 'Test', options: {fill: 'cccccc', color: '000000', align: 'center', colspan: 4, font_size: 6}},
        { text: 'Test', options: {fill: '4286f4', rowzpan: 3, font_size: 6}}
    ]);
    rowz.push([
        { text: 'Test', options: { align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: ' ', options: { fill: 'ffffff', color: '000000', align: 'left', font_size: 6}}
    ]);
    rowz.push([
        { text: 'Test', options: { align: 'center', font_size: 6}}
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: ' ', options: { fill: 'ffffff', color: '000000', align: 'left', font_size: 6}}
    ]);
    rowz.push([
        { text: ' ', options: {fill: 'cccccc', color: '000000', font_size: 6}},
        { text: 'Test', options: {fill: 'cccccc', color: '000000', align: 'center', colspan: 4, font_size: 6}},
        { text: 'Test', options: {fill: 'ffffff', font_size: 6}}
    ]);
    rowz.push([
        { text: 'Test', options: { align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: ' ', options: { fill: 'ffffff', color: '000000', align: 'left', font_size: 6}}
    ]);
    rowz.push([
        { text: 'Test', options: { align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: 'Test', options: { fill: '4286f4', align: 'center', font_size: 6}},
        { text: ' ', options: { fill: 'ffffff', color: '000000', align: 'left', font_size: 6}}
    ]);
    rowz.push([
        { text: 'RISKS/OPPORTUNITIES', options: { align: 'center', color: 'ffffff', fill: '999999', colspan: 4, font_size: 4}},
        { text: 'NOTES', options: { align: 'center', color: 'ffffff', fill: '999999', colspan: 2, font_size: 4}},
    ]);
    rowz.push([
        { text: 'Test', options: { align: 'left', color: '000000', fill: 'ffffff', colspan: 4, font_size: 6}},
        { text: 'Test', options: { align: 'left', color: '000000', fill: 'ffffff', colspan: 2, font_size: 6}},
    ]);
    let rowzOpts = { x:.15, y: 0.8, w: 6,colW: [.75,.75,.75,.75,.25,2]};
    slide.addTable(rowz, rowzOpts);

**Comment by CameronOC** [comment]
I've narrowed the problem down to rowspan as being the issue for table. If any item of a row has rowspan as a variable and it's greater than 1 it causes the powerpoint no to be able to be opened by Microsoft 2007

**Comment by gitbrent** [comment]
Good work on narrowing the cause down.

Is the issue present even with a simple table example?

**Comment by CameronOC** [comment]
No, the issue is not present with a simple table, every time I add a rowspan I have an issue and the powerpoint slide cannot be openned

**Comment by CameronOC** [comment]
I've been fiddling with the input but I still cannot fix the issue, where do you handle rowspan in the code, maybe I could contribute a fix!

**Comment by gitbrent** [comment]
So this generates an error?

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
var arrTabRows = [
  [ {text:'A1 and A2', options:{rowspan:2}}, {text:'B1'} ],
  [ 'B2' ]
];
slide.addTable( arrTabRows, {x:1, y:1, w:4,border:{pt:1, color:'666666'}} );
pptx.save('PptxGenJS-Issue180');
```
![screen shot 2017-09-20 at 23 31 55](https://user-images.githubusercontent.com/7218970/30679037-1fdb1f16-9e5c-11e7-9f6b-e1f21cafe01c.png)

**Comment by CameronOC** [comment]
This Table works correctly, however I'm still having issues with my cell if there's other items underneath it.

This code hear will fail in powerpoint 2007,
 var pptx = new PptxGenJS();
    var slide = pptx.addNewSlide();
    var arrTabRows = [
        [ {text:'A1 and A2', options:{rowspan:2}}, {text:'B1'} ],
        [ 'B2' ], [{text:'C1' }]
    ];
    slide.addTable( arrTabRows, {x:1, y:1, w:4,border:{pt:1, color:'666666'}} );
    pptx.save('PptxGenJS-Issue180');

**Comment by CameronOC** [comment]
So where in the library do you construct table cell columns, I could look into it and find out why it may not be working in 2007
