### ISSUE TITLE
Option to Set Show Data Table through code

### ISSUE THREAD

**Issue by akashkarpe** [gitbrent/PptxGenJS#182]
Hi ,
Thanks for creating this library.
It would be nice if we have option set Show Data Table flag ,so that when I open PPT I can see graph with Data Table.

**Comment by gitbrent** [comment]
Hi @akashkarpe ,

I'm not clear on what you're asking for.  Viewing the data behind a table is done via the Ribbon (see below - "Edit Data in Excel"), i'm not sure there's something i can set that will open/show the data.

![screen shot 2017-09-11 at 19 41 37](https://user-images.githubusercontent.com/7218970/30302845-806e512a-9729-11e7-910e-0c93481d8b77.png)

**Comment by akashkarpe** [comment]
Hi @**gitbrent**  , thanks for quick reply.
I understood your point.
But our need is different .
We want Data Table Property in **CHART ELEMENT** by default checked or we should able to set it from code. Please see following screenshot
![datatableoption](https://user-images.githubusercontent.com/8823590/30309884-497065c8-97ab-11e7-9e56-05db27547055.png)

We are expecting output like below when user open's PPT for first time.
![graphwithdata](https://user-images.githubusercontent.com/8823590/30309911-754a071c-97ab-11e7-8d7b-fd8870ac0ab9.png)

**Comment by gitbrent** [comment]
Hi @akashkarpe ,

The ability to show Data Table has been implemented.  I also added the same 4 Data Table options found in PowerPoint.

Check the README for all the new [chart options](https://github.com/gitbrent/PptxGenJS#chart-sizeformatting-options)

Ex:
```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var arrDataRegions = [
  {
    name  : 'Region 1',
    labels: ['May', 'June', 'July', 'August'],
    values: [26, 53, 100, 75]
  },
  {
    name  : 'Region 2',
    labels: ['May', 'June', 'July', 'August'],
    values: [43.5, 70.3, 90.1, 80.05]
  }
];

var optsChartBar1 = { x:0.5, y:0.6, w:6.0, h:3.0,
  barDir:                  'bar',
  showDataTable:           true,
  showDataTableKeys:       true,
  showDataTableHorzBorder: true,
  showDataTableVertBorder: true,
  showDataTableOutline:    true
};
slide.addChart( pptx.charts.BAR, arrDataRegions, optsChartBar1 );

pptx.save('PptxGenJS-Data Table');
```

Result:
![screen shot 2017-09-16 at 19 30 28](https://user-images.githubusercontent.com/7218970/30516997-963175d8-9b15-11e7-9c66-fca144d3853d.png)

**Comment by akashkarpe** [comment]
@**gitbrent** ,Thanks a lot, this will definitely solve our problem.
