### ISSUE TITLE
arrange text diagonally

### ISSUE THREAD

**Issue by vanekar** [gitbrent/PptxGenJS#183]
Hello can i arrange a text diagonally

![untitled-1](https://user-images.githubusercontent.com/20844203/30272765-b64b202c-9713-11e7-86ee-f34731291b77.png)

similar to this is jack in the image

**Comment by gitbrent** [comment]
Look at the demo page for some examples:
`examples/pptxgenjs-demo.html`

![screen shot 2017-09-11 at 19 36 45](https://user-images.githubusercontent.com/7218970/30302757-cd567888-9728-11e7-8409-da9b93e00393.png)

**Comment by gitbrent** [comment]
Also see the `rotate` option for Shapes and Lines.

[Shape Options](https://github.com/gitbrent/PptxGenJS#shape-options)
