### ISSUE TITLE
Validation: Secondary axis must be used by one of the multiple charts

### ISSUE THREAD

**Issue by jpala** [gitbrent/PptxGenJS#186]
There is a hard requirement to use a secondary axis while building a combo chart. In my opinion, there could be many scenarios, where both the chart types are plotted against a single value axis. 

Eg. Revenue as bar graph and Average Revenue as line graph. 

Enforcing this validation, results in unnecessary use of 2nd axis and the confusion caused around it when they are on different scales.

**Comment by gitbrent** [comment]
Hi @jpala ,

Thanks for the feedback.

The design we came up for multi-type charts that requires a secondary axis was chosen as it would be the most intuitive (two charts <-> two axes).  I would argue that in cases where the scale is the same, you'd just use the same numbers.  Making the secondary axis optional would only benefit the minority of use cases where users are plotting against the same scale and would lend to confusion when looking at sample code, etc.
