### ISSUE TITLE
Ability to "highlight" text like Google Slides?

### ISSUE THREAD

**Issue by aranard** [gitbrent/PptxGenJS#189]
Is there a way to add a background/fill color to a block of text? I see information on fill colors for shapes and table cells in the documentation, but nothing currently to add a background color to plain text.

Thanks!

**Comment by Malangs** [comment]
If you take a look at the [text options](https://github.com/gitbrent/PptxGenJS#text-options) in the documentation, there is actually an option called `fill`. So I guess what you need is something like `slide.addText('text here', { x: 1.0, y: 1.0, w: 3.0, h: 3.0, fill: 'ADD8E6' });`.

**Comment by aranard** [comment]
I tried using `fill`, but it doesn't seem to do anything. It works fine for coloring the background of a cell, but not on standalone text.

**Comment by gitbrent** [comment]
Hi @aranard ,

@Malangs is correct.  `addText()` creates a textbox object, which can be filled with color.  The only other option is the color of the text itself (`color`).

I'm unable to guess what you mean by "does nothing", but the code Martin provided works fine and has the correct fill properties in the format window.

Can you show us what you're looking for?  Preferably with a Format or Properties dialog.

![screen shot 2017-09-15 at 18 13 37](https://user-images.githubusercontent.com/7218970/30506493-f0849c42-9a41-11e7-9ef2-85b7424a8b9d.png)

**Comment by aranard** [comment]
@gitbrent 

Sorry for the confusion, I did a poor job of explaining in my original message what I'm attempting to do. In your example, it looks like the fill is on a shape that the text is contained in. What I'm needing is the ability to set the "highlight" color of a piece of standalone text (an example of doing this configuration in Google Slides is attached below). Is this something that is either currently supported or would be possible to support in the future?
 
![Uploading Screen Shot 2017-09-18 at 9.24.47 AM.png…]()

Thanks!

**Comment by gitbrent** [comment]
Hi @aranard 

Ah yes, now I see what you're talking about.

As far as I know, there is no corresponding functionality in PowerPoint.

**Comment by aranard** [comment]
Ok, thanks for looking into it!
