### ISSUE TITLE
align expected result different

### ISSUE THREAD

**Issue by eddyclock** [gitbrent/PptxGenJS#191]
Hi @gitbrent ;

Under the addtext function,
if style added align, the array of text will be expected to add breakline in each array data element.

example:
`var data = [ {'a'},{b} ]
slide.addText(data, { x:0.5, y:1, w:3, font_size:10 ,align :'l', font_face:'Arial'}); break;
output will be
--------------
a
b
--------------
slide.addText(data, { x:0.5, y:1, w:3, font_size:10, font_face:'Arial'}); break;
output will be
--------------
ab
--------------
`
No sure if it is expected result.
If I want the text (storing in array) without linebreak and align center or right, i cannot find do this with this limitation.

Regards,
Eddy Kwok

**Comment by gitbrent** [comment]
Hi Eddy,

The objects inside the `text` array have their own properties, one of which is `align`.

Whenever a text object has an `align` value or has `breakLine` set, a line break will be generated.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

slide.addText(
  [
    { text:'left',   options:{ align:'l' } },
    { text:'center', options:{ align:'c' } },
    { text:'right',  options:{ align:'r' } }
  ],
  { x:0.5, y:0.5, h:1, w:2, font_size:18, font_face:'Arial', fill:'f1f1f1' }
);

slide.addText(
  [
    { text:'left',   options:{ font_size:12 } },
    { text:'center', options:{ font_size:12 } },
    { text:'right',  options:{ font_size:12 } }
  ],
  { x:0.5, y:2.0, h:1, w:2, font_size:18, font_face:'Arial', fill:'fffccc' }
);

slide.addText(
  [
    { text:'left',   options:{ font_size:12, breakLine:true } },
    { text:'center', options:{ font_size:12, breakLine:true } },
    { text:'right',  options:{ font_size:12, breakLine:true } }
  ],
  { x:0.5, y:3.5, h:1, w:2, font_size:18, font_face:'Arial', fill:'f2f9fc' }
);

pptx.save('PptxGenJS-text-align');
```

![screen shot 2017-09-18 at 20 39 07](https://user-images.githubusercontent.com/7218970/30572177-bd937eee-9cb1-11e7-98bc-9d63aa171f07.png)

**Comment by eddyclock** [comment]
Hi @gitbrent ,

Thanks for your help.
I try to code with addtext with below picture, I still cannot workout the correct coding.

1. Single line with right align
2. Individual have their own style

![image](https://user-images.githubusercontent.com/1147530/30587205-ed39071e-9d64-11e7-9b23-675ede307924.png)

Thanks,
Eddy Kwok
