### ISSUE TITLE
Add new chart type: XY Scatter

### ISSUE THREAD

**Issue by shaunvdp** [gitbrent/PptxGenJS#192]
Hi all...

I was going through the documentation, looking for mention of XY Scatter chart... I don't see anything, has anyone had any luck with creating this type of chart using this tool?

thanks in advance
Shaun

**Comment by gitbrent** [comment]
Hi @shaunvdp ,

Thanks for the feature request.  I'll work on adding scatter charts.

**Comment by shaunvdp** [comment]
That will be Awesome! Thanks so much @gitbrent .

**Comment by gitbrent** [comment]
Hi @shaunvdp ,

XY Scatter Charts are now supported!  I've added some examples to the demo page.

Thanks again for the suggestion.

**Comment by shaunvdp** [comment]
awesome! thanks so much!!
