### ISSUE TITLE
Flexible width of text.

### ISSUE THREAD

**Issue by the-yadu** [gitbrent/PptxGenJS#194]
I am trying to achieve a result like this

<img width="165" alt="screen shot 2017-09-20 at 3 02 55 pm" src="https://user-images.githubusercontent.com/7404181/30637070-f876bfa8-9e14-11e7-89ca-10c8a4571fa9.png">
But the width of text automatically takes way more space than expected.

<img width="428" alt="screen shot 2017-09-20 at 3 05 46 pm" src="https://user-images.githubusercontent.com/7404181/30637206-4bf05784-9e15-11e7-9498-df427838e40a.png">

The text behavior is like div but I want it to behave like span
How to achieve something like this.

**Comment by gitbrent** [comment]
Hi @the-yadu ,

Yeah, this gets asked periodically, but there's no fix per se.  Objects have to have a specified width - even ones with an auto-size property set - and there's no way for the code to know how wide "RalphLauren" is.

Best I can tell, PowerPoint does this type of thing in the app itself, not in the generated XML, so I'm unable to mimic it.

**Comment by the-yadu** [comment]
Thank you for your response. I understand the limitation. 
Currently, I am counting the letters and multiplying it by *0.15 inch. This has done the trick for me.
That's how I am setting the width.

Thanks for putting a good library out there. Appreciate it.

**Comment by gitbrent** [comment]
Thanks @the-yadu !
