### ISSUE TITLE
addSlidesForTable css background color only works on cell level

### ISSUE THREAD

**Issue by sungkimns** [gitbrent/PptxGenJS#195]
Specifying a background color on the table, table head/body, or row does not appear correctly on the slide generated by the addSliderForTable function. Only background colors specified on the cell render correctly. The text color can be applied to any of the table components and is rendered correctly but unsure if any other style properties are affected.

**Comment by gitbrent** [comment]
Hi @sungkimns,

I'm not able to reproduce that.  The PptxGenJS demo page works correctly for me and inherits styles.

Using `examples/pptxgenjs-demo.html`:

![screen shot 2017-09-21 at 22 29 45](https://user-images.githubusercontent.com/7218970/30728328-c5956572-9f1c-11e7-8fcf-37653066d9a6.png)

![screen shot 2017-09-21 at 22 29 20](https://user-images.githubusercontent.com/7218970/30728331-c8d89c72-9f1c-11e7-8e28-9a6866db006f.png)

![screen shot 2017-09-21 at 22 30 03](https://user-images.githubusercontent.com/7218970/30728334-ccc21250-9f1c-11e7-88ee-04aed6ac71b1.png)
