### ISSUE TITLE
Unable to draw vertical line

### ISSUE THREAD

**Issue by Malangs** [gitbrent/PptxGenJS#197]
I'm currently working with shapes and I'm afraid I found a bug. You can draw horizontal lines by assigning  option `h` the value `0`. This works fine, but when I try to draw a vertical line by doing the same with the option `w`, I get a diagonal line which looks like in the picture below.
![w_zero](https://user-images.githubusercontent.com/31987637/30701817-9202516a-9eeb-11e7-83ca-29da37de52a8.png)
However, if I use a very small value it (almost) looks like what I need. In the following image i used `0.01`.
![w_epsilon](https://user-images.githubusercontent.com/31987637/30702080-3c252abe-9eec-11e7-8d6d-9b198e2b76bd.png)
Tested this by using the `line` option in `defineSlideMaster` as well as directly via `addShape` and tried the latest release plus the latest commit, but the behavior remains the same.
After a look in the code I think I could identify the root cause. In the function `addShapeDefinition` there is the line `options.w = ( options.w || 1.0 );`. If `options.w` is zero, `1.0` will be assigned, so `options.w` can never be zero.

**Comment by gitbrent** [comment]
Using zero-width shapes for lines is not the intended method...

See discussion in: Issue #112

**Comment by Malangs** [comment]
Hi @gitbrent, thanks for the response. I understand that a line with a width of zero makes no sense and rotating is the intended method, but as Kurtis mentioned in the referenced issue, it rotates around the center point which is not convenient all the time. So I guess I will tweak the library for now...
