### ISSUE TITLE
Get size of exported PPTx file

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#198]
On **pptx.save()** method, a PPTx file gets downloaded with 'n' no. of slides. How can someone get to know the size of that PPTx file.  (in B/KB/MB)

**Comment by sangramjagtap** [comment]
I am using javascript client slide version of Pptxgenjs. And have analytics applied on it, which tracks for ppt download, average number of slides in ppt and average file size. 

is there any callback or return value set to .save() method which will share basic file data on save.
e.g. name of file, size of file, etc

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

It doesn't look like this is possible outside of Node.js (which can obviously use `fs` to get the filesize post-export).

See [JSZip Issue](https://github.com/Stuk/jszip/issues/247)
