### ISSUE TITLE
Discrepancy between docs and code regarding setting a slide's background

### ISSUE THREAD

**Issue by msambarino** [gitbrent/PptxGenJS#207]
Hey there, first of all, thanks a bunch for this awesome library!

I noticed an error while trying to set a slide's background and managed to track it to the fact that the docs state that slide background should be set as `slide.bkgd` but the code looks for `slide.back`. Not sure which is the right one :)

https://github.com/gitbrent/PptxGenJS/blob/e92834cfb9100cf4afe9e15044bacbdc1846a3a3/dist/pptxgen.js#L643

Thanks again!

**Comment by gitbrent** [comment]
Hi @msambarino ,

Thanks for the feedback and for opening this Issue.  The docs were wrong - it is supposed to be `back`.

I've updated the README.
