### ISSUE TITLE
Bubble Chart Development

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#208]
Hello, all,
   How to create bubble chart using pptxgenjs project.
Thanks in advance!
Shrikant Bhongade
shri.bhongade@gmail.com

**Comment by gitbrent** [comment]
Hi @shrikantbhongade ,

Thanks for the suggestion.

Bubble charts are an option now (main branch, targeted for v1.10.0)

![screen shot 2017-10-15 at 23 01 42](https://user-images.githubusercontent.com/7218970/31594828-12950b78-b1fd-11e7-8cf5-01bb4745301d.png)

**Comment by aranand2006** [comment]
Kindly send me the Bubble chart code with example

i have used follwing data structure and get not the result
var arrDataScatter1 = [
			{ name:'X-Axis',    values:[-5,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25] },
			{ name:'X-Value 1', values:[12, 20, 21, 25] },
			{ name:'Y-Value 1', values:[12, -22, 25, 49] }
		];

for example x:10 y:12. so bubbles are located in x value 10th location and y value 12th Location in the charts.

**Comment by aranand2006** [comment]
![image](https://user-images.githubusercontent.com/6480594/44014416-7e2a76be-9ee9-11e8-8268-3ef7f69b1bdb.png)
kindly send  me the example code of above images

**Comment by gitbrent** [comment]
@aranand2006 

https://github.com/gitbrent/PptxGenJS/blob/d2293b761748f15652f0dc23cd6e59b09aa1a3ff/examples/pptxgenjs-demo.js#L1457

**Comment by AtulSalaria** [comment]
is there any way to add Labels to each bubble

**Comment by jsvishal45** [comment]
Is there a way to add custom label in each bubbles
