### ISSUE TITLE
Bullet List Issue

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#209]
Hello,
How to create bullet list containing another bullet list in PPT? I have the sample attached file, please check.
Thanks,
Shrikant
shri.bhongade@gmail.com
![2017-10-06_1919](https://user-images.githubusercontent.com/6658215/31280839-5626018c-aacb-11e7-9275-d36986e15e1d.png)

**Comment by gitbrent** [comment]
Hi @shrikantbhongade ,

Those are bullets with different `indentLevel` values.

See [README](https://github.com/gitbrent/PptxGenJS#text-options) for options and `examples/pptxgenjs-demo.html` for code.

![screen shot 2017-10-06 at 22 44 15](https://user-images.githubusercontent.com/7218970/31304554-0272a3f6-aae9-11e7-8887-dde1298eadfd.png)

**Comment by shrikantbhongade** [comment]
Thanks for correcting me
I have 2 more question again.

How to set bullet dot color only?
How set bullet with "-"?

Please refer my above-attached image.
Thanks!
Shrikant
shribhongade@gmail.com

**Comment by gitbrent** [comment]
Bullets are the color of the text.
Bullet type is in the [README](https://github.com/gitbrent/PptxGenJS#text-options) - choose any unicode dash character:
`bullet:{code:'2605'}`
