### ISSUE TITLE
Pagination for slideObj.addTable() ?

### ISSUE THREAD

**Issue by TheDorkSide74** [gitbrent/PptxGenJS#21]
I'm absolutely loving this project so far, thanks for the great work!

Is an option for automatic pagination in slideObj.addTable() in the works? This is the one thing that's preventing me from being able to use this project in production.

**Comment by gitbrent** [comment]
Thanks for the feedback!

You know, that's a good idea.  The `addSlidesForTable` method does pagination now, so I should be able to just take an `addTable()` object and work with that to create slides as needed...

**Comment by itskun** [comment]
Can you explain how to apply this method to a particular table? I do not quite understand how it works from the example.

**Comment by gitbrent** [comment]
Hi @itskun,

What the submitter requested (automatic paging of tables across slides) isn't completed yet.

You can use `addSlidesForTable()` if you have an HTML table you're trying to place in a Presentation.

@TheDorkSide74
This is done in my local branch and i'm working on updating the demo page and docs now.

**Comment by gitbrent** [comment]
Hi Guys @TheDorkSide74 @itskun,

Tables auto-page now and i've included an example of this new feature in the `examples/pptxgenjs-demo.html` file.

Let me know how they work or if you have any feedback.

**Comment by gitbrent** [comment]
The version checked in today (APP_REL = "20170209") fixes some minor issues with table paging and i've added some more examples to the demo page
