### ISSUE TITLE
Rotate Text in table cell

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#212]
Hello all,

How to Rotate text from table cell with 90 degree.
Thanks
shri.bhongade@gmail.com

**Comment by gitbrent** [comment]
Please provide the code you've written thus far and the results.

**Comment by apurupa281** [comment]
@gitbrent Even I am facing the same issue not able to rotate the text within the table cell.

whereas i was able to rotate it when we use slide.addText directly. Please let me know if there is any solution for this. 

email address: apurupachintala@gmail.com

**Comment by evgenyzhdanov** [comment]
@gitbrent Can you please provide me details on how to rotate the text within the table cell, too? I've already tired 'vert: "vert270"' and 'rotate : 270' properties and doesn't succeed.
let arrTabRows1 = [
                    [
                        { text: "M&A", options: { fill: "666E70", color: "ffffff", align: "center", valign: "middle", bold: true, rowspan: 3, vert: "vert270", rotate : 270} },
                        { text: "Top Lft", options: { valign: "top", align: "left", fontFace: "Arial" } },
                        { text: "Top Ctr", options: { valign: "top", align: "center", fontFace: "Courier" } },
                        { text: "Top Rgt", options: { valign: "top", align: "right", fontFace: "Verdana" } },
                    ],
                    [
                        { text: "Mdl Lft", options: { valign: "middle", align: "left" } },
                        { text: "Mdl Ctr", options: { valign: "middle", align: "center" } },
                        { text: "Mdl Rgt", options: { valign: "middle", align: "right" } },
                    ],
                    [
                        { text: "Btm Lft", options: { valign: "bottom", align: "left" } },
                        { text: "Btm Ctr", options: { valign: "bottom", align: "center" } },
                        { text: "Btm Rgt", options: { valign: "bottom", align: "right" } },
                    ],
                ];
email address: evgeny.z@websolo.ca

**Comment by L-Actalia** [comment]
[See Issue 755](https://github.com/gitbrent/PptxGenJS/issues/755)
> The author has added this feature in a [commit of version 3.13.0-beta.0](https://github.com/gitbrent/PptxGenJS/commit/7c778ecdc55a69bff446281c2b7de6c27387e001) (not available in a cdn at the moment)
> Syntax looks like this :
> `rows.push({ text: "Hello world", options: { textDirection: "vert270" } }) //Or textDirection: "vert"`
