### ISSUE TITLE
Creating Table issue

### ISSUE THREAD

**Issue by shrikantbhongade** [gitbrent/PptxGenJS#213]
Hello all,
I want to create the table like that. Please refer my attached image. I am able to generate table but I have the issue in the second row how to split into 2 and see 3rd row as well.

![image](https://user-images.githubusercontent.com/6658215/31440238-d037fd60-aeac-11e7-9c6c-f68b210c0ce4.png)

**Comment by gitbrent** [comment]
I'd rather you not open an Issue for every minor question you have.

There's not a support bulletin board or anything setup here on GitHub, but you can go to StackExchange and use the `pptxgenjs` tag to view other questions and/or create new ones.

Lastly, you really should look at the `examples/pptxgenjs-demo.html` file.
