### ISSUE TITLE
reduce space between bullet and text 

### ISSUE THREAD

**Issue by ade212** [gitbrent/PptxGenJS#214]
No idea how I can reduce the space between the bullet and  text ? 

Many help for your help 

![image](https://user-images.githubusercontent.com/32713349/31453231-b757da04-aeb1-11e7-97d1-5bf376f5a97b.png)

**Comment by gitbrent** [comment]
Hi @ade212 

There's no option to adjust this spacing that I can find in PowerPoint.

The default is a normal looking amount though:

![screen shot 2017-10-11 at 20 55 45](https://user-images.githubusercontent.com/7218970/31475488-bed1e72e-aec6-11e7-8589-94cb96d6293d.png)

**Comment by ade212** [comment]
There is one way, just explan how 

![image](https://user-images.githubusercontent.com/32713349/31486249-21a34418-af37-11e7-99a8-6c07ceb46cf2.png)

the result 
![image](https://user-images.githubusercontent.com/32713349/31486371-8dc65748-af37-11e7-87d5-b4fccd625f2b.png)

pptx used below ..
without modification P1.pptx 
[P1.pptx](https://github.com/gitbrent/PptxGenJS/files/1378600/P1.pptx)
the result is in p2.pptx the
[P2.pptx](https://github.com/gitbrent/PptxGenJS/files/1378605/P2.pptx)

**Comment by gitbrent** [comment]
Hi @ade212 ,

Ah, you found it.  Paragraph indent does adjust that space.  I'm already using a default for that value, and that's what you're looking to adjust.  Looking at the colored bullets above, those various indent levels are this default * 1, etc.

Try adjusting the value on line 3336: `var bulletLvl0Margin = 342900;`

914400 is one inch, so the default being used is about 1/3 of an inch.

**Comment by adrienco88** [comment]
Hi @gitbrent ,

In order to provide an easier way to change this value for the spacing between the bullet and the text, I created a new variable and changed some code in you library so I can change this from my script. Here are the modifications done in case somebody else is looking for a solution:

1. Create a variable in the Presentation Property Defaults:
after line 183 add:

```javascript
/** @type {Number} global variable to define the default indent space, also used for space between bullet and text */
    gObjPptx.defaultIndentSize = 342900;
```

2. Replace the hardcoded value with the Presentation Property
line 3552 
```javascript
var bulletLvl0Margin = 342900;
```
replace with:
```javascript
var bulletLvl0Margin = gObjPptx.defaultIndentSize;
```

3. Create the setter function
around line 4375 add:
```javascript
	/**
	 * Sets the Presentation's default Indent size
	 */
	this.setDefaultIndentSize = function setDefaultIndentSize(intSize) {
		gObjPptx.defaultIndentSize = intSize || 342900;
	};
```

After this, you can use it in your script like:
```javascript
var pptx = new PptxGenJS();
// set the default indent size to be around 1/5 of an inch (0.18 inch)
pptx.setDefaultIndentSize(171450);
```

Best Regards,
Adrian

**Comment by Kevin-McIsaac** [comment]
This would be valuable as an option or a function I can call without changing the code.

**Comment by skittishsahil** [comment]
> No idea how I can reduce the space between the bullet and text ?
> 
> Many help for your help
> 
> ![image](https://user-images.githubusercontent.com/32713349/31453231-b757da04-aeb1-11e7-97d1-5bf376f5a97b.png)

need help, unable to resolve this issue

**Comment by gitbrent** [comment]
@skittishsahil 

![Screen Shot 2021-04-28 at 22 10 17](https://user-images.githubusercontent.com/7218970/116498097-8ff50300-a86e-11eb-88af-93afa1ef5a18.png)

![Screen Shot 2021-04-28 at 22 08 55](https://user-images.githubusercontent.com/7218970/116498093-8cfa1280-a86e-11eb-9a8b-10bf584334d6.png)

**Comment by Ezra-Bartlett** [comment]
I'm still having issues with this.  I've tried adding indent, margin, and marginPoint. The text still comes out an awkward distance away from the bullet. Any ideas how I can fix this?
<img width="189" alt="image" src="https://github.com/gitbrent/PptxGenJS/assets/108287646/6abbff64-0d17-42a1-919d-bdb4bb7f8797">
