### ISSUE TITLE
Put the legend inside the bar chart

### ISSUE THREAD

**Issue by phavanagi** [gitbrent/PptxGenJS#215]
Hi,

I would like to put the legend inside the bar chart, but i see options like 
legendPos: 't', //'r','l','tr' etc.

Attached is the expected output-

![legend](https://user-images.githubusercontent.com/31074908/31465082-de738036-aea0-11e7-973f-4be4f7493223.jpg)

Is there a way to over ride this and provide the exact coordinates of the legend? Kindly help!

**Comment by gitbrent** [comment]
That's not an option offered by PowerPoint that i'm aware of.

**Comment by phavanagi** [comment]
Hi @gitbrent ,

Is there a way I can provide the x and y coordinates to the Legend? This may be a workaround since the option is not provided by Power point.

**Comment by gitbrent** [comment]
Sorry, no such options exists.  It is PowerPoint though, you are welcome to create a legend yourself and order it on top of the chart using `x` and `y`...

![screen shot 2017-10-12 at 23 01 18](https://user-images.githubusercontent.com/7218970/31529821-56fefed0-afa1-11e7-9ef9-8e50aeffc24b.png)
