### ISSUE TITLE
Passing HTML

### ISSUE THREAD

**Issue by SylarVolkoff** [gitbrent/PptxGenJS#218]
Hi, 

First of all, Good job ! I like this !

Will the possibility to pass HTML code be added ? 

Thanks.

**Comment by gitbrent** [comment]
Hi @SylarVolkoff ,

Thanks for the feedback!

Can you give me an example of the functionality you're asking about?  For example, would you be passing an HTML table as a string and producing 1-N slides.

**Comment by SylarVolkoff** [comment]
Hi!

Well, I'm working on a presentation generator with javascript, PHP and
QuillJS . Actually I generate either an html file (contains the slides and
js for animations) and a pdf file. Now I'm trying to make a PowerPoint
file. So, I was wondering if I can pass html tags like bold, italic, sizes,
text color (CSS), images... That the user can have with QuillJS (text
editor).

Thank you for the rapidity.


Le 21 oct. 2017 06:00, "Brent Ely" <notifications@github.com> a écrit :

Hi @SylarVolkoff <https://github.com/sylarvolkoff> ,

Thanks for the feedback!

Can you give me an example of the functionality you're asking about? For
example, would you be passing an HTML table as a string and producing 1-N
slides.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitbrent/PptxGenJS/issues/218#issuecomment-338361958>,
or mute the thread

**Comment by gitbrent** [comment]
Okay, i see what you mean.

Decoding HTML to PPT is not something i plan to support in the API at this time.  You could probably just write a small wrapper function or library that would call the PptxGenJS methods for a given HTML tag.
