### ISSUE TITLE
Saving the PPT as PDF?

### ISSUE THREAD

**Issue by phavanagi** [gitbrent/PptxGenJS#219]
Hi @gitbrent ,

Is there a way i can save the PPT as PDF?

**Comment by gitbrent** [comment]
Hi @phavanagi ,

Thanks for the question.

The library generates lots of XML, then exports it (PPTX file, stream, etc.), so i'm not aware of an easy way to convert that to PDF off-hand...

**Comment by phavanagi** [comment]
Thanks @gitbrent , if you come to know of any way, kindly let me know.

**Comment by gitbrent** [comment]
Will do.

**Comment by somprabhsharma** [comment]
@phavanagi @gitbrent Were you able to find a way to save the PPT as PDF?

**Comment by ketansp** [comment]
+1 for this feature or workaround.

**Comment by prashanthv** [comment]
+1 for this feature

**Comment by jorben** [comment]
+1 for this feature

**Comment by gitbrent** [comment]
Appreciate all the +1 comments, but this library is designed to create PowerPoints, not PDFs...

If anyone finds a way to bolt on jsPDF or something, please let us know, but PDF functionality will not be included natively as its way outside the scope of the library.
