### ISSUE TITLE
Table autopage not working with word-level formatting in cell

### ISSUE THREAD

**Issue by ineran** [gitbrent/PptxGenJS#223]
Hello,

Auto page works just find when I format the rows like this:

`var rows = [

	[
	'Priority 2',
	{text:'Line 1\nLine 2\nLine3', options:{bullet:{code: '2022'}, color:'000000'}},
	{text:'At Risk', options: {fill:'BA2A42', color:'FFFFFF', align: 'c'}}
	]]`

However, if I try to do word-level formatting in a cell, like the following, autopage no loner works:
`var testText = [
        {text:'Header', options:{color:'000000'}},
        {text:'Line 1\nLine 2\nLine3', options:{bullet:{code: '2022'}, color:'000000'}},
    ];

var rows = [

	[
	'Priority 1',
	{text: testText},
	{text:'On Plan', options: {fill:'23B5E2', color:'FFFFFF', align: 'c'}}
	],

`

I removed many of the rows to save space, but in my actual project I have about 6 rows which autopage when I do not do the word-level formatting trick.

**Comment by gitbrent** [comment]
Hi @ineran ,

That is correct.  Auto-paging does not currently work when complex text objects are used.

Piecing together the various ways in which the text is formatted and accounting for that is beyond the paging engine at this time.

**Comment by fred31330** [comment]
Hi @gitbrent,
I noticed that latest release (3.5.0 at the time of this comment) still does not support auto-paging when tables contain fine-grained text formatting (complex text objects). Do you have some plans to integrate it at some point?
Thanks!
