### ISSUE TITLE
Is there a way to render a path like you would using SVG?

### ISSUE THREAD

**Issue by heavysixer** [gitbrent/PptxGenJS#224]
Wondering if this library supports more than the basic straight line and would support something like:

`<path d="M10 10 C 20 20, 40 20, 50 10" />`

**Comment by gitbrent** [comment]
Hi @heavysixer ,

Unfortunately, no.  The OOXML/PPT spec doesn't support this type of drawing that i'm aware of.  SVG images can be added to a presentation, but Microsoft doesn't render them - even in PowerPoint Online.

**Comment by heavysixer** [comment]
@gitbrent Thank you for the prompt reply, I am curious how are the shapes you do support generated, i.e. the squares, triangles and the like. I see reference to them in the source but they don't seem to be actually building the shapes themselves... are they referencing some sort of built in functionality with powerpoint?

**Comment by gitbrent** [comment]
Sure.

Shapes are defined using the Open Office XML Presentation spec: [Shapes](http://officeopenxml.com/prSlide-shapeTree.php)
