### ISSUE TITLE
Line chart with one series displays broken in Powerpoint with version 1.9.0

### ISSUE THREAD

**Issue by andrei-cs** [gitbrent/PptxGenJS#225]
Adding a series like in the example:

var MONS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
var dataChartLine = [
    {
        name: 'Proj Sales', labels: MONS,
        values: [1000, 2600, 3456, 4567, 5010, 6009, 7006, 8855, 9102, 10789, 11123, 12121]
    }
]; 
slide.addChart(
    pptx.charts.LINE, dataChartLine,
    { x:4.3, y:4.0, w:4.0, h:3.2, chartColors:['0088CC','99FFCC'], chartColorsOpacity:25,
    dataBorder: {pt:2, color:'FFFFFF'}, fill:'D1E1F1' }
);

creates a chart that displays a legend item for each label in the MONS set. 

![image](https://user-images.githubusercontent.com/3409418/32368728-6d6114ca-c08f-11e7-9fc0-7ee42249f1ee.png)

When trying it with v1.7.0 everything looks fine. Graphs with two series display correctly.

**Comment by gitbrent** [comment]
Hi @andrei-cs ,

Thanks for opening this issue!

The defect was triggered when using a single data series along with the `chartColors` option.

```javascript
var MONS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

var dataChartLine = [{ name: 'Proj Sales', labels: MONS, values: [1000, 2600, 3456, 4567, 5010, 6009, 7006] }];
var dataChartLine2 = [
	{ name: 'Proj Sales 1', labels: MONS, values: [2000, 2600, 3456, 4567, 5010, 6009, 7006] },
	{ name: 'Proj Sales 2', labels: MONS, values: [2100, 2600, 3456, 4567, 5010, 6009, 7006] }
];

slide.addChart( pptx.charts.LINE, dataChartLine, { x:.5, y:1, w:6, h:3, chartColors:['0088CC'],showLegend: true });
slide.addChart( pptx.charts.LINE, dataChartLine, { x:.5, y:4, w:6, h:3, showLegend: true });
slide.addChart( pptx.charts.LINE, dataChartLine2, { x:6.5, y:1, w:6, h:3, chartColors:['0088CC'],showLegend: true });

pptx.save('PptxGenJS-Sandbox_'+getTimestamp());
```

Before:
![screen shot 2017-11-06 at 21 00 54](https://user-images.githubusercontent.com/7218970/32475206-43ac541a-c336-11e7-859b-e8ce2dbcbc38.png)

After:
![screen shot 2017-11-06 at 21 01 25](https://user-images.githubusercontent.com/7218970/32475212-4700f33c-c336-11e7-9432-3ef1c15b3c96.png)

**Comment by andrei-cs** [comment]
Thanks for the quick response. I guess it will go out with 1.10.0 release.

**Comment by gitbrent** [comment]
Yes, it's tagged for v1.10.0 - it'll be released this month.
