### ISSUE TITLE
How is chart data formatted into sizes like Kb, MB, etc.?

### ISSUE THREAD

**Issue by RavalikaP** [gitbrent/PptxGenJS#227]
Hi,

I want to show the formatted date on charts like 3K(instead of 3000).
Is there anyway to send the formatted data and show on charts after it plots??

Thanks in advance

**Comment by gitbrent** [comment]
Are you looking for the `dataLabelFormatCode` under [Chart Data Options](https://github.com/gitbrent/PptxGenJS#chart-data-options)?

It takes standard Microsoft formatting strings like: `'#.0'`

**Comment by RavalikaP** [comment]
Hi @gitbrent ,

Can I get some example?

Thanks in Advance

**Comment by gitbrent** [comment]
Any of the codes on the Microsoft [Number Format Codes](https://support.office.com/en-us/article/Number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68) page will work.

You'd use what they show to reduce my 1,000's: "To display a comma as a thousands separator or to scale a number by a multiple of 1000, include a comma (,) in the code for the number format."

```javascript
slide.addChart(
	pptx.charts.BAR,
	[
		{
			name  : 'Two Color Series',
			labels: ['Jan', 'Feb','Mar', 'Apr', 'May', 'Jun'],
			values: [2000, 3000, 1000, 2500, 1500, 9999]
		}
	],
	{  x:0.5, y:4.0, w:'45%', h:3,
		barDir: 'bar',
		chartColors: ['0077BF','4E9D2D','ECAA00'],
		dataLabelPosition: 'outEnd',
		dataLabelFormatCode: '#,K',
		valAxisLabelFormatCode: '#,###',
		showValue: true
	}
);
```

![screen shot 2017-11-06 at 21 54 29](https://user-images.githubusercontent.com/7218970/32476497-59205bc8-c33d-11e7-9ebc-e43b013eb2d7.png)
