### ISSUE TITLE
Request: add Master Slide placeholder

### ISSUE THREAD

**Issue by ineran** [gitbrent/PptxGenJS#228]
Is there anyway to Insert a "Placeholder" (this is the PowerPoint name) to a Master slide?

**Comment by gitbrent** [comment]
Hi @ineran,

That feature is not supported yet, so i'll add it an enhancement.

**Comment by ManyBaby** [comment]
Hi @gitbrent,
This library is very impressive I have to say. This could be a game changer feature for me to create placeholders in a Slide Master that I can fill when creating a new slide from this Slide Master.

**Comment by gitbrent** [comment]
Hi @ManyBaby,

Thanks!  I haven't researched what changes need to be made to support this yet.  Let me look into the level of effort...

**Comment by ManyBaby** [comment]
Thank you for your quick answer. Currently we are using a python library but we want to refactor to js.
Here is a link to this library documentation about placeholders:
http://python-pptx.readthedocs.io/en/latest/user/placeholders-understanding.html?highlight=placeholder

Hope this helps @gibrent.

**Comment by freekvdp** [comment]
Hi, I was wondering if there's any update on this?
