### ISSUE TITLE
Master Slide slide number doesn't show using "New Slide" PPT Function

### ISSUE THREAD

**Issue by ineran** [gitbrent/PptxGenJS#229]
When I add slideNumber to a master slide, it works fine when I add that slide from JS. 

But once I'm in the PowerPoint, and I try to add a new slide with the predefined master slide, the slide number does not show up.

Copy and pasting existing slides DOES however keep the slide number.

**Comment by gitbrent** [comment]
Hi @ineran ,

The way the library adds slide numbers is non-standard, so yes, this is known issue.

**Comment by gitbrent** [comment]
Hi @ineran,

Thanks for opening this issue.

Slide Numbers are created per the standard method now and are available on new slides, etc.

Slide Numbers on Slide Master and Layout:
![screen shot 2017-11-26 at 22 26 10](https://user-images.githubusercontent.com/7218970/33251014-f15339c6-d2f9-11e7-9a35-d1168d40a27c.png)

New Slide with numbers:
![screen shot 2017-11-26 at 22 27 21](https://user-images.githubusercontent.com/7218970/33251025-16a0709a-d2fa-11e7-90b1-d2a6bd757270.png)
![screen shot 2017-11-26 at 22 27 38](https://user-images.githubusercontent.com/7218970/33251028-1a47d7ec-d2fa-11e7-90b2-3140ef01f959.png)
