### ISSUE TITLE
Supported usage via node program instead of HTML

### ISSUE THREAD

**Issue by parsleyt** [gitbrent/PptxGenJS#23]
Hello,

I am a nodeJS newbie and I apologize if this is a basic question.

I'm attempting to use PptxGenJS from a simple standalone nodeJS script.  I've used NPM to install the pptxgenjs module locally.    When I try to import the module into my script, the require keyword returns an empty object.

Here is my code where `pptxgenjs`  is the empty object that is returned.

`var pptxgenjs = require ('pptxgenjs'); `
  
Is this a supported use of PptxGenJS? I notice the examples are all called from an HTML page.  

If so, can anyone help me understand how to import the module into my script?

Thanks,
Travis

**Comment by gitbrent** [comment]
Hi Travis,

Release v1.1.5 (npm 1.1.5-1) fixes the broken Node.js integration.

There's now a Node test file under ./examples that can be run using `node nodejs-demo.js`

Thank you for reporting this!
