### ISSUE TITLE
Custom curve shape?

### ISSUE THREAD

**Issue by smhanov** [gitbrent/PptxGenJS#230]
How can we create a bezier curve or polygon? For example, I can draw a line using the pencil tool in Powerpoint but I don't see any way to create it in PptxGen.

**Comment by gitbrent** [comment]
Hi @smhanov ,

The library does not currently support anything outside of the what's in the `pptxgen.shapes.js` file.

**Comment by prasademc** [comment]
How to create the shape triangle 
Like : slide3.addShape(pptx.shapes.ISOSCELES_TRIANGLE, { x:4.15, y:0.75, w:5, h:2, fill:{ type:'solid', color:'0088CC', alpha:25 } });

I am getting an error

**Comment by gitbrent** [comment]
@prasademc - have you included the shape library?
`<script type="text/javascript" src="../dist/pptxgen.shapes.js"></script>`

```javascript
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

slide.addShape(
    pptx.shapes.ISOSCELES_TRIANGLE,
    { x:4.15, y:0.75, w:5, h:2, fill:{ type:'solid', color:'0088CC', alpha:25 }}
);
pptx.save('PptxGenJS-Sandbox_'+getTimestamp());
```

![screen shot 2018-03-19 at 18 41 19](https://user-images.githubusercontent.com/7218970/37628032-62028d26-2ba5-11e8-8875-e837be6bd33e.png)

**Comment by gurdeep-sourcefuse** [comment]
@gitbrent 
is there any way to draw a bell curve?
![image](https://user-images.githubusercontent.com/78344911/116832257-c2d22a80-abd1-11eb-9c72-16c17ae93a5b.png)
Referenced video of the bell curve: https://www.youtube.com/watch?v=dysqb2vEkh0
