### ISSUE TITLE
*AxisLineShow options do not work

### ISSUE THREAD

**Issue by mconlin** [gitbrent/PptxGenJS#231]
It appears that both the `catAxisLineShow` and `valAxisLineShow` options don't change anything when generating a chart.  True or false, the axis lines will always show up.

Looking at the source code for building the axes, I couldn't find any reference to these options.  Maybe I'm missing something, but it seems like functionality might have been lost somewhere along the line with regard to these options.

There are some working options that produce a result that is close to what is desired. 
 `catAxisHidden`, for example, does indeed hide the axis line, but it also hides the category text at the same time, which is not desired.

**Comment by mconlin** [comment]
I've created a pull request with a potential fix: https://github.com/gitbrent/PptxGenJS/pull/232

**Comment by gitbrent** [comment]
Thanks @mconlin! The Issue has been fixed in the current codebase.

These options were indeed lost in a past merge.
