### ISSUE TITLE
New Chart option: Legend Text Color

### ISSUE THREAD

**Issue by mconlin** [gitbrent/PptxGenJS#233]
Currently, there appears to be no way to specify a custom color for legend text.  It appears to always default to black.

Other similar aspects of graphs, like titles (`titleColor`) and category labels (`catAxisLabelColor `), can have colors specified.  It would be nice to be able to specify legend colors as well.

**Comment by mconlin** [comment]
I've created a pull request with a potential solution: https://github.com/gitbrent/PptxGenJS/pull/234

**Comment by gitbrent** [comment]
Thanks for the contribution @mconlin !
