### ISSUE TITLE
Pass a var into options

### ISSUE THREAD

**Issue by SylarVolkoff** [gitbrent/PptxGenJS#235]
Hi !

Is it possible to pass a var into the slide.addtext() options ?

Here's an example of what I'm trying to do:
`
// Contains tags			
var tags = ['\<b>', '\<strong>', '\<i>'];
// Contains full tags for options in slide.addText()
var tagsOptions = ['bold', 'strong', 'italic', ''];
				
for(var z = 0; z < tags.length; z++) {
					
	if (str.search(tags[z]) != -1) {
		var typeStyle = tagsOptions[z];

		slide.addText(
			 [
			  {text: $(str).text(), options: typeStyle : true },
			 ],
			  { x:0.0, y:1, h:1.5, align:'c'}
				);
	}
}`

Thanks.

**Comment by gitbrent** [comment]
Sure, the text `options` is just a javascript object with property names and values.

Your example is not valid JavaScript, so that's likely the issue.

Also, `options` should be an object, not "typeStyle : true"

**Comment by SylarVolkoff** [comment]
Thanks for your help. This works now. 

I have another question about options again. This is why I didn't open a new issue. 
Can we use an object array too into x and y coordinates ? I made an array  that contains :  

```
[x: 0, y: 1, h: 1.5, align: "c"]
align : "c"
h : 1.5
x : 0
y : 1

Type of : object
```

The type of it is an object, but it's ignored. I want this to auto-increment y for each line.

And the code is : 

`slide.addText(
	[
		{ text: $(str).text(), options:tagsstyle }, 
	],
		{coordinates}
);
`

Where coordinates contains x, y, h and align. If I use something like **{x:0.0, y:1, h:1.5, align:'c'}** it's ok but not with an array.

Thank you for your help.
