### ISSUE TITLE
MS office version problem in 2007 shows error and in 2013 works fine

### ISSUE THREAD

**Issue by gauravjain024** [gitbrent/PptxGenJS#247]
In MS office 2007 it shows error as shown in image for the area chart and that slide is repaced by blank slide. Can someone help me to resolve this issue

![image](https://user-images.githubusercontent.com/12432506/33126698-694fad1c-cfab-11e7-9fc6-12ace4662a28.png)

**Comment by gitbrent** [comment]
Duplicate issue - see Issue #241
