### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by adrienco88** [gitbrent/PptxGenJS#249]
Hi @gitbrent ,

I have some improvements for the library but I'm not sure if commiting them into master it's a good idea and I can't create a new branch in the repo. can you create a branch named _improvements_ or something where we can push?

The following improvements will be available:
1. Default Indent Size: The option to set a default global indent size used also for the space between bullets and text.

2. Shapes / Text border cap: for example the dotted borders are by default square dots, setting the _cap_ option to _rnd_ it will draw rounded dots on the border

3. Table cell border type: allow you to add different border styles for table cells (line, dotted+rounded, dash etc) and cell background color with transparency.

4. Image object improvements: 
    - Background color + Transparent bg color
    - Image transparency
    - Image rotation
    - Image borders (size, type, color, cap)

Thanks,
Adrian

**Comment by gitbrent** [comment]
Hi @adrienco88,

Improvements are submitted via pull requests.  Create a fork of PptxGenJS, then develop, test and document your changes.  Create a Pull Request when you're done.

See [the docs](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for more info.
