### ISSUE TITLE
Page Number Y position.

### ISSUE THREAD

**Issue by priyaraskar** [gitbrent/PptxGenJS#25]
I need to set y positions of Page Numbers.
I am using 'LAYOUT_WIDE' layout for slides.
but when i set isNumbered : true, it is showing page number middle of the slide.
like this:
![image](https://cloud.githubusercontent.com/assets/24734651/22095424/9682b7b0-de3a-11e6-8359-ca00e20918ba.png)

Can you please help me in this.

**Comment by gitbrent** [comment]
Done!

Thanks for requesting this.
