### ISSUE TITLE
Relative URL for Image Path IE 11

### ISSUE THREAD

**Issue by ineran** [gitbrent/PptxGenJS#250]
I'm sorry, I can't tell if this is a PptxGenJS issue or an internet explorer issue or both. 

Here is an example of my code:

```
pptx.defineSlideMaster({
  title:` 'Title Slide With Picture 1',
     bkgd:`  {path: "../pptReportAssets/images/bkgdImage.png" },
      objects:` [
        {` 'image': { x:11.58, y:5.78, w:1.31, h:1.31, path: "../pptReportAssets/images/logoTitleBlue.png" } }
      ],
      slideNumber:` { x:0.42, y:7.17, font_face:'Calibri', fontSize:7, color:'FFFFFF' }
    });
  };
```

In FireFox, Chrome, and Edge this all works just fine. However, in Internet Explorer, it doesn't like the relative path here.  I can use the same relative path as a link on my HTML page and it works fine.  

Internet Explorer appears to take this relative path, and turn it into an absolute path. So....

Let's say I'm in the following directory:
http://localhost/TopDir/SecondDir/

By using the relative path above, I would expect it to go here: (and it does in the other browsers):
http://localhost/TopDir/pptReportAssets/images/bkgdImage.png

But with Internet Explorer, it goes here:
http://localhost/TopDir/SecondDir/../pptReportAssets/images/bkgdImage.png

I also tried something simpler 
`slide.addImage({ path:'../pptReportAssets/images/logo.png', x:1.0, y:1.0, w:8.0, h:4.0 });`

This also does not work in Internet Explorer.

**Comment by gitbrent** [comment]
Hi @ineran,

I tested this issue today on Windows 10 using IE11 and the image loaded successfully for me.

`slide.addImage({ path:'../logo.png', x:1.0, y:1.0, w:1.0, h:1.0 });`

I'm not sure why you're experiencing this issue... If you find anything, please let me know.

**Comment by ineran** [comment]
I can't add an image at all now actually.  I've tried this on multiple devices.  I have one function in my entire HTML file...

`function createPowerPoint(){`
``
 ` var pptx = new PptxGenJS();
`  `var slide = pptx.addNewSlide();`

  `slide.addImage({ path:'logo.png', x:1.0, y:1.0, w:1.0, h:1.0 });`
  `pptx.save('Test Slides');`

`};`

When I compare the debugger in Internet Explore and Google Chrome, something happens at function convertImgToDataURLviaCanvas(slideRel) but I can't quite tell what.  In Google Chrome, it jumps right to the line that says canvas = null.  In Internet Explore it goes through the:

`catch(ex) {`
`	this.onerror();
``	return;
``	}`

"ex" says "Promise is undefined." It then takes you through this.onerror().

The console error messages I'm getting are 👍 
"Unable to load image: "logo.png"
Please check the image URL:
http://localhost/IEBug/logo.png"

and

"SCRIPT5009: Promise is undefined
pptxgn.js (1692, 3)"

I'm sorry, I thought it was an issue with relative paths but it actually appears to be something different.

**Comment by ineran** [comment]
So found something very interesting.... when I link to the library using:

<script lang="javascript" src="PptxGenJS/libs/jquery.min.js"></script>
<script lang="javascript" src="PptxGenJS/libs/jszip.min.js"></script>
<script lang="javascript" src="PptxGenJS/dist/pptxgen.js"></script>

It doesn't work. I get the errors I'm mentioning.  However, when I link to the library using:

<script type="text/javascript" src="../PptxGenJS/dist/pptxgen.bundle.js"></script>

It works. Can that be possible? lol

**Comment by gitbrent** [comment]
> SCRIPT5009: Promise is undefined

There it is - IE11 users need to include `promise.min.js` or use the bundle.

**Comment by gitbrent** [comment]
This requirement is mentioned elsewhere, but not in the README for some reason (oops), so i've added a blurb about it now.  Sorry!

**Comment by ineran** [comment]
No worries.  I'm assuming there isn't a major issue with using the bundle with other browsers, correct?

**Comment by gitbrent** [comment]
Correct.
