### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by the-yadu** [gitbrent/PptxGenJS#252]
Hi,

It's sort of warning for the upcoming versions of node.
Can someone please get rid of this warning for all of us.
`DeprecationWarning: Calling an asynchronous function without callback is deprecated.
        at maybeCallback (fs.js:133:42)
        at Object.fs.writeFile (fs.js:1283:14)
        at /Users/narayan/Sites/campaygn_v3/node_modules/pptxgenjs/dist/pptxgen.js:1624:72
        at <anonymous>
`

<img width="1070" alt="screen shot 2017-11-29 at 6 18 56 pm" src="https://user-images.githubusercontent.com/7404181/33376136-6f25c618-d532-11e7-85f6-f058dc3ffae6.png">

**Comment by gitbrent** [comment]
Hi @the-yadu,

Thanks for reporting this.

I've checked in a fix that will be in the next NPM release.

**Comment by the-yadu** [comment]
Another one.

(node:33960) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
        at maybeCallback (fs.js:133:42)
        at Object.fs.writeFile (fs.js:1283:14)
        at /Users/narayan/Sites/campaygn_v3/node_modules/pptxgenjs/dist/pptxgen.js:1620:73
        at <anonymous>
