### ISSUE TITLE
The UP_DOWN_ARROW shape appears to have duplicate keys.

### ISSUE THREAD

**Issue by heavysixer** [gitbrent/PptxGenJS#253]
https://github.com/gitbrent/PptxGenJS/blob/6eb3649f1914e22fb48ebc949fe02bbd14ff8170/dist/pptxgen.shapes.js#L1340-L1341

**Comment by gitbrent** [comment]
Hi @heavysixer,

Thanks for reporting this.

I checked the original file in the officegen project, and this issue has been fixed there, so i've copied it here as well.

https://github.com/Ziv-Barber/officegen/blob/5f96506471a395bf810ce52f75ae509fb22591a6/lib/pptxshapes.js#L1346-L1347
