### ISSUE TITLE
Objet into text

### ISSUE THREAD

**Issue by SylarVolkoff** [gitbrent/PptxGenJS#256]
Hi ! 

I have two little questions.

Can we use an object array into x and y coordinates ? I made an array that contains :

```
[x: 0, y: 1, h: 1.5, align: "c"]
align : "c"
h : 1.5
x : 0
y : 1
```

The type of it is an object, but it's ignored. I want this to auto-increment y for each line.

And the code is :

slide.addText( [ { text: $(str).text(), options:tagsstyle }, ], {coordinates} );

Where coordinates contains x, y, h and align. If I use something like {x:0.0, y:1, h:1.5, align:'c'} it's ok but not with an array.

And, can we do something like : 

`slide.addText(ppt)`

Where ppt contains : 

`ppt[w] = {
	[text: $(str).text()], 
	[options:taggstyle]
};
`

taggstyle contains : [y: 6, align: "c", breakLine: true] 

This works with : 

`slide.addText(
					[
						{ text: $(str).text(), options:tagsstyle},
					]						
				);`

The returned type is always an Object but I have this error : 

> pptxgen.js:3578 Uncaught TypeError: Cannot read property 'split' of undefined
    at pptxgen.js:3578
    at Array.forEach (<anonymous>)
    at genXmlTextBody (pptxgen.js:3565)
    at pptxgen.js:1004
    at Array.forEach (<anonymous>)
    at Object.slideObjectToXml (pptxgen.js:667)
    at makeXmlSlide (pptxgen.js:4037)
    at doExportPresentation (pptxgen.js:1669)
    at PptxGenJS.save (pptxgen.js:4407)

I'm doing an html to pptx converter. Actually I can generate the pptx but all lines are superimposed.

Thank you! :+1:

**Comment by gitbrent** [comment]
Hi @SylarVolkoff,

Thanks for the feedback.

The API only works as shown in the example and in the `README` files.

Regarding the error: ensure you're passing a valid string in the `text` option to avoid split errors, etc.

To auto-increment text you need your own loop, the library wont automate that type of thing.

```javascript
var arrY = [1,2,3,4,5];
arrY.forEach(function(yVal,idx){
  slide.addText( "yVal:"+idx, {x:1, y:yVal} );
});
```

![screen shot 2017-12-12 at 23 13 31](https://user-images.githubusercontent.com/7218970/33922717-39b2bd14-df92-11e7-8269-6786e0bbc870.png)

**Comment by SylarVolkoff** [comment]
Hi @gitbrent ,

I inspired myself with your example and you solve 3 problems I have with your 4 lines :rofl:.

To the error, I was only passing text, but I resolve it with the example you send. 

Thank you !
