### ISSUE TITLE
Image not being added to slide when using Visualforce+Chrome

### ISSUE THREAD

**Issue by IvanTao** [gitbrent/PptxGenJS#259]
I'm sorry for that I can't tell if this is a PptxGenJS issue . My code write in visualforce page .below is my code:
var pptx = new PptxGenJS();
        pptx.setLayout('LAYOUT_16x9');
 var slide1 = pptx.addNewSlide('MASTER_SLIDE');
pptx.defineSlideMaster({
          title: 'MASTER_SLIDE',
          bkgd:  'FFFFFF',
          objects: [
            { 'image': { x:7.25, y:5.0, w:1.6, h:0.4, path:'{!$Resource.AptivLogo}' } }
          ],
          margin:[0.5, 0.75, 0.5, 0.75],
           //slideNumber: { x:0.3, y:'90%' }
        });
slide1.addImage({ path:"../servlet/servlet.FileDownload?file={!ProductFeatures.id}", x:7.25, y:3.25, w:1.5, h:1.5});

My code page in https://c.cs13.visual.force.com/apex/PPTGenerate
 and image url is https://c.cs13.visual.force.com/servlet/

but when I running code , The path always be https://c.cs13.visual.force.com/apex/servlet/
Can you to me what how I can get Url is https://c.cs13.visual.force.com/servlet/

I had imported js ::

<apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/libs/jquery.min.js')}" />
    <apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/libs/jszip.min.js')}" />
    <apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/dist/pptxgen.js')}" />
    <apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/dist/pptxgen.bundle.js')}" />
    <apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/libs/promise.min.js')}" />

**Comment by IvanTao** [comment]
Can I write all the url adress?

**Comment by gitbrent** [comment]
Hi @IvanTao,

You only need to include the bundle - it has all the necessary .js files.
`<apex:includeScript value="{!URLFOR($Resource.PptxGenJS,'/PptxGenJS/dist/pptxgen.bundle.js')}" />`

Are there any errors or warning are in the console?

What is the output of:
`var pptx = new PptxGenJS; pptx.version`

![screen shot 2017-12-28 at 19 00 43](https://user-images.githubusercontent.com/7218970/34426946-8be29818-ec01-11e7-90ab-c29c7f854520.png)

**Comment by IvanTao** [comment]
My output is:
![image](https://user-images.githubusercontent.com/34829050/34506679-ecc04222-f069-11e7-8977-c6f3c1852d09.png)
As you can see , console error olny  url is incorrect；my url should be:  https://c.cs13.visual.force.com/servlet/servlet.FileDownload?file=00PW0000003xTfKMAU;
Is my version incorrect?  my code below：
slide1.addImage({ path:'../servlet/servlet.FileDownload?file=00PW0000003xTfKMAU', x:9.12, y:4.26, w:3.77, h:2.51});
And I also try to write "/servlet/servlet.FileDownload?file=00PW0000003xTfKMAU"; but the url not have hostname.

**Comment by gitbrent** [comment]
Try the full path
`slide1.addImage({ path:'https://c.cs13.visual.force.com/servlet/servlet.FileDownload?file=00PW0000003xTfKMAU`

**Comment by IvanTao** [comment]
Hi,gitbrent, When I try the full path, It was showed :https://c.cs13.visual.force.com/apex/https://c.cs13.visual.force.com/servlet/servlet.FileDownload?file=00PW0000003xTfKMAU
![image](https://user-images.githubusercontent.com/34829050/35224852-6bd8910c-ffc1-11e7-9a05-bfadf6c6abec.png)
![image](https://user-images.githubusercontent.com/34829050/35224873-84570484-ffc1-11e7-9e0d-66e3ed6b3bb1.png);
 I converted the image to Base64 on the server then  method that data:'{!imageData}'; it is right to show. Thank you very much
