### ISSUE TITLE
Support for .mov/.mp4 files

### ISSUE THREAD

**Issue by shashank2104** [gitbrent/PptxGenJS#26]
Hey Brent, 

Thank you for the support for animated GIFs. They work absolutely fine. 

Could you, by any chance, extend or enhance the library to support .mov and/or .mp4 files?

**Comment by gitbrent** [comment]
Media support added!  Audio, Video and YouTube are supported and documented now.

Try it out and let me know how it works for you.

**Comment by shashank2104** [comment]
Awesome. It works out absolutely fine. Thanks a lot Brent. 👍
