### ISSUE TITLE
fill data into PPT Template?

### ISSUE THREAD

**Issue by popsugon** [gitbrent/PptxGenJS#260]
Is it possible to add data in format ppt template

**Comment by gitbrent** [comment]
Hi @popsugon

If you're asking about adding tables, there is no way to add any data to a template via `defineSlideMaster()` method.

The only objects that can added are here: [Options](https://github.com/gitbrent/PptxGenJS#slide-master-object-options)
`chart`, `image`, `line`, `rect`, `text`

Example:
```javascript
pptx.defineSlideMaster({
  title: 'CORP_MASTER',
  bkgd: 'F1F1F1',
  objects: [
    {rect: { x:0, y:0, w:'100%', h:0.5, fill:'0088CC' }},
    {text: { text:'S.T.A.R. Laboratories', options:{x:0.17, y:0.1, color:'FFFFFF'} }}
  ]
});
```

**Comment by popsugon** [comment]
Hi @gitbrent 

Wondering if your team will provide a function like below:
users provide the format template, developer only need fill in the data into the template according to shape name.

this is the actual case I met

**Comment by gitbrent** [comment]
Hi @popsugon 

That sounds like more of a tool built with PptxGenJS than a library method, so no i dont see adding like that as of now.

If you end up creating something, please let me know.
