### ISSUE TITLE
Numbered and bulleted lists

### ISSUE THREAD

**Issue by adnanafzal565** [gitbrent/PptxGenJS#261]
Hi. I am unable to find any function for adding numbered and bullet lists in PPTX gen JS. It is awesome library, please add these features too.

Thank you.

**Comment by gitbrent** [comment]
Hi @adnanafzal565 

Check out the demo for lots of bullet examples/code: `examples/pptxgenjs-demo.html`

![screen shot 2018-01-05 at 22 07 27](https://user-images.githubusercontent.com/7218970/34636362-df3f3ea8-f264-11e7-8ac0-1a7ab44d7f1f.png)

**Comment by adnanafzal565** [comment]
It is amazing. Thank you.
My mistake, I didn't find it.

**Comment by gitbrent** [comment]
No problem.

Hope you find the library useful!

**Comment by adnanafzal565** [comment]
Yes. It is exactly what I needed.
Thanks again.

**Comment by kasturi15** [comment]
Hello,
Can I know the code for numbering?

Thanks

**Comment by gitbrent** [comment]
@kasturi15 check `demos/common/demos.js`

<img width="1328" alt="Screen Shot 2020-06-02 at 23 37 34" src="https://user-images.githubusercontent.com/7218970/83596434-32571a00-a52a-11ea-8a8d-1267ffc18d86.png">
