### ISSUE TITLE
Feature Request: 'addTable()' should have an 'addHeaderToEach' option

### ISSUE THREAD

**Issue by okaiyong** [gitbrent/PptxGenJS#262]
I did this slide.addTable(rows, addHeaderToEach: true);
But it didn't work. I have checked the API documents, this API is not documented. 
Able to advise?

**Comment by gitbrent** [comment]
Hi @okaiyong,

The `addTable()` method does not utilize that option.

The [`addSlidesForTable()`](https://github.com/gitbrent/PptxGenJS#table-to-slides-feature) method is what you would use when creating auto-paginated slides.

Most users create a shadow (display:none) table on their page and then call addSlidesForTable using that temp table's ID.

Check out the demo (`examples/pptxgenjs-demo.html`) for a working example.

![screen shot 2018-01-08 at 22 16 38](https://user-images.githubusercontent.com/7218970/34704848-b0a2c466-f4c1-11e7-8cac-65336fc8ca50.png)

**Comment by okaiyong** [comment]
Hi Brent,

Thanks for replying. I was constructing a table using the lib api instead of exporting an html table.
Is it possible to do header repeat for addTable() instead? Or any solution?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by gitbrent** [comment]
That's a good suggestion.

I've marked it as a feature request and will work on it after 2.0 releases.

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by Smithvinayakiya** [comment]
So we won't be having this option in near future ??

**Comment by gitbrent** [comment]
Thanks @okaiyong 

This feature now available in the master branch and will be released with v.3.3.0

**Comment by Smithvinayakiya** [comment]
Thanks @gitbrent You are a genius

**Comment by gitbrent** [comment]
Demos added as well.

**Comment by jsvishal** [comment]
This does not seem working with colspan/rowspan in header
![image](https://user-images.githubusercontent.com/7326080/85059472-5587f780-b1c1-11ea-917d-c678c7f3bb4d.png)
![image](https://user-images.githubusercontent.com/7326080/85059512-659fd700-b1c1-11ea-877d-fffa63213a3d.png)

**Comment by gitbrent** [comment]
@jsvishal - did you specify to repeat 2 rows using: `autoPageHeaderRows:2` ?

**Comment by jsvishal** [comment]
Thank. It works. Is there any way to copy Table Heading[Produc level Performace in our case] in slides?

**Comment by jsvishal** [comment]
Also table height does not seem working in extra slide added

**Comment by gitbrent** [comment]
@jsvishal - create a master page with that heading, use it in `addSlide()` and it'll repeat across new slides. Table height is ignored during auto-paging - use slide margins to constrain the table. There are examples under `/demos/browser`

**Comment by jsvishal** [comment]
@gitbrent so in that case we have to create n master slides (if there are n different heading). I tried with placeholder text in master slide. That too was not copying itself

**Comment by gitbrent** [comment]
@jsvishal yes, for now I dont have a better solution. the work-around I use myself for my apps, is to create a master `{}` object and clone it, just changing the one bit of text i need.
