### ISSUE TITLE
Unable to plot lines as quadrant in bubble chart

### ISSUE THREAD

**Issue by glssravya** [gitbrent/PptxGenJS#263]

**Comment by gitbrent** [comment]
Hi @glssravya,

I'm not sure what this means off-hand.

Can you provide the code you're using to create the Bubble Chart and maybe a screen-cap of what you're looking to create?

**Comment by glssravya** [comment]
[
![untitled](https://user-images.githubusercontent.com/5071808/34707196-25aa3940-f532-11e7-991a-6a36d06e5a7e.png)
](url)

something like the black line.

**Comment by gitbrent** [comment]
What options are you using to create those in PowerPoint?

Ex:
![screen shot 2018-01-15 at 21 40 43](https://user-images.githubusercontent.com/7218970/34971022-a6cb9cde-fa3d-11e7-878f-04c50dcfa58a.png)
