### ISSUE TITLE
Labels are not displayed on bubbles in bubble chart.

### ISSUE THREAD

**Issue by glssravya** [gitbrent/PptxGenJS#264]

**Comment by gitbrent** [comment]
Hi @glssravya,

The only option PowerPoint offers for bubble charts is to show the values, which is enabled by `showValue: true`.

```javascript
slide.addChart( pptx.charts.BUBBLE, arrDataBubble1, {showValue: true} );
```

It's on a demo slide under examples.

![screen shot 2018-01-15 at 21 40 43](https://user-images.githubusercontent.com/7218970/34970952-1f8f193a-fa3d-11e7-8c07-da3f2b838009.png)
