### ISSUE TITLE
Missing Character Spacing option

### ISSUE THREAD

**Issue by nguyenhuuphuc83** [gitbrent/PptxGenJS#265]
Hi Brent Ely,

It would be great if you could support the "Character Spacing" option :-)

Many thanks

**Comment by gitbrent** [comment]
Hi @nguyenhuuphuc83,

Thanks for the feature request.  I've implemented the `charSpacing` option for text objects.

```javascript
{ text:'Character Spacing 16', options:{ fontSize:16, charSpacing:16 } }
```

![screen shot 2018-01-15 at 21 26 25](https://user-images.githubusercontent.com/7218970/34970644-1f55f224-fa3b-11e7-995a-10441e5138c2.png)

**Comment by nguyenhuuphuc83** [comment]
Oh my god, super thanks, @gitbrent. I would like to invite you for a cup of coffee 👍

**Comment by gitbrent** [comment]
Thanks for your suggestion!
