### ISSUE TITLE
Using the addHeaderToEach option with addSlidesForTable doesn't calculate table height correctly on slides after the first

### ISSUE THREAD

**Issue by tjrueter** [gitbrent/PptxGenJS#267]
When you check for the addHeaderToEach option in the getSlidesForTableRows() function, if the option is turned on and you add the header row, I believe you also need to update the emuTabCurrH variable with the max height of the header row.  Otherwise you'll extend the table beyond the limit of the margins of the page.

**Comment by gitbrent** [comment]
Hi @tjrueter,

Thanks for the observation.

There is no update needed as the code works by having an allocated height that is then reduced with every row added, and the repeating header row is simply another one of those rows.  Hence, there's no need to re-calc the available height.

See the loop for more details

https://github.com/gitbrent/PptxGenJS/blob/459af1037149737e47d44489d61b49508ddb28d1/dist/pptxgen.js#L2137-L2142
