### ISSUE TITLE
Underline text in table cells does not work with addSlidesForTable method.

### ISSUE THREAD

**Issue by tjrueter** [gitbrent/PptxGenJS#268]
When creating the options for each of the table rows in the addSlidesForTable function, you are not checking to see if text is set to be underlined.  Would be great if you could add support for underlined text.

**Comment by gitbrent** [comment]
Hi @tjrueter,

The `addSlidesForTable ()` method does not provide support for word-level formatting, only cell-level formatting is applied.

For example, the text in both of these cells will look the same in the Slide produced.
<table>
<tr><td>Words like <strong>BOLD</strong> text</td><td>wont be bold on the Slide</td></tr>
</table>

NOTE:
There is currently an open feature request (Issue #262) to allow `addTable()` to auto-page, which would then allow fine-grained control over formatting...

**Comment by gitbrent** [comment]
Upon further review:

The code within `addTable()` that will allow auto-paging disables itself when complex text objects are detected. It's too difficult at present to determine how to calculate line height when there can be line breaks, bullets and various other things in text objects.

So, long story short, at present only text formatted at the cell level can be auto-paged as of 2.0.0
