### ISSUE TITLE
Export HTML table to PPT/PPTX is NOT working

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#269]
Export HTML table to PPT/PPTX is NOT working

Thanks!
mcamail2002@gmail.com

**Comment by gitbrent** [comment]
Hi @ravi-ku,

Try the demo and check out the [README](https://github.com/gitbrent/PptxGenJS#table-to-slides-feature) for examples.

`examples/pptxgenjs-demo.html`

![screen shot 2018-01-17 at 21 07 49](https://user-images.githubusercontent.com/7218970/35078958-86eeb0a2-fbca-11e7-8083-bccf2e4c516f.png)

If you're still getting errors, please provide your code, screencaps, etc.

**Comment by ravi-ku** [comment]
Thanks for response. I able to to export HTML table to power point. But now i want create below table structure: Please help:

![image](https://user-images.githubusercontent.com/11146609/37273382-a3da653a-25ff-11e8-9595-0e10ecd5ba32.png)

Thanks!
mcamail2002@gmail.com
