### ISSUE TITLE
question - does it support pptx template?

### ISSUE THREAD

**Issue by andypeng2015** [gitbrent/PptxGenJS#27]
Hi,
may I check if I can load pptx template from server to browser then replace / insert content (text/table/image) to the template and save as new ppt? thanks

**Comment by gitbrent** [comment]
Hi Andy,

That functionality does not exist a present. 

If your template(s) are not very complex, I'd look at creating a [Master Slide](https://github.com/gitbrent/PptxGenJS#master-slides-and-corporate-branding)  and using that instead. 

There's several examples in the [pptxgen.masters.js](https://github.com/gitbrent/PptxGenJS/blob/master/dist/pptxgen.masters.js) file under dist.

**Comment by Abhijith-Sugunan** [comment]
@gitbrent  Is the support for pptx template available now ?

**Comment by Himanshu-CEB** [comment]
In one of my projects, I had to add charts, text, and shapes based on certain conditions, and also there are some static texts and charts as well. Is there any way by which I can load the ppt template and make the changes to it? Any leads?

**Comment by gitbrent** [comment]
Loading of existing PPTX files is listed in our unsupported features page, sorry.
