### ISSUE TITLE
Different Versions of Font Faces/Font Weights

### ISSUE THREAD

**Issue by eth5881** [gitbrent/PptxGenJS#270]
Is it possible with the current functionality to define font weights? I know there is a bold option, but I would like my font to be thinner/lighter than the regular font weight.

For example, I'm using Proxima Nova at a font weight of 100 in a web page that I would like to translate to a PPT. In PPT, this font would be defined as Proxima Nova with the Thin option selected.

See attached screenshot:

![screen shot 2018-01-18 at 2 06 20 pm](https://user-images.githubusercontent.com/10981874/35116278-e122806a-fc58-11e7-97d0-b49c315742b6.png)

I would like this option to be able to be selected already on export. Is this a feature already present in the current functionality or is planned for the future?

Really great tool, by the way! Thanks!

**Comment by pstoll** [comment]
@eth5881 I think you can just try specifying the fontFace as "Proxima Nova Thin".

I looked inside a basic PPT I made and it looks like that is all there is. 

I also used this library to generate a pptx and specified "Proxima Nova Thin" and voila it used it. Give it a try.

**Comment by pstoll** [comment]
Oh...or are you asking for this to be automagic/an option that gets passed in separate from the fontFace?

**Comment by gitbrent** [comment]
OMG, I never thought to just specify the complete name. :-)

If that works, then we're done.

**Comment by ReimaFrgos** [comment]
Passing through the full name of the font is visually fine. I'm using this for Light fonts.

The only thing I've noticed is that if you pass through the name of a bold font, it doesn't activate the 'Bold' button in PowerPoint, a very minor detail, as the font itself will still be displayed in bold. My personal preference in this scenario is to just pass in the regular font and then set bold: true in the options, although others may find it unnecessary. 

Not sure if there's a simple way to trigger bold:true automatically, as looking at the font name doesn't always give it away. Bold, Heavy, Wide, Demibold, Black for example are all used as descriptors to indicate Bold by different fonts

**Comment by gitbrent** [comment]
Thanks for the feedback.

I'm going to avoid auto-trigger code.

Bold can be specified using existing options, so i'd recommend others use that method.
