### ISSUE TITLE
showValue in 'area' chart is not working.

### ISSUE THREAD

**Issue by pankajsindagi** [gitbrent/PptxGenJS#271]
Firstly, Thank you for the amazing library. It's easy to use and works well except the below.

I'm unable to use showValue in area chart, if I use `showValue:true` I get prompted for repair when tried to open the downloaded ppt and ppt is blank when clicked repair. If `showValue:false` the chart works perfect.

Here is the code snippet of options parameter used for adding chart to slide.

       chartOptions = {
               chartColors: ["0096d6", "822980", "87898b", "99d5ef", "c094bf", "b9b8bb", "59bbe4", "d9eff9", 
                                                  "008b2c", "40a85f", "007dba", "b1b5b8", "707477"],
        	title: name,
        	showTitle: true,
        	catAxisTitle: name,
        	showCatAxisTitle: true,                 	
        	valAxisTitle: measurelabel,
        	showValAxisTitle: true,
        	
                      	
               // Fonts
               font_size: 11,
                catAxisLabelFontSize: 9, 
                valAxisLabelFontSize: 9,
                      	
               // Grid Line
               catGridLine: 'solid',
               catGridLine: {color: 'BFBFBF'},
               valGridLine: {color: 'BFBFBF'},
                      	
               // Data points
            //            showValue: true,

               // Layout Size
               y: 0.5,
               w: '80%',
               h: '80%'
     }

Just so you know: Even if we just use `showValue:true`,  commenting out all of the above code. We get prompted for repair.

**Comment by gitbrent** [comment]
This issue is no longer present in the current release.
