### ISSUE TITLE
Small issues on multi format addText

### ISSUE THREAD

**Issue by eddyclock** [gitbrent/PptxGenJS#274]
Hi,

Small bugs found on "strSlideXml += genXmlBodyProperties(textObj.options);" as objOptions.bodyProp is undefined:
It is result in the margin cannot add to textbox;
here is sample code:

```javascript
slide.addText(
    [
        { text:'word-level', options:{ font_size:36, color:'99ABCC', align:'r', breakLine:true } },
        { text:'formatting', options:{ font_size:48, color:'FFFF00', align:'c' } }
    ],
    { x:0.5, y:4.1, w:8.5, h:2.0, fill:'F1F1F1', margin:0 }
);
```

Thanks,
Eddy Kwok

**Comment by gitbrent** [comment]
Hi @eddyclock,

Thanks for the report.

I cant find this line of code in the current (2.0.0) codebase and the slide seems to be created okay... ?

![screen shot 2018-02-07 at 23 44 59](https://user-images.githubusercontent.com/7218970/35957408-06af9a9e-0c61-11e8-9a6e-7be04a6e4143.png)

**Comment by eddyclock** [comment]
Hi @gitbrent 

Yes and look ok in latest version 2.0 
I just found i am still using version 1.4.0.

Thanks,
Eddy

**Comment by gitbrent** [comment]
Thanks for checking.  :-)
