### ISSUE TITLE
How to hide data label having value 0

### ISSUE THREAD

**Issue by skbelalmd** [gitbrent/PptxGenJS#278]
Hii Brent,
Thanks for this awesome library.

I can generate presentations with graph. Below is an attached screenshot.

![image](https://user-images.githubusercontent.com/15244653/35626517-f44f2202-06bb-11e8-9f7a-72b1681ab401.png)

I want to hide the data values in the graph, those are displayed as 0%. Is it possible???
I use the following object as my chart options.
{
    x: 0.25, y: 1, w: 9.5, h: 4.0, barDir: 'col', barGrouping: 'percentStacked', chartColors: ['808080', 'FFCC00', '986142', 'B3B3FF', 'FF8000'], barGapWidthPct: 150, showPercent: true, showValue: true, valGridLine: 'none', valAxisLabelFormatCode: '0%', dataLabelFormatCode: '0%'
  }

**Comment by gitbrent** [comment]
Hi @skbelalmd,

Thanks for the suggestion,  I'll log it as an enhancement request.

**Comment by gitbrent** [comment]
Thanks @ReimaFrgos !

**Comment by gitbrent** [comment]
Added section to Chart API regarding hiding of zero values.

## [API Chart: Note](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#notes)

**Comment by skbelalmd** [comment]
Thanks @ReimaFrgos

**Comment by jefersonla** [comment]
Thanks @ReimaFrgos

**Comment by shalini1228** [comment]
@gitbrent text:"pptgen",options:{align:'center',fontSize:20,color:"326fa8",bullet:{type:'number'}} using this am not able to align text in centre of slide, i tried x, y coordinates as well http://gitbrent.github.io/PptxGenJS/docs/api-text.html can you please suggest. i need text to be aligned in centre of slide.

**Comment by gitbrent** [comment]
@skbelalmd - have you looked at the browser demo under /demos?
There is a ton of code in `/demos/common/demos.js`

**Comment by shalini1228** [comment]
@gitbrent yea i have tried couple methods mentioned in that file but somehow i couldn’t get header in center of slide even though by using x,y,w,h coordinates, can you please help on this.

**Comment by skbelalmd** [comment]
@shalini1228 
you need to mention width as 100%

Check this link: https://jsfiddle.net/skbelal/q3k6wazf/14/

**Comment by shalini1228** [comment]
@skbelalmd thanks for above link, even by using w: '100%' , i still don t see header in middle of slide, is there anything else i can use? 

![image](https://user-images.githubusercontent.com/28868314/73951858-36e92a00-48cc-11ea-97c8-bf19d1518c61.png)

**Comment by shalini1228** [comment]
slide3.addText([
    {
      text:"Page Performance", options:{ align:'center',w: '100%',margin:100, color: "363636",fontFace:'Arial',fontSize:20,bold:true}

    }
]);  @skbelalmd

**Comment by skbelalmd** [comment]
Hi,
As per the documentation, margin value should be between 0 to 99. 

Can you share a fiddle or demo of the issue you are facing.
