### ISSUE TITLE
AddImage gives Red X

### ISSUE THREAD

**Issue by mtrayne** [gitbrent/PptxGenJS#283]
Hi -- whenever I run any code with images in the sandbox, they should up as a giant red X on the PowerPoint output.

Example code:
slide.addImage({ path:'https://pbs.twimg.com/media/DVCgCRbVQAIw8pq.jpg', x:1.0, y:1.0, w:8.0, h:4.0 });
[PptxGenJS-Sandbox_201802021248.pptx](https://github.com/gitbrent/PptxGenJS/files/1690460/PptxGenJS-Sandbox_201802021248.pptx)

**Comment by gitbrent** [comment]
Hi @mtrayne,

If you're running in a browser, you're limited to images on the same server.

The only way to encode an image into base64 (for inclusion in the PPTX) is to utilize `canvas` toBase64 method, but `canvas` will throw same origin/tainted canvas errors in cases like yours.

The solution is to either pre-encode images into base64 and add them using:
`addImage({ data:'base64code' })`, or host them locally.

[Image Code Examples](https://gitbrent.github.io/PptxGenJS/docs/api-images.html#image-examples)

**Comment by mtrayne** [comment]
Thank you! This was super-helpful.

**Comment by sriganeshharitz** [comment]
@gitbrent Im using Angular. I'm unable to add images to the ppt even if they are on the same server as my angular app.

**Comment by timsp97** [comment]
@sriganeshharitz When using Angular, this error is fired when using media because it detects Angular as Node.

By addding `&& !gObjPptx.isBrowser` to the if statement in line 2316, I solved the problem.
For this to work, make sure you have set `pptx.setBrowser(true);`.

@gitbrent Can you add this to the project?

**Comment by gitbrent** [comment]
Hi @timsp97,

Node detection has been improved in [future release] v2.2.0 so Angular is no longer detected as Node.

**Comment by eeshamkohli** [comment]
Hi, What is the work around for this issue on angular? Setting pptx.setBrowser(true); still dosent work for me and I'm unable to load local image to the ppt.

**Comment by gitbrent** [comment]
Hi @eeshamkohli ,

You can either edit/replace your local copy of pptxgen.js to include the recent Node detection changes, or wait until 2.2.0 is released (not too long).
