### ISSUE TITLE
fs.writeFile is not a function

### ISSUE THREAD

**Issue by Wendlereis** [gitbrent/PptxGenJS#286]
I'm creating an ReactJs app, and it uses NodeJs and NPM to install PptxGenJs.

Following the getting started i reached this code

```js
import pptx from 'pptxgenjs'

download() {
  let presentation = new pptx();
  presentation.addNewSlide().addText('Presentation 1', {x:1, y:1});
  presentation.save('PptxGenJS-Presentation-1');
}
```
But when the `.save()` function is called, it results the following error - `TypeError: fs.writeFile is not a function - pptxgen.js:1685`

Am i doing something wrong?

**Comment by gitbrent** [comment]
Hi @Wendlereis,

See the API docs on [Library Integration](https://gitbrent.github.io/PptxGenJS/docs/integration.html)

You'll want to use `pptx.setBrowser(true);` so your solution will utilize browser `window` saving methods instead of Node `fs`.

**Comment by Wendlereis** [comment]
Thank you @gitbrent now it's working properly.
