### ISSUE TITLE
Other Table to slide methods?

### ISSUE THREAD

**Issue by SylarVolkoff** [gitbrent/PptxGenJS#287]
Hi ! 

Is it possible to put an HTML table into a slide (something like slide.addSlidesForTable('tableId');) instead of pptx.addSlidesForTable('tableId'); ?

This adds another slide that only contains the table.

Thank you for the amazing work.

**Comment by gitbrent** [comment]
Hi @SylarVolkoff.

There is also the [Add Table](https://github.com/gitbrent/PptxGenJS#adding-tables) method.

Check the `exmaples/pptxgenjs-demo.html` for lots of table examples.
