### ISSUE TITLE
Allow custom Layout sizes (ex: A3)

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#29]
I would like to see in your wonderful project such new features:
- A3 layout format
- images in table cells
- text multiformatting in single table cells

**Comment by gitbrent** [comment]
Hi @itskun ,

You can now specify any layout size you want using the existing `setLayout()` method.

Just pass a name/width/height and all the Slides in the that Presentation will be your layout size:

`pptx.setLayout({ name:'A3', width:16.5, height:11.7 });`

**Comment by itskun** [comment]
Thank you, @gitbrent !

**Comment by gitbrent** [comment]
Hi @itskun ,

Sure enough there was an issue with the `name` value in the Slide Layout XML tags.

It's been fixed now and an A3 opens for me in PowerPoint without errors now.

**Comment by badlee** [comment]
I haved same bug (PowerPoint need recover) when I want set A4 layout. 
```js
pptx.setLayout({ name: 'A4', width:10.834645669, height:7.5 });
```

> When I'm trying to set layout, there appears a message:
>
> PowerPoint found unreadable content in Presentation.pptx. Do you want to recover the contects of this presentation? If you trust the source of this presentation, click Yes.


I solved it, by change two lines at pptgen.js
```js
/*2620*/ LAYOUTS['LAYOUT_USER'].width  = Number(inLayout.width ) * EMU;
/*2621*/ LAYOUTS['LAYOUT_USER'].height = Number(inLayout.height) * EMU;
```
to this

```js
/*2620*/ LAYOUTS['LAYOUT_USER'].width  = Math.round(Number(inLayout.width ) * EMU);
/*2621*/ LAYOUTS['LAYOUT_USER'].height = Math.round(Number(inLayout.height) * EMU);
```

The width or the height must be an integer not a float.

**Comment by gitbrent** [comment]
Hi @badlee ,

Thanks for the info!  I've added rounding to the `width` and `height` so this won't be an issue going forward.
