### ISSUE TITLE
Question on HTML-to-PowerPoint with nested tables and cell text formatting

### ISSUE THREAD

**Issue by ramakrishnade** [gitbrent/PptxGenJS#290]
Hi Team,

I am having an issue when trying to generate a html table to PowerPoint using the Table-to-Slides feature.
The table appears fine on Sharepoint page.but when I open the generated PowerPoint the cell paragraph style is not showing same as html table. 
attached HTML test table . 

![table](https://user-images.githubusercontent.com/10866640/36384057-d93e1532-1542-11e8-9b7c-81ccd06533d9.png)

**Comment by gitbrent** [comment]
Hi @ramakrishnade ,

Nested tables and word-level formatting are not supported in the `addSlidesForTable()` method.

I've updated the [HTML-to-PowerPoint documentation](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html) to better clarify what is supported, and added some new screencaps as well.

Thanks.
