### ISSUE TITLE
Request to upgrade/replace jquery-node dependency

### ISSUE THREAD

**Issue by alhugot** [gitbrent/PptxGenJS#292]
Hi,
First, this is a great lib! 
Second this is perhaps not the place to report it, please feel free to close the issue, but:

The base version of jquery-node specified in the package.json is affected by these security vulnerabilities:

pptxgenjs@2.0.0 > jquery-node@0.3.0 > jquery@2.2.4
https://nodesecurity.io/advisories/328  

pptxgenjs@2.0.0 > jquery-node@0.3.0 > jsdom@9.12.0 > request@2.81.0 > hawk@3.1.3 > hoek@2.16.3
https://nodesecurity.io/advisories/566  

This issue is just to request that the dependency be upgraded, if that's possible or perhaps the dependency removed as from what this article states: jquery added support for node in 2.1.x
https://github.com/UncoolAJ86/node-jquery

nb you can add a vulnerability badge with:

Would also be good to have a security badge with:

snyk: https://github.com/snyk/snyk#badge
or
nsp: see https://github.com/dwyl/repo-badges

Thx
Alex

**Comment by gitbrent** [comment]
Closing as jQuery is no longer included.
