### ISSUE TITLE
Default is not a constructor

### ISSUE THREAD

**Issue by jorgelub12** [gitbrent/PptxGenJS#293]
I'm added PPTXGENJS using NPM, I added to my component in ANGULAR 5

But when I'm trying to use, I'm getting this error:
pptxgenjs_1.default is not a constructor

Code:
```
console.log('exporting');
const pptx = new PptxGenJS();
```

Console:
```
exporting
ERROR 
TypeError: pptxgenjs_1.default is not a constructor
```

**Comment by gitbrent** [comment]
Hi @jorgelub12,

How are you including PptxGenJS in your project (in the `.ts` file, etc.) and how are you invoking it (via `.html` file)?

**Comment by jorgelub12** [comment]
Same problem here

` createSkeletonPPT() {

        const pptx = new PptxGenJS();
        pptx.defineSlideMaster({
            title: 'MASTER_SLIDE',
            bkgd: 'f17f29'/*,
            objects: [
              { 'image': { data: this.clientLogo, x: '85%', y: '2%', w: '12%', h: '6%', type: 'contain' } }
            ]*/
        });`

**Comment by sriganeshharitz** [comment]
Even im facing the same issue

**Comment by sriganeshharitz** [comment]
Hey, try this:
```
const PptxGenJS = require('pptxgenjs');
const pptx = new PptxGenJS();

pptx.setBrowser(true);

export function generatePPT() {
    const slide = pptx.addNewSlide();
    const opts = { x: 1.0, y: 1.0, font_size: 42, color: '00FF00' };
    slide.addText('Hello World!', opts);
    pptx.save();
}
```

**Comment by busha98** [comment]
enabling "esModuleInterop": true in your tsconfig.json fixes the problem. [link](https://github.com/codex-team/editor.js/issues/929#issuecomment-555920862)

**Comment by th30d0r** [comment]
it doesn't work for me
