### ISSUE TITLE
Pptx not found after save

### ISSUE THREAD

**Issue by okaiyong** [gitbrent/PptxGenJS#294]
Tried on chrome browser when saving a power point with the lib. In some computer it works but some does not. There is no error logged. Anybody experience this and any advice to trouble shoot further?

**Comment by IvanTao** [comment]
I have also encountered this problem, My solution is close the browser,and reopen my url

**Comment by okaiyong** [comment]
Yes. Unfortunately, this is not seen as a solution.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by gitbrent** [comment]
How is your solution setup (a regular webpage with script includes, bower, node, etc.)?

What does your PptxGenJS code look like?

**Comment by okaiyong** [comment]
Yes, included lib as script in a webpage built with angular 1.x. the save() is definitely called as a breakpoint was set there and the code was executed.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by gitbrent** [comment]
* Be sure you're using `pptx.setBrowser(true);` so the library will use web browser saving.
* Only IE11 and modern browsers are supported.  If you're trying to download to Android/mobile, etc. YMMV

[Library Integration](https://gitbrent.github.io/PptxGenJS/docs/integration.html)
