### ISSUE TITLE
Unable to call method 'slide.addSlidesForTable(id)'

### ISSUE THREAD

**Issue by IvanTao** [gitbrent/PptxGenJS#295]
Hi, My version is "2.1.0-beta.20180220", and donw the resouce  today,but not found slide.addSlidesForTable(id)',only have 'pptx.addSlidesForTable' .  errory messe  is 'slide.addSlidesForTable  is not a  function ',Can you help me?
PS: My task is  take rich text in div to  a slide, so I want try the HTML-to-PowerPoint method to finish my task.

**Comment by gitbrent** [comment]
Hi @IvanTao,

What kind of solution do you have (webpage, node, electron, etc.) and how are you instantiating PptxGenJS?

![screen shot 2018-03-02 at 23 24 33](https://user-images.githubusercontent.com/7218970/36930912-03aaee94-1e71-11e8-9807-5f0e01b3e9da.png)

**Comment by IvanTao** [comment]
Hi, @gitbrent ,I use PptxGenJS in webpage, and copy pptxgenjs-demo.html as my test page. I can use pptx.addSlidesForTable, But I want use slide.addSlidesForTable. Because I see:
![2018-03-05_8-54-47](https://user-images.githubusercontent.com/34829050/36953141-61660af8-2053-11e8-8abb-f5ceda61d00d.png)
Can you help me?

**Comment by gitbrent** [comment]
You're calling it incorrectly. `addSlidesForTable` is not a slide method, it's a library method.

```
var pptx = new PptxgenJS;
pptx.addSlidesForTable('tableId');
```

Dont create a Slide - its not necessary.

**Comment by gitbrent** [comment]
I've updated the README section you screencapped and replaced `slide` with `pptx` to correct the example.
