### ISSUE TITLE
Does it supports RowSpan,ColSpan & nested html table?

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#296]
Hi,
I have html table with row span & col span with cell colouring. How to export it?

HTML TABLE:
============================
<table class="table table-bordered" id="risks" width="100%">
                            <colgroup>
                                <col />
                                <col />
                                <col width="200" />
                            </colgroup>
                            <tr>
                                <td bgcolor="lightgray">
                                    <h3><b>Risk</b> <font size="+0">(#@Model.Number)</font></h3>
                                </td>
                                <td>
                                    <b>@Model.Title</b>
                                    <br />
                                    @Model.Description
                                </td>

                                <td class="text-center">
                                    Overall Risk Level<br />
                                    @{
                                        string RiskColor = "black";
                                        if (Model.RiskLevel == 1) { RiskColor = "green"; }
                                        if (Model.RiskLevel == 2) { RiskColor = "yellow"; }
                                        if (Model.RiskLevel == 3) { RiskColor = "red"; }
                                    }
                                    <font color="@RiskColor" size="+50"><span class="glyphicon glyphicon-stop" aria-hidden="true"></span></font>
                                </td>
                            </tr>
                            <tr>
                                <td bgcolor="lightgray">
                                    <b>How and when will it be known that the risk is mitigated?</b>
                                </td>
                                <td>
                                    @Model.HowKnownMitigated &nbsp;
                                    @((Convert.ToDateTime(Model.WhenKnownMitigated)).ToShortDateString())
                                </td>
                                <td>
                                    @{
                                string ImpactColor = "";
                                if (Model.Impact <= 3) { ImpactColor = "green"; }
                                else
                                {
                                    if (Model.Impact == 4) { ImpactColor = "yellow"; }
                                    if (Model.Impact == 5) { ImpactColor = "red"; }
                                }
                                    }
                                    &nbsp;<font color="@ImpactColor"><span class="glyphicon glyphicon-stop" aria-hidden="true"></span></font> &nbsp;
                                    <a href="#" class="AssessRiskImpact" data-id="@Model.ID" title="Assess Risk Impact Score">Impact <font size="-i"><i>(@Model.ImpactIdentifier2)</i></font></a>
                                    <br />

                                    @{
                                string LikelihoodColor = "";
                                if (Model.Likelihood <= 3) { LikelihoodColor = "green"; }
                                else
                                {
                                    if (Model.Likelihood == 4) { LikelihoodColor = "yellow"; }
                                    if (Model.Likelihood == 5) { LikelihoodColor = "red"; }
                                }
                                    }

                                    &nbsp;<font color="@LikelihoodColor"><span class="glyphicon glyphicon-stop" aria-hidden="true"></span></font> &nbsp;
                                    <a href="#" class="AssessRiskLikelihood" data-id="@Model.ID" title="Assess Risk Likelihood Score">Likelihood</a>

                                </td>
                            </tr>
                        </table>

==============================
![risk-table](https://user-images.githubusercontent.com/11146609/37030355-af33fcf0-2160-11e8-97f8-00f4c024a89e.png)

Thanks!
Ravi K Singh
mcamail2002@gmail.com

**Comment by gitbrent** [comment]
Hi @ravi-ku,

Cell background colors and colspans/rowspans are supported.

Use the syntax: `pptx.addSlidesForTable('tableId')`

You can view the [API Docs for HTML to PowerPoint](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html), or check out the demo under `examples/pptxgenjs-demo.html`:

![screen shot 2018-03-07 at 23 32 34](https://user-images.githubusercontent.com/7218970/37134973-a3bb3c48-2260-11e8-8db1-de9a6b480047.png)
