### ISSUE TITLE
Fix docs/examples to use new fontSize, remove unsupported font_size

### ISSUE THREAD

**Issue by pstoll** [gitbrent/PptxGenJS#297]
This caught me - many examples in the docs/README still use font_size. Spent unnecessary time trying to get basic examples working.

Would you be open to a PR that updated the examples & docs?

**Comment by gitbrent** [comment]
Hi @pstoll,

Dang it!! Thanks for letting me know. The renames must've got lost somewhere in all the 2.0 changes.

I've updated the README and done a project-level search to ensure there's no more floating around anywhere.

**Comment by pstoll** [comment]
Awesome, thx!
