### ISSUE TITLE
Feature Request: Text Outline

### ISSUE THREAD

**Issue by stevenljacobsen** [gitbrent/PptxGenJS#298]
Text outline would be very helpful. Our group uses backgrounds that have dramatic contrast. An outline helps define the character when it lands upon a background of the same color. I'm using Shadow right now but since it is only one sided it isn't as good as it could be.  A simple solid line with width and color options would be great!

**Comment by gitbrent** [comment]
Hi @stevenljacobsen,

Text Outline turned out to be pretty trivial to add - thanks for the suggestion.

`outline` has two options: size (pt) and color.

```javascript
slide.addText(
    "Text Outline",
    {
        x:7.5, y:6.5, w:'40%', h:0.6,
        fontSize:32, color:'0088cc', outline:{size:1.5, color:'00DD00'}
    }
);
```

![screen shot 2018-03-19 at 20 55 21](https://user-images.githubusercontent.com/7218970/37631695-ed867b42-2bb8-11e8-9d89-14c03a98f669.png)

**Comment by stevenljacobsen** [comment]
Awesome! I'll download and test it out!

**Comment by stevenljacobsen** [comment]
I pulled down the new code and added the outline options and that works. But I'm having an issue with the font size now.

In this code the font defaults to 12p in the generated PPTX filet:
                var optLyrics = {color: lyricscolor, marginPt: 0, border: [0, 0, 0, 0], align: 'center', valign: 'middle', font_size: lyricssize,
                    font_face: lyricsfont, bold: lyricsbold};
                slide.addTable([[{text: songPPTdata[z]['title'], opts: optLyrics}]], {x: 0.01, y: 0.01, cx: slidewidth, cy: slideheight});

And in this code it defaults to 18pt:
slide.addText(slidetext, {x: 0.01, y: 0.01, cx: slidewidth, cy: slideheight, color: lyricscolor,
                            align: 'center', valign: 'middle', font_size: lyricssize, font_face: lyricsfont, bold: lyricsbold,
                            italics: lyricsitalic, outline: {size: .5, color: '000000'}
                        });
I logged the variables to console and they show the correct values but don't seem to

**Comment by gitbrent** [comment]
Many option names changed in 2.0 and wont work...

Use: `fontSize`, `fontFace` and use `w` for cw and `h` for cy

**Comment by stevenljacobsen** [comment]
Got it! Much better! Thanks!
