### ISSUE TITLE
Image size variable

### ISSUE THREAD

**Issue by mtrayne** [gitbrent/PptxGenJS#299]
Hi -- I'm looking to insert an image onto the slide and the image sizes will vary, but I want the space they go to remain constant (1.8 h, 4.5 w) and the image would be resized to 1.8" tall and the width would vary depending on the image's dimensions. If I don't assign a width, it defaults to 1". Am I missing how I can drop in the image with the correct ratio?

This is the code I'm working with:
```
slide.addImage({ 
path:'images/cake.jpg', x:0.1, y:0.5, h:1.6,
sizing: {type:'contain', w:4.5, h:1.6 } 
});

```
No width (only 1 inch)
![float](https://user-images.githubusercontent.com/36079372/37230403-02fd05fe-23ad-11e8-8998-ddd5e23745c8.JPG)
Biggest width (stretched)
![stretched](https://user-images.githubusercontent.com/36079372/37230433-1c8e9f32-23ad-11e8-88bd-724007e132fb.JPG)

Also is possible to add an image to a cell...haven't figured that out yet but thought it would be a way to get the image flush left...

**Comment by gitbrent** [comment]
Hi @mtrayne,

Images in table cells are currently supported.

Check out the [image sizing options](https://gitbrent.github.io/PptxGenJS/docs/api-images.html#image-sizing).  It sounds like you're looking for `contain`.

![screen shot 2018-03-10 at 23 50 26](https://user-images.githubusercontent.com/7218970/37250250-f317236a-24bd-11e8-8ba1-b08e87116acd.png)
