### ISSUE TITLE
Create table with rowspane & Colospan with cell color code 

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#300]
Hi,

I want to create BELOW table with rowspan, colspan with some color coding in cell. Please help.

![image](https://user-images.githubusercontent.com/11146609/37273687-8c894e0e-2600-11e8-800d-21d4e902c6f7.png)

Thanks!
mcamail2002@gmail.com

**Comment by gitbrent** [comment]
Copy your PowerPoint objects sizes and locations from the picture above and pass them to `.addTable()`

There's tons of sample code in the demo:
`examples/pptxgenjs-demo.html#tab6`

![screen shot 2018-03-17 at 22 46 03](https://user-images.githubusercontent.com/7218970/37562396-05981824-2a35-11e8-9ca2-44a9ddc7bff9.png)
