### ISSUE TITLE
BUG, while exporting HTML table with first row with col span

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#301]
Hi, 

Case 1: When we have colspan in last row then table is exported correctly: [WORK]
Output 1:

![image](https://user-images.githubusercontent.com/11146609/37278959-567dcefc-260f-11e8-917d-f50ae8feba18.png)

HTML TABLE 1:
=================================

`<table class="table table-bordered" id="riskTab" width="100%">
     <tr>
                                <td bgcolor="lightgray">
                                    <b>How and when will it be known that the risk is mitigated?</b>
                                </td>
                                <td>
                                    Because it works and i said so .... take that!
                                </td>
                                <td>30-06-2017</td>
                            </tr>
                            <tr>
                                <td bgcolor="lightgray">
                                    Risk<font size="+0">#01</font>
                                </td>
                                <td colspan="2">
                                    Factory/Service VFD Support :   Factory/Service resources for VFD support will be insufficient causing poor support and negatively impacting future sales.
                                </td>
                            </tr>
                      </table>`

Case 2: When we have colspan in very first row then table added extra columns [NOT WORK]

Output 2:
![image](https://user-images.githubusercontent.com/11146609/37279132-e3788842-260f-11e8-867e-531d80692b30.png)

HTML TABLE 2:
=================================

`<table class="table table-bordered" id="riskTab" width="100%">
                            <tr>
                                <td bgcolor="lightgray">
                                    Risk<font size="+0">#01</font>
                                </td>
                                <td colspan="2">
                                    Factory/Service VFD Support :   Factory/Service resources for VFD support will be insufficient causing poor support and negatively impacting future sales.
                                </td>
                            </tr>
                            <tr>
                                <td bgcolor="lightgray">
                                    <b>How and when will it be known that the risk is mitigated?</b>
                                </td>
                                <td>
                                    Because it works and i said so .... take that!
                                </td>
                                <td>30-06-2017</td>
                            </tr>
                        </table>`

Thanks!
mcamail2002@gmail.com

**Comment by gitbrent** [comment]
Hi @ravi-ku,

Please download the latest code.  There is a fix for this issue that's in the latest codebase.

**Comment by ravi-ku** [comment]
Thanks alot. all files required to update or pptxgen.js file?

 One more query, i want to export table data coming from remote server. How we will achieve it?

**Comment by gitbrent** [comment]
Just `pptxgen.js`

Build an HTML table (eg: using forEach loop and `$('#table').append('<tr></tr>')`)
or
Pass data to `addTable()` as an array.

```javascript
var arrTabRows = [
    [
        { text: 'Top Lft', options: { valign:'top',    align:'left'  , fontFace:'Arial'   } },
        { text: 'Top Ctr', options: { valign:'t'  ,    align:'center', fontFace:'Courier' } },
        { text: 'Top Rgt', options: { valign:'t'  ,    align:'right' , fontFace:'Verdana' } }
    ],
    [
        { text: 'Ctr Lft', options: { valign:'middle', align:'left' } },
        { text: 'Ctr Ctr', options: { valign:'center', align:'ctr'  } },
        { text: 'Ctr Rgt', options: { valign:'c'     , align:'r'    } }
    ],
    [
        { text: 'Btm Lft', options: { valign:'bottom', align:'l' } },
        { text: 'Btm Ctr', options: { valign:'btm',    align:'c' } },
        { text: 'Btm Rgt', options: { valign:'b',      align:'r' } }
    ]
];
slide.addTable(
    arrTabRows, { x:0.5, y:1.1, w:5.0, rowH:0.75, fill:'F7F7F7', fontSize:14, color:'363636', border:{pt:'1', color:'BBCCDD'} }
);
```
