### ISSUE TITLE
Show table data into ONLY one Slide

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#303]
Hi,

I am exporting table into power point slide. I want to show table data into ONLY 1 slide. while i am trying, its created 2 slides. Is there any settings to keep Only one slide? Appreciated in advance.

![image](https://user-images.githubusercontent.com/11146609/37285492-21e47072-2625-11e8-949c-7dcbdc3684a8.png)

Thanks!
mcamail2002@gmail.com

**Comment by ravi-ku** [comment]
Any updates pls???

**Comment by gitbrent** [comment]
Hi @ravi-ku,

Check out the demo page for HTML-to-Slides.  It has several options and examples.

`examples/pptxgenjs-demo.html#tab2`

Also ensure that you've set proper margins.

**Comment by ravi-ku** [comment]
Not clear, which property we have use to get fit generated table into one slide.

**Comment by ravi-ku** [comment]
Ideally, there should be default settings. if content's length exceeded from first slide then rest content, by default moved to next slide.

**Comment by ravi-ku** [comment]
Hi,
I am creating table using row[];
then pushing rows into row array.

 $("#editRiskMitigationImpactTab tr").each(function (i) {
            //debugger;
            var $tds = $(this).find('td');
            rowz.push([
            {
                "text": $tds.eq(0).text().trim(),
                "opts": {
                    "bold": true, "color": "333333", "fill": "D3D3D3", "align": "left", "valign": "top", "margin": [1, 1, 1, 1], colspan: 4,
                    "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
                }
            },
            {
                "text": $tds.eq(1).text().trim(), "opts": {
                    "bold": false, "color": "333333", "fill": "FFFFFF", "align": "left", "valign": "top", "margin": [1, 1, 1, 1], colspan: 2,
                    "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
                }
            }
            ]);
        });

 var tabOpts = { x: 0.0, y: 0.7, w: 11.0, fill: 'F7F7F7', fontSize: 10, color: '000000', colW: [0.0, 0.0, 0.8, 0.0, 0.0, 0.9] };
        slide.addTable(rowz, tabOpts);
        var fileName = "ProjectRiskDetails-" + getFormattedTime();
        pptx.save(fileName);

**Comment by ravi-ku** [comment]
Any updates Pls?

**Comment by gitbrent** [comment]
Hi @ravi-ku,

The library works correctly as far as paging functionality.

Outside of pointing you towards documentation, I don't provide code support, etc.
