### ISSUE TITLE
How to generate table row dynamically using jquery [reading text value from HTML Table]

### ISSUE THREAD

**Issue by ravi-ku** [gitbrent/PptxGenJS#304]
Hi,

I am reading data from HTML table like below & want to create row to export it.

 $("#actionsToMitigateRisk tr th").each(function (i) {
                   
            //alert($(this).text());
                        
        });
============
i want to set text from HTML table by iterating
============
 rowz.push([
           {
               "text": $(this).text(), "opts": {
                   "font_size": "8", "bold": true, "color": "333333", "fill": "D3D3D3", "align": "left", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           },
           {
               "text": "Target Date for Completion", "opts": {
                   "font_size": "8", "bold": false, "color": "333333", "fill": "D3D3D3", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           },
           {
               "text": "Level After Action", "opts": {
                   "font_size": "8", "bold": false, "color": "333333", "fill": "D3D3D3", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           },
           {
               "text": "Reduces Impact", "opts": {
                   "font_size": "8", "bold": false, "color": "333333", "fill": "D3D3D3", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           },
           {
               "text": "Reduces Likelihood", "opts": {
                   "font_size": "8", "bold": false, "color": "333333", "fill": "D3D3D3", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           },
           {
               "text": "Action Status", "opts": {
                   "font_size": "8", "bold": false, "color": "333333", "fill": "D3D3D3", "valign": "top", "margin": [1, 1, 1, 1],
                   "border": [{ "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }, { "pt": 1, "color": "DDDDDD" }]
               }
           }

        ]);

**Comment by gitbrent** [comment]
That sounds like more a coding question than a PptxgenJS question.

Generate an HTML table on a webpage or pass table data in array form to `.addTable()` ([REF](https://gitbrent.github.io/PptxGenJS/docs/api-tables.html))
