### ISSUE TITLE
Set text as footer?

### ISSUE THREAD

**Issue by LucaLovagnini** [gitbrent/PptxGenJS#306]
I need to define a text footer for all the slides in my presentation, is that possible? If so, how?

**Comment by gitbrent** [comment]
Hi @LucaLovagnini,

[Slide Masters](https://gitbrent.github.io/PptxGenJS/docs/masters.html) perform that functionality.  They can be defined and then used to create one or more slides.

Define a slide master, then pass its name to create a slide using your template:
```javascript
pptx.defineSlideMaster({
  title : 'MASTER_SLIDE',
  margin: [0.5, 0.25, 1.25, 0.25],
  bkgd  : 'EEEEEE',
  objects: [
    {rect: { x:0, y:6.9, w:'100%', h:0.6, fill:'003b75' }},
    {text: { text:'S.T.A.R. Laboratories', options:{x:0.17, y:0.1, color:'FFFFFF'} }}
  ],
  slideNumber: { x:1.0, y:7.0, color:'FFFFFF' }
});

var slide = pptx.addNewSlide('MASTER_SLIDE');
```

The demo (`examples/pptxgenjs-demo.html`) has footer sample code and more:

![screen shot 2018-03-17 at 22 29 02](https://user-images.githubusercontent.com/7218970/37562294-af634e6c-2a32-11e8-90cc-cd3c325ab5f4.png)
