### ISSUE TITLE
Using PptxGenJs in React 

### ISSUE THREAD

**Issue by shyam2794** [gitbrent/PptxGenJS#308]
Hi , 

How to import the pptxgenjs in the react app . i have installed it via npm . But not sure how to import it in the file . 
 
I am getting the PptxGenJS() as undefined . i am using the version 2.0.0 . 

Thanks .

**Comment by shyam2794** [comment]
Hi @gitbrent , Any update on this ?

**Comment by gitbrent** [comment]
There's a couple Issues open for Angular/React at the moment, but i'm unable to produce a test case as i dont use either.

I use this in Node.js:
`var pptx = require("pptxgenjs");`

**Comment by TinkerJack** [comment]
@sriganeshharitz  Thank you man!

This also works in Vue!

**Comment by gitbrent** [comment]
Thanks everyone!

Example code and link to this Issue have been added to the API docs:

### [Library Integration](https://gitbrent.github.io/PptxGenJS/docs/integration.html)
