### ISSUE TITLE
insert png to existing ppt in browser

### ISSUE THREAD

**Issue by andypeng2015** [gitbrent/PptxGenJS#31]
hi Brent,

if I have loaded one pptx file template and one png file into browser, how can I insert the png to pptx?

is there a way similar to code below?

var pptx = new PptxGenJS("content of pptx in browser");
var slide = pptx.addNewSlide();
slide.addImage({ data:'image/png;base64,iVtDafDrBF[...]=', x:3.0, y:5.0, w:6.0, h:3.0 });

thanks

**Comment by gitbrent** [comment]
Hi Andy,

The PptxGenJS library does not have the ability to ingest (read) existing PPTX documents, so unfortunately you will not be able to do this particular task.

Thanks for inquiring!
