### ISSUE TITLE
How to create table with different number of cells per row

### ISSUE THREAD

**Issue by LucaLovagnini** [gitbrent/PptxGenJS#310]
I didn't find any way to create tables with different number of cells per row, for example:

![screen shot 2018-03-19 at 4 22 55 pm](https://user-images.githubusercontent.com/11682952/37604700-da1b40be-2b91-11e8-81a8-3ace3f9213eb.png)

If I create something like: `[[Hello], [Cell1, Cell2], ...]` the table will have only one column (the left-most ones).

Is it possible?

**Comment by gitbrent** [comment]
Hi @LucaLovagnini,

Check the demo: `examples/pptxgenjs-demo.html`

![screen shot 2018-03-19 at 18 45 36](https://user-images.githubusercontent.com/7218970/37628097-d2f0e2ee-2ba5-11e8-8c42-e35fbb81c9fe.png)

![screen shot 2018-03-19 at 18 45 26](https://user-images.githubusercontent.com/7218970/37628099-d6069df2-2ba5-11e8-964c-70f77e798e1d.png)
