### ISSUE TITLE
Borderless cells/rows

### ISSUE THREAD

**Issue by LucaLovagnini** [gitbrent/PptxGenJS#311]
Quoting the doc about tables:

> Cell borders can be removed (aka: borderless table) by passing a 'none' (Ex: border:'none')

However, this applies for *all* the cells in the table. Is it possible to apply this to only *some* cells/rows?

What I'm trying to do:
<img width="141" alt="screen shot 2018-03-20 at 6 27 31 pm" src="https://user-images.githubusercontent.com/11682952/37671764-c3001a36-2c6c-11e8-952e-b17c50c693a7.png">

Or:

<img width="144" alt="screen shot 2018-03-20 at 6 28 02 pm" src="https://user-images.githubusercontent.com/11682952/37671786-cc1e6870-2c6c-11e8-890b-a16d714b2f9a.png">

**Comment by gitbrent** [comment]
No, it's all-or-nothing at the moment when using the `border:'none'` setting.

An easy alternative is to color the borders white (or whatever your background color is):

```javascript
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

var arrBorder = [ {color:'FFFFFF',pt:1}, {color:'00ff00',pt:3}, {color:'0000ff',pt:5}, {color:'9e9e9e',pt:7} ];

slide.addTable(
  [['the top border color is white']],
  { x:0.5, y:4.3, w:12.3, rowH:1.5, color:'3D3D3D', fontSize:18, border:arrBorder, align:'c', valign:'c' }
);

pptx.save('PptxGenJS-Issue-311');
```

![screen shot 2018-03-21 at 22 12 57](https://user-images.githubusercontent.com/7218970/37749266-330fe17e-2d55-11e8-8706-40c28cfc4c69.png)
