### ISSUE TITLE
Sizing options for images don't appear to be working.

### ISSUE THREAD

**Issue by jonathanrbowman** [gitbrent/PptxGenJS#313]
Thanks for making such a great library!

I haven't been able to get the `sizing` option to work on images for master slides, though. Using `sizing` with `contain` has worked great on other images to maintain their aspect ratios. Is this a bug, user error, or simply a feature that hasn't made it's way into master slides yet?

**UPDATE**
Actually, it looks like all images are being added in a square bounding box, I have just lucked out and only included generally square images up to this point. Is anyone else experiencing this?

The following should place an image, test.png, at (1, 1) on the slide and resize it until it hits either 2 in length or 2 in height, whichever comes first, while maintaining the image aspect ratio. Correct?

```
      pptExporter.slide.addImage({
        path: '/images/test.png',
        x: 1,
        y: 1,
        sizing: {
          type: 'contain',
          w: 2,
          h: 2
        }
      })
```

Also, if the only thing I include is the `path`, with no positioning or sizing, it just places it at the top left corner, still with the image warped into a square, regardless of the aspect ratio of the image.

**Comment by gitbrent** [comment]
Hi @jonathanrbowman,

Image sizing works with non-square images as well, and will limit the w/h once that boundary is hit.

Try adding `w` and `h` values - the lack of values may be triggering some default sizing behavior or preventing a calculation from occurring...

From `examples/pptxgenjs-demo.html`:

```javascript
slide.addImage({
  data:LOGO_STARLABS, x:0.6, y:4.65, w:5.0, h:2.5, sizing:{ type:'contain', w:3, h:1.5 }
});
```

![screen shot 2018-03-21 at 22 04 17](https://user-images.githubusercontent.com/7218970/37749004-e4beca68-2d53-11e8-9a3c-b4ad498ce420.png)

**Comment by jonathanrbowman** [comment]
Thanks for getting back to me!

I copied that code you provided and just swapped the data attribute out with my image encoded, and it still stretched it. I may have just misunderstood the API docs, but I was thinking it worked the same way background-size in CSS, works - where you don't need to know the dimensions of the image, just provide the dimensions of a some container and it will resize the image to contain it. But with this it seems like you need to know the aspect ratio to provide w and h to the builder?

```
pptExporter.slide.addImage({
  data: presentation_data.logo, x:2, y:2, w: 5.0, h: 2.5, sizing:{ type:'contain', w:3, h:1.5 }
});
```

I'm also on a Mac, so maybe that version of powerpoint (Mac 16.11.1) interprets things differently? As a workaround solution I wrote a helper method in Rails (where my project lives) to get the aspect ratio and handle the resizing conversion to inches on the server, which is working, but I would love to not have the additional overhead if this is a bug or something I'm just not reading correctly.

**Comment by gitbrent** [comment]
The PowerPoint rendering engine produces the same results across PC and MacOS generally...  Plus I develop the library on a Macbook, so it better work for me. :-)

Maybe we've got a case where the option doesn't work for some reason?  Does the image I use under the `examples` folder work and/or the Image slides from the demo?  I see the logo limited in size in the bottom left ("contain Example"), so i'm sure it works for a base64-encoded PNG.

**Comment by jonathanrbowman** [comment]
I downloaded the repo and ran the image example, and it looks correct when using the Stark Labs logo. But, then I tried leaving everything the exact same and just swapping out the Base64 for the Stark Labs logo with the Base64 for the winter landscape image (image2.jpg), also from your repo, and it's stretched, keeping the same dimensions as the Stark Logo.

Wouldn't the expected behavior be that this nearly square image not distort aspect ratio when a sizing option is given? Otherwise, wouldn't I still have to compute the sizing based on the image aspect ratio?

![screen shot 2018-03-29 at 11 08 47 am](https://user-images.githubusercontent.com/3761543/38096932-173306d2-3342-11e8-904b-8eafee28fabe.png)

**Comment by michaelcbrook** [comment]
I am having the same issue. Why was this closed?

**Comment by gitbrent** [comment]
The sizing options are working as intended from what i can see in the screencap.  It contained, covered and cropped the image.

Are you expecting some different results?

**Comment by michaelcbrook** [comment]
Sorry, you are right. It does work as described, it just seemed counterintuitive at first. Didn't realize I have to get the dimensions of the image myself and plug, and that's what goes into the main image options. Then the dimensions of the container go in the sizing property.

I did find something which I think is a bug, though. When the w and h in the main image properties are too high, the image won't show. All I did to fix it was divide each by 10000 and it worked. Can you see this issue?

**Comment by PrakashCSTillid** [comment]
Hi, How to set image default width & height like w:100px?

**Comment by thezaff** [comment]
> Sorry, you are right. It does work as described, it just seemed counterintuitive at first. Didn't realize I have to get the dimensions of the image myself and plug, and that's what goes into the main image options. Then the dimensions of the container go in the sizing property.
> 
> I did find something which I think is a bug, though. When the w and h in the main image properties are too high, the image won't show. All I did to fix it was divide each by 10000 and it worked. Can you see this issue?

Hey. Maybe it is already very late to ask. Have you found out the way to identify dimensions of image? Thanks.

**Comment by EnricoPinheiro** [comment]
https://github.com/gitbrent/PptxGenJS/issues/1268
