### ISSUE TITLE
Can I embed a new slide (from already generated PPT) into the PPT I create using PptxGenJS

### ISSUE THREAD

**Issue by PrashantHavanagi** [gitbrent/PptxGenJS#314]
Hi @gitbrent ,

I am using PptxGenJS to create a PPT (with multiple slides), I want to add a couple of slides which are static and are in some other PPT. Can I do that ? Is there an approach I should follow to get this feature implemented ?

Thanks !

**Comment by PrashantHavanagi** [comment]
Hi @gitbrent,

Any info on this would be of a great help !

**Comment by gitbrent** [comment]
Hi @PrashantHavanagi,

No, PptxGenJS will not parse or extract slides from existing PowerPoints.

**Comment by PrashantHavanagi** [comment]
Hi @gitbrent 

If I have XML of the slide, is there a way I could use that with pptxgen.js and create a new PPT ? Kindly, let me know. So basically if I have **var strSlideXml**, can I use it ?

**Comment by gitbrent** [comment]
Hi @PrashantHavanagi,

No, the library wont do that.  A PowerPoint slide is more then just the XML found in the Slide.xml file.  It's the layout, theme, etc - files from all over the zip/pptx.

If you're trying to recycle your Master Slides/company design then just use the Master Slide feature:

## [Master Slides](https://gitbrent.github.io/PptxGenJS/docs/masters.html)

![screen shot 2018-03-27 at 21 48 36](https://user-images.githubusercontent.com/7218970/38005973-c4627364-3208-11e8-9283-04c08bbd4bbf.png)

![screen shot 2018-03-27 at 21 49 31](https://user-images.githubusercontent.com/7218970/38005977-c83e35cc-3208-11e8-9292-ae3b45622aba.png)

**Comment by jsvishal** [comment]
I want to achieve the same

**Comment by BhargaviCD25** [comment]
Can I merge multiple PPT before generating PPT using PptxGenJS?
