### ISSUE TITLE
Can I convert HTML to ppt for any HTML tag, or it necessarily should be a table tag only for the export to take place?

### ISSUE THREAD

**Issue by eeshamkohli** [gitbrent/PptxGenJS#315]

**Comment by eeshamkohli** [comment]
Example, i want to export all the information in a div tag pair, to a slide in a ppt. Is that possible?

**Comment by gitbrent** [comment]
Hi @eeshamkohli,

The only HTML element that can be used to create PowerPoint presentations are tables.

Any other items will use the normal API: `addText()`, `addImage()`, etc.

**Comment by eeshamkohli** [comment]
Thanks
