### ISSUE TITLE
Unable to rotate image?

### ISSUE THREAD

**Issue by alabaki** [gitbrent/PptxGenJS#317]
Is it not possible to rotate an image? I am unable to find the rotate option for the addImage() function. Are there any plans to implement this?

**Comment by gitbrent** [comment]
Hi @alabaki 

The `addImage()` method does not currently have an option for rotation.

It's a good feature to have, so i've flagged it for future inclusion.  I'd also encourage you to pursue a patch if you feel inclined.

**Comment by alabaki** [comment]
@gitbrent I created a PR which adds the ability to rotate an image. The functionality was already implemented, I just added the 'rotate' attribute to the addImage() function 😄 

PR #639

**Comment by gitbrent** [comment]
This feature is complete now - will be in release v3.1.0
