### ISSUE TITLE
Save PPTX in another folder or save it in AWS S3 (Node.js)

### ISSUE THREAD

**Issue by AlexTeusz** [gitbrent/PptxGenJS#319]
Hi,

I am using the PptxGenJs module for one of my Alexa Skills. In this Skill I create a pptx file but the problem is that AWS Lambda can't find the file.pptx after it was created. 
I found out that lambda doesn't store the files during a session. If I understood it right. 

So I have to store the file.pptx in AWS S3 or on my server. 
Does anyone know how to do this? 

Thank you for your help!

Greetings
Alex

**Comment by gitbrent** [comment]
Hi @AlexTeusz,

Check the `examples/nodejs-demo.js` file for various save methods that may provide a way to save the file directly to AWS.

**Comment by AlexTeusz** [comment]
Hi @gitbrent , 

I found this solution: 
`// D: or use callback with 'http' in filename to get content back instead of writing a file - use this for streaming
//pptx.save( 'http', streamCallback );`

But how should I implement the streamCallback? Do you know an example?

Thank You!
