### ISSUE TITLE
Table cell marginPt should allow zero and take TRBL array of values

### ISSUE THREAD

**Issue by ellisgl** [gitbrent/PptxGenJS#32]
marginPt should accept 0, since you can do no margins in a table cell.
Also it would be nice to be able to TRBL definition on them.

**Comment by gitbrent** [comment]
Hi @ellisgl ,

You can now specify a zero margin and provide values in a TRBL array.

`slide.addTable( ['margin:0'], { x:1.5, y:2.5, margin:[0,0,0,20], w:1, fill:'FFFCCC' } );`

Thanks for opening an issue!
