### ISSUE TITLE
Not Able to Generate PPT in ie11

### ISSUE THREAD

**Issue by anuragsapanbharat** [gitbrent/PptxGenJS#320]
Hi,
Please help as I am not able to use the plugin in ie11. When I try with chrome its working fine. But I the system I am targeting is on ie11, where it showing error. Please find the screenshots below for reference.

![code](https://user-images.githubusercontent.com/38289792/38665408-dae51b30-3e2b-11e8-9363-8a274e905917.png)

![error](https://user-images.githubusercontent.com/38289792/38665411-db58f17c-3e2b-11e8-8ea3-d4ff128f62b3.png)

![reference](https://user-images.githubusercontent.com/38289792/38665414-dbd7a04e-3e2b-11e8-86a3-117da6072563.png)

![ieversion](https://user-images.githubusercontent.com/38289792/38665413-db978860-3e2b-11e8-89f8-88785759fa16.png)

**Comment by gitbrent** [comment]
Try loading the `promise.min.js` library before pptxgen.bindle.js - IE11 requires that polyfill.

**Comment by gitbrent** [comment]
Anything in the IE11 console?

If the library is undefined then it's not being loaded, or it's being clobbered by another library...

**Comment by MariyaBaby123** [comment]
Hi @gitbrent , I have the same issue. And I tried loading promise.min.js before pptxgen.bundle.js.
Still the same error.
SCRIPT5022: SecurityError
polyfills.6a2904254165b0ccd0cb.js (7416,25)

**Comment by gitbrent** [comment]
"SecurityError" sounds like a setting needs to be tweaked in IE, scripts set allowed to run, etc.
