### ISSUE TITLE
Ability to find/replace based on data object (for templates)

### ISSUE THREAD

**Issue by naterodata** [gitbrent/PptxGenJS#323]
Is it possible to do a search and replace on an existing presentation?  E.g., to use a slide deck as a template and then to replace markers with the text based on json data.  So something like: { customer_name: "Acme" } would replace text in the template where the text is [customer_name].

**Comment by gitbrent** [comment]
No, sorry.  PptxGenJS only generates presentations - it has no read/parse functionality.
