### ISSUE TITLE
addImage is not working (Nodejs) - Unable to read media

### ISSUE THREAD

**Issue by casassanta** [gitbrent/PptxGenJS#326]
Hello;

Im trying add an image to my pptx (local image or url image) and everytime I get a RED X in my ppt and this error.

MY Code:
var PptxGenJS = require('pptxgenjs')
    var pptx = new PptxGenJS()
    pptx.setBrowser(true);
    var slide = pptx.addNewSlide();
    slide.addText('Hello World!', { x:1.5, y:1.5, fontSize:18, color:'363636' });
    slide.addImage({ path:'../../image/sign.jpg', x:1, y:2, w:3, h:3 })
    pptx.save('Sample Presentation');

ERROR:
![image](https://user-images.githubusercontent.com/5024483/39341838-6852e8aa-49ab-11e8-940b-f93f7a7c09b6.png)

**Comment by casassanta** [comment]
Hi @gitbrent 

I did it so many times, but I also get the same error even If I use Urls paths insted of images paths

**Comment by leexin** [comment]
I also can confirm that remote URL does not work with addImage and addMedia.
It works if the images are on my server and I call addImage with relative path, but does not work if I supply an URL.

**Comment by gitbrent** [comment]
The ability to add remote images was just checked in the other day.

If you're a Node.js user, you won't have this feature yet.  Client browser users should check their version:

```
var pptx = new PptxGenJS();
pptx.version
```
It should be: `2.2.0-beta.20180422` (or higher)

As for local images in Node, the node-demo loads these successfully, so i'm not sure what to add to the troubleshooting.

**Comment by casassanta** [comment]
@gitbrent Its weird, im trying do it static, check it:

![image](https://user-images.githubusercontent.com/5024483/39608710-d0b3a02e-4f19-11e8-86e5-517252150273.png)

The code is on the file campaign.route.js, and in the same place you can see a folder "Image" with a file "slider.jpg".
And in my code you can see the path: './image/slider.jpg' and Im still getting a big error X in the slide when I save it

**Comment by casassanta** [comment]
@gitbrent  I solved it:

Just use -> path: path.resolve(__dirname, 'image/slide1.jpg') and dont forget to import the lib 'path'

Thanks :)

**Comment by Gohil07** [comment]
What is the library  to import for Path ?

**Comment by Gohil07** [comment]
Mu question is  for this statement Just use -> path: path.resolve(__dirname, 'image/slide1.jpg') and dont forget to import the lib 'path'
What is the library to import for Path ?

**Comment by gitbrent** [comment]
Have you looked through the `examples` folder?  There's lots of Node/Image code samples.

**Comment by Gohil07** [comment]
Yes, I did try those examples , But still I am getting same issue.Can you send any example.

**Comment by vijayst** [comment]
It did not work for me as well from the browser.

```
const ppt = new pptxgen();
const coverSlide = ppt.addSlide();
coverSlide.addImage({
        path: 'https://storage.googleapis.com/dandi-dev-assets/logo-smiley.png',
        x: MARGIN_LEFT / PPI,
        y: MARGIN_TOP / PPI,
        w: 20 / PPI,
        h: 20 / PPI
    });
```

**Comment by vijayst** [comment]
I added a question in StackOverflow as well - https://stackoverflow.com/questions/67908723/not-able-to-add-an-image-to-a-slide-using-pptxgenjs-in-the-browser

**Comment by PedroMoreira87** [comment]
> @gitbrent I solved it:
> 
> Just use -> path: path.resolve(__dirname, 'image/slide1.jpg') and dont forget to import the lib 'path'
> 
> Thanks :)

I've just had the same problem. Your workaround works like a charm. Thank you =)
