### ISSUE TITLE
How do I define a Color Scheme for generated pptx file

### ISSUE THREAD

**Issue by KentAls** [gitbrent/PptxGenJS#328]
What I don't understand is how to define the colors that will be used initially. How do I define the colors that are used by the **this.colors** array? I see where the default is defined but I want to generate something beautiful initially and then enable the end user to change to another scheme and still have good results.

How do define the colors?

**Comment by gitbrent** [comment]
Hi @KentAls 

Colors are defined in `pptxgen.colors.js`

https://github.com/gitbrent/PptxGenJS/blob/34f2cad59817c6776c99aea3a62e50ef5faaabbb/dist/pptxgen.colors.js#L30-L41

**Comment by KentAls** [comment]
So, for example, on line 31 in the code above I can set TEXT1: '00a0dd' (i.e. to a hex color value) if I want TEXT1 to show in light blue? That does not appear to work is why I am asking. If you are saying it should I will re-examine my code.

**Comment by gitbrent** [comment]
Ah, okay.

The scheme support built into the library is for Schemes already defined in your PowerPoint app, whether that's a corporate environment that has defined them for everyone or someone just wanting to use the PPT scheme colors (see the demo).

If you're trying to define your own shorthand like `BLUE99: '0000FF'`, that is not supported at present.

**Comment by KentAls** [comment]
Ok, that is sort of what I thought after poking around the source. I will create my own options. Thanks for responding and thanks for you work on this project.
