### ISSUE TITLE
Assign Existing Master Page

### ISSUE THREAD

**Issue by skellman** [gitbrent/PptxGenJS#329]
Any plan to allow the use of an existing master page pptx file instead of defining one in code?  Thanks.

**Comment by gitbrent** [comment]
Hi @skellman,

No, this is listed in our [Unimplemented Features](https://github.com/gitbrent/PptxGenJS#unimplemented-features) section.

This library only creates presentations, it doesn't ingest/parse them.

Master Slide object are super easy to create though:

## [Master Slides API](https://gitbrent.github.io/PptxGenJS/docs/masters.html)
