### ISSUE TITLE
autoFit is missing 'Shrink text on overflow' variation?

### ISSUE THREAD

**Issue by cdutson** [gitbrent/PptxGenJS#330]
I've recently been trying to add text to a slide that is basically html content. I simplify the content using innerText and inject it.

```
const text = data.element.innerText; // element is an html div
slide.addText(text, { x: '0%', y: '0%', w: '100%', h: '100%', autoFit: true, valign: 'top' });
```

I expected this to shrink the text to fit within the box, but instead the text overflows out of the box (It's a lot of text). Looking into powerpoint itself, I found that within the text box's autofit options, there are a total of 3: `Do not Autofit`, `Shrink text on overflow`, and `Resize shape to fit text`. From what I understand, setting autoFit to false equates to `Do not autofit` and true equates to `Resize shape to fit text`. I'm looking for the middle option: `Shrink text on overflow`.

Is this currently possible with the library? I've read through the docs but nothing standing out to me.

Thanks,

**Comment by cdutson** [comment]
Welp not 30 seconds after posting this and digging into the source code, I find `shrinkText` which is an undocumented property you can add to the props.

As such: `slide.addText(text, { x: '0%', y: '0%', w: '100%', h: '100%', shrinkText: true, valign: 'top' });` achieves what I wanted.

I'd suggest updating the documentation to expose this prop.

**Comment by gitbrent** [comment]
Hi @cdutson,

Thanks for letting me know about this.

I've updated the docs to include `shrinkText`.

## [addText API](https://gitbrent.github.io/PptxGenJS/docs/api-text.html)
