### ISSUE TITLE
LineCharts Different Marker and Different Line Style

### ISSUE THREAD

**Issue by shaunvdp** [gitbrent/PptxGenJS#332]
Hi everyone and @gitbrent

I cant seem to figure out how to get the lines on my line chart (pptx.charts.LINE) to have different styles per line and different markers per line... the different colors for each line is working well with : 
chartColors: ['ED6737', '008E94', '1F497D', '008000', 'FF0000'],

but if I want to do a different marker for each line and a different style for each line I cant seem to get it working...  I did a download of a sample I created (attached) and manually changed the styles of the markers and lines to show what i mean. If there is anyone who successfully achieved these results using the software, help will be very much appreciated... 
[test.pptx](https://github.com/gitbrent/PptxGenJS/files/1979432/test.pptx)

thanks
Shaun

**Comment by gitbrent** [comment]
Hi @shaunvdp,

At the moment, PptxGenJS only supports line marker, line size, and other properties at the chart level, not on a per-line level.

![screen shot 2018-05-08 at 12 19 59](https://user-images.githubusercontent.com/7218970/39772337-a1d095b0-52ba-11e8-8b4f-6cccc9b24498.png)
