### ISSUE TITLE
addMedia of type='online' not working?

### ISSUE THREAD

**Issue by lndev1** [gitbrent/PptxGenJS#335]
I have created a pptx using the library and am trying to include and embedded youtube clip in the presentation. 
```javascript
let pptx = new PptxGenJS();
let videoSlide = pptx.addNewSlide();
videoSlide.addMedia({
    type: 'online',
    link: 'https://www.youtube.com/embed/Dph6ynRVyUc',
    x: 0,
    y: 0,
    w: slideWidth,
    h: slideHeight
});
pptx.save(filename);
```

This creates a presentation with and error 
![screen shot 2018-05-15 at 1 23 34 pm](https://user-images.githubusercontent.com/39308249/40073015-a77a3a82-5843-11e8-94b9-75e11ccc7ef1.png)

After accepting this error, the media object is empty with the message "The picture can't be displayed." Also it seems to have overridden slide masters previously created. Is this no longer working properly or have I added the online media object incorrectly?

**Comment by gitbrent** [comment]
Hi @lndev1,

Thanks for reporting this.

The preview image (a circle-triangle play-button type png) was missing for online videos, hence the "picture can't be displayed" error.

I've fixed the preview image so it's no longer broken (YouTube would still play correctly in presentation mode).

![screen shot 2018-05-15 at 22 09 31](https://user-images.githubusercontent.com/7218970/40094723-4748db8c-588e-11e8-879e-a3285199b84d.png)

YouTube Notes:
1. YouTube videos only work in PowerPoint online (Office 365)
2. The videos only show in presentation mode (a tooltip hint appears on hover saying as much)

![screen shot 2018-05-15 at 22 22 07](https://user-images.githubusercontent.com/7218970/40094794-998e3932-588e-11e8-99af-e9cb834d171c.png)

![screen shot 2018-05-15 at 22 09 56](https://user-images.githubusercontent.com/7218970/40094626-bb2c2cc6-588d-11e8-97f8-1ca3aeeeca2a.png)
