### ISSUE TITLE
Add w and h attributes to page number

### ISSUE THREAD

**Issue by s7726** [gitbrent/PptxGenJS#336]
My OCD kicked in when all the slide numbers were statically sized to flow off the slide.

https://github.com/gitbrent/PptxGenJS/blob/8c8cea72f943462bb9f64df9825cef9404b23fbb/dist/pptxgen.js#L1123

The following change (sorry not in a spot to do a proper pull request right now) adds `w` and `h` to the  slide number options.

```
					+ '    <a:xfrm><a:off x="'+ getSmartParseNumber(slideObject.slideNumberObj.x, 'X') +'" y="'+ getSmartParseNumber(slideObject.slideNumberObj.y, 'Y') +'"/>'
					+ '    <a:ext cx="'+ getSmartParseNumber(slideObject.slideNumberObj.w, 'X') +'" cy="'+ getSmartParseNumber(slideObject.slideNumberObj.h, 'Y') +'"/></a:xfrm>'
```

**Comment by gitbrent** [comment]
Hi @s7726,

Thanks for your contribution!
