### ISSUE TITLE
Adding notes into the presentation

### ISSUE THREAD

**Issue by shaunvdp** [gitbrent/PptxGenJS#337]
Hi All and @gitbrent 

has anyone had any luck with adding notes to presentations? I think they are called speaker notes? is this a feature yet? if not could it be added?

thanks in advance
Shaun

**Comment by gitbrent** [comment]
Hi @shaunvdp 

There's an open enhancement request for this feature: Issue #239 

I'd encourage you to create a patch for this functionality if you're so inclined.

**Comment by travispwingo** [comment]
This patch will be available after https://github.com/gitbrent/PptxGenJS/pull/361
