### ISSUE TITLE
App getting hang

### ISSUE THREAD

**Issue by balajiHms** [gitbrent/PptxGenJS#338]
Hi @gitbrent ,
I have created desktop application using electron .In that I have generated more than 400 MB ppt file at that time app getting hang after calling pptx.save() function. And sometimes app getting crashes.

Anyone help me on this.I have bee facing an issue this.I have tried multiple ways.For this any minimum configuration is needed??

Note: Happening most of the times on windows

**Comment by gitbrent** [comment]
Hi @balajiHms 

Maybe you're hitting the limits of Electron's file and/or memory limits on Windows...?

Does the library work for smaller presentations?

**Comment by Bunny2242** [comment]
Yes, it works fine up to 100MB ppt generation. if it's crossed that then it got the hang. But finally, ppt has been generated. I had requirement of unlimited HD images(around 4 to 5MB each) can add to PPT. I have tried it in 16GB RAM system also faced the same issue.

**Comment by balajiHms** [comment]
Yes, it works fine up to 100MB ppt generation. if it's crossed that then it got the hang. But finally, ppt has been generated. I had requirement of unlimited HD images(around 4 to 5MB each) can add to PPT. I have tried it in 16GB RAM system also faced the same issue.

**Comment by gitbrent** [comment]
This sounds like an Electron or a system issue.

I'd recommend creating multiple presentations as a work-around.
