### ISSUE TITLE
Create slide deck from list of individual slides selectable by a user from a GUI.

### ISSUE THREAD

**Issue by skellman** [gitbrent/PptxGenJS#341]
One of my users would like the ability (if possible) to select N number of individual slide decks (via a checkbox list) to create a new deck from that.  I can mock something up if that would help.

**Comment by gitbrent** [comment]
Hi @skellman 

If you're asking to do something like clone or copy the style of an existing PPTX, then no, the library doesn't read/parse presentations.

If you're asking how to create multiple presentations, that's covered in the docs:
### [Saving Multiple Presentations](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html#saving-multiple-presentations)

**Comment by skellman** [comment]
Hi, thanks for replying.  I was talking about let's say 10 people working
on 10 different slides.  If they were loaded into a place I could add them
to a checkbox list, another user could select each slide and create one
large presentation from the selected slides.  Make sense?



[image: www.novetta.com]
<http://www.google.com/url?q=http%3A%2F%2Fwww.novetta.com&sa=D&sntz=1&usg=AFQjCNHSU1i3NII9urdYONyagAjAE0awTg>

*Scott J. Kellman, CEH, Sec+CE, ITIL*

Sr. Software Engineer*, InfoEx, SOF*

600 South Magnolia Ave
Suite 300
Tampa, FL 33606

Email  skellman@novetta.com
<http://www.google.com/url?q=http%3A%2F%2Fwww.novetta.com%2F&sa=D&sntz=1&usg=AFQjCNHHqVUIrTB7_ljUa426rfwGUkP7Fg>

Mobile 941-812-1197
Client Site 813-529-3065


Follow Novetta:

[image: Linkedin-e1500319531488.png]
<https://www.google.com/url?q=https%3A%2F%2Fwww.linkedin.com%2Fcompany-beta%2F2548054%2F&sa=D&sntz=1&usg=AFQjCNHFVz9Of2jTf7PY2mULsfammyP5FQ>
[image:
Twitter-e1500319481481.png]
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FNovettasol&sa=D&sntz=1&usg=AFQjCNE4pEbgbIohuTIPGgcy8ZT5SMqsFw>
[image:
Google-e1500318911339.png] <https://plus.google.com/+Novetta> [image:
YouTube-e1500319506583.png]
<https://www.youtube.com/channel/UCkAdZ7uESEHJMowTkMGz8Jw/featured>

[image: GPTW-emailsig-BR.png]
<https://www.google.com/url?q=https%3A%2F%2Fwww.glassdoor.com%2FOverview%2FWorking-at-Novetta-EI_IE665112.11%2C18.htm&sa=D&sntz=1&usg=AFQjCNHAMGQK4loYOYo_up5ds5fcZzAokw>

**Comment by gitbrent** [comment]
However you choose to utilize the library to generate a solution to this requirement sounds like an interesting project.
