### ISSUE TITLE
Ability to add a section in the generated PPTX

### ISSUE THREAD

**Issue by atulsingh0913** [gitbrent/PptxGenJS#349]
Do we have an ability to add a section in the generated PPTX as we have here .
<img width="200" alt="screen shot 2018-06-07 at 2 31 31 pm" src="https://user-images.githubusercontent.com/33565663/41089652-fbbb7916-6a5f-11e8-9737-9c9b67f22b74.png">

Or do we have some workaround that. I went through the documentation and couldn't find anything like that.

**Comment by gitbrent** [comment]
Hi @atulsingh0913 ,

This functionality does not exist as of yet.

**Comment by John-HW-Cao** [comment]
any updates? This functionality is really useful

**Comment by gitbrent** [comment]
Pushing to 3.1 as 3.0 has taken a huge effort already.

**Comment by gitbrent** [comment]
@atulsingh0913 @John-HW-Cao - this feature has finally landed!

Usage:
```javascript
pptx.addSection({ title: 'Charts' });

var slide = pptx.addSlide({sectionTitle:'Charts'});
```

<img width="1636" alt="Screen Shot 2020-02-12 at 23 29 02" src="https://user-images.githubusercontent.com/7218970/74404374-ea33b080-4def-11ea-85b1-41667f875286.png">
