### ISSUE TITLE
Is it possible to open and edit an existing slide?

### ISSUE THREAD

**Issue by i0natan** [gitbrent/PptxGenJS#352]
I already have my desired look&feel in an existing PPTX file, I just want to open and edit few slides. Is this possible? any reference to relevant article/technique will be appreciated

**Comment by gitbrent** [comment]
Hi @i0natan ,

No, sorry.  This is listed under [Unimplemented Features](https://github.com/gitbrent/PptxGenJS#unimplemented-features).

Making Master Pages/Layouts/Look-n-feel is super easy though:
## [API: Master Pages](https://gitbrent.github.io/PptxGenJS/docs/masters.html)
