### ISSUE TITLE
How to get slide number of the slide created?

### ISSUE THREAD

**Issue by okaiyong** [gitbrent/PptxGenJS#353]
There are two ways that we can create a slide.
1. Manual create.
2. Insert a table that auto flow if exceed a slide. 

How to know the slide number for the 2 cases above?

**Comment by gitbrent** [comment]
Hi @okaiyong ,

There is currently no API method to return the slide number for a given `slide`.

**Comment by kumaarraja** [comment]
Returned slide object of addNewSlide API has getPageNumber() and its public. You can use that to get slide number for manual created one.

**Comment by gitbrent** [comment]
Thanks @kumaarraja !

I forgot all about `getPageNumber()` - it wasn't even in the docs... :-(

It's documented now: [Slide Methods: getPageNumber](https://gitbrent.github.io/PptxGenJS/docs/usage-slide-options.html#page-number)

**Comment by iainfreestone** [comment]
Is there a way to do this in v3? It looks like getPageNumber is no long available.

I use this functionality to hot link between slides where I do not no the what the slide number will be in advance of creating in the presentation.

**Comment by avsilva** [comment]
Same issue. any plans to add getPageNumber method to v3?

**Comment by avsilva** [comment]
found !!! getPageNumber() is now a property: "number"
