### ISSUE TITLE
How to add a margin to the bottom of a table before it moves on to the next page?

### ISSUE THREAD

**Issue by carlpage** [gitbrent/PptxGenJS#356]
![screen shot 2018-06-18 at 2 37 10 pm](https://user-images.githubusercontent.com/25409616/41558029-399779ee-7305-11e8-84aa-0b1e6aabe769.png)

I want the table to break above the footer.

    this.element.createTableHygiene = function (slide, headerRows, bodyRows, y_axis) {

        var concatObj = [headerRows].concat(bodyRows);

        var test = slide.addTable(concatObj, {
            x: 0.5,
            y: y_axis,
            w: 7.5,
            color: '000000',
            fontSize: 11,
            border: {
                pt: '1',
                color: '000000'
            },
            margin: 8,
            autoPage: true,
            newPageStartY: 2.2,
            colW: [3.25, 1.25, 3],
            valign: 'middle',
            align: 'center',
            fill: '004684',
            color: 'ffffff',
            bold: true
        });

this.element.createTableHygiene(slide, obj3, obj4, 5.75);

**Comment by carlpage** [comment]
I figured it out. 

A negative lineBreak attribute solves this problem.

**Comment by jsvishal** [comment]
"A negative lineBreak attribute solves this problem"
can you please help me with this ..facing the same problem.. I want to define a bottom margin for slide.

**Comment by gitbrent** [comment]
@jsvishal - please see `/demo` - there are examples of line height adjustments, etc.
