### ISSUE TITLE
Table formatting bug

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#36]
Given a table with 7 cols and 2 rows:
![image](https://cloud.githubusercontent.com/assets/9961535/22780440/cf12a392-eecf-11e6-90a9-24bc43d33981.png)
When I try to bring a table to a form, the value in cell B2 is lost:
![image](https://cloud.githubusercontent.com/assets/9961535/22780617/5e3f219e-eed0-11e6-8d9c-4cde827f3ab5.png)
Now, when I try to connect F1 and F2 rowspan getting corrupted pptx file. Code:
`var slide2 = pptx.addNewSlide();
var rows2 = [
	[ {text:'A0 and B0', opts:{rowspan:2}},{text:'A1 and A2', opts:{rowspan:2}},{text:'B1 and C1', opts:{colspan:2}},{text:'D1 and E1',opts:{colspan:2}},'F1' ],
	[ 		'B2','C2','D2','E2','F2' ]
];
var tabOpts2 = { x: 0.5, y: 1.5, w: 13, margin:0 };
var celOpts2 = { font_size: 10, font_face: 'Times New Roman', align: 'center', valign: 'middle', border: { pt: '1' } };
	slide2.addTable( rows2, tabOpts2, celOpts2 );`

**Comment by gitbrent** [comment]
Hi @itskun ,

Thanks very much for reporting this!

Apparently, the test cases i had in the table demo pages were the only ones that worked... Sequential rowspans and/or colspans were causing issues across the board and necessitated a complete re-write of the table building algorithm.

I've created some complex test cases and added them to the demo page.

![screen shot 2017-02-15 at 18 13 18](https://cloud.githubusercontent.com/assets/7218970/23001684/d669991c-f3ab-11e6-954c-28b1384118c0.png)
