### ISSUE TITLE
Blanks display in line charts

### ISSUE THREAD

**Issue by guipas** [gitbrent/PptxGenJS#364]
Hi Guys ! 

First, thank you very much for your work on this library, it's been very useful to us where I work, we use it every day to generate presentations and It works very well 😉

We had an issue while generating line graphs, some value where null and so there was a gap between values like this :
![capture d ecran 2018-06-26 a 15 39 17](https://user-images.githubusercontent.com/11334913/41916614-b4000206-7958-11e8-9c17-fde78c5d6384.png)

We wanted the line to continue between the gap (it can be done directly in powerpoint) but I didn't find any option in pptxgenjs to change this behaviour. My colleague saw by changing that option in powerpoint and making a diff of the two files that this had to do with one xml tag (`<c:dispBlanksAs val="gap"/>`). If it is replaced with : `<c:dispBlanksAs val="span"/>`, it works :
![capture d ecran 2018-06-26 a 16 40 15](https://user-images.githubusercontent.com/11334913/41919809-ae84e1be-795f-11e8-85d9-fa35c493980e.png)

Would you guys be ok with adding an option `displayBlankAs` in the graphs options ? I'm making a PR right now 😉

**Comment by guipas** [comment]
Hey @gitbrent, sorry to bother you, just wanted to ask if you think this change will be available in 2.3.0, and if so if you have any idea when this version will be released ?

Cheers ! 🖖

**Comment by gitbrent** [comment]
Hi @guipas 

The 2.3.0 release is coming out very soon.  I've got one or two more items, then i'm done. :-)
