### ISSUE TITLE
Rotate working incorrectly

### ISSUE THREAD

**Issue by michaelcbrook** [gitbrent/PptxGenJS#370]
When I rotate text, it becomes skewed on LibreOffice, and in MS Office, it gets rotated completely in a different direction. I've checked that I'm doing it right, but not getting the expected result.

The expected result:

![screenshot from 2018-07-01 23 17 08](https://user-images.githubusercontent.com/4737526/42145119-f401e8d0-7d84-11e8-87b2-ea99d1b1529b.png)

The actual result (in LibreOffice):

![screenshot from 2018-07-01 23 14 06](https://user-images.githubusercontent.com/4737526/42145126-fd00b556-7d84-11e8-8f56-7f5593228f68.png)

Can also provide a screenshot with MS Office if necessary. Just cumbersome for me to get it.

Thank you!

**Comment by gitbrent** [comment]
Hi @michaelcbrook 

What code are you using and can you provide a screenshot of the expected result in PPT?

**Comment by gitbrent** [comment]
Sure, it'll be in the upcoming 2.3.0 release.

**Comment by michaelcbrook** [comment]
Hate to open this back up, but it looks like this issue isn't totally resolved. The angle of the rotated text seems right, but its position is not. The same code given above results in the text starting off the page.

![screenshot from 2018-08-05 19 46 27](https://user-images.githubusercontent.com/4737526/43691934-aefe123e-98e8-11e8-9738-c7c6cddec3ae.png)

Should be more or less centered on the page:

![screenshot expected output](https://user-images.githubusercontent.com/4737526/42245821-cec259e0-7edf-11e8-85f9-bf6dc8d6cd7a.png)

The code again:

```js
const pptx = new PptxGenJS();

const slide = pptx.addNewSlide();

slide.addText("This is a test This is a test This is a test", {
  w: 3.915895061728395,
  h: 0.2022839506172839,
  x: 3.76929012345679,
  y: 4.322916666666667,
  rotate: 306,
  align: 'center',
  fontSize: 12.888888888888888,
  isTextBox: true,
  inset: 0,
  margin: 0,
  valign: 'middle'
});

//send file to output
pptx.save("https", (data) => {
  const headers = {
    'Content-Type': 'application/vnd.openxmlformats',
    'Content-Disposition': 'attachment; filename=Test.pptx',
    'Content-Length': data.length
  };
  res.writeHead(200, headers);
  res.end(new Buffer(data, "binary"));
});
```

I appreciate your help with this!

**Comment by gitbrent** [comment]
Hi @michaelcbrook 

Your example comes out correctly using the latest build (2.3.0-beta.20180706).

```javascript
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

slide.addText("This is a test This is a test This is a test", {
  w: 3.915895061728395,
  h: 0.2022839506172839,
  x: 3.76929012345679,
  y: 4.322916666666667,
  rotate: 306,
  align: 'center',
  fontSize: 12.888888888888888,
  isTextBox: true,
  inset: 0,
  margin: 0,
  valign: 'middle'
});
```

Result:
![screen shot 2018-08-07 at 21 50 13](https://user-images.githubusercontent.com/7218970/43813670-4a69a162-9a8c-11e8-936b-80144acbed35.png)

**Comment by michaelcbrook** [comment]
I'm afraid it doesn't because your code is different. You've added `pptx.setLayout('LAYOUT_WIDE');` If you remove that part, it comes out like mine.

I've essentially created a script that translates object properties drawn in a canvas into PPT objects using this library. My first inclination is that maybe I got the translation wrong, but everything else aligns perfectly, except for rotated objects. Rotated images don't work at all.

Expected output:
![screenshot from 2018-08-08 13 14 19](https://user-images.githubusercontent.com/4737526/43856130-464859ee-9b0d-11e8-9e77-d99526a0e422.png)

Actual output:
![screenshot from 2018-08-08 13 14 36](https://user-images.githubusercontent.com/4737526/43856252-9e7b6a2a-9b0d-11e8-8dbe-cdd465761d3d.png)

It's difficult to post all the code, but here are the object properties for the rotated text element:

```js
{ w: 2.797067901234568,
 h: 0.2022839506172839,
 x: 5.44753086419753,
 y: 4.099151234567901,
 rotate: 270,
 align: 'center',
 bold: false,
 color: '181818',
 fontFace: 'Open Sans',
 fontSize: 12.888888888888888,
 isTextBox: true,
 italic: false,
 underline: false,
 inset: 0,
 margin: 0,
 valign: 'middle' }
```

And canvas is set to size: `LAYOUT_16x9`

I hope this helps, and thank you!

**Comment by ACPrice** [comment]
I think this issue does need to be reopened, unfortunately. I'm seeing the same (incorrect) rotation behavior. I'm on `2.5.0`. Also: thanks for the very useful library!

I'm adding a slide like so:

```
slide.addText('Text Here', {
      shape: pptx.shapes.RECTANGLE,
      x: 0,
      y: 0,
      w: 5,
      h: 5,
      align: 'left',
      valign: 'top',
      line: '000000',
      line_size: 1,
      font_size: fontSize,
      rotate: -90
})
```

**Comment by ACPrice** [comment]
@gitbrent Thanks again for the fantastic repo. I'm curious if this issue is likely to get another look in the foreseeable future. Trying to figure out if I should implement a workaround on a project.

**Comment by gitbrent** [comment]
Hi @ACPrice 

There must be something about your process flow that is causing this as normal test cases work correctly.

Regarding the Aug 2018 comment, whether `setLayout` is used or not the result is a rotated object at 306*
<img width="1129" alt="Screen Shot 2019-04-23 at 22 06 13" src="https://user-images.githubusercontent.com/7218970/56630119-b778bb80-6615-11e9-8773-277231123f1b.png">

Your current code works as well - resulting in an object rotated -90*

<img width="1330" alt="Screen Shot 2019-04-23 at 22 10 18" src="https://user-images.githubusercontent.com/7218970/56630074-8f895800-6615-11e9-9404-c99ec18afe6b.png">

<img width="1400" alt="Screen Shot 2019-04-23 at 22 08 48" src="https://user-images.githubusercontent.com/7218970/56630081-944e0c00-6615-11e9-92df-a14fdfcd025b.png">
