### ISSUE TITLE
slide.addNotes

### ISSUE THREAD

**Issue by cyberjetx** [gitbrent/PptxGenJS#374]
slide.addNotes is no longer working.

**Comment by cyberjetx** [comment]
/* PptxGenJS 2.2.0-20180617 */

**Comment by gitbrent** [comment]
That feature was only added recently.

If you're using npm, you'll have to wait for 2.3.0 to be released, otherwise grab an updated .js file.

**Comment by cyberjetx** [comment]
Validated that /* PptxGenJS 2.3.0-beta-20180706 */  fixes this issue.
