### ISSUE TITLE
slide.hidden

### ISSUE THREAD

**Issue by cyberjetx** [gitbrent/PptxGenJS#375]
While not a show stopper, slide.hidden = true; does not hide the slide.  

--Running PP 2016 on a windows 10 machine.

**Comment by gitbrent** [comment]
What version of PptxGenJS are you using?

**Comment by cyberjetx** [comment]
/* PptxGenJS 2.2.0-20180617 */ 

('We' should add that to the non-min file.  Even though I am using the min I wen't to the non-min first to find the version.)

**Comment by gitbrent** [comment]
Please update to the latest version.

**Comment by cyberjetx** [comment]
Verified that /* PptxGenJS 2.3.0-beta-20180706 */ fixes the issue
