### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by tovab** [gitbrent/PptxGenJS#376]
Hi

Thank you for the awesome library! 

It seems there is something wrong with Font Size.

Here is code I used for a trial.

`
```
let slide = this.pptx.addNewSlide();

            slide.addText('Hello', { x: 0.5, y: 0.7, w: 3, color: '0000FF', fontSize: 64 });

            slide.addText('World!', { x: 2.7, y: 1.0, w: 5, color: 'DDDD00', fontSize: 90 });

            this.pptx.save("hello world");
````

The text is there, the colors are there, but the font is not.

I appreciate any ideas.

Thank you
TB

**Comment by gitbrent** [comment]
I'm not sure what the issue is, but the code works for me.

Have you tried running the demo page under `examples`?

![screen shot 2018-07-12 at 22 42 44](https://user-images.githubusercontent.com/7218970/42671323-0c7e9806-8625-11e8-9f44-55e06d3cdc80.png)

**Comment by tovab** [comment]
The issue was that I didn't have the latest version. Thanks a lot
