### ISSUE TITLE
Uncaught TypeError: slideN.addNotes is not a function

### ISSUE THREAD

**Issue by rakesheega** [gitbrent/PptxGenJS#377]
Hi Brent,

Thank you for the Library. i am getting error when trying to add speaker notes to the slide. 

i am following the steps mentioned here https://gitbrent.github.io/PptxGenJS/docs/speaker-notes.html
i am loading the bundle as below 

<script lang="javascript" src="PptxGenJS/dist/pptxgen.bundle.js"></script>
<script lang="javascript" src="PptxGenJS/dist/pptxgen.shapes.js"></script>

please let me know if iam missing anything. 

Thank you for the help

**Comment by gitbrent** [comment]
Feature is present in the 2.3.0 release.
