### ISSUE TITLE
Ability to rotate chart axis labels

### ISSUE THREAD

**Issue by teejayvanslyke** [gitbrent/PptxGenJS#378]
Hello: First, thanks for your efforts on PptxGenJS. What an incredible resource for the JavaScript community.

We're generating data-dense stacked bar charts with numerous categories, each of which has long names. Because the category names are so long, they bleed into one another or are omitted entirely. I've looked high and low through the PptxGenJS documentation for an API option to rotate chart axis labels, but all I could find were options to rotate the axis _titles_ (`catAxisTitleRotate` and `valAxisTitleRotate`). 

Is it possible to rotate chart axis labels so their text is vertical as in the image below?

![Vertical axis labels](https://d2d42mpnbqmzj3.cloudfront.net/images/stories/doc-excel/rotate-axis-label/xdoc-rotae-axis-label-4.png.pagespeed.ic.AD49ZzpmFw.webp)

Thank you!

**Comment by dimfeld** [comment]
We made this change in these two commits that seem to take care of it:
https://github.com/Carevoyance/PptxGenJS/commit/e9ce7dc9acea25e27a317719e97b4306abb0d730
https://github.com/Carevoyance/PptxGenJS/commit/60f2a1df6046d37bd10b54a2fa1739c6ceb56c38

There are other changes in the fork that make it inconvenient to open a PR, and I'm using ES6 template strings in my version which you may not want to do, but feel free to pull those in and change them however you want, if you'd like.

**Comment by gitbrent** [comment]
Thanks for the suggestion @teejayvanslyke 

Thanks for the code @dimfeld !
