### ISSUE TITLE
ppt corrupted when wrong color entered 

### ISSUE THREAD

**Issue by lilou1234** [gitbrent/PptxGenJS#379]
Hi,

When entering a wrong color value, the ppt created is corrupted 

Just trying using code sandbox 
```
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

// Bullets with indent levels
slide.addText(
  [
    { text:'1st line', options:{ font_size:24, bullet:true, color:'hello' } },
    { text:'2nd line', options:{ font_size:36, bullet:true, color:'FFFF00', indentLevel:1 } },
    { text:'3rd line', options:{ font_size:48, bullet:true, color:'0088CC', indentLevel:2 } }
  ],
  { x:1.5, y:1.5, w:6, h:2, margin:0.1, fill:'232323' }
);

pptx.save('PptxGenJS-Sandbox_'+getTimestamp());
```

**Comment by sorb999** [comment]
@gitbrent why don't we add a default value of color if color name is not valid? Let me know if you are agree with it so that I can push this change set.

**Comment by gitbrent** [comment]
Hi @sorb999 

The code uses black (`000000`) as a default when no color is specified, however, i'd rather use Regex to validate a correct color in this case...

**Comment by gitbrent** [comment]
Hi @lilou1234 Thanks for the issue. The `color` property is used by almost every method all over the codebase so checking each one - even at the `addWhatever` method level is a lot of code. The library has many areas where it provides feedback to the console, etc. but people are on their own here. :)
