### ISSUE TITLE
Proposal to allow passing rotate option in float (or in radians)

### ISSUE THREAD

**Issue by olyverDev** [gitbrent/PptxGenJS#382]
I want to draw a LINE shape from point A to point B, but as there is no such functionality, I'm using **x**, **y**, **w**, **h** and **rotate** options.
So I'm calculating angle and offsets after rotation to position a line correctly.
But there are some inaccuracies in angle because of **rotate** should have integer type .
On top of this, I propose to make it more precise.

Maybe there is more handy way to solve this simple task, so I'll appreciate if somebody shares it to me.

**Comment by gitbrent** [comment]
The library can create lines:

### [API Shapes](https://gitbrent.github.io/PptxGenJS/docs/api-shapes.html)

Also check `examples`

![screen shot 2018-08-08 at 23 35 14](https://user-images.githubusercontent.com/7218970/43878265-c0f78948-9b63-11e8-92e3-0953c81cb720.png)
