### ISSUE TITLE
Possible to Change size/width of bar-area/val-axis?

### ISSUE THREAD

**Issue by Jank1310** [gitbrent/PptxGenJS#383]
Hey guys,

first of all, thank you for this great library! :+1: 

Maybe I overlooked it at the docs but is it possible to change the width of the "bar-area"/length of the val-axis to some specific value? My goal is to have identical val-axis lengths on both charts.

![bildschirmfoto von 2018-08-02 16-54-47](https://user-images.githubusercontent.com/789096/43592024-f2d478de-9674-11e8-8856-c939446f16de.png)

**Comment by gitbrent** [comment]
Hi @Jank1310 

I don't believe there is a PowerPoint setting that allows the alignment of chart val axis' like you're aiming for... IIRC, we can only specify the entire chart area, then MS proportions the layout.
