### ISSUE TITLE
Transform html to PowerPoint 

### ISSUE THREAD

**Issue by masterlilou** [gitbrent/PptxGenJS#390]
Will be nice to convert a html text into PowerPoint 

Example
TEXT=
     '<b>hello <i> WORLD </></>`';

**Comment by gitbrent** [comment]
Only tables can be used to create slides (not divs etc).

Use jQuery to do that:

```
$('body').append('<table id="newTab" style="display:none">...</table>');
pptx.addSlidesForTable('newTab');
```
