### ISSUE TITLE
pptxgen JS line chart plot discarding null/undefined values

### ISSUE THREAD

**Issue by karankia** [gitbrent/PptxGenJS#392]
Hi,
It seems a similar issue was addressed before with the framework not generating data points when the data value was 0, however in this case I am having a issue with slide generated using pptxgenjs framework plotting the line chart at wrong coordinates if the data value is null or undefined. To overcome this problem I replaced all the nulls with 0 but for us that is not an actual description of the data. Below is a piece of  my code.
`var pptx = new PptxGenJS(); 
var slide = pptx.addNewSlide();
var chartData =[
  {
    "name": "Liberty Mutual Insurance Company",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      0.6,
      null,
      null,
      null,
      0.026208
    ],
    "index": 0
  },
  {
    "name": "manager",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      3.1839709999999997,
      null,
      3.1429930200000005,
      null,
      0.614098,
      null,
      null,
      0.6,
      1.6232028000000003
    ],
    "index": 1
  },
  {
    "name": "Amazon.com",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      4.68225142,
      11.95689875,
      8.1950808,
      35.12873491,
      null,
      3.74666482,
      null,
      null,
      null,
      null
    ],
    "index": 2
  },
  {
    "name": "Liberty Mutual",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      5.02750007,
      14.04236167,
      1.13333336,
      5.0686934,
      12.584045000000003,
      11.1698898
    ],
    "index": 3
  },
  {
    "name": "Liberty Mutual Insurance",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      1.50000004,
      null,
      2.0121253,
      0.8,
      null
    ],
    "index": 4
  },
  {
    "name": "Call Center",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 5
  },
  {
    "name": "Liberty",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      1.5800002,
      null,
      null,
      null,
      0.62
    ],
    "index": 6
  },
  {
    "name": "Manager",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      0.812984,
      null,
      null,
      null,
      1.485892
    ],
    "index": 7
  },
  {
    "name": "Boston",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      -0.24000001
    ],
    "index": 8
  },
  {
    "name": " Amazon.com",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      0.665,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 9
  },
  {
    "name": "€™",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      1.9318145,
      0.94416666
    ],
    "index": 10
  },
  {
    "name": "\"perks\"",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0.49,
      null,
      0.49
    ],
    "index": 11
  },
  {
    "name": "amazon",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      0.520894,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 12
  },
  {
    "name": "€¢",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      0.950392,
      0.6834166,
      null,
      null,
      null,
      null,
      null,
      0.8335
    ],
    "index": 13
  },
  {
    "name": "open door",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      0.81461704,
      null,
      0.414617,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 14
  },
  {
    "name": "\"rate\"",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 15
  },
  {
    "name": "HR",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 16
  },
  {
    "name": " to.do",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 17
  },
  {
    "name": " #1",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      4.013119
    ],
    "index": 18
  },
  {
    "name": " before.it",
    "labels": [
      43010,
      43011,
      43012,
      43013,
      43014,
      43015,
      43017,
      43018,
      43019,
      43020
    ],
    "values": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "index": 19
  }
];
slide.addChart( pptx.charts.LINE, chartData);
 pptx.save();`
Attached is the output slide
![screenshot at 2018-08-13 10 58 43](https://user-images.githubusercontent.com/8050469/44095000-b062d024-9fa5-11e8-8b9a-8b717633fe78.png)
However the actual result should be something like this 
![screenshot at 2018-08-13 13 17 25](https://user-images.githubusercontent.com/8050469/44095030-c1b59f96-9fa5-11e8-998d-457bff48782a.png)
Any help will be great as it most likely seems a bug in  the framework, it seems that the program discards null values and starts drawing when it finds an actual number. Using v2.2.0

**Comment by nevermore2014** [comment]
wow.. looks like you really hate closing tabs..

**Comment by gitbrent** [comment]
Hi @karankia 

Version added a new option for this: `displayBlanksAs`.  It defaults to 'span' (drawing a line between missing values), so it should just "work" now.
