### ISSUE TITLE
addImage with not working with node version

### ISSUE THREAD

**Issue by stevedorke** [gitbrent/PptxGenJS#394]
tried to run the node-example with the slide.addImage with an http link for the path:

`slide.addImage({
	path: "https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg",
	x: 1,
	y: 1,
});
`

and got the following error:
pptxgenjs ver: 2.3.0-beta.20180820
ERROR....: Unable to read media: "https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg"
DETAILS..: Error: ENOENT: no such file or directory, open 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg'

passing a relative path to a local image works,  but passing an http link does not.

**Comment by gitbrent** [comment]
Hi @stevedorke 

Node encoding for remote images was the sole remaining feature for the new `path` features introduced recently.

The final code is checked in and this URL loads successfully now.

![screen shot 2018-08-25 at 20 08 20](https://user-images.githubusercontent.com/7218970/44623908-bb93e400-a8a2-11e8-99ad-822bbe75cf1a.png)
