### ISSUE TITLE
Table Row Size and Margin issues causes proper Row margin settings to be ignored

### ISSUE THREAD

**Issue by tanhe03** [gitbrent/PptxGenJS#396]
Due to problem in PPTXGenJS (which we love) we can not generate tables of with desired row margin sizes.  See attached images.

Table rowH values of < 0.3 are ignored.   When we specify rowH of  0.3 the height the PPT Layout Row height is set to 0.32".  However, if we change the rowH value to 0.1 or 0.2 the PPT layout Row height is still set to 0.32 or greater.  
However, if I use PowerPoint to define a custom  desired margin, for example to of 0.01" for left, right, top and bottom values then we can NOT set the height to 0.12"   (Font Calibri size 6 )  and the table generated is correct.

Powerpoint doc indicates that the row Height will be constrained to be LESS than the margin size.

I assume the problem is due to a rounding error when rowH of < 0.3" is specified.   OR it is due to margin array values [0.01, 0.01, 0.01, 0.01} being ignored due to there small size or rouding error?

If there is a workaround please let us know.
![beforelimitation](https://user-images.githubusercontent.com/6098895/44742340-a222b000-aacd-11e8-9cc6-5b354e2d263a.png)
![nolimitationwhenusingpowerpoint](https://user-images.githubusercontent.com/6098895/44742344-a4850a00-aacd-11e8-8703-4d5132b37e8d.png)

Regards, Henry

**Comment by tanhe03** [comment]
Note:  The first screen shot shows our table with the rowH of 0.3,  However, we would like to show more rows on the slide by decreasing the row margins or change the rowH.  However, changes to any of these values are ignored.   The second screen shot shows that within PowerPoint we can 1) change he Margin values to 0.1"  2) once changed we can the change the row height and we have the desired layout.

Thanks
Henry

**Comment by gitbrent** [comment]
What code are you using?

**Comment by tanhe03** [comment]
I apologize for the delay in responding,
We are using node version  pptxgenjs@1.8.0
