### ISSUE TITLE
callback support for save method

### ISSUE THREAD

**Issue by ellisgl** [gitbrent/PptxGenJS#40]
I was noticing that I was sending the file before it was update and would like to have a callback fired after the file is written.

**Comment by ellisgl** [comment]
https://github.com/gitbrent/PptxGenJS/pull/41

**Comment by gitbrent** [comment]
Hi @ellisgl ,

Thanks for opening an Issue and supplying the code!

Change has been implemented (I've added the filename as a return value to the callback function) and the `nodejs-demo.js` file has been updated with examples.

**Comment by Slidemagic** [comment]
My presentations have a lot of images, so I use plenty of async/awaits while generating a PPTX, the "filename" callback fires too early in my case. I saw that a Promise for save is coming in 3.0 https://github.com/gitbrent/PptxGenJS/blob/master/CHANGELOG.md, is there already a quick fix I can apply to the code while waiting for the full release?

**Comment by Slidemagic** [comment]
My temporary fix for the saveCallback firing too early for whatever reason in Electron is saving as a node buffer, then saving the buffer as a '.pptx' in my own app.
` pptx.save(fileNameNotUsed, buffer => {
 fs.writeFileSync(fileName + '.pptx, buffer)
                }, 'nodebuffer')`

**Comment by gitbrent** [comment]
Version 3.0 will be released very soon and returns a Promise with every save method.
