### ISSUE TITLE
Add bullet of text to Master

### ISSUE THREAD

**Issue by IvanTao** [gitbrent/PptxGenJS#400]
Hi, I want to add bullet of text to Master. but I can't change the fontsize, the word font size always 18. below is my code. please help me.
My import js is:
/PptxGenJS/libs/jquery.min.js
/PptxGenJS/libs/jszip.min.js
/PptxGenJS/libs/promise.min.js
/PptxGenJS/dist/pptxgen.js
/PptxGenJS/dist/pptxgen.shapes.js 

-------- my code is below ------------

	pptx.defineSlideMaster({
		title: 'MASTER_BACKUP',
		bkgd: 'FFFFFF',
		margin:  [ 0, 0, 0, 0 ],
		objects: [
                    { 'text':  { text:
                                [
				{ text:'Bullet one',     options:{ fontSize:24, bullet:true, color:'99ABCC'                } },
				{ text:'Indent-Level 1', options:{ fontSize:32, bullet:true, color:'FFFF00', indentLevel:1 } },
				{ text:'Indent-Level 2', options:{ fontSize:42, bullet:true, color:'0088CC', indentLevel:2 } },
				{ text:'Indent-Level 3', options:{ fontSize:48, bullet:true, color:'CC88BB', indentLevel:3 } },
				{ text:'Indent-Level 3', options:{ fontSize:48, bullet:true, color:'CC88BB', indentLevel:3 } },
				{ text:'Indent-Level 2', options:{ fontSize:42, bullet:true, color:'0088CC', indentLevel:2 } },
				{ text:'Indent-Level 2', options:{ fontSize:42, bullet:true, color:'0088CC', indentLevel:2 } },
				{ text:'Indent-Level 1', options:{ fontSize:32, bullet:true, color:'FFFF00', indentLevel:1 } },
				{ text:'Bullet no indent', options:{ fontSize:24, bullet:true, color:'99ABCC'                } },
				{ text:'Bullet Last',    options:{ fontSize:24, bullet:true, color:'99ABCC'                } }
			], 
                                options:{ x:0, y:0.5, w:'100%',h:6.0,fontFace:'Arial',fontSize:24}
                               } 
                    }
             	]
	});
![2018-09-12_14-13-06](https://user-images.githubusercontent.com/34829050/45405678-76d7bd80-b696-11e8-88a8-74cf5fcd5453.png)

**Comment by IvanTao** [comment]
When I download the last version demo. the same issues exist. the issue is below:
 I find the demo html and the demo js. I change the Master text fontsize from 20 to 32. but it always 20.
![2018-09-12_16-59-52](https://user-images.githubusercontent.com/34829050/45414298-93cbbb00-b6ad-11e8-8228-de610cc43809.png)
![image](https://user-images.githubusercontent.com/34829050/45414361-b9f15b00-b6ad-11e8-80bb-a7a07b5b2369.png)

**Comment by IvanTao** [comment]
My  environment : 
    browser  --  Chrome.
    system --- Win 10.

**Comment by gitbrent** [comment]
`fontSize` is correct - `font_size` was removed in 2.0

What version are you using?

**Comment by IvanTao** [comment]
Hi,@gitbrent.
I used 2.0 before today, but now I have update to 2.3.0. but when I generate PPT.  it always show : 
![image](https://user-images.githubusercontent.com/34829050/45465932-0ee2af00-b74a-11e8-9f31-8df1d3ce6580.png)

**Comment by IvanTao** [comment]
hi,@gitbrent . The version  2.0 to 2.3.0. without remove font_size to fontSize. Are there any other changes?

**Comment by gitbrent** [comment]
Sure, here's the list:

### [2.0 Changes](https://gitbrent.github.io/PptxGenJS/docs/deprecated.html)

**Comment by IvanTao** [comment]
hi,@gitbrent , my ppt always need me to repair after change the version from 2.0 t0 2.3.0 ,and I have update code according to 2.0 changes. Do you have any  suggestions to check the problem?

**Comment by IvanTao** [comment]
@gitbrent ,Thanks, I have fixed my issue. Has the function path  of img in defineSlideMater  been modified from 2.0 to 2.3.0?  when I use : 
pptx.defineSlideMaster({
          title: 'MASTER_SLIDE',
          bkgd:  'FFFFFF',
          margin:[0.5, 0.75, 0.5, 0.75],
          objects: [
              { 'image': { x:10.3, y:6.72, w:2.51, h:0.56, path:'{!$Resource.AptivLogo}' } }, 
              
          ]
          
           //slideNumber: { x:0.3, y:'90%' }
        });

The img can be displayed. but always show ppt repair reminder.

**Comment by gitbrent** [comment]
@IvanTao, no... there's lots of examples in the `pptxgenjs-demo.html` file, full path, URL, etc. and they still work the same.

**Comment by IvanTao** [comment]
Ok, I will test more. Thanks for your help.
