### ISSUE TITLE
Question - Html-to-powerpoint

### ISSUE THREAD

**Issue by PauldaviesDM** [gitbrent/PptxGenJS#404]
Does the Html-to-powerpoint method apply the css styles from the class?

<tr>
			<td class="TableRecords_OddLine">Record1</td><td class="TableRecords_OddLine"><div align="right">1</div></td><td class="TableRecords_OddLine"><div align="center"><img alt="" src="/RichWidgets/img/Icon_Check_Green.gif?907"></div></td><td class="TableRecords_OddLine"><div style="display:none">hiddenOne</div></td>
		</tr>

ie 

.TableRecords_OddLine {
    border-bottom: 1px solid #ddd;
    padding: 10px;
    vertical-align: middle;
}

**Comment by gitbrent** [comment]
Yes, it does.  There are exceptions, and `display:none` is one of them.

If that's what you're having issues with, i'd recommend creating a table clone using jQuery, modify it, then pass to PptxGenJS.

See `examples/pptxgenjs-demo.html` for lots of table styling demos.

**Comment by PauldaviesDM** [comment]
Brent,

Thanks for your response.  Is nth-child() one of the exceptions.  I've noticed that for the snippets below of the application we aren't getting the background colour in the PPTX. 

.TableRecords tr:nth-child(even) {
    background-color: #03f3f3;
}


<table class="TableRecords OSFillParent OSAutoMarginTop" id="DublinTheme_wt32_block_wtMainContent_wtExampleTable" cellspacing="0">
......................	
</table>

**Comment by gitbrent** [comment]
I use jQuery to interrogate styles, so it should.
