### ISSUE TITLE
[Feature Request] Adding label to Scatter plot

### ISSUE THREAD

**Issue by nevermore2014** [gitbrent/PptxGenJS#410]
Hello @gitbrent !

I really appreciate the library that you created, I happen to have a small feature not sure if is possible? So for generating a XY SCATTER chart would it be possible to add label to each of the data point? Right now you can only add label to Bar chart or Radar chart, not Scatter chart.

// Chart Type: XY SCATTER var dataChartScatter = [ { name:'X-Axis', values:[1,2,3,4,5,6,7,8,9,10] }, { name:'Y-Value 1', values:[13, 20, 21, 25] }, { name:'Y-Value 2', values:[21, 22, 25, 49] } ]; slide.addChart( pptx.charts.SCATTER, dataChartScatter, { x:1.0, y:1.0, w:6, h:4 } );

Let me know, thanks!

Hongyu

**Comment by gitbrent** [comment]
Hi @nevermore2014 ,

If you'd like to look through the code and see what it would take to add this feature via a pull request, i'd encourage you to do so.

**Comment by nevermore2014** [comment]
@ReimaFrgos oh man, who are you.. you are just the equalizer to me, thanks so much!! I would love to buy you a cup of coffee if you are in great Boston area!

**Comment by jsvishal** [comment]
Do we have support for labels in BUBBLE CHART?
