### ISSUE TITLE
X and Y table coordinates with value of zero ignored

### ISSUE THREAD

**Issue by tovab** [gitbrent/PptxGenJS#411]
Hi

Thanks for the great library.

There seems to be a bug when adding a table with coordinates of 0. When an x or y of 0 is set in the options for addTable, the function defaults the coordinate to some other larger number.

This seems to be happening because of this code-line 4994
```
opt.x          = getSmartParseNumber( (opt.x || (EMU/2)), 'X' );
opt.y          = getSmartParseNumber( (opt.y || EMU), 'Y' );
```
where the option to the right of the "||" is used when opt.x or opt.y is falsey, including 0. It needs to check for undefined instead of false.

Can you fix this? 

Thanks so much

**Comment by gitbrent** [comment]
Hi @tovab ,

Thanks for reporting this issue.

Tables can reside at `0`,`0` now

![screen shot 2018-10-11 at 23 41 49](https://user-images.githubusercontent.com/7218970/46848505-dae1c480-cdaf-11e8-8305-d26e48548e43.png)

**Comment by tovab** [comment]
thank you!
