### ISSUE TITLE
Rounded Rectangle shape not working

### ISSUE THREAD

**Issue by sjones88** [gitbrent/PptxGenJS#412]
When I try to add `pptx.shapes.ROUNDED_RECTANGLE` to a slide, I get an error: `pptxgen.bundle.js:2 Missing/Invalid shape parameter! Example: 'addShape(pptx.shapes.LINE, {x:1, y:1, w:1, h:1});'`

**Comment by gitbrent** [comment]
Be sure you've included the shape library.

[Shape Library](https://github.com/gitbrent/PptxGenJS#full-powerpoint-shape-library)

**Comment by sjones88** [comment]
That solved it. I was confused because I included pptxgen.bundle.js and pptx.shapes.RECTANGLE worked, so I assumed the shape library was included in the bundle. Thanks!

**Comment by Smithvinayakiya** [comment]
Have the name of all shapes been mentioned somewhere??
