### ISSUE TITLE
How to upload PPT on S3 Without download into local

### ISSUE THREAD

**Issue by AjayRawat232** [gitbrent/PptxGenJS#413]
Hi @gitbrent 

i want to upload ppt on s3. how can we achive it.

Thanks in advance.

**Comment by gitbrent** [comment]
Hi @AjayRawat232 

- Node app: use a stream and pass it amazon's API, or save the file locally and FTP/REST post, etc.
- Client-side browser: There's no way to redirect the file.  Your browser downloads the presentation.

**Comment by AjayRawat232** [comment]
Hi,

I am unable to download the PPT in Firefox but the same PPT is downloading in Chrome.
I have checked Issue #81 which is not worked for me. Can you give me any other reliable solution for it.

Thanks in Advance

**Comment by gitbrent** [comment]
Follow-up:

As of version 2.5.0, client-browsers can save presentations as a `blob`, which could then be redirected to Amazon S3, OneDrive, DropBox, etc.

### [API Docs: Saving](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html)
