### ISSUE TITLE
Table options to disable "AutoFit Row Height" or "Resize rows to fit contents"

### ISSUE THREAD

**Issue by mfikria** [gitbrent/PptxGenJS#416]
Currently, the rows always wrap the text inside. How could i do to make the row's height as minimum as possible without wrapping the content inside with this library?
In powerpoint you can disable "AutoFit Row Height" or if you use keynote you can disable "Resize rows to fit content" as well.

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by burivuhster** [comment]
@mfikria Did you find a solution by any chance? I'm facing exactly the same issue right now
