### ISSUE TITLE
Set fixed width to column using "addSlidesForTable".

### ISSUE THREAD

**Issue by priyaraskar** [gitbrent/PptxGenJS#42]
I am trying to fix the width of Col2 column, as shown in table,
but it always takes same width for all columns.
![image](https://cloud.githubusercontent.com/assets/24734651/22924095/e380d896-f2c9-11e6-880c-5280831db99c.png)

How to provide width style to column?

**Comment by gitbrent** [comment]
Hi @priyaraskar 

I'll look into adding a way to specify a size for columns (either inches or percent).

**Comment by gitbrent** [comment]
Hi @priyaraskar 

Are you generating the table using `addSlidesForTable()` or `addTable()`?

The later enables you to specify column widths using `colW` [table ref](https://github.com/gitbrent/PptxGenJS#table-layout-options)... will that work?

If you generating the table from an HTML table using `addSlidesForTable()`, then you can utilize a data tag to specify a minimum width.

Example:
```html
<table>
  <thead>
    <th data-pptx-min-width="0.75">Emp ID</th>
    <th>First Name</th>
    <th>Last Name</th>
  </thead>
  <tbody>
  [...]
  </tbody>
</table>
```

**Comment by gitbrent** [comment]
Update:
* Added to [README](https://github.com/gitbrent/PptxGenJS#table-to-slides-html-options)
