### ISSUE TITLE
Data Label Position outside(callout) in Doughnut Charts.

### ISSUE THREAD

**Issue by BandaSatish07** [gitbrent/PptxGenJS#425]
Hi Team,

Thank for the providing such great library for PPT Generation.

  While using the Doughnut charts data labels are overlapping when the value is nearly equal with minor difference, Is there any solution to display labels out side of the chart without overlapping, we tried the property dataLabelPosition(bestFit,b,ctr,inBase,inEnd,l,outEnd,r,t) but it is not affecting to doughnut charts.

Thanks.
![overlappingissue](https://user-images.githubusercontent.com/44244180/47633597-7dea5a80-db74-11e8-8e6e-4e6f5de158db.png)

**Comment by gitbrent** [comment]
[Closing due to age]
