### ISSUE TITLE
Bold Font for Axis labels in chart and legend font face.

### ISSUE THREAD

**Issue by BandaSatish07** [gitbrent/PptxGenJS#426]
Hi Team,

Is there any option to apply bold property to Axis labels of the charts. and also is there any option to specify FontFace to the legends for the graph.

Thanks
 
![legendfontface](https://user-images.githubusercontent.com/44244180/47633896-8f803200-db75-11e8-9944-17f5e2b007b4.png)

**Comment by gitbrent** [comment]
Hi @BandaSatish07 

Sure, there are about 100 `chart` options.

[Chart API documentation](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#chart-axis-options)

**Comment by BandaSatish07** [comment]
Hi ,

Thanks for the reply,

Tried all the available options to change the FontFace of the legends, We Found legendFontSize, legendColor, legendPos properties but legendFontFace is not available,
 So we have tried with the following lines of code in plugin it worked for us, 

After line:  2660 
Function : makeXmlCharts 
Code : strXml += '<a:latin typeface="'+ (rel.opts.legendFontFace || 'Arial') +'"/>';

Below code changes for Bold  Axis label in Chart

Line no: 3446
**Old Statement** : strXml += '    <a:defRPr sz="'+ (opts.catAxisLabelFontSize || DEF_FONT_SIZE) +'00" b="0" i="0" u="none" strike="noStrike">';

**Updated statement** : strXml += '    <a:defRPr sz="'+ (opts.catAxisLabelFontSize || DEF_FONT_SIZE) +'00" b="'+(opts.catAxisLabelFontBold ? 1:0)+'" i="0" u="none" strike="noStrike">';

Line no:2892
**Old Statement** : strXml += '        <a:defRPr b="0" i="0" strike="noStrike" sz="'+ (opts.dataLabelFontSize || DEF_FONT_SIZE) +'00" u="none">';

**Updated statement** :  strXml += '        <a:defRPr b="'+(opts.dataLabelFontBold ? 1:0)+'" i="0" strike="noStrike" sz="'+ (opts.dataLabelFontSize || DEF_FONT_SIZE) +'00" u="none">';

Please review and make a note about the changes, correct me if we miss something.

Thanks,

**Comment by gitbrent** [comment]
Hi @BandaSatish07 

I hadn't noticed that the API lacked `legendFontFace`!  Thanks for adding this option.

Bold options added as well: `catAxisLabelFontBold`, `dataLabelFontBold`, `valAxisLabelFontBold`.
