### ISSUE TITLE
Dynamic Text Options do not apply

### ISSUE THREAD

**Issue by sunnyar** [gitbrent/PptxGenJS#427]
Thanks for this amazing package.

I have been using the "table2slides2" method call to add dynamic content for a table from your example-demo file but it seems the addText options parameter has no effect to the text content whatsoever.

i.e If I change the fontSize, color etc. it doesn't apply to the text.

Can you please fix it.

**Comment by gitbrent** [comment]
Hi @sunnyar 

So you're using the `addText()` option in your `addSlidesForTable()` method call?

Please provide the code and the output.

### [API Docs](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html)

**Comment by sunnyar** [comment]
Hi @gitbrent ,

My code snippet is as below:

objOpts = {}
objOpts.addText = { text: "Table Title", options:{ x:1.1, y:"10%", color:'0088CC', fontFace:'Arial', fontSize:12 } };
pptx.addSlidesForTable('table-id', objOpts);

**Comment by sunnyar** [comment]
Any updates @gitbrent . Is the issue I am facing a bug or am I doing something wrong ?

**Comment by sunnyar** [comment]
Got it resolved.
The issue is that we need to use "opts" instead of "options" in the addText assignment call for the addSlidesForTables.

**Old code**
`objOpts.addText = { text: "Table Title", options:{ x:1.1, y:"10%", color:'0088CC', fontFace:'Arial', fontSize:12 } };`

**New Code**
`objOpts.addText = { text: "Table Title", opts:{ x:1.1, y:"10%", color:'0088CC', fontFace:'Arial', fontSize:12 } };`

**As per Line 5307 in pptxgen.js**

`if ( opts.addText  ) newSlide.addText(  opts.addText.text,   (opts.addText.opts  || {}) );`

Thank You

**Comment by gitbrent** [comment]
Thanks @sunnyar 

The code and the documentation did not match, hence `opts` working instead of `options`

I've updated the code to now accept either one.
