### ISSUE TITLE
Oval shape not drawn

### ISSUE THREAD

**Issue by Dzivo** [gitbrent/PptxGenJS#429]
Oval shapes are not drawn at all

Example on your fiddle with your example:
https://jsfiddle.net/qkm6eabg/

**Comment by gitbrent** [comment]
Hi @Dzivo 

You'll want to include the [full shape library](https://github.com/gitbrent/PptxGenJS#full-powerpoint-shape-library) in order to utilize anything other than basic shapes.

**Comment by adong** [comment]
@dzivo

You can add this link to your jsfiddle: https://cdn.jsdelivr.net/gh/gitbrent/PptxGenJS/dist/pptxgen.shapes.js

Demo Link:
https://jsfiddle.net/9L7k31jd
