### ISSUE TITLE
Bullets do not work with text objects in addText() method

### ISSUE THREAD

**Issue by ellisgl** [gitbrent/PptxGenJS#44]
I've tried a couple way to make a bullet list - but it's not working as expected:

Test 1:

                         slide2.addText(
                             [
                                 {
                                     text: '1st point.'
                                 },
                                 {
                                     text: 'Something...'
                                 }
                             ],
                             {
                                 x: 7.75,
                                 y: 1.3,
                                 w: 2.17,
                                 h: 5.5,
                                 valign: 'top',
                                 margin:0.1,
                                 font_face: 'Arial',
                                 font_size: 12,
                                 bullet: true
                             });

Test 2:

                         slide2.addText(
                             [
                                 {
                                     text: '1st point.',
                                     options: {
                                         bullet: true,
                                     }
                                 },
                                 {
                                     text: 'Something...',
                                     options: {
                                         bullet: true,
                                     }
                                 }
                             ],
                             {
                                 x: 7.75,
                                 y: 1.3,
                                 w: 2.17,
                                 h: 5.5,
                                 valign: 'top',
                                 margin:0.1,
                                 font_face: 'Arial',
                                 font_size: 12,
                                 bold: false,
                             });

**Comment by gitbrent** [comment]
Hi @ellisgl ,

Thanks for opening this issue.

I'm pleased to report that bullets within text objects are now supported.

Example:
```javascript
slide.addText(
  [
    { text:'I am a text object with bullets.. ', options:{bullet:true, color:'CC0000'} },
    { text:'and i am the next text object!'    , options:{bullet:true, color:'00CD00'} },
    { text:'Text object without bullet:true.. ', options:{font_size:12} },
    { text:'then this is a text object too!'   , options:{font_size:12} },
    { text:'Final text object w/ bullet:true!!', options:{bullet:true, color:'0000AB'} }
  ],
  { x:8.0, y:5.0, w:'30%', h:1.4, color:'ABABAB', margin:1 }
);
```
![screen shot 2017-02-26 at 17 59 44](https://cloud.githubusercontent.com/assets/7218970/23345067/6622aa54-fc4d-11e6-92d9-91d9623673e4.png)

**Comment by gregroyal** [comment]
This doesnt seem to work correctly anymore? I used this exact snippet and it doesnt bullet items correctly.

The issue I'm running into is if i start a bulleted list, the bullets dont stop if its within the same text block
