### ISSUE TITLE
[Feature Request] Add catAxisLabelRotate feature.

### ISSUE THREAD

**Issue by sorb999** [gitbrent/PptxGenJS#441]
Hello @gitbrent,

I really appreciate the library that you have created.
I happen to have a small feature **catAxisLabelRotate**. I am able to find **valAxisTitleRotate** to rotate chart title but not find any way to rotate axis labels.

**Comment by gitbrent** [comment]
Hi @sorb999 

`catAxisTitleRotate` exists as an option already: [Chart API](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#chart-axis-options)

**Comment by sorb999** [comment]
Hi @gitbrent 

I know there is a feature to rotate _title_ but I want to rotate _tabel_ for that I am looking an option `catAxisLabelRotate ` like `catAxisTitleRotate ` .

**Comment by gitbrent** [comment]
Ah, got it.  Feel free to submit a pull request to implement this feature.  I'd imagine the code is similar to the other *rotate XML...

**Comment by gitbrent** [comment]
Addressed via Pull #938
