### ISSUE TITLE
Angular integration failed - '/node_modules/PptxGenJS/dist/pptxgen"' resolves to a non-module entity and cannot be imported using this construct.'

### ISSUE THREAD

**Issue by Prasanth-ECE** [gitbrent/PptxGenJS#444]
Tried the Ppt generation into the angular 5 project by installing through yarn.
Getting error as '/node_modules/PptxGenJS/dist/pptxgen"' resolves to a non-module entity and cannot be imported using this construct.'

seems the error is around the exporting module.

exported PptxGenJS module be like 
class PptxGenJS { }
'export = PptxGenJS.PptxGenJS;' - pptxgen.d.ts

if i change that to
export default class PptxGenJS { }
'export = PptxGenJS;'

source from 'https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this'

then it's working fine.

**Comment by crazyx13th** [comment]
sorry, but both not working for me.
the new version gives me a:
`Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.`
I tried a lot of combinations, but always fail

thanks!

**Comment by gitbrent** [comment]
Dang.

Does it build if you remove the first 2 lines?
```
export as namespace PptxGenJS;

export = PptxGenJS;
```

**Comment by crazyx13th** [comment]
I try all combinations, but don't find a clean solution. Maybe I'll found some time next weeks to update the d.ts file, but now...

And there are some missing props, too
![grafik](https://user-images.githubusercontent.com/8912561/51824176-dcdd7e00-22e1-11e9-8f52-f11d5da92a7e.png)

thanks!
