### ISSUE TITLE
Line chart value's color is not applying.

### ISSUE THREAD

**Issue by sorb999** [gitbrent/PptxGenJS#445]
I am trying to add different colors at different value points of the bar chart. It gives me below chart ``
![barchart](https://user-images.githubusercontent.com/18715975/49363016-88b18580-f706-11e8-8009-c0983d742a8a.PNG)
It is working fine and give different bar colors with the following code
```
var PptxGenJS = require("pptxgenjs");
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();
var MONS = ['Jan','Feb','Mar','Apr','May','Jun'];
var dataChartLine = [{ name: 'Proj Sales', valAxisTitleRotate:50, labels: MONS, values: [1000, 2600, 3456, 4567, 5010, 6009] }];

var optsChartBar = { x:1, y:1, w:12, h:6,
  showCatAxisTitle: true,
  valAxisTitleRotate: 60,
  catAxisLabelColor   : 'CC0000',
  catAxisLabelRotate   : 60,
  catAxisTitle: "Housing Type",
  catAxisTitleRotate: 60,
  showLabel:true,
  showLegend: true,
  chartColors:['653328','8DA20D','312A28','4F64A5','030818','0088CC']
}
slide.addChart( pptx.charts.BAR, dataChartLine, optsChartBar);
pptx.save('Demo-Chart');
```
But when I change chart type to **LINE** using `pptx.charts.LINE` it doesn't add different colors of different value points(like bar chart) but shows only one color to all value point. Like this :-

![linechart](https://user-images.githubusercontent.com/18715975/49363239-286f1380-f707-11e8-9b77-6e0f1b4a3a38.PNG)

> Looking through the code it seems like it is some how of an intended behavior. Seems like different color of different values is designed to work for bar charts only:
>
> [PptxGenJS/dist/pptxgen.js](https://github.com/gitbrent/PptxGenJS/blob/e4c46021f91deb4b34be9043e72d5f5ae37ab391/dist/pptxgen.js#L2691-L2695) 
> Lines 2691 to 2695 in [e4c4602](/gitbrent/PptxGenJS/commit/e4c46021f91deb4b34be9043e72d5f5ae37ab391)
>  // Color chart bars various colors 
>  // Allow users with a single data set to pass their own array of colors (check for this using != ours) 
>  if ( chartType == 'bar' && ( data.length === 1 || opts.valueBarColors ) && opts.chartColors != BARCHART_COLORS ) { 
>  	// Series Data Point colors 
>  	obj.values.forEach(function(value,index){ 
......
..
Where as for line chart it does not allow array to set colors,
> [PptxGenJS/dist/pptxgen.js](https://github.com/gitbrent/PptxGenJS/blob/e4c46021f91deb4b34be9043e72d5f5ae37ab391/dist/pptxgen.js#L2674-L2689)

Please check this and let me know if any other information is needed.

**Comment by gitbrent** [comment]
Does PowerPoint support varying colors along a single line like what you're asking for?

**Comment by Harshith996** [comment]
> Does PowerPoint support varying colors along a single line like what you're asking for?

yes, i think it does. Is there a way to do so through this lib?
