### ISSUE TITLE
[Feature Request] Support for template

### ISSUE THREAD

**Issue by TalissonJunior** [gitbrent/PptxGenJS#447]
I would do like to suggest the template feature for pptxGenjs to be able to replace text, images and charts on a existent pptx, do you think that it is a good idea?  i can work on that for you guys, "i really need this feature on most of my projects"

**Comment by gitbrent** [comment]
Hi @TalissonJunior 

The PptxGenJS library is only used to generate PowerPoint presentations.

Opening, modifying, templating, etc. of other pptx files are features that will not be added.
