### ISSUE TITLE
Hyperlinks that reference to other slides

### ISSUE THREAD

**Issue by gabrielm0** [gitbrent/PptxGenJS#45]
Hi! is it possible to add hyperlinks in text elements that reference to other slides?

Thank you for this awesome library!

**Comment by gitbrent** [comment]
Hi @gabrielm0 ,

There's currently no hyperlink functionality, so i'll tag it as an enhancement.

Thanks!

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,
It will be great feature if it is implemented.
I will do my best to help you.

**Comment by ZouhaierSebri** [comment]
i yhink it Is it better to add new method addHyperlink

                       else if ( rel.type.toLowerCase().indexOf('hyperlink') > -1 ) {
				// As media has *TWO* rel entries per item, check for first one, if found add second rel with alt style
				if ( strXml.indexOf(' Target="'+ rel.Target +'"') > -1 )
					strXml += ' <Relationship Id="rId'+ rel.rId +'" Target="'+ rel.Target +'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink"/>'+CRLF;
				else
					strXml += ' <Relationship Id="rId'+ rel.rId +'" Target="'+ rel.Target +'" TargetMode="External" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink"/>'+CRLF;
			}

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,

can you check my solution to integrate it ?

**Comment by gitbrent** [comment]
Hi @ZouhaierSebri ,

This issue was actually asking for links across Slides, not external hyperlinks.  Those should be in the next release though.

Please use pull requests in the future when submitting code.

Thanks.

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent 
Thank you for the response

**Comment by gitbrent** [comment]
This is now supported:

```javascript
// EX: Hyperlink: Slide in Presentation
slide.addText(
    [{
        text: 'Slide #2',
        options: { hyperlink:{ slide:'2', tooltip:'Go to Summary Slide' } }
    }],
    { x:1.0, y:2.5, w:5, h:1 }
);
```

**Comment by balajiHms** [comment]
Hi Brent Ely ,
                    The above example has not working.Shows an mentioned error.Kindly help me.
ERROR: 'hyperlink.url is required and/or should be a string'

**Comment by balajiHms** [comment]
I want to switch to particular slide through hyperlink is that possible ??

**Comment by gitbrent** [comment]
@balajiHms 

Check to ensure you're using a recent version.

The sample code below works.  Use "Edit Link" to validate it's target.

```
var pptx = new PptxGenJS();

var slide1 = pptx.addNewSlide();
slide1.addText(
    [{
        text: 'Slide #2',
        options: { hyperlink:{ slide:'2', tooltip:'Go to Summary Slide' } }
    }],
    { x:1.0, y:2.5, w:5, h:1 }
);

var slide2 = pptx.addNewSlide();
slide2.addText(
  [
    { text:'1st line', options:{ fontSize:24, bullet:true, color:'99ABCC' } },
    { text:'2nd line', options:{ fontSize:36, bullet:true, color:'FFFF00', indentLevel:1 } },
    { text:'3rd line', options:{ fontSize:48, bullet:true, color:'0088CC', indentLevel:2 } }
  ],
  { x:1.5, y:1.5, w:6, h:2, margin:0.1, fill:'232323' }
);

pptx.save('PptxGenJS-Links');
```

![screen shot 2018-05-03 at 22 08 42](https://user-images.githubusercontent.com/7218970/39611647-e3193a26-4f1e-11e8-8c8e-71c9e11fc645.png)

**Comment by balajiHms** [comment]
HI Brent Ely.

slide.addText([{
        text: 'Slide 1',
        options: { hyperlink:{ url:'#2',tooltip:'Go to product details slide' }}
    }],
    { 
      x: '1.5%',
      y: '2',
      w: '55%',
      font_size: 15,
      color: '000000',
      align: 'l',
      indentLevel: 1,
      bold: true,
      fontFace: 'Arial',
      bullet: true });


I'm using latest version only.But I have faced an issue without URL.So changed code like above mentioned.It's working fine for me now.
