### ISSUE TITLE
checkbox within pptx output

### ISSUE THREAD

**Issue by roix31** [gitbrent/PptxGenJS#450]
Hi,
Is it possible to insert a tickable checkbox within the generated powerpoint file? or is it possible to embed/insert an excel object and use its tickable checkbox?
Please note: I need a checkbox that can be check NOT during the slide show presentation of powerpoint file. Please give me an idea of a checkbox that can be tick while editing the file.
Thank you.

**Comment by gitbrent** [comment]
Hi @roix31 

There are no plans to support form fields or embedded Excel workbooks at this point in time.
