### ISSUE TITLE
Set a row height of a table using h or rowH does not work

### ISSUE THREAD

**Issue by stephanielsx** [gitbrent/PptxGenJS#451]
Hi Team,

I have a table with multiple rows and I would like to only specify the height for one of the rows.

I have tried using the h and rowH properties in the options of the respective row and table, but row height remains the same.

Also, is there a way to get the height of a table?

Thanks.

**Comment by gitbrent** [comment]
Hi @stephanielsx 

Please see the `examples/pptxgenjs-demo.html` page for many examples of tables, including `rowH`

```
var arrTabRows = [
    [ {text:'1x1'}, {text:'2x1'}, { text:'2.5x1' }, { text:'3x1' }, { text:'4x1' } ],
    [ {text:'1x2'}, {text:'2x2'}, { text:'2.5x2' }, { text:'3x2' }, { text:'4x2' } ]
];
slide.addTable( arrTabRows,
    {
        x:0.5, y:4.0,
        rowH: [1, 2], colW: [1, 2, 2.5, 3, 4],
        fill:'F7F7F7', color:'6c6c6c',
        fontSize:14, valign:'center', align:'ctr',
        border:{pt:'1', color:'BBCCDD'}
    }
);
```

![screen shot 2018-12-11 at 19 49 51](https://user-images.githubusercontent.com/7218970/49841648-f5b7c180-fd7d-11e8-8f59-020ffbc49d67.png)
