### ISSUE TITLE
Ability to specify numbered list format

### ISSUE THREAD

**Issue by mayvazyan** [gitbrent/PptxGenJS#452]
First of all **Thank You** for such a great library!

Would you please advise on how hard would be to extend "bullet options" to allow to specify numbered list format?
At the moment all we can do is to specify that list is numbered, but we can't change which chars it will be using:
```
{
    bullet: {
        type: 'number'
    } 
}
```

In particular I need to built something like:
![image](https://user-images.githubusercontent.com/2960760/50174452-45146980-030b-11e9-8d24-b0f6bc21b740.png)

 `indentLevel` already allows to set indent, but "child" lists are using the same numbering format
![image](https://user-images.githubusercontent.com/2960760/50174878-69bd1100-030c-11e9-8d04-4c7ffbaa10f3.png)

**Comment by mayvazyan** [comment]
That's actually pretty easy to do!

Just replace 
```
strXmlBullet = '<a:buSzPct val="100000"/><a:buFont typeface="+mj-lt"/><a:buAutoNum type="arabicPeriod"/>';
```
by
```
const style = textObj.options.bullet.style ? textObj.options.bullet.style : 'arabicPeriod';
strXmlBullet = '<a:buSzPct val="100000"/><a:buFont typeface="+mj-lt"/><a:buAutoNum type="' + style + '"/>';
```

With that change in place you could specify any format you'd like:
- alphaLcParenBoth -- (a), (b), (c), ...
- alphaLcParenR -- a), b), c), ...
- alphaLcPeriod -- a., b., c., ...
- alphaUcParenBoth -- (A), (B), (C), ...
- alphaUcParenR -- A), B), C), ...
- alphaUcPeriod -- A., B., C., ...
- arabicParenBoth -- (1), (2), (3), ...
- arabicParenR -- 1), 2), 3), ...
- arabicPeriod -- 1., 2., 3., ...
- arabicPlain -- 1, 2, 3, ...
- romanLcParenBoth -- (i), (ii), (iii), ...
- romanLcParenR -- i), ii), iii), ...
- romanLcPeriod -- i., ii., iii., ...
- romanUcParenBoth -- (I), (II), (III), ...
- romanUcParenR -- I), II), III), ...
- romanUcPeriod -- I., II., III., ...

Source: (http://officeopenxml.com/drwSp-text-paraProps-numbering.php)[http://officeopenxml.com/drwSp-text-paraProps-numbering.php]

Example:
`bullet: { type: 'number', style: 'romanLcPeriod' }
`

**Comment by gitbrent** [comment]
Hi @mayvazyan 

Thanks for the request.

This feature has been added to the upcoming 3.0 release.

**Comment by artur-michalak** [comment]
@gitbrent latest pptgen supports only arabicPeriod (https://github.com/gitbrent/PptxGenJS/blob/1263b148178fd9b0bbadff7b69cfe2bf7390c189/dist/pptxgen.js#L4209). It looks like some regression to code in pull #555
Is there a chance to bring this feature back?

**Comment by gitbrent** [comment]
[Version 3.0](https://github.com/gitbrent/PptxGenJS/tree/version-3.0) supports any type of bullet.
