### ISSUE TITLE
Adding hyperlink to text in a slide corrupts presentation and results in blank slide

### ISSUE THREAD

**Issue by stephanielsx** [gitbrent/PptxGenJS#454]
Hi Team,

I tried declaring hyperlink in the options and assigning it to a text but when I save and open it in Powerpoint, the file is corrupted and the slide containing the hyperlink text is blank.

`var contentOptions = {
font_size: 8,
hyperlink: {slide: '2'}
}`

**Comment by gitbrent** [comment]
Please see the demo - it has hyperlink code samples

`examples/pptxgenjs-demo.html`

**Comment by ReimaFrgos** [comment]
Are there other objects on the slide? I suspect this could be the same issue as #465

**Comment by gitbrent** [comment]
Closing this as a duplicate (even though is was reported first).

### Tracking Issue: #465
