### ISSUE TITLE
table overlapped with master Slide

### ISSUE THREAD

**Issue by Prasanth-ECE** [gitbrent/PptxGenJS#456]
Hi Team,
Am facing a issue, If I have defined a masterSlider with logo and some other text at the bottom.

And If set table to 'autoPage', if table has more rows then the table overlapped with master Slider. 

Can we define to avoid overlapping. is there any option available ?
 or only forced to set height of table only ?
If I set manual height to table that looks weird.

1. first slide
![1](https://user-images.githubusercontent.com/35594090/50203398-6024bf00-0387-11e9-90d9-b71adbe0d173.png)

2. second slide table overlapped with master.
![2](https://user-images.githubusercontent.com/35594090/50203522-cb6e9100-0387-11e9-96e2-7965f99ba915.png)

3. continuation to table to auto fit.

![3](https://user-images.githubusercontent.com/35594090/50203437-86e2f580-0387-11e9-8d22-5f3a6bb69989.png)

Thanks.

**Comment by Prasanth-ECE** [comment]
I have tried like below: but same result as above, getting overlapped

       let pptx = new PptxGenJS();
        pptx.setBrowser(true)
        pptx.setLayout('LAYOUT_WIDE');
        pptx.setTitle('Prediction Presentation');
        pptx.defineSlideMaster({
            title: 'test',
            margin: [1,1,2.5,1],
            objects: [
                { 'rect':  { x: 0.00, y:6.90, w:'100%', h:0.8, fill:'003b75' } },
                { 'text':  { text:'Sample text', options:{ x:0.18, y:'87%', w:'30%', h:0.75, fontSize:16, fontFace:'Calibri', italic: true, color:'676666' } } },
                { 'image': { x:'80%', y:'85%', w:2.25, h:0.77, path:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Citi.svg/150px-Citi.svg.png' } }
            ]
        })

**Comment by gitbrent** [comment]
[Closing due to age]
