### ISSUE TITLE
Scatter Chart: Adding horizontal/vertical lines

### ISSUE THREAD

**Issue by vrimar** [gitbrent/PptxGenJS#459]
Hello, I'm trying to add horizontal/vertical lines to a scatter chart as seen in the example below:

![image](https://user-images.githubusercontent.com/5660247/50319075-58524100-0493-11e9-8bd5-9c4bf6564539.png)

I've managed to get something similar working in PptxGenJS:
```
  const pptx = new PptxGenJS();
  const slide = pptx.addNewSlide();

  const values = [];
  values[0] = 5;

  const horizontalValues = [];
  horizontalValues[1] = 10;
  horizontalValues[2] = 10;

  const verticalValues = []
  verticalValues[3] = 0;
  verticalValues[4] = 40;

  const data = [
    { name: 'X-Axis', values: [1, 10, 0, 5, 5] },
    { name: 'First', values },
    { name: '', values: horizontalValues },
    { name: '', values: verticalValues }
  ];

  slide.addChart(pptx.charts.SCATTER, data, {
    showLegend: true,
  });

  pptx.save('Testing');
```
The code above generates this powerpoint.
![image](https://user-images.githubusercontent.com/5660247/50319026-0e695b00-0493-11e9-8713-d44160885ef7.png)

Is there a better way to achieve this?

**Comment by ReimaFrgos** [comment]
Is it a requirement that the horizontal and vertical lines are part of the chart?
Are they fixed or dynamic?
Can your set known ranges for your axis values?

Depending on the above, you could use standard line shapes and automatically calculate the position that they need to be. Build them underneath the scatter chart so they aren't accidentally clicked and moved, but will still be visible.

**Comment by vrimar** [comment]
@ReimaFrgos, I actually did just that. I managed to get it working by using the axis min/max values and calculating line positions based on number of items. Isn't exactly flawless but is enough for my use case.
