### ISSUE TITLE
Table formatting bug with rowspans and colspans

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#46]
Found another bug with dissapearing value in cells:

![image](https://cloud.githubusercontent.com/assets/9961535/23059172/3ba00e8e-f509-11e6-8198-f739330e8e95.png)

Code: http://pastebin.com/zBKA3zMd

**Comment by gitbrent** [comment]
Hi @itskun ,

Ack!!  How did this bite me twice?! :-)  There was a single line of code that needed to be excised and that fixed the issue.

This time, i've created a crazy complicated example and added it to the demo:
![screen shot 2017-02-18 at 10 04 19](https://cloud.githubusercontent.com/assets/7218970/23095327/c0564af2-f5cd-11e6-9b75-7faf75a74179.png)

Thanks for the excellent bug hunting abilities. 👍
