### ISSUE TITLE
Extra line break if align specified

### ISSUE THREAD

**Issue by mayvazyan** [gitbrent/PptxGenJS#460]
- We have single paragraph of text
- First two words are in bold
- Other part of the paragraph is in plain text
- Extra line break occurs

Expected result:

![image](https://user-images.githubusercontent.com/2960760/50326157-b580dd80-04f9-11e9-8294-c6c355dbe3e5.png)

Actual Result:

![image](https://user-images.githubusercontent.com/2960760/50326170-cb8e9e00-04f9-11e9-9e19-ac2cd36620d0.png)

**Comment by gitbrent** [comment]
Fixed via #751
