### ISSUE TITLE
Setting colW when colSpan is used

### ISSUE THREAD

**Issue by katsuya-horiuchi** [gitbrent/PptxGenJS#461]
Calling `addTable` when the table's first row has `colspan` options, I cannot set `colW`.

Example:
```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var rows = [
    [{text: "Header row", options: {colspan: 2}}],
    [
        {text: "Field 1"},
        {text: "Field 2"}
    ]
];
slide.addTable(rows, {colW: [1, 2]});
pptx.save("test");
```

I'm certain this is because the library checks the length of first row when `colW` is passed. (cf: https://github.com/gitbrent/PptxGenJS/blob/master/dist/pptxgen.js#L5040 )
Is it possible to configure each column's width (in this case, `Field 1` and `Field 2`)?

**Comment by katsuya-horiuchi** [comment]
Any update on this?

I was thinking that following implementation would work:
* When `colW` is set, all rows should be checked if the number of "cells" in the given row is less than or equal to the length of `colW`.
* If the check above fails, ignore the setting while giving warning as it is now.
* In case the number of "cells" in a row is less than the length of `colW`, merge columns.

Some things I haven't figured out yet:
* How to merge columns the way end-user wants (i.e. leave 1 column as is, merge the next 2 columns)
* Whether it affects the speed as it would require to loop through the entire table.

**Comment by gitbrent** [comment]
Hi @katsuya-horiuchi 

You need to set a table width for `colW` to work.

Adding `w:3` to your code produces the following.

```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var rows = [
    [{text: "Header row", options: {colspan: 2}}],
    [
        {text: "Field 1"},
        {text: "Field 2"}
    ]
];
slide.addTable(rows, {colW: [1, 2], w:3 });
pptx.save("test");
```

Result = 1" column followed by a 2" column:
![screen shot 2019-01-21 at 18 15 11](https://user-images.githubusercontent.com/7218970/51504838-a1eebe00-1da8-11e9-928f-8702001c0cd5.png)

**Comment by katsuya-horiuchi** [comment]
Thanks @gitbrent! It worked well.

However, is there any reason you have to explicitly specify `w` option?
Looking at the solution, I just thought it'd be nice to implicitly add `w` option by calculating the sum of `colW`.

**Comment by gitbrent** [comment]
Yeah, glad it's working.

Some tables are too complex to simply add col widths, so a table size is needed to work backwards from.
![screen shot 2019-01-22 at 18 48 37](https://user-images.githubusercontent.com/7218970/51575127-6fab9200-1e76-11e9-8afe-5bddc33c8420.png)

**Comment by gitbrent** [comment]
Great point, thanks for reminding me.

![screen shot 2019-01-25 at 21 41 27](https://user-images.githubusercontent.com/7218970/51782218-51e66300-20ea-11e9-86cb-589ac0fab49d.png)

**Comment by Subbu033** [comment]
@gitbrent , When I use colspan along with table width, I see the message '**addTable: mismatch: (colW.length != data.length) Therefore, defaulting to evenly distributed col widths.**' in the console. 

I've checked using the same code above:
`var rows = [
    [{text: "Header row", options: {colspan: 2}}],
    [
        {text: "Field 1"},
        {text: "Field 2"}
    ]
];
slide.addTable(rows, {colW: [1, 2], w:3 });`

**Comment by psubrownie** [comment]
@Subbu033 this appears to broke in 3.x
