### ISSUE TITLE
autoPage and colW

### ISSUE THREAD

**Issue by rickykoh** [gitbrent/PptxGenJS#463]
Hello Team,

Not sure if this is a bug but when colW is defined and autoPage is set to the default true for table's options, new slide will not be created when table is overflowed. 

However, new slide will be created for overflowing table when colW is not defined but autoPage is set to true.

Working:
`var tabOpts1 = {
      autoPage: true
 };`

Not working:
`var tabOpts1 = {
      autoPage: true,
      colW: 2.0
 };`

**Comment by gitbrent** [comment]
[Closing due to age]
