### ISSUE TITLE
Extending Master Slide Object Shapes Using React/Webpack

### ISSUE THREAD

**Issue by cavaloni** [gitbrent/PptxGenJS#464]
Currently, it appears that `MASTER_OBJECTS` is not extensible to those objects/shapes available in `pptxgen.shapes.js`. If I am understanding your code well enough, would it seem reasonable in your design to be able to pass `gObjPptxShapes` into the instantiation of `PptxGenJS` and conditionally extend the object `MASTER_OBJECTS` to include them if they are present? (also adding appropriate calls to `addShapeDefinition`).

I am using React and so importing the script with `<script>` is not desirable so it would also help on that level. But primarily, I would like to be able to create a master slide with more shapes than what seems to be readily available. If this seems like a reasonable approach then I would be happy to submit a PR.

**Comment by cavaloni** [comment]
Should I just go ahead and submit a PR so you can see what I'm referring to @gitbrent?

**Comment by gitbrent** [comment]
Hi @cavaloni 

Sure, let me see what you're thinking of as a solution here.

**Comment by cavaloni** [comment]
Ok @gitbrent, here's what I've got. Ready to submit a PR if you're good with the idea.

Very simple change, but you can let me know if it is in keeping with your patterns enough or not, and I can change as needed.

Starts with passing in `gObjPptxShapes` when instantiating a `new PptxGenJS` instance, and checks for existence here and assigns :

```
var PptxGenJS = function(shapesExt){
	if (!gObjPptxShapes && !!shapesExt) gObjPptxShapes = shapesExt;
```

Then it extends `MASTER_OBJECTS` if it extists:

```
if (gObjPptxShapes) {
		Object.keys(gObjPptxShapes).forEach(function(shapeName) {
			// FIXME If needed, to alter name best for the api
			const masterObjectName = gObjPptxShapes[shapeName].displayName.toLowerCase();
			MASTER_OBJECTS[masterObjectName] = { name: masterObjectName, objName: shapeName };
		})
	}
```

Then the check for `MASTER_OBJECTS` looks like so (primary changes are in the beginning, checking for existence on the object, then the last `else if` statement which adds it):

```
slideDef.objects.forEach(function(object,idx){
					var key = Object.keys(object)[0];
					var masterObject = MASTER_OBJECTS[key];
					
					if (!MASTER_OBJECTS[key]) return;

					if      ( MASTER_OBJECTS[key] && key == 'chart' ) gObjPptxGenerators.addChartDefinition(CHART_TYPES[(object.chart.type||'').toUpperCase()], object.chart.data, object.chart.opts, target);
					else if ( MASTER_OBJECTS[key] && key == 'image' ) gObjPptxGenerators.addImageDefinition(object[key], target);
					else if ( MASTER_OBJECTS[key] && key == 'line'  ) gObjPptxGenerators.addShapeDefinition(gObjPptxShapes.LINE, object[key], target);
					else if ( MASTER_OBJECTS[key] && key == 'rect'  ) gObjPptxGenerators.addShapeDefinition(gObjPptxShapes.RECTANGLE, object[key], target);
					else if ( MASTER_OBJECTS[key] && key == 'text'  ) gObjPptxGenerators.addTextDefinition(object[key].text, object[key].options, target, false);
					else if ( MASTER_OBJECTS[key] && key == 'placeholder' ) {
						// TODO: 20180820: Check for existing `name`?
						object[key].options.placeholderName = object[key].options.name; delete object[key].options.name; // remap name for earier handling internally
						object[key].options.placeholderType = object[key].options.type; delete object[key].options.type; // remap name for earier handling internally
						object[key].options.placeholderIdx  = (100+idx);
						gObjPptxGenerators.addPlaceholderDefinition(object[key].text, object[key].options, target);
					}
					else if (!!gObjPptxShapes[masterObject.objName]) gObjPptxGenerators.addShapeDefinition(gObjPptxShapes[masterObject.objName], object[key], target);
```

**Comment by cavaloni** [comment]
PR #512

**Comment by gitbrent** [comment]
[Closing due to age]
