### ISSUE TITLE
Remove slides

### ISSUE THREAD

**Issue by StefanBrand** [gitbrent/PptxGenJS#467]
Is it somehow possible to remove slides? 

After initiating `PptxGenJs()` and setting slide masters in my app the user can save a presentation clicking a button. Then they might alter the sorting of the slides and click that button again. Now all slides are appended to the already existing slides.

To get a "clear state" before adding the slides again, I'd like to do something like `pptx.removeSlides()` or similar.

**Comment by StefanBrand** [comment]
This means that I redundantly have to define the Master Slides for the new instance again, right? I suppose the performance aspect is negligible. 

Hm, just for learning purposes, I might be able to expand the constructor... I haven't done this before. How would I approach this?



-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 3. Januar 2019 06:25:44 MEZ schrieb Brent Ely <notifications@github.com>:
>Hi @StefanBrand 
>
>Creating a new instance of `pptx` is the preferred clearing method.
>
>### [API
>Docs](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html#saving-multiple-presentations)

**Comment by gitbrent** [comment]
Well, you can define Master Slide objects at a high level and pass them to `defineSlideMaster()` in order to easily recreate them, but yes, point taken.

Version 3.0 will be a major rewrite that will move to interacting with slide objects, making a delete method much easier to craft.

**Comment by StefanBrand** [comment]
Ah, cool! Well, in any case, PptxGenJS made this whole private project of mine possible in the first place and it was easy to work with it. So there are already many points on the plus side. 😉


-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 4. Januar 2019 05:12:18 MEZ schrieb Brent Ely <notifications@github.com>:
>Well, you can define Master Slide objects at a high level and pass them
>to `defineSlideMaster()` in order to easily recreate them, but yes,
>point taken.
>
>Version 3.0 will be a major rewrite that will move to interacting with
>slide objects, making a delete method much easier to craft.

**Comment by gitbrent** [comment]
(Closing due to age)
