### ISSUE TITLE
How to import pptxgen.shapes.js file in .vue Single File?

### ISSUE THREAD

**Issue by abumphy** [gitbrent/PptxGenJS#469]
my code ：

```js
import PptxGenJS from "pptxgenjs";
import "pptxgenjs/dist/pptxgen.shapes.js"
……
data() {
    return {
         pptx: null
    } 
},
methods:{
   ……
    pptRender(){
        const slideContent = this.pptx.addNewSlide("MASTER_SLIDE");
         slideContent.addShape(this.pptx.shapes.PIE, { x:0.50, y:0.75, w:5, h:3, fill:'FF0000' });
    }
……
}
```

error：
>  Missing/Invalid shape parameter! Example: `addShape(pptx.shapes.LINE, {x:1, y:1, w:1, h:1});` 

I don't know how to import it correctly.
Thank you！

**Comment by abumphy** [comment]
For the time being, I comment out this if statement.

- pptxgen.js
```js
// [Node.js] <script> includes
// if ( NODEJS ) {
	var gObjPptxColors = require('../dist/pptxgen.colors.js');
	var gObjPptxShapes = require('../dist/pptxgen.shapes.js');
// }
```
Is there a better way?

**Comment by gitbrent** [comment]
Original/Tracking Issue: #137

**Comment by gitbrent** [comment]
Hi @abumphy 

I was just going to move these declarations to the bottom where we do `require()` and `module.exports = PptxGenJS;`

Basically, use `require()` where possible, so it'll load for Angular/Vue, etc. but not for web clients.

Would that work?

**Comment by gitbrent** [comment]
Issue resolved in current codebase.
