### ISSUE TITLE
Table location and pagination

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#47]
Greetings! I continue to torment the table :)
At this time I would like to draw your attention to the location of the table when moving to the next slide. The new slide table is moved to the same place where there was a parent.
![image](https://cloud.githubusercontent.com/assets/9961535/23117800/7be7f19a-f762-11e6-9223-3f2fa80f744c.png)

I do not understand how far from the bottom of the slide begins the transfer table. The screenshot shows that the space on the slide is still a lot, but part of the table has been moved to a new slide. 
It would be nice if it was possible to disable pagination option.
![image](https://cloud.githubusercontent.com/assets/9961535/23117839/a772a9a4-f762-11e6-97be-7f5f3a5ffd29.png)
I apologize for these screenshots and my bad english, but the more I can not show.

**Comment by gitbrent** [comment]
Hi @itskun ,

First, your english is excellent!  Thanks for the details you always provide.

Second, this overlaps with Issue #43 (table always uses same x,y when paging), plus i've got some things in mind to upgrade in table paging like the ability to weight the line heights (letting you adjust the space taken up as you said) and to have a flag to disable when needed.

I'll create a meta-Issue to hold all these and tag this Issue.

Thanks as always!

**Comment by gitbrent** [comment]
Hi @itskun ,

Regarding free space left under the table: check out the new `lineWeight` option for tables.  There's documentation for it and an example in the demo.

**Comment by gitbrent** [comment]
Hi @itskun ,

Thanks for opening this issue.

I've added two new features that address the problem of free space:

1. By default, new Slides use the slide margin as the starting `y` location
2. A new option (`newPageStartY`) enables you to specify the `y` value for subsequent Slides.

There's several examples of the new features in the `pptxgenjs-demo.html` file.

![screen shot 2017-02-26 at 19 28 44](https://cloud.githubusercontent.com/assets/7218970/23345865/0a3d7d42-fc5a-11e6-899a-33495c3d4a54.png)
![screen shot 2017-02-26 at 19 28 54](https://cloud.githubusercontent.com/assets/7218970/23345866/0f3a6580-fc5a-11e6-8815-3b4090ab5f65.png)
