### ISSUE TITLE
Rounding in percentage leads to small deviations

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#470]
Attached is a PowerPoint file with a fine grid (it looks a bit like a Finish flag :-) ):

Slide one was generated with coordinates as percentages
Slide two was generated by converting the percentages to inches and feeding them directly

Slide two is the correct rendering. I think there is a rounding somewhere in the percentage conversion that causes issues with fine grids. Maybe the issue can be solved with keeping the full length floating point numbers in the code?

[Grid test - inches and percentage.pptx](https://github.com/gitbrent/PptxGenJS/files/2731519/Grid.test.-.inches.and.percentage.pptx)

**Comment by ReimaFrgos** [comment]
@Slidemagic You haven't provided the values you used for testing this. Would I be right in assuming you used values of 8.7% and 0.87 inches?

The issue seems to be the use of parseInt instead of parseFloat to in getSmartParseNumber.  It's rounding the percentage to a whole number before the conversion to the relevant EMU is completed.

`		// CASE 3: Percentage (ex: '50%')
		if ( typeof inVal == 'string' && inVal.indexOf('%') > -1 ) {
			if ( inDir && inDir == 'X') return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.width  );
			if ( inDir && inDir == 'Y') return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.height );
			// Default: Assume width (x/cx)
			return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.width );
		}`

**Comment by Slidemagic** [comment]
> @Slidemagic You haven't provided the values you used for testing this. Would I be right in assuming you used values of 8.7% and 0.87 inches?
> 
> The issue seems to be the use of parseInt instead of parseFloat to in getSmartParseNumber. It's rounding the percentage to a whole number before the conversion to the relevant EMU is completed.
> 
> ```
> // CASE 3: Percentage (ex: '50%')
> if ( typeof inVal == 'string' && inVal.indexOf('%') > -1 ) {
> if ( inDir && inDir == 'X') return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.width  );
> if ( inDir && inDir == 'Y') return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.height );
> // Default: Assume width (x/cx)
> return Math.round( (parseInt(inVal,10) / 100) * gObjPptx.pptLayout.width );
> }
> ```

I don't remember the exact values. I am just carving up a page in a 10-box grid, "measuring" the gaps in the PPT gives about 0.33 inch. I assume we can just switch to parseFloat without breaking things?

**Comment by ReimaFrgos** [comment]
I have submitted a PR #475  to update this along with samples showing the before and after impact.

**Comment by Slidemagic** [comment]
> I have submitted a PR #475 to update this along with samples showing the before and after impact.
Thx!

**Comment by gitbrent** [comment]
@Slidemagic - thanks for reporting this.
@ReimaFrgos - thanks for the quick patch!

I'll get it reviewed and checked-in soon.

**Comment by gitbrent** [comment]
Pull #475 has been merged.

Thanks @ReimaFrgos and @Slidemagic !

**Comment by gitbrent** [comment]
![screen shot 2019-01-26 at 17 09 22](https://user-images.githubusercontent.com/7218970/51793868-2ec0bf80-218d-11e9-90b1-5ee927027a28.png)

![screen shot 2019-01-26 at 17 08 43](https://user-images.githubusercontent.com/7218970/51793869-31bbb000-218d-11e9-8613-75b5e79b3dab.png)

**Comment by Slidemagic** [comment]
Thx!
