### ISSUE TITLE
Set proper MIME type for PPTX presentation

### ISSUE THREAD

**Issue by StefanBrand** [gitbrent/PptxGenJS#471]
When I `save()` a presentation and manually remove the ".pptx" at the end of the file name, I get a file that doesn't automatically open with Powerpoint. This is confusing to my users because they like to rename their output presentations (and Powerpoint adds the file extension _after_ pressing the save button).

I suspect that this depends on the MIME type -- if it is not set properly, a file will have no extension unless manually appended. According to [this SO answer]( https://stackoverflow.com/a/4212908/9778755) the MIME type of PPTX presentations is

    application/vnd.openxmlformats-officedocument.presentationml.presentation

Can the library support saving with the correct MIME type? A quick try with setting `mimeType` in [`zip.generateAsync(...)`]( https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html#mimetype-option ) did not work for me.

PS.: I'm using Electron to build an app and I'm not sure about the implications. It's both a browser and Node.js in some way... All I could find out is that it executes the statement on [line 1823]( https://github.com/gitbrent/PptxGenJS/blob/f89024787f859ccd81b0a769d01a153b89a4a973/dist/pptxgen.js#L1823).

**Comment by StefanBrand** [comment]
I think what I want to accomplish is related to #217. In order to be able to use the proper Electron methods PptxGenJs would have to give me access to `fs`.

**Comment by gitbrent** [comment]
Hi @StefanBrand 

Same here.  I tried adding a MIME type to the `zip` call, but it just creates a file that PowerPoint complains abut being corrupt.

The JSZip docs says MIME-type is only for blob files, so it may be that we use nodebuffer for `fs` calls... i'm not sure.

I'd encourage you to play around with the code and see what you can find.

**Comment by gitbrent** [comment]
Hi @StefanBrand 

This is now fixed in the current branch and in `3.0`

![IMG_1705](https://user-images.githubusercontent.com/7218970/64494489-236d6080-d253-11e9-9f02-5c4a654d4901.PNG)
