### ISSUE TITLE
[Feature Request] save output as blob

### ISSUE THREAD

**Issue by crazyx13th** [gitbrent/PptxGenJS#478]
Hi there,

I wanna generate a PPTX with the client and upload it to a service.
Would be cool if I can get only the **blob**, not a automatic download.

Thanks!

Greetings
crazyx13th

**Comment by gitbrent** [comment]
Hi @crazyx13th 

Thanks for the suggestion.  The library already generates a blob (it just feeds it to a dynamic href to download), so the code already exists.

The only way i can see to get it back to users right off-hand would be the use of a callback function that i could pass the blob to.

Sound about right?

**Comment by crazyx13th** [comment]
hey gitbrent,
yeah sounds good! (my current local hack url='blob' does the same :-) )
thanks!

greetings
crazyx13th

**Comment by gitbrent** [comment]
Hi @crazyx13th 

Now that i look at the code, it appears this functionality already exists.  If you pass an output type of 'blob' (3rd argument after a callback function), the browser will receive a blob:

Example:
```
pptx.save('PptxGenJS-blob-test', function(blob){ console.log(blob) }, 'blob');
```
![screen shot 2019-02-04 at 21 35 25](https://user-images.githubusercontent.com/7218970/52251846-d09a8780-28c4-11e9-8924-2b2d5e311b6d.png)

**Comment by gitbrent** [comment]
Thanks @crazyx13th 

![screen shot 2019-02-07 at 23 15 05](https://user-images.githubusercontent.com/7218970/52460234-f7f48d00-2b2e-11e9-9e00-4abec13a29f9.png)

**Comment by crazyx13th** [comment]
Sorry, das ich mich jetzt erst melde, war kurz "auf einer anderen Baustelle" :-) . Aber diese Funktion ist aktuell nur für node vorgesehen (hatte mir ja zu dieser Zeit den code angeschaut und einen eigenen "patch" für unser Projekt eingespielt). Jedenfalls stößt er immer einen Download an... ich möchte ja nur ein Blob :-)

Danke & Gruß!

**Comment by happygreen17** [comment]
Hi, 
It is not saved as a 'blob' but as a 'string'

![캡처](https://user-images.githubusercontent.com/39076061/61458843-6b37e000-a9a6-11e9-8720-7abbf7cbf450.PNG)

Can I still save it only in Node.js?

Thanks
