### ISSUE TITLE
NPM Release Date

### ISSUE THREAD

**Issue by robertedjones** [gitbrent/PptxGenJS#483]
@gitbrent firstly thank you for a great library - it's saved us a lot time! 

Do you know when you will be making the next release to NPM as there is quite a bit of functionality now mentioned in the docs that's not available in the latest release?

Thanks

**Comment by gitbrent** [comment]
Hi @robertedjones 

I usually try to release the library at least every 3 months, so the newest version should be coming out soon.

**Comment by robertedjones** [comment]
Thanks

**Comment by jonwardsisu** [comment]
Hey there @gitbrent I really appreciate all of the awesome work that you have done on this project. I am really excited to use the new typescript definitions, and I am wondering when the next release is planned for. Thanks! 
(Also please let me know if there is anything I can do to support this project).

**Comment by gitbrent** [comment]
Hi @jonwardsisu 

Thanks for the feedback. The new typescript-based version will be out in the next few months.
