### ISSUE TITLE
Unable to generate PPT in Windows 10 IE 11

### ISSUE THREAD

**Issue by anuragsapanbharat** [gitbrent/PptxGenJS#484]
Hi

I have been using the plugin for last 3 /4 months and its been working wonderfully. The problemstarted when my office moved to Windows 10 platform. Since then I am not able to generate PPT withthis. When I go to debug mode there is no issues, but just the ppt is not generated. When I test it witholder platform in other PCs its working very fine. Please help.

My IE11 version
version: 11.1563.15063.0
Update versions: 11.0.105 (KB4480965)
Product ID: 00150-20000-00003-AA459

Code am Using
<meta content="IE=edge" http-equiv="X-UA-CompatibleMeta http-equiv="Content-Type" content="text/html: charset-UTF-8 / >
<script language="javascript type="text/javascript" src="libpptGen/jquery.js"></script>
<script language-"javascript" type="text javascript" src="lib/pptGen/jszip.js" ></script>
<script language "javascript" type "text/javascript" src="lib/pptGen/pptxgen.bundle.js"> </script>
<script language-"javascript" type="text/javascript" src="libjs/customFunction.js"> </script>

Thank you

**Comment by gitbrent** [comment]
Hi @anuragsapanbharat 

I downloaded the newest code earlier today on a Windows 10 laptop and ran every demo under `examples` with IE11 and it worked fine.  There must be something with the setup going on.

Does the demo (`examples/pptxgenjs-demo.html`) work on Win10 IE11?

![screen shot 2019-01-29 at 20 08 56](https://user-images.githubusercontent.com/7218970/51953376-c0d0fe00-2401-11e9-844a-40d237b326cd.png)

**Comment by anuragsapanbharat** [comment]
My apology to respond late. I am not very sure what was the issue. But it's again stared working. Thank you for your response. Sorry for being late again.

**Comment by gitbrent** [comment]
Glad to hear, thank you for letting me know!
