### ISSUE TITLE
table overflow vertically using addTable

### ISSUE THREAD

**Issue by rickykoh** [gitbrent/PptxGenJS#486]
Hi Team,

I have a table with 3 equal columns but the table does not auto split to the next slide when it is overflowed vertically.

Please advise..

Thank you.

**Comment by gitbrent** [comment]
Please see the demo under `example` for working code samples.

![screen shot 2019-01-25 at 22 02 24](https://user-images.githubusercontent.com/7218970/51782390-f23d8700-20ec-11e9-8eaa-9b93458b3625.png)
