### ISSUE TITLE
autoPage and rowspan

### ISSUE THREAD

**Issue by stephanielsx** [gitbrent/PptxGenJS#488]
Hello Team,

Just to clarify if this is a bug.

I've tried creating table using HTML DOM and assigning rowSpan attribute to the first column of each rows accordingly and finally add the HTML table to the slide using addSlidesForTable().

From my understanding, the method addSlidesForTable() would have split the table to multiple slides if it overflowed a slide.

However, with the assignment of rowSpan attribute, the table will not split to multiple slides when it overflowed. The addSlidesForTable() works fine after removing the line to set the rowSpan attribute.

```
td = document.createElement('td');
td.rowSpan = rowSpanCount[i];
td.appendChild(document.createTextNode("Line 1"));
tr.appendChild(td);
```

```
var objOpts = {};
objOpts.master = 'MASTER_SLIDE';
objOpts.addHeaderToEach = true;
objOpts.newPageStartY = 1.0;
pptx.addSlidesForTable("table-id", objOpts);
```

Kindly assist.

Thank you.

**Comment by gitbrent** [comment]
Hi @stephanielsx 

Rowspans shouldn't hinder paging.

Please see `example` for working code samples.

![screen shot 2019-01-25 at 22 02 24](https://user-images.githubusercontent.com/7218970/51782413-5f511c80-20ed-11e9-90bd-3c96570032fa.png)

**Comment by gitbrent** [comment]
Acknowledged.

### TRACKING ISSUE: #331

**Comment by tallajobmails** [comment]
Hi I am facing the above issue when the slide over flows to next slide the fourth column cell value is displaying in the first column and the other three cells are bold bordered: Please help 
![51783611-42612b80-2177-11e9-9856-4a4ee2bbf5a6](https://user-images.githubusercontent.com/100961957/157978327-27e9180a-3c53-4c74-852d-1683e1bb84cc.png)
