### ISSUE TITLE
Option Request: Chart DataTable formatting for percent values

### ISSUE THREAD

**Issue by phobos7000** [gitbrent/PptxGenJS#489]
Hello,

I'm trying your amazing library.

However, I didn't found how to show the datatable value in percentage.

If you could help me to understand where is my mistake I would be very grateful.

Thank you in advance.

Best regards,

Here is my code 

```javascript
var opts = {
    x: 0.17,
    y: 0.32,
    h: 2.81,
    w: 9.18,
    barDir: "col",
    barGrouping: "stacked",
    catAxisLabelColor: "AAAAAA",
    catAxisLabelFontFace: "Gotham Office",
    catAxisLabelFontSize: 8,
    catAxisOrientation: "minMax",
    showDataTable: true,
    showLegend: false,
    showTitle: false,
    showPercent: true,

    valAxisLabelFontSize: 8,
    valAxisLabelFormatCode: "0.00%",
    dataLabelFormatCode: "0.00%",
    valAxisLabelFontFace: "Gotham Office",
    axisLineColor: ["EEEEEE"],
};

var labels = labelsValues;
var chartTypes = [
    {
        type: pptx.charts.BAR,
        data: [
            {
                name: "Bottom",
                labels: labels,
                values: barvalues,
            },
        ],
        options: {
            chartColors: ["D8DDE3"],
            invertedColors: ["D8DDE3"],
            barGrouping: "standard",
            shadow: "none",
        },
    },
    {
        type: pptx.charts.LINE,
        data: [
            {
                name: "Current",
                labels: labels,
                values: linevalues,
            },
        ],
        options: {
            chartColors: ["445F7E"],
            lineSmooth: true,
            shadow: "none",
            showValue: true,
        },
    },
];
slide.addChart(chartTypes, opts);
```

![image](https://user-images.githubusercontent.com/47020499/51726432-ab597e00-2067-11e9-93bf-dc06a47a9e36.png)

**Comment by gitbrent** [comment]
At present, there are no options for formatting - the library just defaults the formatting of data table values.

If you'd like to look at existing uses of formatting (eg: `valAxisLabelFormatCode`) and submit a pull request, that would be helpful.

**Comment by arjunapp** [comment]
May I know if this is implemented?

**Comment by gitbrent** [comment]
Done via Pull #684 

<img width="495" alt="Screen Shot 2020-06-14 at 00 49 23" src="https://user-images.githubusercontent.com/7218970/84585808-0ca6fc00-add9-11ea-81ab-c858ecc4663a.png">

<img width="605" alt="Screen Shot 2020-06-14 at 00 51 03" src="https://user-images.githubusercontent.com/7218970/84585820-32cc9c00-add9-11ea-879b-1a005586b402.png">
