### ISSUE TITLE
Enhance bullet feature: offer diff types of bullets and add numbering option

### ISSUE THREAD

**Issue by gitbrent** [gitbrent/PptxGenJS#49]
Add a couple new features to `addText()` bullet option:

- [x] Diff types of bullets (not just the plain black circle one)
- [x] Add numbering as a new bullet option

Feature request from @sangramjagtap

**Comment by gitbrent** [comment]
Requested bullet features have now been added.  Both the documentation and the demos have been updated as well.

![screen shot 2017-03-04 at 10 48 23](https://cloud.githubusercontent.com/assets/7218970/23580477/4b2cab12-00c8-11e7-94fb-59828f14c0b5.png)

**Comment by sangramjagtap** [comment]
Thanks Brent.
That was very quick.
