### ISSUE TITLE
legendFontFace is not working

### ISSUE THREAD

**Issue by octy40** [gitbrent/PptxGenJS#491]
When passing in the legendFontFace it's not getting applied. Here's a sample code to replicate

`var pptx = new PptxGenJS();
            var slide = pptx.addNewSlide();

            // Chart Type: LINE
            var arrDataRegions = [
                {
                    name  : 'Region 1',
                    labels: ['May', 'June', 'July', 'August'],
                    values: [26, 53, 100, 75]
                },
                {
                    name  : 'Region 2',
                    labels: ['May', 'June', 'July', 'August'],
                    values: [43.5, 70.3, 90.1, 80.05]
                }
            ];
            var arrDataHighVals = [
                {
                    name  : 'California',
                    labels: ['Apartment', 'Townhome', 'Duplex', 'House', 'Big House'],
                    values: [2000, 2800, 3200, 4000, 5000]
                },
                {
                    name  : 'Texas',
                    labels: ['Apartment', 'Townhome', 'Duplex', 'House', 'Big House'],
                    values: [1400, 2000, 2500, 3000, 3800]
                }
            ];

            // TOP-LEFT: H/bar
            var optsChartBar1 = { x:0.5, y:0.6, w:6.0, h:3.0,
                // General, Legend, Title
                chartColors: ['3D6577','779FB1', 'A6A6A6', '69ADAB', '5E5E5E'],                
                legendPos: 't',
                legendColor: '5E5E5E',
                legendFontFace: 'Arial Black',
                legendFontSize: '20',
                showLegend: true,
                
                barDir: 'col',
                border: { pt:'3', color:'00EE00' },
                fill: 'F1F1F1',

                catAxisLabelColor   : 'CC0000',
                catAxisLabelFontFace: 'Arial Narrow',
                catAxisLabelFontSize: 14,
                catAxisOrientation  : 'maxMin'
            };
            
            slide.addChart( pptx.charts.BAR, arrDataRegions, optsChartBar1 );

            pptx.save('Demo-Bar-Chart');`

The legend comes with **Arial Body** instead of **Arial Black**. The legend gets sized properly with no issue.

I used **version 2.4.0**.

**Comment by gitbrent** [comment]
Hi @octy40 

Thanks for reporting this issue.

This has already been fixed in the upcoming 2.5.0 release.

![screen shot 2019-01-25 at 21 58 01](https://user-images.githubusercontent.com/7218970/51782350-57dd4380-20ec-11e9-9286-62bc55f2ec5f.png)

![screen shot 2019-01-25 at 21 56 57](https://user-images.githubusercontent.com/7218970/51782352-5c096100-20ec-11e9-8ba2-ed0b5698575b.png)
