### ISSUE TITLE
breakLine option set to false not working for cell level formatting

### ISSUE THREAD

**Issue by sandesh27** [gitbrent/PptxGenJS#494]
![2019-01-31 16_52_28- table-slide service ts - infinity ui - visual studio code](https://user-images.githubusercontent.com/150098/52051162-b5eca980-2578-11e9-8a61-e885b3cca530.png)
![2019-01-31 16_51_28-powerpoint config ts - infinity ui - visual studio code](https://user-images.githubusercontent.com/150098/52051163-b5eca980-2578-11e9-9b11-3ec53b111193.png)
![2019-01-31 16_49_30-scorecardproject 25 pptx - microsoft powerpoint](https://user-images.githubusercontent.com/150098/52051165-b6854000-2578-11e9-823b-6b4eb8157734.png)

Hi Gitbrent, 
I am having a table created with dynamic styles configuration.
There are total of 7 columns.
The first column is having extra row width (rowW) than others.
Some of the rows also uses  col span (colspan: 7).
I want to place the desired text in first cell only with col span as 7.
But with text prefix having no style and text suffix as bold.
The styles are getting applied but the two words using break line (breakLine: true).
How I can solve this issue?
Please let me know.
Thank you,
Sandesh

**Comment by gitbrent** [comment]
Hi @sandesh27 

Please check the table code used for the demo: `examples/pptxgenjs-demo.html`

There's lots of formatting examples.

![screen shot 2019-01-31 at 21 54 39](https://user-images.githubusercontent.com/7218970/52101818-eb0df180-25a2-11e9-837a-50f9ed2eb107.png)

![screen shot 2019-01-31 at 21 54 27](https://user-images.githubusercontent.com/7218970/52101819-eb0df180-25a2-11e9-9b05-8df15179c34a.png)
