### ISSUE TITLE
Electron Windows App - pptx.save() creating a blob rather than using fs to save locally

### ISSUE THREAD

**Issue by chrisrosa418** [gitbrent/PptxGenJS#495]
I have developed this application locally, and have it working flawlessly when running it via node.  However, when I run from within the Windows Electron Desktop App that I am building, whenever I try to save using pptx.save(), it tries to save it as a blob file from within a save file popup box.  

I have tried out a few solutions proposed within your issues.  
 - pttx.setBrowser(true | false)
 - node: { fs: "empty" }
 - Also just tried saving the pptx via fs from within the function (which failed)
 - Using the jzip functionality still gave me the save file popup box

I've seen some integration with Angular, but does anyone have a proposed solution.

**Comment by gitbrent** [comment]
What version are you using?

**Comment by chrisrosa418** [comment]
Version == "2.4.0.20181028"

I'm gonna try to pull down the most recent production code to see if that helps.  

Even with setBrowser(False), when running from within the Electron Application, pptxgen uses the blob to save the files.  Is there anyway I can force the file write to use (fs) instead of blob?

**Comment by chrisrosa418** [comment]
Just re-ran with version="2.5.0-beta.20190126"
Still experiencing same issue when setBrowser is set to True OR False

**Comment by chrisrosa418** [comment]
I fixed temporarily with the following

I replaced the else block on line 1842
```
else {
	zip.generateAsync({type:'blob'}).then(function(content){writeFileToBrowser(strExportName, content); });
}
```
with
```
else {
        const fs = require('fs');
	zip.generateAsync({type:'nodebuffer'}).then(function(content){ fs.writeFile(strExportName, content, function(){} ); });
	}
```

Essentially forcing my program to use the fs.writeFile method.  

I am then importing that package directly, rather than requiring the package through npm
```
    //Require pptxgenjs 
    // var PptxGenJS = require("pptxgenjs");
    var PptxGenJS = require('./dist/pptxgen.js');
```

**Comment by gitbrent** [comment]
Hi @chrisrosa418 

Thanks for the testing and feedback.

So, the library should be detecting Electron and treating it like Node - thereby using `fs` to save files, not pushing to the browser.

Line 55 at the very beginning of the library checks for `fs`, if it's found, then it's subsequently used to save files.

Therefore, i'm guessing `fs` isn't being included in your Electron build or something like that.

The node demo under `examples` shows how to require fs before initializing PptxGenJS, i'm not familiar with building Electron off-hand.

**Comment by gitbrent** [comment]
This should no longer be an issue as of v3.0
