### ISSUE TITLE
Performance issue of PPT download

### ISSUE THREAD

**Issue by Prasanth-ECE** [gitbrent/PptxGenJS#496]
Hi Team,
Am facing a issue with the performance of PPT download. I have integrated into PptxGenJS Angular v5.

When downloading PPT of 3 pages, the performance of the export decreases with every execution.

first time in under 2 sec
second time - 4 sec
third time - 10 sec
fourth time - more than 16 sec.

with the same data. 

I could see where it lacks
'zip.generateAsync({type:'blob'}).then(function(content){ writeFileToBrowser(strExportName, content); });'

is it possible to generate PPT in synchronous ??

**Comment by gitbrent** [comment]
Hi @Prasanth-ECE 

Are you adding to or clearing an existing Presentation?

e.g.: `var pptx = new PptxGenJS()`

I'm guessing the Presentation is growing larger after each save...

**Comment by Prasanth-ECE** [comment]
creating a new instance for each download like below, 

    downloadPPT(SVGObject:any) {
          let pptx = new PptxGenJS();
          pptx.setBrowser(true)
          pptx.setLayout('LAYOUT_WIDE');
          pptx.setTitle('Prediction Presentation');
          pptx.defineSlideMaster({
                 title: 'test',
                 objects: [
                       { 'text':  { text:'Sample', options:{ x:0.18, y:'82%', w:'30%', h:0.75, fontSize:19, fontFace:'Calibri', bold: true } } },
                       { 'text':  { text:'Innovation', options:{ x:0.18, y:'86%', w:'30%', h:0.75, fontSize:16, fontFace:'Calibri', italic: true, color:'676666' } } },
                    ]
                 })
          for(let i=0;i<SVGObject.length;i++) {
                slide = 'slide'+i+1;
                slide = pptx.addNewSlide('test');
                slide.addImage({ data:SVGObject[i].svgContent.toString(), x:'2%', y:'10%', w:'96%', h:(SVGObject[i].svgHeight/100) , type:'cover' })
                    }
          let t2 = performance.now();
          let t3;
          pptx.save('Race-'+getTimestamp(), ()=>{ 
                t3 = performance.now();
                console.log("PPT save took " + (t3 - t2) + " milliseconds.")
              })
          }


Is it possible to clear the presentation after save ?

**Comment by gitbrent** [comment]
The `pptx` instance is growing over time.

Yes, there is a way to clear it:
### [Saving Documentation](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html#saving-multiple-presentations)
