### ISSUE TITLE
Can slide.addImage() use the default size of the image?

### ISSUE THREAD

**Issue by PavanBahuguni** [gitbrent/PptxGenJS#498]
Can slide.addImage() use the default size of the image?
Currently by default it takes w and h as 1 inches, is there an option to not give w and h and work with the default width and height of the image.

**Comment by gitbrent** [comment]
The library would have to create a Canvas, load, render the image, then measure it.

I'd rather not do that.

For consistency, please provide the image size, the same way sizes are provided for every other object type.

Thanks.

**Comment by PavanBahuguni** [comment]
@gitbrent  Thank you for your inputs. One question though.

The input is in inches and it would be very hard to know the w and h of the image in inches for a dynamic image. Is there a way to work around this?

**Comment by gitbrent** [comment]
Images are 96-300 px per inch.  Using 100 works most of the time.

However, unless you're trying to reproduce an image to scale, you normally do it the other way around: find the highest quality image you can, then fit it into the available space on that slide. 

That way, it was looks good (aspect ration aside).  E.g.: Take a 1920x1080 image and use it as a background - dont use a smaller size that equals the available slide inches.
