### ISSUE TITLE
Not able to set bubble chart scale size and custom tooltip per bubble

### ISSUE THREAD

**Issue by sandesh27** [gitbrent/PptxGenJS#499]
![bubbles_original_no_custom_tooltip](https://user-images.githubusercontent.com/150098/52470859-4ea4aa00-2bb5-11e9-9c20-e0243408f3dc.png)
![bubbles_original](https://user-images.githubusercontent.com/150098/52470869-52d0c780-2bb5-11e9-95a5-26f12e050478.png)
![bubble_scale](https://user-images.githubusercontent.com/150098/52470873-56fce500-2bb5-11e9-85c7-2bbe6449f5ac.png)
![color_vary_bubble](https://user-images.githubusercontent.com/150098/52470882-5a906c00-2bb5-11e9-99da-6ab9be092473.png)
![bubbles](https://user-images.githubusercontent.com/150098/52470889-5e23f300-2bb5-11e9-9dd8-7bd722575461.png)

Hi Gitbrent,

I am not able to set bubble size scale option and custom tooltip per bubble.
Please refer the attached snaps for the reference.
Also, the various colors are not getting applied to bubbles due to common x-axis values for all the respective y-axis values, this is leading same series, so the color for all bubbles are same.
I tried with XY scatter chart also,  but that was not working either.
We can't have x-axis and y-axis values clubbed together for a single bubble , so we can't have different tooltip for different bubbles as well.

Can you just help me to solve these issues?
Thanks,
Sandesh

**Comment by gitbrent** [comment]
Hi @sandesh27 

Please see the `examples/pptxgenjs-demo.js` file for lots of Bubble Chart code.

```
var arrDataBubble2 = [
    { name:'X-Axis',   values:[1, 2, 3, 4, 5, 6] },
    { name:'Airplane', values:[33, 20, 51, 65, 71, 75], sizes:[10,10,12,12,15,20] },
    { name:'Train',    values:[99, 88, 77, 89, 99, 99], sizes:[20,20,22,22,25,30] },
    { name:'Bus',      values:[21, 22, 25, 49, 59, 69], sizes:[11,11,13,13,16,21] }
];

var optsChartBubble2 = { x:7.0, y:0.6, w:'45%', h:3,
    fill: 'f1f1f1',
    showLegend: true,
    legendPos : 'b',
    lineSize  : 8,
    lineSmooth: true,
    lineDataSymbolSize: 12,
    lineDataSymbolLineColor: 'FFFFFF',
    chartColors: [ COLOR_RED, COLOR_AMB, COLOR_GRN, COLOR_UNK ],
    chartColorsOpacity: 25
};
slide.addChart( pptx.charts.BUBBLE, arrDataBubble2, optsChartBubble2 );
```

<img width="879" alt="Screen Shot 2019-05-07 at 23 16 36" src="https://user-images.githubusercontent.com/7218970/57349041-3265ca00-711e-11e9-99a9-915b0fcf2e40.png">
