### ISSUE TITLE
Label positioning issue in pie chart.

### ISSUE THREAD

**Issue by skbelalmd** [gitbrent/PptxGenJS#501]
Hello,
Thanks for this awesome library. 

I am trying to create pie chart, but issue is that data labels are little misplaced. Please have a look at the 1% on the top. 

![image](https://user-images.githubusercontent.com/15244653/52775674-3970c500-3066-11e9-9adc-0246bd2c7d96.png)

Below is my configs.

{
  x: 0.25, y: 1, w: 9.5, h: 4.0,
  showLegend: true, legendPos: 'r', legendFontSize: 15, legendFontFace: 'Calibri',
  showPercent: true,
  dataLabelFontBold: true, dataLabelColor: '000000',
  chartColors: ['dc0ee0', '00B050', 'dd3513', '81e00e', 'e0c10f', '0ee0a4', '2de00e', '0e8fe0', '9a0ee0', '7030A0', '000000', '42f4a7', 'e00e62']
};

**Comment by skbelalmd** [comment]
Also I would be very much thankful if you can suggest how to apply shape effects like shadow/glow/bevel as shown in picture below. 

Is there any option to reduce the space between the chart and the legend.


![image](https://user-images.githubusercontent.com/15244653/52776096-ffec8980-3066-11e9-97e9-aed30024c80b.png)

**Comment by gitbrent** [comment]
PowerPoint takes only a few arguments for label position and does what it wants to as far as the placement goes.  The library is not telling each and every one of these labels to be in or out, it outputs XML saying 'INNER', 'OUTER', etc. as a chart-wide setting and that's it.

There is currently an Issue open to modify the layout of piechart labels and this may lead to a solution for this issue. 

Glow/Bevel are not supported as of yet, `shadow` ex:

```
shadow: {
    offset: 20,
    blur: 20,
    type: 'inner'
}
```

### [Chart API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#chart-options)

**Comment by skbelalmd** [comment]
Hello,
Thanks for your quick response. I was able to fix the positioning issue with the {dataLabelPosition:'outEnd'}  setting for pie chart.
