### ISSUE TITLE
unable to download PPT in Firefox but it working on Chrome.

### ISSUE THREAD

**Issue by AjayRawat232** [gitbrent/PptxGenJS#502]
Hi,

I am unable to download the PPT in Firefox but the same PPT is downloading in Chrome.
I have checked Issue #81 which is not worked for me. Can you give me any other reliable solution for it.

Thanks in Advance

**Comment by gitbrent** [comment]
Hi @AjayRawat232 

I downloaded the latest version, opened the demo page in the latest Firefox and chose the simple demo which opened without issue in PowerPoint desktop.

Without any other information, there's no way to know what the issues you're facing is exactly.

**Comment by AjayRawat232** [comment]
Hi @gitbrent ,

Thanks for your quick reply.
So i will explain you from the beginning that i had faced and also resolved.

I want to download PPT on click of button on same html page (Appending PPT in <div></div>). The PPT was created and downloaded for first click of button but if i click it for second time than PPT was not created and even not even downloaded. While debugging the code all looks good but creation and downloading process is not happened. 
So i have solved that issue by setting id randomly change so each time new id is generating and PPT is created without any issue.

The above mentioned task is working in Chrome.But while testing it in Firefox PPT does not Created.

Kindly find the detailed info of issue. which was facing in Firefox browser.
