### ISSUE TITLE
X Axis Label Rotation in Bar Chart

### ISSUE THREAD

**Issue by skbelalmd** [gitbrent/PptxGenJS#503]
Is there any way to disable the axis label rotation. 

There is one option "catAxisLabelRotate". Though it is not present is the documentation but looking at this commit https://github.com/gitbrent/PptxGenJS/issues/378#issuecomment-408535723 and the code in pptxgen.js it looks like that the above option is being used while generating ppt.

Specifying catAxisLabelRotate: 0 also doesn't work. 

My requirement is, I want to make X axis label either completely horizontal (0 deg) or completely vertical (90 deg) depending on the number of the series.

Thanks.

**Comment by skbelalmd** [comment]
Hello,
Can you please suggest, where can I make changes in pptgen core files to disable X axis label rotation.

**Comment by gitbrent** [comment]
Hi @skbelalmd 

I've added `catAxisLabelRotate` to the [API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html)

What is the problem you're trying to solve?  Be default the library sets no value for `catAxisLabelRotate` so PowerPoint renders it however it sees fit.  If you need to rotate it for some reason, the option works as designed:

```
var optsChartLine1 = {
    x:0.5, y:0.6, w:'45%', h:3,
    catAxisLabelRotate: 45,
    catAxisOrientation:'maxMin', valAxisOrientation:'maxMin'
};
slide.addChart( pptx.charts.AREA, arrDataTimeline2ser, optsChartLine1 );
```

![screen shot 2019-03-06 at 20 20 47](https://user-images.githubusercontent.com/7218970/53927849-b41d7680-404d-11e9-9d6d-53753b07de62.png)

**Comment by skbelalmd** [comment]
Hi,
Here is the snapshot of a chart getting generated.

![Picture1](https://user-images.githubusercontent.com/15244653/54194387-2aa0f500-44e2-11e9-88c2-c1d1fe89c5c1.png)


I want to disable the rotation of x-axis labels. Is that possible?
If "No", is there any way so that the axis labels are either rotated 0 degree or rotated 90 degree bot not 45.

**Comment by gitbrent** [comment]
What's happening here is that PowerPoint is rotating the labels on its own because they're very lengthy - it's the default behavior.

You'll need to over-ride that behavior to get the result you're looking for.

Have you tried setting the `catAxisLabelRotate`value to 0?

**Comment by skbelalmd** [comment]
> You'll need to over-ride that behavior to get the result you're looking for.
   Please suggest where should I make changes. 

> Have you tried setting the `catAxisLabelRotate`value to 0?
Yes. 
That's what I have specified in issue (https://github.com/gitbrent/PptxGenJS/issues/503#issue-412284593).

**Comment by gitbrent** [comment]
Hi @skbelalmd 

Sorry, i'm out of ideas...

**Comment by skbelalmd** [comment]
OK, No Problem.
Thanks for your support and for this awesome library
