### ISSUE TITLE
Bullet Gap Differs from Manually Adding

### ISSUE THREAD

**Issue by Cyan005** [gitbrent/PptxGenJS#504]
I was browsing around and reviewing all of the documentation I could, but couldn't find any information regarding the following:

When adding a bullet in a table cell, the space between the bullet and text is much larger than the default PowerPoint.  

Examples:

**Normal Text**
![image](https://user-images.githubusercontent.com/28266974/53123295-b6001980-3526-11e9-94b5-867959ab57bf.png)

**Normal Bullet**
![image](https://user-images.githubusercontent.com/28266974/53123274-aaacee00-3526-11e9-819e-dbf7bbd6f8c9.png)

**PptxGenJS Bullet**
![image](https://user-images.githubusercontent.com/28266974/53123256-9e289580-3526-11e9-950e-436ac37ebd3b.png)

I can't find any additional information on if there is something coded that can reduce that gap.  Any help would be appreciated.

Thank you!

**Comment by adrienco88** [comment]
You can also use the Setter function from #214 so you can control the spacing from your script

**Comment by gitbrent** [comment]
Thanks for the issue @Cyan005 

Bullet left margin indent can now be controlled with a new option `marginPt`

```javascript
slide.addText("Bullets with marginPt:", { x:7.0, y:3.65, w:'40%', h:0.3, margin:0, color:pptx.colors.ACCENT1 });
slide.addText(
    [
        { text: 'bullet marginPt:10', options: { bullet: { marginPt: 10 } } },
        { text: 'bullet marginPt:30', options: { bullet: { marginPt: 30 } } }
    ],
    { x:7.0, y:3.95, w:5.75, h:0.5, margin:0.1, fontFace:'Arial', fontSize:12 }
);
```

<img width="287" alt="Screen Shot 2020-05-10 at 16 42 35" src="https://user-images.githubusercontent.com/7218970/81511214-4e75eb80-92dd-11ea-8f80-91f8ed4ff3a5.png">
