### ISSUE TITLE
Is the examples directory hosted anywhere?

### ISSUE THREAD

**Issue by multiplegeorges** [gitbrent/PptxGenJS#505]
I have not been able to find a hosted version of the examples directory. 
It's a really great resource for showing the capabilities of the library.

I've had to put up my own S3 static site to show clients.

The examples are referenced quite a bit in the docs, but there's no hosted version to link to.

**Comment by gitbrent** [comment]
Hi @multiplegeorges 

Great suggestion, thanks.

I believe i can just host it on the GitHub.io site that serves the API Docs.

**Comment by gitbrent** [comment]
The demo is now hosted online!

### [PptxGenJS Demo](https://gitbrent.github.io/PptxGenJS/demo/)
