### ISSUE TITLE
Chart is display only after clicking on edit data in PPT 

### ISSUE THREAD

**Issue by 9899962543** [gitbrent/PptxGenJS#506]
I am creating a chart in PPT but in some of cases chart is not drawing in PPT once I edit data the data in PPT(by Right Click on Chart>Edit data) then chart is getting display.
Please sugget me what could be the issue.
Thanks in advance.

**Comment by gitbrent** [comment]
Hi @9899962543 

I'm not seeing any behavior like that in the current PowerPoint and Excel.

The chart redraws as i change data, then stays on screen after i save and close Excel.

![screen shot 2019-03-06 at 20 31 49](https://user-images.githubusercontent.com/7218970/53928303-3b1f1e80-404f-11e9-8054-d416d2f103a0.png)

![screen shot 2019-03-06 at 20 32 06](https://user-images.githubusercontent.com/7218970/53928309-3f4b3c00-404f-11e9-98b8-4d478bcc462b.png)

![screen shot 2019-03-06 at 20 32 28](https://user-images.githubusercontent.com/7218970/53928311-43775980-404f-11e9-8284-6de5880263c2.png)

**Comment by subangbang19950406** [comment]
![image](https://github.com/user-attachments/assets/a3e9c5b6-d772-4a81-8e63-9d079adb247a)

Add a new dimension to the table, such as adding the dimension "Region3 added" in the figure, but the bar chart does not display the new dimension
