### ISSUE TITLE
barGrouping option not working for clustered

### ISSUE THREAD

**Issue by vikasnale** [gitbrent/PptxGenJS#507]
I am trying to add multiple column series on 2 values axis. Here i want two columns to be sie by side instade barGrouping  option generating them as stacked.

Here is fiddle of my scenario.. 
[https://jsfiddle.net/vikasnale/wngo074a/6/](https://jsfiddle.net/vikasnale/wngo074a/6/)

Please guide what i am missing..

**Comment by gitbrent** [comment]
Are you able to create such a chart in desktop PowerPoint and do you have a screencap?

**Comment by vikasnale** [comment]
Ahh.. i missed this

Thanks @gitbrent  for pointing me to this. event i can not generate this MS Office.  

Thanks again for update.
