### ISSUE TITLE
Convert Html to Pdf with scripts

### ISSUE THREAD

**Issue by AjayRawat232** [gitbrent/PptxGenJS#508]
Hi,

I want to convert my Html page to pdf format. Html page contains javascript to hide and show the link.
Html page with link is working properly but while converting Html to Pdf that link is visible even if the hidden (style = "display:none") is applied on Linkbutton.

kindly share the idea. 
soon reply helps me lot.

Thanks.

**Comment by gitbrent** [comment]
If you actually mean PDF and not PPT, check out [jsPDF](https://github.com/MrRio/jsPDF).

Otherwise, check out the demo under `examples` for working HTML-to-PPT code.
