### ISSUE TITLE
Add ability to create charts

### ISSUE THREAD

**Issue by alagarrk** [gitbrent/PptxGenJS#51]
Hi,

I am trying to export the charts to ppt using PptxGenJS. Facing some issues and can you please give idea/suggestion using this plugin.

Thanks in advance

**Comment by gitbrent** [comment]
Hi @alagarrk ,

Chart support is not in the library yet, so I'll see what it takes to get chart support added. 

Thanks for the request.

**Comment by alagarrk** [comment]
Hi @gitbrent,

Ok. Thank you :+1:

**Comment by gitbrent** [comment]
Branch created for Chart work:
[add-chart-functionality](https://github.com/gitbrent/PptxGenJS/tree/add-chart-functionality)

**Comment by alagarrk** [comment]
Any example for add chart? No idea how to pass parameters/options for chart?

**Comment by gitbrent** [comment]
Oh, no Charts are nowhere near done.  This is just a branch to complete that effort.

**Comment by gitbrent** [comment]
Hi @alagarrk,

Charts are now available!  Please give the demo page a try and tell me everything works okay.
