### ISSUE TITLE
Placeholder Shapes

### ISSUE THREAD

**Issue by rnoelle** [gitbrent/PptxGenJS#513]
In PowerPoint, there is an option to change the shape of the placeholders. I know there is "rounding" for inserting an image cropped into a circle, but Is it currently possible with PptxGenJS to create a circular placeholder?

**Comment by rnoelle** [comment]
I'm not sure if it's in the docs and I missed it, but I found that

``{ "placeholder" : { options: { name: 'presenterPhoto1', type: 'image', h: .57, w: .57, x: .92, y: 4.28, shape: pptx.shapes.OVAL }, text: ' ' }},``

**Comment by gitbrent** [comment]
Thanks for posting a follow-up.  Yes any of the thousands of available shapes should work with `shape`
