### ISSUE TITLE
SVG images _were_ working until v2.4.0

### ISSUE THREAD

**Issue by michaelcbrook** [gitbrent/PptxGenJS#515]
Preface: I've read the other issues describing that SVG's are not supported in Node but they are in the browser, such as [here](https://github.com/gitbrent/PptxGenJS/issues/401#issuecomment-452550030).

However, it _did_ work as of version 2.3.0-beta. It seems since then, the update adding SVG support for browsers explicitly prohibited it from working in Node now, regardless if it was meant to. Is it possible to relax this so we can have the potential of using SVG's again instead of being explicitly denied with the error `SVG is not supported in Node`?

This is a fantastic package and we get a lot of use out of it, but this is causing us a huge headache right now and we're stuck having to use an old version just to maintain SVG support...

Thank you.

**Comment by RicardoNiepel** [comment]
With #528 the SVG support in general should be fixed.

For node support my suggestion will be to use
- [svg-to-png](https://github.com/filamentgroup/svg-to-png) if PhantomJS as headless browser is ok
- [node-svg2img](https://github.com/fuzhenn/node-svg2img) if no headless browser should be used, and Cairo is ok

**Comment by gitbrent** [comment]
Hi @michaelcbrook 

How was it working before in Node? Were you embedding the SVG as base64 or...?

**Comment by gitbrent** [comment]
Hi @RicardoNiepel 

Thanks for the patch.

As for Node support, I still believe that including a ton of libraries (JSDOM alone has 26 dependencies)  just to enable SVG on Node is massive overkill.

**Comment by RicardoNiepel** [comment]
Maybe we can enable it just as an extension?

There is only one extensibility point needed (where the node not supported error happens).

And maybe sometimes in the future it can be done without this large set of dependencies...

**Comment by ronnyroeller** [comment]
+1

**Comment by gitbrent** [comment]
### FIXED! 
Node can again generate SVG images.

Thanks to Pull #528, @michaelcbrook, @RicardoNiepel 

```bash
=> node demo.js Image -local

-------------
STARTING DEMO
-------------

---==~==[ LOCAL MODE ]==~==---
* pptxgenjs ver: 3.0.0-beta.4
* save location: /Users/brentely/GitHub/PptxGenJS/demos/node

--------------
DEMO COMPLETE!
--------------

Demo file created:
 * PptxGenJS_Demo_Node_Image_201909232347
```

<img width="1605" alt="Screen Shot 2019-09-23 at 23 50 30" src="https://user-images.githubusercontent.com/7218970/65481967-12307080-de5d-11e9-9300-f9860382f3e7.png">

**Comment by Evgenus** [comment]
<img width="617" alt="зображення" src="https://user-images.githubusercontent.com/379412/121066911-19371800-c7d3-11eb-8ba4-aff1fb11eb36.png">
<img width="1102" alt="зображення" src="https://user-images.githubusercontent.com/379412/121067001-34a22300-c7d3-11eb-89fe-db858f66ab45.png">

Generated from browser works fine. 

@gitbrent Am I doing something wrong?

**Comment by Evgenus** [comment]
I've tried also versions 3.0.0 and 3.3.0. Got the same result. Does SVG work in node? I'm a bit confused because I see lots of issues about it closed and also some remarks in comments and in the changelog.

I'm especially interested in SVG from base64 ability.

Will appreciate any reply.

**Comment by gitbrent** [comment]
Issue #963 opened to address the node SVG issue
