### ISSUE TITLE
when colspan in table, lines calculated based on distributed cols

### ISSUE THREAD

**Issue by YakQin** [gitbrent/PptxGenJS#516]
Hello,
I am a fan of 'SpRestLib' & this great 'PptxGenJS' lib too :)

it seems the lines in the table cell with colspan is calculated still based on the distributed width which is not correct. for example, one row has 2 cols with cell 2 for 2 cols (cell 1 for 1 col), the lines in cell 2 should be calculated with colWidth*2 

per current design the number of lines in cells with colspan is much greater than the actual lines as the 'inWidth' in  parseTextToLines(cell, inWidth) is much smaller. this will result in the table rows break earlier as expected 

	// 3: Parse cell contents into lines (**MAGIC HAPPENSS HERE**)
				var lines = parseTextToLines(cell, (opts.colW[iCell] / ONEPT));
				arrCellsLines.push(lines);
				if (opts.debug) console.log('Cell:' + iCell + ' - lines:' + lines.length);

**Comment by YakQin** [comment]
I add 3 lines of code to handle the cell with colspan
`	var _colWidth = opts.colW[iCell]
				if (cell.opts.colspan) {
					_colWidth = _colWidth * cell.opts.colspan
				}

				// 3: Parse cell contents into lines (**MAGIC HAPPENSS HERE**)
				var lines = parseTextToLines(cell, (_colWidth / ONEPT));`

![Capture](https://user-images.githubusercontent.com/17231180/54485138-88508b00-48ae-11e9-9d89-b93aec46ccf7.PNG)

**Comment by gitbrent** [comment]
This is fixed as of v3.0.0
