### ISSUE TITLE
Return the height of the current table

### ISSUE THREAD

**Issue by YakQin** [gitbrent/PptxGenJS#517]
Hello,
Can you return the height of the table when a table is created using addTable function? This will be very helpful if we have for example 2 tables in one slide and with the height of the first table we can automatically set the "y" for the second table. Currently it seems there is no such API/Document and we need to work with source code to get such info.

Thanks!

**Comment by gitbrent** [comment]
Hi @YakQin 

Even though the auto-paging code does some calculations along these lines, implementing this would still be costly and tricky and i'm not sure this passes the 'used by most people' threshold, so i'm going to pass on it for now.

Always appreciate for your feedback and contributions.

**Comment by jsvishal** [comment]
This feature is very useful if we use multiple Tables in a single slide.
Do we have any workaround for this?

**Comment by gitbrent** [comment]
@vrimar - not really. It's a complicated calculation/lots of code for <10% users, so it's not slated to be implemented.
