### ISSUE TITLE
No able to set dataLabelPosition for Doughnut Chart using pptxgen library. Please help me in this

### ISSUE THREAD

**Issue by gvijay94** [gitbrent/PptxGenJS#518]
Hi Team,
          I'm triying to put Doughnut Chart using pptxGen library . But i'm not able to set the datalabels position outwards the chart series. but i'm able to put the position the datalabels outside in pie  chart. can anybody please help me in this issue.

**Comment by gitbrent** [comment]
[Closing due to age]
