### ISSUE TITLE
load a Template

### ISSUE THREAD

**Issue by proadiga** [gitbrent/PptxGenJS#52]
Hello ,
is it possible to load a pre-prepared Template and used ? for example :  a Master Template with logo and colors .

**Comment by gitbrent** [comment]
Hi @proadiga ,

Thanks for the question.

There is currently no functionality to import existing Slide Templates.  Templates/Master Slides are supported, but you'll need to define them (adding shapes, image, etc.)

See the documentation [here](https://github.com/gitbrent/PptxGenJS#master-slides-and-corporate-branding) and check out the demo code (`examples/pptxgenjs-demo.html`) to see them in action.
