### ISSUE TITLE
addText with hyperlink and addImage on different slide brakes image

### ISSUE THREAD

**Issue by ronnyroeller** [gitbrent/PptxGenJS#520]
I create a PPT consisting of a slide with an image and **another** slide with a hyperlink and an image. In this case, the image on the second slide is broken.

I can reproduce the issue with the latest 2.5.0 release.

This issue is likely related to https://github.com/gitbrent/PptxGenJS/issues/465 (which covers hyperlink and image on the **same slide**). I verified that the test case for https://github.com/gitbrent/PptxGenJS/issues/465 works with my 2.5.0 release, i.e. this issue is a different problem.

## Reproduce

This code reproduces the issue:

```javascript
var PptxGenJS = require("pptxgenjs");

var IMAGE = 'image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7';

var pptx = new PptxGenJS();

var slide1 = pptx.addNewSlide();
slide1.addImage({ data: IMAGE });

var slide2 = pptx.addNewSlide();
slide2.addText([
    {
        text: 'Link',
        options: {
            hyperlink: { url: 'https://www.github.com' }
        }
    }
]);
// This image will be broken
slide2.addImage({ data: IMAGE, y:1 });

pptx.save('reproduce-issue-465');
```

The code generates the following output:
![image](https://user-images.githubusercontent.com/9339055/54747006-f60df700-4bcd-11e9-8ffb-1dc8349000db.png)
![image](https://user-images.githubusercontent.com/9339055/54746991-e7274480-4bcd-11e9-8249-cbc8cff2078a.png)

**Comment by ReimaFrgos** [comment]
@gitbrent this bug no longer appears present in the latest build. Here's the v3 updated code I used to test on the 3.2.1 JS Fiddle.

```
let pptx = new PptxGenJS();
let IMAGE = 'image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7';

let slide1 = pptx.addSlide();
slide1.addImage({ data: IMAGE });

let slide2 = pptx.addSlide();
slide2.addText([
    {
        text: 'Link',
        options: {
            hyperlink: { url: 'https://www.github.com' }
        }
    }
]);
// This image will be broken
slide2.addImage({ data: IMAGE, y:1 });
pptx.writeFile('reproduce-issue-465');
```

**Comment by gitbrent** [comment]
Thanks @ReimaFrgos !
