### ISSUE TITLE
Is there a way to change the default font size?

### ISSUE THREAD

**Issue by paolochiodi** [gitbrent/PptxGenJS#521]
Any text that is added to a slide without a specific `fontSize` option has a font size of 12. Can this be changed?

**Comment by gitbrent** [comment]
Hi @paolochiodi 

There is not currently an method that allows setting the global options such as `fontSize`, `color`, etc.

A new API will be added in 3.0 that will expose all the default options and allow changes.

**Comment by lukevella** [comment]
@gitbrent was support for this ever added? Wondering if there's anyway to set a default value for `fontFace`.
