### ISSUE TITLE
SVG added with data on Slide Master causes file corruption

### ISSUE THREAD

**Issue by rnoelle** [gitbrent/PptxGenJS#522]
Adding an image to a slide with SVG in base64 works great, but I can't add an image this way to a slide master without receiving an error when I open the file -
**PowerPoint found a problem with content in Executive Deck.pptx.
PowerPoint can attempt to repair the presentation.**

`pptx.defineSlideMaster({
       title: 'MASTER_SLIDE',
       objects: [ { "image" : {x: .83, y: 1.6, w: 5.57, h: 1, data: svgBase64}}],
})`

The file does open, and I don't see anything actually removed, but with multiple masters it's causing the PowerPoint to save multiple times for every pptx.save()

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by Sher-V** [comment]
Did you solve this?
