### ISSUE TITLE
rowSpan not working when autoPage is set to false

### ISSUE THREAD

**Issue by katsuya-horiuchi** [gitbrent/PptxGenJS#523]
When `{autoPage: false}` is configured in `addTable` function, setting `rowSpan` messes up the table, regardless of whether table overflows the slide or not. Version is `2.5.0.20190208`.

You can check it by modifying `pptxgenjs-demo.js`, [l.352](https://github.com/gitbrent/PptxGenJS/blob/master/examples/pptxgenjs-demo.js#L352):
```
var tabOpts2 = {autoPage: false, x: 0.5, y: 3.3, ...}
```
What you would see is this:
![screenshot](https://user-images.githubusercontent.com/25268267/54874124-631cc900-4e28-11e9-8aff-96d9bf1da843.png)

I wasn't sure if this is related to #331. Could you clarify if this is a new bug or an existing one?

**Comment by katsuya-horiuchi** [comment]
Hi @gitbrent, any update on this?

**Comment by gitbrent** [comment]
[Closing due to age]
