### ISSUE TITLE
Not able to show legend properties in pie chart #PptGenJS

### ISSUE THREAD

**Issue by harishkatta** [gitbrent/PptxGenJS#524]
Hi All,
I am trying generate pie chart,but facing some issues, here is my fiddle link, I am unable to show legends  'DE', 'GB', 'MX', 'JP', 'IN', 'US' on right of chart
https://jsfiddle.net/harishkattas/d1yrgq0x/6/

this is i want to show legends right of chart
![image](https://user-images.githubusercontent.com/20572170/54912712-34c9e700-4f17-11e9-8136-110eb1b2d006.png)

Can you help me

**Comment by joeberth** [comment]
i am having the same problem, i really need to get this fixed, can you help us?! I started to code the ppt export of my project using PptGenJS, i dont want to change de library.
Thank You!

**Comment by joeberth** [comment]
@gitbrent

**Comment by joeberth** [comment]
@harishkatta How did you go about your project? Could you fix it locally or switch library?

**Comment by joeberth** [comment]
Look, the same code in fiddle generate different legend labels. In mobile or windows the download is the correct one. (see below):
![image](https://user-images.githubusercontent.com/33490097/60493261-dc775380-9c82-11e9-9c79-28b3ab3e5816.png)


But when i download using unix SO, i got this picture below:

![image](https://user-images.githubusercontent.com/33490097/60493330-fa44b880-9c82-11e9-8920-5f09e25eec41.png)

how can i fix it?

**Comment by gitbrent** [comment]
Use the `legendPos` option to specify where the legend should go.

### [Chart Docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#general-legend-title)

The [examples demo](https://gitbrent.github.io/PptxGenJS/demo/#tab3) has them top, bottom and left.

<img width="1022" alt="Screen Shot 2019-07-25 at 17 48 04" src="https://user-images.githubusercontent.com/7218970/61913992-8a81c080-af04-11e9-8334-8db9a5056974.png">

**Comment by davodesign84** [comment]
@gitbrent I'm experiencing the same issue. @joeberth  did you find a solution?

On a linux device, if passing the following:
```
const data = [{
    title: 'TEST',
    labels: ['AAPL', 'TSLA'],
    values: [1000, 800]
}];

slide.addChart('pie', data, {
    type: 'pie',
    showLegend: true,
    legendPos: 't'
});
```

The pie chart shows only one Legend element with the string 'TEST', instead of showing two 'AAPL', 'TSLA'

Is anybody looking at this? If you can provide some pointers I'm happy to send a PR as well.

**Comment by davodesign84** [comment]
Hi @gitbrent do you need any help on this? With some guidance I might be able to submit a PR

**Comment by vivekkhurana** [comment]
I am facing the same issue

**Comment by vivekkhurana** [comment]
> @gitbrent I'm experiencing the same issue. @joeberth did you find a solution?
> 
> On a linux device, if passing the following:
> 
> ```
> const data = [{
>     name: 'TEST',
>     labels: ['AAPL', 'TSLA'],
>     values: [1000, 800]
> }];
> 
> slide.addChart('pie', data, {
>     type: 'pie',
>     showLegend: true,
>     legendPos: 't'
> });
> ```
> 
> The pie chart shows only one Legend element with the string 'TEST', instead of showing two 'AAPL', 'TSLA'
> 
> Is anybody looking at this? If you can provide some pointers I'm happy to send a PR as well.

I am facing the same issue

**Comment by gitbrent** [comment]
This issue appears to stem from the application that is used to view the file.

Microsoft PowerPoint will show each different bar color in the legend as different items, whereas other applications will show the data set name as you'd expect.
