### ISSUE TITLE
lineDash Option is not in documentation

### ISSUE THREAD

**Issue by Jank1310** [gitbrent/PptxGenJS#526]
The **lineDash** option should be in the documentation.

Possible options: `['dash','dashDot','lgDash','lgDashDot','lgDashDotDot','solid','sysDash','sysDot']`
Default value: `solid`

**Comment by gitbrent** [comment]
Hi @Jank1310 

Thanks for letting me know, but i do see this in the API docs...?

<img width="1100" alt="Screen Shot 2019-05-07 at 22 40 35" src="https://user-images.githubusercontent.com/7218970/57347805-3ba06800-7119-11e9-9e79-f2833faefa22.png">

**Comment by Jank1310** [comment]
Yes for shapes it is documented. But for charts it isn't (forgot to mention category :/)

**Comment by gitbrent** [comment]
Ha, now it makes sense.

**Comment by gitbrent** [comment]
Thanks @Jank1310
