### ISSUE TITLE
Is it possible to use a line as a connector between two rectangles

### ISSUE THREAD

**Issue by dashmaker** [gitbrent/PptxGenJS#527]
I need to create flow diagrams and would like the links (lines) that connect boxes to be fixed so that if someone moves a box in the output presentation the lines will stay connected. In powerpoint this is done by dragging the line onto the little nodes that appear on edges of the text-box. I can't find guidance on this in the documentation. Is it possible? And if so, how?

Thanks for the great work on this library!

**Comment by gitbrent** [comment]
Hi @dashmaker 

The library does not currently support connectors.

Thanks for the feedback!
