### ISSUE TITLE
Can a table row image be exported using HTML to PPT?

### ISSUE THREAD

**Issue by yushouqing** [gitbrent/PptxGenJS#530]

**Comment by gitbrent** [comment]
Hi @yushouqing 

No, only text is reproduced when using the `addSlidesforTable()` method.

[API Docs](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html)

What kind of image do you have? An icon, background image?

**Comment by yushouqing** [comment]
> Hi @yushouqing
> 
> No, only text is reproduced when using the `addSlidesforTable()` method.
> 
> [API Docs](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html)
> 
> What kind of image do you have? An icon, background image?

the inner image element. eg:<img />
