### ISSUE TITLE
How to make template ppt upload designs with PPTXGenJs 

### ISSUE THREAD

**Issue by Muhammadarya23** [gitbrent/PptxGenJS#532]
I want to design a template ppt, with the following conditions:
- the slide master for headers uses an image and can be inserted in the text title
- Under the header table, in the menu section I insert a table with 4 row and 4 column

please guide to make design templates use pptxgenjs
Best Regards

**Comment by gitbrent** [comment]
Hi @Muhammadarya23 

There are many code samples you can use, including Slide Masters.

See the demo: `examples/pptxgenjs-demo.html` and the code: `examples/pptxgenjs-demo.js`
