### ISSUE TITLE
Is it possible to set an image as the background of the slide ?

### ISSUE THREAD

**Issue by antoinebattagliotti** [gitbrent/PptxGenJS#533]
I am currently working on a project aiming to create a PowerPoint thanks Python pptx. However I am trying to set an image as the background of the slide and I can’t seem to find the solution in the docs of Python pptx. Is it possible to set an image as background if so can someone help me ?

**Comment by gitbrent** [comment]
Sure, just create a [master slide](https://gitbrent.github.io/PptxGenJS/docs/masters.html) and use it on any Slide you'd like a background image on.

**Comment by gitbrent** [comment]
Agreed. If the background option an be expanded to include an image instead of just a color, that would be preferable to creating a master.

**Comment by nateshim** [comment]
is there a way for us to upload background images via local pathing? All i get is a ? jpg

**Comment by gitbrent** [comment]
This feature is now available thanks to @thomasowow via Pull #610
