### ISSUE TITLE
is it possible to set different font styles to substring of text in text objects?

### ISSUE THREAD

**Issue by rickykoh** [gitbrent/PptxGenJS#534]
Example of output I want: This is **IMPORTANT**

My text object: 

rows.push([ 
  { text: "This is IMPORTANT'', options: { color: 'ff0000' } }
 ]);

**Comment by gitbrent** [comment]
Please see the [API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-text.html#text-examples) or the demo under the `examples` directory.

<img width="493" alt="Screen Shot 2019-04-25 at 23 15 09" src="https://user-images.githubusercontent.com/7218970/56783184-ffcbe100-67af-11e9-9631-7522a43c7d96.png">
