### ISSUE TITLE
No Category names for Piecharts

### ISSUE THREAD

**Issue by RokasDie** [gitbrent/PptxGenJS#535]
Hello,

There seems to be a bug with Piecharts. Here is the code which I used to create it:
```
var dataChartAreaLine = [
    {
      name: "Actual Sales",
      labels: ["Jan", "Feb", "Mar"],
      values: [1500, 4600, 5156]
    }
  ];
  slide.addChart(pptx.charts.PIE, dataChartAreaLine, {
    x: 1.0,
    y: 1.0,
    w: 2.897638,
    h: 2.452756,
    dataLabelPosition: "outEnd",
    dataBorder: { pt: "3", color: "ffffff" },
    shadow: "none"
  });
```

However, once it is created Category Name is ticked but it is not showed:
![image](https://user-images.githubusercontent.com/44611740/56732384-d5553600-6765-11e9-84be-ce2d2ba1314c.png)

And once I untick and then tick it again it starts showing them:

![image](https://user-images.githubusercontent.com/44611740/56732415-ed2cba00-6765-11e9-93ea-42f70c03c063.png)

Am I doing something wrong? Because it is really important for me to show these values :/

Regards,
Rokas

**Comment by RokasDie** [comment]
Hello, will there be any plans to look into this issue or any ideas how to fix it?

**Comment by gitbrent** [comment]
Hi @RokasDie 

Thanks for the detailed report. I'll check to see what may be causing this issue.

I'm not sure there's any work-around other than what you're doing now - checking/unchecking the option.

**Comment by gitbrent** [comment]
it doesn't appear to be a bug, you're just not adding the option for "Category Name" (`showLabel`).

<img width="596" alt="Screen Shot 2019-05-07 at 22 32 40" src="https://user-images.githubusercontent.com/7218970/57347480-119a7600-7118-11e9-8303-d3277f1e3eec.png">

![Screen Shot 2019-05-07 at 22 30 26](https://user-images.githubusercontent.com/7218970/57347568-5c1bf280-7118-11e9-889d-a3b9390d9126.jpg)
