### ISSUE TITLE
Barchart data label rotation

### ISSUE THREAD

**Issue by pablodicosta** [gitbrent/PptxGenJS#538]
Is there a way to make the data label vertical in barcharts?

**Comment by gitbrent** [comment]
Not that i'm aware of. The various `dataLabelPosition` options may partially achieve that.

### [Chart API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#bar-data-line)

**Comment by rafmuller** [comment]
I was looking for a solution on this and was able to make some changes to solve this but haven't completed it properly (not even close). 

In pptxgen.js around line 3160.

`
						if (chartType == 'bar') {
							strXml += '      <a:bodyPr rot="-5400000" />';
						} else {
							strXml += '      <a:bodyPr />';
						}
`

I might try and do a pull request to get something like this done properly. I am not that great a JS dev. And I am not really sure what this value is ( just got it from making the change in PPT and looking for the change in the saved file ). 

So just wanted to throw this here in case anyone wants to pick it up and do a better job.
