### ISSUE TITLE
Radar chart line colors

### ISSUE THREAD

**Issue by pablodicosta** [gitbrent/PptxGenJS#539]
I couldn't find a way to change line colors for standard radar charts. It always renders the same color scheme.
If I use chartColors property, only the data points colors are changed, but the line colors remains the same.
Is there a way to change them? or is it a PowerPoint limitation?

**Comment by gitbrent** [comment]
Can you create what you're looking for in PowerPoint?

If so, will you include a screencap of the settings used?

**Comment by jealmgren** [comment]
I've the same issues. I cannot change the colors of the lines. chartColors only changes the color of the markers.

Result:
![image](https://user-images.githubusercontent.com/45264110/88164186-17448480-cc14-11ea-9e65-f76cfc3fe811.png)

Code:
```     
      let radarChartData = [
        {
          name: 'Series 1',
          labels: ['Lab1', 'Lab2', 'Lab3', 'Lab3', 'Lab4', 'Lab5'],
          values: [3, 4, 6, 4, 1, 0]
        },
        {
          name: 'Series2',
          labels: ['Lab1', 'Lab2', 'Lab3', 'Lab3', 'Lab4', 'Lab5'],
          values: [0, 7, 3, 8, 0, 0]
        }
      ]
      let radarChartOpts = {
        x: 9.97,
        y: 4.21,
        w: 3.45,
        h: 2.75,
        showTitle: true,
        title: 'Title',
        titleFontFace: 'Franklin Gothic Book',
        titleFontSize: 9,
        showLegend: true,
        legendFontFace: 'Franklin Gothic Book',
        legendFontSize: 8,
        legendPos: 'b',
        catAxisLabelFontFace: 'Franklin Gothic Book',
        catAxisLabelFontSize: 8,
        catAxisLineShow: false,
        valAxisHidden: true,
        valGridLine: { color: 'D9D9D9', size: 0.75 },
        chartColors: ['FF0000', '7F7F7F']
      }
      slide.addChart(ppt.charts.RADAR, radarChartData, radarChartOpts)
   ```

**Comment by gzeeel** [comment]
Hello, any update on this on ? does anyone successed in changing radar line colors please ? I got the same issue.
Thanks
![image](https://user-images.githubusercontent.com/56316342/129739322-1623e978-688e-41e7-8720-68633aac9cdc.png)

**Comment by ankush-uipath-13** [comment]
Hello, any update on this issue ? does anyone able to change the color for radar lines? I am stuck with same issue.
Thanks

![radar](https://user-images.githubusercontent.com/82217330/151912262-a9b775d3-3daf-4213-b194-3c612bccbeca.png)

**Comment by gitbrent** [comment]
Thanks for opening this issue @pablodicosta 

The library was not correctly handling line color properties and the demos available were not well documented.

I've enabled line colors and updated the demos - the updated code will ship with v3.10

![Screen Shot 2022-02-24 at 20 56 00](https://user-images.githubusercontent.com/7218970/155645428-1f84160d-24c9-4555-a662-70caf921ce30.png)

**Comment by gitbrent** [comment]
Thanks to @jealmgren @gzeeel @ankush-uipath-13 for the reminder about this issue.

Feel free to test with the latest build and review the updated typedefs.

**Comment by pablodicosta** [comment]
@gitbrent  I forgot that I had reported this issue and it feels good seeing it fixed. Thank you very much! :D
