### ISSUE TITLE
how to add animations to text

### ISSUE THREAD

**Issue by vanekar** [gitbrent/PptxGenJS#54]
Hello,

Would like to know how i could add animation to text like appear, can someone assist me if possible

regards
Anwar

**Comment by gitbrent** [comment]
hi @vanekar ,

There are currently no plans to support animation in the near term, but i am curious to know what you were looking to do.

Can you give me some examples of animation functionality you ere looking to use?

**Comment by vanekar** [comment]
Hello ,

Thanks for your reply, what i mean  all the text are displayed at 1 shot
what i want is each text to appear when user presses enter keys just like
the animation tab in powerpoint where text property can be set to
'APPEAR',"FADEIN' etc...

Thanks

Anwar

**Comment by gitbrent** [comment]
Hi @vanekar ,

I could see implementing at least some base functionality to enable click to fadein, etc.

I'll keep this issue open and revisit it once the other items i'm working on now are completed.

Thanks for the request!

**Comment by vanekar** [comment]
Hi Bent,

Sorry to rush you , but i need to implement for a web site any suggestion
that you could give me or not to sound rude but any timeline by when this
will be available, if you guide me perhaps i could do and submit it to you.

Regards
Anwar

**Comment by gitbrent** [comment]
Hi Anwar,

I won't be able to help with your current project as it'll be a while before i look into animations.

..Brent

**Comment by vanekar** [comment]
Hi Brent,

Any development on this Time line request just like this macro in powerpoint 2010 onwards

Sub TestShapeAnimation()

    With ActivePresentation.Slides(1)
        Dim shp1, shp2, shp3 As Shape
        ' This sets the initial shape, with which we will test the animation sequences.
        Set shp1 = .Shapes.AddShape(msoShape12pointStar, 20, 20, 100, 100)

        ' This creates the animations.
        .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectFadedSwivel, , msoAnimTriggerAfterPrevious
        .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectPathBounceRight, , msoAnimTriggerAfterPrevious
        .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectSpin, , msoAnimTriggerAfterPrevious

        ' This acquires the animation... [i]
        shp1.PickupAnimation

        ' [i] ... and applies it to another shape.
        Set shp2 = .Shapes.AddShape(msoShapeHexagon, 100, 20, 100, 100)
        shp2.ApplyAnimation

        ' Another shape creation / animation application.
        Set shp3 = .Shapes.AddShape(msoShapeCloud, 180, 20, 100, 100)
        shp3.ApplyAnimation

    End With

End Sub

**Comment by Arya-Programmer** [comment]
Have their been any developments regarding this matter?

**Comment by gitbrent** [comment]
My current opinion is that this feature isn't requested enough to warrant coding. If someone would submit a pull request, i'd be happy to review it.
