### ISSUE TITLE
Downloading PPT in iOS using Safari does not work. File named as UNKNOWN.

### ISSUE THREAD

**Issue by mustafagentrit** [gitbrent/PptxGenJS#540]
Hi all,
While trying PPT download in iPhone/iPad using Safari browser the file is being named as UNKNOWN and I am not able to open it.

![IMG_0141](https://user-images.githubusercontent.com/36186906/57654180-dabed700-75d3-11e9-8b0b-086b7b23c93e.PNG)

**Comment by gitbrent** [comment]
I wonder if this is related to Issue #471 - MIME Type?

**Comment by adrienco88** [comment]
I also had issues with iOS and it is related to MIME Type and also the Safari browser.
The Blob needs to have the following MIME type:
`var blob = new Blob([content], {type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation'});`

Beside this, I also had to save the pptx file on the disk to serve it for direct download and redirect the page to that URL. 

Hope that this helps.

Best Regards,
Adrian

**Comment by gitbrent** [comment]
I've marked this for release `3.0` - i'll ensure iOS Safari downloads are supported in the near future.

**Comment by Alex-Golovin** [comment]
@gitbrent Many thanks for your work on this library!
Waiting for the release 3.0 with fixed this iOS Safari issue

**Comment by Alex-Golovin** [comment]
@gitbrent Unfortunately it doesn't work not only on Safari, but on Chrome as well.

Does it works on any mobile at all?

**Comment by Alex-Golovin** [comment]
@gitbrent I've replaced in source code type `octet/stream` to `application/vnd.openxmlformats-officedocument.presentationml.presentation`

BUT downloading file still has UNKNOWN.pptx name for some reason

**Comment by gitbrent** [comment]
This is now fixed in the current branch and in `3.0`

![IMG_1705](https://user-images.githubusercontent.com/7218970/64494488-20727000-d253-11e9-925e-b644bdbe306f.PNG)
