### ISSUE TITLE
Table header gets mangled when a cell with both rowspan and colspan is present

### ISSUE THREAD

**Issue by dipan66** [gitbrent/PptxGenJS#543]
I have been trying to create a table with a corner cell which has both rowspan and colspan. 

![image](https://user-images.githubusercontent.com/2462362/58176249-85638380-7cbf-11e9-9a53-f5378a9ed52a.png)
As the image shows - when such a such a scenario is used, the table loses values in the row that is spanned out - for the number of columns that is spanned out. That is, this example, I have been using 2 rows and 2 columns spanned, so the last 2 values in the second row are lost. I have experimented with 2 rows and 3 columns spanned, and the result is consistent - last 3 values of the second row is lost. 

Have uploaded the sample code here: https://pastebin.com/nUEmLiGG

**Comment by dipan66** [comment]
A workaround as below works to get me the lost cells. Basically - I introduced as many blank values in the second row as there were columns spanned out. And the lost values reappeared.
![image](https://user-images.githubusercontent.com/2462362/58177167-78e02a80-7cc1-11e9-92f2-f57db68e870f.png)

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by jsvishal** [comment]
@dipan66
your workaround is working fine. 
it seems like a bug. rowspan and colspan both not working together
