### ISSUE TITLE
I am unable to open the ppt file generated using  pptxgenjs(2.5.0) from linux server

### ISSUE THREAD

**Issue by charanponnoju** [gitbrent/PptxGenJS#545]
I am unable to open the ppt file generated using pptxgenjs(2.5.0) from linux server redhat(dev environment) but it works fine via local server which is windows..Please help"

I have tried to unblock the settings in PPT options and also in trusted network settings but no luck.

My Code:

downloadTextSlidePpt (){
  let pptx = new PptxGenJS();
 
var slide = pptx.addNewSlide();
	var opts = { x:1.0, y:1.0, fontSize:42, color:'00FF00' };
	slide.addText('Hello World!', opts);
	

  pptx.save('DemoSlides-PPT.ppt');

 }

**Comment by charanponnoju** [comment]
Hi,
It is working now with the version 2.5.0 ...On dev it was automatically upgrading to latest version which was causing the issue...clean build did fix the issue.

**Comment by gitbrent** [comment]
Hi @charanponnoju - good to hear it's working, thanks for the follow-up.

**Comment by joeberth** [comment]
Hello @charanponnoju , i am using pptxGenJs 2.5.0 version and i am having this issue on ubuntu 16.04.
 
the same code in fiddle generate different legend labels. In mobile or windows the download is the correct one. The 'name' key is being binded instead the labels. (see below):
image

But when i download using unix SO, i got this picture below:

image

how can i fix it? The 'name' key is being binded instead the labels.

**Comment by charanponnoju** [comment]
Hi Joberth , I am using html2canvas for my chart to convert it into image and download..I am not sure what you are using?? but if you are using the samw way..please check if your div element consists of the labels u are looking for to download...

**Comment by joeberth** [comment]
Hi charanponnoju , i am using pptxGenJs to create a powerpoint with my charts. The label is actually correct. Only the 'pie' chart has this issue and only in linux or ios OS. The both prints above was created with the same code, but the first one i opened in windows/mobile and the second one i opened in linux. i am really worried about that, after code almost all features using this lib, i wish get some solution for this issue.

**Comment by charanponnoju** [comment]
Hi Joberth, Please try to set -->dataLabelPosition(Play with it if it shows what you need)
https://gitbrent.github.io/PptxGenJS/docs/api-charts.html

**Comment by joeberth** [comment]
Hi charanponoju, i really appreciate your desire to help. please take a look at this fiddle https://jsfiddle.net/n5o7kw8x/ . i am downloading this pptx in linux and get only one label called 'location', but when i download the same fiddle code in windows i get the correct labels and colors. 
I tried to set different dataLabelPosition, but idk what problem it can be.

**Comment by charanponnoju** [comment]
Can you check if this works for you...{dataLabelPosition:'outEnd'}

**Comment by joeberth** [comment]
Nothing changed, i tested almost all dataLabelPosition, but i think that the problem is the Value of the data Label that unix OS sees, i mean, i can change the data label position with dataLabelPosition option, but the value that coming from data label is not the label of the object, but the name.
