### ISSUE TITLE
Appending array items to a placeholder

### ISSUE THREAD

**Issue by Sahbaaat** [gitbrent/PptxGenJS#546]
Hi,

I am struggling with this problem for a while.
I have an array of text that I want to append each item in that array to a master slide place holder.
is a for loop possible in addText()?

tests = ['test1', 'test2', 'test3'];

for (var i = 0; i < tests.length; i++) {
slide.addText(tests[i], { placeholder:'placeholder1', fontSize:8, fontFace: 'Arial'});
}

With this code only the last item would appear in the place holder which make sense!
Do you have any solutions?

**Comment by gitbrent** [comment]
[Closing due to age]
