### ISSUE TITLE
control angle and thickness in arc and blockArc shapes

### ISSUE THREAD

**Issue by paolochiodi** [gitbrent/PptxGenJS#547]
If I add a BLOCK_ARC shape to a slide I get a 180 degrees arc. 

Is it possible to control this and have instead a 45 or 90 degrees arc? Also, is it possible to control the block arc "thickness"?

From the docs it is not apparent to me.

Thanks

----

Default behaviour:
<img width="185" alt="current" src="https://user-images.githubusercontent.com/81542/58494764-21850300-8176-11e9-9953-6b1cad6fb1e9.png">

Desired behaviour:
<img width="188" alt="desired" src="https://user-images.githubusercontent.com/81542/58494766-221d9980-8176-11e9-9724-cee8f182ddb1.png">

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by apresmoi** [comment]
Hi @gitbrent Could this be added ?

**Comment by apresmoi** [comment]
I've sent a PR(#861 ) for this

**Comment by gitbrent** [comment]
This is done thanks to Pull #861
