### ISSUE TITLE
Cannot locate type definitions

### ISSUE THREAD

**Issue by iota-pi** [gitbrent/PptxGenJS#549]
After installing from `npm` (pptxgenjs v2.5.0), one should be able to import thus:

```
import PptxGenJS from 'pptxgenjs';
```

However, this gives the following error:

```
Could not find a declaration file for module 'pptxgenjs'. '.../node_modules/pptxgenjs/dist/pptxgen.min.js' implicitly has an 'any' type.
  Try `npm install @types/pptxgenjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'pptxgenjs';`
```

Instead, in order to successfully import it:

```
import PptxGenJS from 'pptxgenjs/dist/pptxgen';
```

**Comment by thitemple** [comment]
That's because the package.json should have a `typings` key pointing to the types definition file. I have created a PR for that. https://github.com/gitbrent/PptxGenJS/pull/558

**Comment by gitbrent** [comment]
Thanks @thitemple !
