### ISSUE TITLE
add base_64 encoded SVG images

### ISSUE THREAD

**Issue by proadiga** [gitbrent/PptxGenJS#55]
hallo , 

I try to add an SVG Image to a slide with this Code : 

`slide.addImage({data:"image/svg+xml;base64,PD94bW..... "});`

but in the Powerpoint file it didn't show the Image , and display the message : "this picture cannot be displayed" 

BUT wenn I remove the "+xml" from the command and will be like this : 

`slide.addImage({data:"image/svg;base64,PD94bW..... "});`

the picture will inserted  and displayed !! but this photos displayed  just wenn I open the file on my computer , on other Computers it will show the last error message and no photos will showed !!!

Please help me in this issue , if someone know or tried how to add an svg Image .

Best Regards !

**Comment by gitbrent** [comment]
Hi @proadiga ,

Thanks for your question.

At this time, PowerPoints SVG support is mostly non-existent.  From what i could find through searching, some people have had success viewing SVG images while others have not.  This explains how you could view the image while your colleagues could not.

I just tried viewing and adding an SVG using O365 and PowerPoint Online would not do either:
![screen shot 2017-03-14 at 11 21 40](https://cloud.githubusercontent.com/assets/7218970/23910701/96b43482-08a8-11e7-8929-b239fcecd703.png)
![screen shot 2017-03-14 at 11 21 09](https://cloud.githubusercontent.com/assets/7218970/23910698/94d0b8ca-08a8-11e7-9917-3b79a426c6b4.png)

Based upon this, i've added a note in the README stating that SVG is still unsupported at this time.

**Comment by gitbrent** [comment]
NOTE: SVG via base64 is now supported in release 2.4.0 thanks to Issue #401 

![screen shot 2018-09-27 at 19 07 13](https://user-images.githubusercontent.com/7218970/46181036-52c8ce80-c289-11e8-806f-2806ca47b454.png)
