### ISSUE TITLE
Ability to set start number "startAt" for a bullet list of type numbered

### ISSUE THREAD

**Issue by bj-mitchell** [gitbrent/PptxGenJS#554]
I have a numbered bullet list that continues over multiple slides and it would be nice to be able to set the starting number for a bullet of type number.  I apologize if this already exist, but I could not find it in the documentation.

**Comment by bj-mitchell** [comment]
After looking thru some past issues, I saw one opened by @mayvazyan regarding numbered list.  Looking at that code pointed to what looks like the right area to address this.  

Around line 4209, I changed 

```javascript
strXmlBullet = '<a:buSzPct val="100000"/><a:buFont typeface="+mj-lt"/><a:buAutoNum type="arabicPeriod"/>';
```

to
```javascript
var startAt = textObj.options.bullet.startAt ? textObj.options.bullet.startAt : '1';
strXmlBullet = '<a:buSzPct val="100000"/><a:buFont typeface="+mj-lt"/><a:buAutoNum type="arabicPeriod" startAt="' + startAt + '"/>';
```
and it gives the current desired result.

Example:
`bullet: { type: 'number', startAt: '4' }`

**Comment by bj-mitchell** [comment]
I merged in changes from gitgrent#452 as they were directly related.

**Comment by linktothapast** [comment]
+1 
Would be great to have this feature.

**Comment by gitbrent** [comment]
Hi @bj-mitchell 

Thanks for the request and the pull code.

This feature has been added to the upcoming 3.0 release.
