### ISSUE TITLE
Set width and height values in px?

### ISSUE THREAD

**Issue by alagarrk** [gitbrent/PptxGenJS#56]
Currently i am trying to export the chart from our app to ppt using PptxGenJS. I am getting px values for all the elements, so how can i set the values (width and height) in px(units) to draw any shapes in PptxGenJS?

If we can't set px in PptxGenJS, do you have any idea that how to convert px to inch/percentage which can be use in PptxGenJS?

Can you please give some suggestion on this. Thanks in advance.

**Comment by gitbrent** [comment]
Hi @alagarrk ,

Thanks for the question.

A good rule of thumb is `100 px = 1 inch` as modern LCD displays are mostly 96px/inch.

You can also pass `x`,`y`,`w`,`h` and `colW` percentage values, so it may be easier to just honor the layout you have now.  For example, create a table that is 100% wide and has 3 columns, 25%/25%/50%, that way no pixel conversion is necessary.

Or you could be super fancy and measure the `innerWidth` of an HTML element relative to its window.size and then use that same percent as arguments to the library...

**Comment by alagarrk** [comment]
@gitbrent Thank you for the solution. Now its works fine :+1: 

Currently we can able to export the basic primitives chart [http:// basicprimitives.com/index.php] to PPT using PptxGenJS (Shapes). But the problem is we have generated chart as shapes(rect & lines), all are separate elements. If user wants to change/move the parent/child node, they need to move the relative shapes(lines & arrows).

Now i am trying to add smartArt(Organisation Chart) in powerpoint to generate the chart.
Is it possible to add the smartArt Graphics and show hierarchical information or reporting relationships in an organization.? 
Ex:
![samplediagram](https://cloud.githubusercontent.com/assets/12545406/24032074/1d1a717e-0b21-11e7-9ce0-b6a2786c25ae.PNG)

**Comment by gitbrent** [comment]
Hi @alagarrk ,

I'm very glad to hear you were successful!

SmartArt isn't something i was planning on supporting, but Charts are coming soon... :-)

**Comment by alagarrk** [comment]
Ok @gitbrent Thank you very much for your support.

Do you have any idea, how to add hierarchical chart in powerpoint using PptxGenJS. If you give some suggestion/idea it will very helpful for me to implement this.

Thanks in advance.
