### ISSUE TITLE
Hyperlink creates malformed slide if it includes &

### ISSUE THREAD

**Issue by Tehnix** [gitbrent/PptxGenJS#562]
This is in relation to the true issue of https://github.com/gitbrent/PptxGenJS/issues/90. Including relevant information here:

Reproduction case:
```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
    slide .addText([
          {text: 'test A & B', options: {hyperlink: {url: 'https://github.com/gitbrent/pptxgenjs?a=1&b=2', tooltip: ' A&B'}}}
          ], {x: 0.62, y: 1, w: 5.3, h: 0.34, font_size: 14, color: '667184', bullet: {code: '27A2'}}
     );
pptx.save('testhyperlink');
```

Doesn't work due to "a=1&b=2" in the url.

In the linked issue, a suggestion was that there was a missing `decodeXmlEntities(rel.Target)` call somewhere in the library.

**Comment by gitbrent** [comment]
Thanks @Tehnix 

This is now fixed and will be released with v3.0
