### ISSUE TITLE
Save / Download Progress : pptx.save(fileName)

### ISSUE THREAD

**Issue by snowPu** [gitbrent/PptxGenJS#563]
I'm using pptx.save(fileName, () => {}) in Angular 6 to save the pptx.
The file is around 6MB, and it takes a while (15-25 seconds) to download. The problem is that while it's downloading there is no way for the user to know that it is. Only once it has fully downloaded, the user can see the file. 

Would it be possible to display the download progress as it's downloading on the download bar?

**Comment by LeoFC97** [comment]
I need this too

**Comment by gitbrent** [comment]
Version 3.0 will return a Promise when `save` is called, enabling the use of progress bars, etc.

Stay tuned!

**Comment by gitbrent** [comment]
Version 3.0 returns a Promise for all save methods, enabling progress, etc.
