### ISSUE TITLE
hyperlink does not work

### ISSUE THREAD

**Issue by LeoFC97** [gitbrent/PptxGenJS#564]
The hyperlink prop on add text does not work. Code implementation below. Nothings change on my .pptx when I implement hyperlink

![image](https://user-images.githubusercontent.com/33994116/59560618-987e2080-8feb-11e9-9eab-3378dea0ccc2.png)

**Comment by gitbrent** [comment]
Hi @LeoFC97 

Your code is incorrect - please include the `options` keyword as shown in the [API Docs](https://gitbrent.github.io/PptxGenJS/docs/api-text.html#text-examples).

```javascript
slide.addText(
    [
        { text:'Visit the ' },
        { text:'PptxGenJS Project', options:{ hyperlink:{ url:'https://github.com/gitbrent/pptxgenjs', tooltip:'Visit Homepage' } } },
        { text:' or ' },
        { text:'(link without tooltip)', options:{hyperlink:{url:'https://github.com/gitbrent'}} }
    ],
    { x:0.5, y:5.35, w:6.0, h:0.6, margin:0.1, fill:'F1F1F1', fontSize:14 }
);
```
<img width="1031" alt="Screen Shot 2019-06-17 at 17 07 30" src="https://user-images.githubusercontent.com/7218970/59640128-c87c0f80-9122-11e9-9835-726146e4b8bd.png">

**Comment by LeoFC97** [comment]
Thanks for the reply, but I'm still having the same problem.
![image](https://user-images.githubusercontent.com/33994116/59734594-71606280-9228-11e9-81fd-e9e0a9ecdaa0.png)

**Comment by gitbrent** [comment]
`hyperlink` goes inside the `options` object (it's a child not a sibling)
