### ISSUE TITLE
Feature Request: Create new PPT based on existing PPT

### ISSUE THREAD

**Issue by vcheeze** [gitbrent/PptxGenJS#565]
Hi @gitbrent, thanks for building this wonderful module. Have you thought about extending the features to allow creating a new file based on existing files, or even simply updating existing files? I am thinking about PPT specifically. Thanks!

**Comment by gitbrent** [comment]
Hi @vcheeze 

Thanks for the feedback. :)

This a somewhat common question and is mentioned in the README... No, this library is solely designed to produce PowerPoint presentations. There are no plans to read/modify existing PPT files.
