### ISSUE TITLE
Code scan issues

### ISSUE THREAD

**Issue by Brent321** [gitbrent/PptxGenJS#566]
Hi. 
I just scanned pptgen.js with SonarCube and it came back with the following issues:
**Lines 2712, 2714**  - "makeValueAxis" declared at line 3784 expects 2 arguments, but 3 were provided.
**Line 3784** - "makeValueAxis" declared at line 3784 expects 2 arguments, but 4 were provided.
**Lines 3695, 3794, 3858** - This conditional operation returns the same value whether the condition is "true" or "false".
**Line 5563** - Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed

Thanks!

**Comment by gitbrent** [comment]
Thanks @Brent321 

The library is currently being converted to Typescript which has brought similar issues to our attention. These have been identified and will be fixed when version 3.0 is released.

**Comment by wuh** [comment]
> Thanks @Brent321
> 
> The library is currently being converted to Typescript which has brought similar issues to our attention. These have been identified and will be fixed when version 3.0 is released.

when the 3.0 version is expected to be released? our team want to improvment the chart ability based on typescript.

**Comment by gitbrent** [comment]
Version 3.0 should be available this fall.

Feel free to check the 3.0 branch to see the progress.

**Comment by gitbrent** [comment]
Version 3.0 is tslinted now in addition to being TypeScript, so code quality is much better now.

The `version-3.0` branch has the new version.
