### ISSUE TITLE
HTML to text - Question

### ISSUE THREAD

**Issue by aniov** [gitbrent/PptxGenJS#567]
Hy there,
I have a html text input obtained from using a js text editor
`(<p>, <span>, <strong>, <em>, <ul>, </li> ...)`
Has anyone done the conversion ?
Do I have to parse the html and convert to pptxGen library style ?
Thank you.

**Comment by adrienco88** [comment]
You have to parse the text and convert the HTML tags and attributes + styles to pptxGexJS style.

**Comment by aniov** [comment]
I've done it in the mean time, ty.

**Comment by gitbrent** [comment]
Correct, converting the string to an HTML element is the way to accomplish this.

Ex: Using jQuery
`$("<table>...</table>")`

**Comment by codemanki** [comment]
@aniov you mind sharing how did you achieve html to PptxGen syntax conversion?

**Comment by gitbrent** [comment]
If someone has code to do this, i'll add it to the Wiki.

**Comment by codemanki** [comment]
If I could get some hints on how to implement this in more or less proper way, then I could write some example code and contribute it to the Wiki
