### ISSUE TITLE
Table-to-Slides default for un-styled tables is black text on black bkgd

### ISSUE THREAD

**Issue by orpitadutta** [gitbrent/PptxGenJS#57]
I implemented table to slides but each time a black band appears. Can you please help? Or assist me where am i going wrong?

[Presentation (1).pptx](https://github.com/gitbrent/PptxGenJS/files/844538/Presentation.1.pptx)

<table id="mytable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Test</th>
                <th>Company</th>
            </tr>
        </thead>
    </table>
    <input type="button" value="Export to PPTX"
           onclick="{ var pptx = new PptxGenJS(); pptx.addSlidesForTable('mytable'); pptx.save(); }">

**Comment by gitbrent** [comment]
Hi @orpitadutta ,

Could you please attach a screencap instead and provide the code you're using?

Thanks.

**Comment by orpitadutta** [comment]
![image](https://cloud.githubusercontent.com/assets/18306593/23987224/859ed7ea-0a4e-11e7-8b67-c8c0aecf7e18.png)


<!DOCTYPE html>
<html>
<head>
<title>DEMO</title>
   <script src="nextgen/jquery.min.js"></script>
    <script src="nextgen/jszip.min.js"></script>
    <script src="nextgen/filesaver.min.js"></script>
    <script src="nextgen/pptxgen.js"></script>
    <script src="nextgen/pptxgen.shapes.js"></script>
</head>
<body>

    <table id="mytable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Test</th>
                <th>Company</th>
            </tr>
        </thead>
    </table>
    <input type="button" value="Export to PPTX"
           onclick="{ var pptx = new PptxGenJS(); pptx.addSlidesForTable('mytable'); pptx.save(); }">
   
</body>
</html>

**Comment by alagarrk** [comment]
Hi @orpitadutta ,

I think, you need to apply some styles for the table. Currently table - background color is black & also text color is black. So you are seeing black box.  @gitbrent Please correct me if i am wrong.

Ex:
<table id="mytable" style="color:white">
    <thead>
        <tr>
            <th>Name</th>
            <th>Test</th>
            <th>Company</th>
        </tr>
    </thead>
</table> 
 @orpitadutta  Please try it

**Comment by orpitadutta** [comment]
@alagarrk Thanks a lot, It worked like a charm.

**Comment by orpitadutta** [comment]
I tried this:

<script type="text/javascript">
        function fnppt()
        {
            var tabOpts = { x:0.5, y:2.0, w:9.0, fill:'F7F7F7', font_size:18, color:'6f9fc9' };
            var pptx = new PptxGenJS();

            pptx.addSlidesForTable('mytable',tabOpts );
            pptx.save();
        }
        
    </script>

 
</head>
<body>
    <table id="mytable" style="background-color:red; color:yellow;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Test</th>
                <th>Company</th>
            </tr>
        </thead>
    </table>
    
    <input type="button" value="Export to PPTX" onclick="fnppt()">
</body>

**Comment by alagarrk** [comment]
@orpitadutta , For addSlidesForTable() - Reproduces an HTML table - background colors, borders, fonts, padding, etc.

So you can add styles using css. For Ex:  
#mytable {
        background: #f2f2f2;
        border: 1px solid black;
        color: black;
    }
    
    #mytable th,
    #mytable tr {
        background: #f2f2f2;
    }

Please check this

**Comment by orpitadutta** [comment]
@alagarrk Thnxx a lot it worked like a charm..

**Comment by gitbrent** [comment]
Hi @orpitadutta @alagarrk ,

Thanks for your help on this Issue.

Turns out that the default color returned by jQuery is black, so in un-styled tables, you end up with black text on a black background...

I've updated the code to detect this condition and default to a white background instead.

**Comment by Strawberry0215** [comment]
hi @gitbrent is it possible for addTable to call it on it's ID instead of var array?
