### ISSUE TITLE
Select data range

### ISSUE THREAD

**Issue by mayank9804** [gitbrent/PptxGenJS#574]
Do we have something like range which tells how many rows to plot on chart
for eg:
<pre>
let opts = {
range: 1-2,
}
let charts =[{
			name  : 'Region 2',
			labels: ['April', 'May', 'June', 'July', 'August'],
			values: [0, 30, 53, 10, 25]
		}, {
			name  : 'Region 3',
			labels: ['April', 'May', 'June', 'July', 'August'],
			values: [17, 26, 53, 100, 75]
		}, {
			name  : 'Region 4',
			labels: ['April', 'May', 'June', 'July', 'August'],
			values: [55, 43, 70, 90, 80]
		}, {
			name  : 'Region 5',
			labels: ['April', 'May', 'June', 'July', 'August'],
			values: [55, 43, 70, 90, 80]
		}];

slide.addChart(pptx.charts.bar,charts,opts)
</pre>
Now, I want that datatable contains all the data but the chart uses only 1st and 2nd row to plot series

**Comment by mayank9804** [comment]
@gitbrent Hey man, thanks for your awesome piece of work. Can you get this confirmed? And if it is not there, it will be a really cool feature. (Syncfusion provides this feature, would love if this becomes pptxgenjs part)

**Comment by gitbrent** [comment]
[Closing due to age]
