### ISSUE TITLE
Base 64 quality

### ISSUE THREAD

**Issue by Skiizoo** [gitbrent/PptxGenJS#577]
hi,

I am currently working with D3JS and would like to share these graphs.

I managed to convert the SVG to base64 but the quality of the image in the .ppt is really, really bad.

am i doing wrong or we just can't get this properly with svg ?
![treemap_1](https://user-images.githubusercontent.com/24459040/62137140-bd9dc880-b2e5-11e9-83ea-d5746144a95c.png)
![treemap_2](https://user-images.githubusercontent.com/24459040/62137141-bd9dc880-b2e5-11e9-9898-a95f6c32c1fb.png)

**Comment by gitbrent** [comment]
Yeah, i see what you mean.

I'm not sure what a fix is off-hand, but you may notice the original size is probably smaller, hence the stretching effect:

<img width="1336" alt="Screen Shot 2019-07-30 at 22 01 30" src="https://user-images.githubusercontent.com/7218970/62180497-dd4ce500-b315-11e9-9d3f-f71e1cb6c476.png">

**Comment by Skiizoo** [comment]
hi,

If we do not set the w / h options in addImage, is it the initial dimensions of the photo taken ?

**Comment by Skiizoo** [comment]
I've been looking into this stretching effect but even if I change the original size I still have the same issue.
Theses pictures down below are the test i made : one with base64 300x150 original size and one with 800x400. (the first picture of each is the preview in chrome and the second one the render in the pptx file)

![chrome_300x150](https://user-images.githubusercontent.com/24459040/62356693-f4582680-b511-11e9-94fe-c34a33e08522.png)
![pptx_300x150](https://user-images.githubusercontent.com/24459040/62356695-f4f0bd00-b511-11e9-8c4f-0eb26f1d7265.png)


![chrome_800x400](https://user-images.githubusercontent.com/24459040/62356694-f4582680-b511-11e9-81ff-fcab6be0339b.png)
![pptx_800x400](https://user-images.githubusercontent.com/24459040/62356698-f4f0bd00-b511-11e9-889a-ab582eeb12c8.png)

Thanks for your time

**Comment by gitbrent** [comment]
Thanks for the update/information.

I double-checked the code and base64 SVG images are created using the w/h size provided. It seemed like they were being set too small, hence the stretching, but that does not appear to be the case.

**Comment by mmayer1** [comment]
See https://github.com/gitbrent/PptxGenJS/pull/528
That fix worked for me

**Comment by Skiizoo** [comment]
@mmayer1 I just have to include the updated pptxgen.min.js file ?
thanks

**Comment by gitbrent** [comment]
Confirmed: Pull #528 fixes this issue.

Version 3.0 incorporates this change.

PREVIOUS:
<img width="936" alt="Screen Shot 2019-09-23 at 23 02 09" src="https://user-images.githubusercontent.com/7218970/65480411-fa55ee00-de56-11e9-92d5-78bc91a7b793.png">

VERSION 3.0:
<img width="939" alt="Screen Shot 2019-09-23 at 23 02 01" src="https://user-images.githubusercontent.com/7218970/65480407-f75afd80-de56-11e9-846e-8f9ad0d77ec6.png">
