### ISSUE TITLE
Outputs varies for list element

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#58]
Following are two text elements created in two different ways.

**EXAMPLE 1**

var pptx = new PptxGenJS(); 
pptx.setLayout('LAYOUT_WIDE'); 
var slide = pptx.addNewSlide(); 

slide.addText(
    [
        {text: 'Hello', options: { color:'393939', font_size:16 }},
        {text: 'Line 1\nLine 2\nLine 3', options: { color:'393939', font_size:16, bullet:true }} 
    ], 
    {x:2.0, y:1.0, w:'50%', h:1, fill:'F2F2F2'}
); 

pptx.save('Demo-Text');
![demo 1](https://cloud.githubusercontent.com/assets/17859100/24043579/4c829fe2-0b3d-11e7-8ff7-36c5ce936c1d.jpg)

**EXAMPLE 2**

var pptx = new PptxGenJS(); 
pptx.setLayout('LAYOUT_WIDE'); 
var slide = pptx.addNewSlide(); 

slide.addText(
    'Hello', { x:2.0, y:1.0, w:'50%', h:1, color:'393939', font_size:16, fill:'F2F2F2' }
); 

slide.addText(
    'Line 1\nLine 2\nLine 3', { x:2.0, y:2.0, w:'50%', h:1, color:'393939', font_size:16, fill:'F2F2F2', bullet:true }
); 

pptx.save('Demo-Text');

![demo 2](https://cloud.githubusercontent.com/assets/17859100/24043610/6c314e4c-0b3d-11e7-8c62-00af6ac036e7.jpg)

I want to know why there outputs vary for bullets as per shown in images above, despite the conversion logic is same.

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

Thanks for opening an issue.

This issue is resolved already in the current branch of the code.  It's not yet released to NPM though - it will be included in v1.3.0.

```javascript
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

slide.addText(
    [
        {text: 'Hello', options: { color:'393939', font_size:16 }},
        {text: 'Line 1\nLine 2\nLine 3', options: { color:'393939', font_size:16, bullet:true }}
    ],
    {x:2.0, y:1.0, w:'50%', h:1.5, fill:'F2F2F2'}
);

slide.addText(
    'Line 1\nLine 2\nLine 3', { x:2.0, y:4.0, w:'50%', h:1.5, color:'393939', font_size:16, fill:'F2F2F2', bullet:true }
);

pptx.save('PptxGenJS-Sandbox');
```

Both of your examples together produce this with the current codebase:
![screen shot 2017-03-19 at 23 45 03](https://cloud.githubusercontent.com/assets/7218970/24088906/1fcd7720-0cfe-11e7-9a46-d62f8b06ae00.png)

**Comment by sangramjagtap** [comment]
Could you please give me a code so as to get a desired output for example given below:

![capture](https://cloud.githubusercontent.com/assets/17859100/26445061/54215db0-415c-11e7-9e1f-9d52cc5da4af.JPG)


PS: (Aim is to add bullet list in PPT, where each list item will have different styling, ie.bold, italic, underline)

**Comment by sangramjagtap** [comment]
![image](https://cloud.githubusercontent.com/assets/17859100/26447131/b322f294-4164-11e7-99c2-6510621edf1c.png)

How to add bold, italic to the list highlighted in above image.

**Comment by ZouhaierSebri** [comment]
hi @sangramjagtap 

1- for only italic you can use the option::  italic:true

2- for styling some part of bullet see my code
```
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();
slide.addText(
[
{ text:'Line 1 - Good Morning', options:{bullet:true} },
{ text:'Test1', options:{} },        
{ text:'Line ', options:{bullet:true} },
{ text:'2 -  Hello ', options:{bold:true} },
{ text:'World', options:{bold:true,italic:true,underline :true} }
 ],
{ x:0, y:0, w:'100%', h:'100%'}
);

pptx.save('PptxGenJS-Test_Bullet_styled');
```

![image](https://cloud.githubusercontent.com/assets/19344990/26453364/5a6073ec-415b-11e7-8f26-adac5f0f2830.png)

**Comment by sangramjagtap** [comment]
Thanks @ZouhaierSebri .

**Comment by sangramjagtap** [comment]
@ZouhaierSebri  , @gitbrent 

![image](https://user-images.githubusercontent.com/17859100/27369875-8909a070-5677-11e7-8ecd-c609d59b8205.png)


Referring to above image, in 2nd line which has bullet, I have added new line using **shift+enter** 

How to export such text? So that there will be 3 bullet lines and 2 sub lines in 2nd one.
