### ISSUE TITLE
Mutliple files getting downloaded if multiple base64 images are added

### ISSUE THREAD

**Issue by akshaymagapu** [gitbrent/PptxGenJS#581]
I added two slides and on each slide, I added two base64 images (SVG to base64). When saving, it downloads two files.
I tried with normal png or jpeg images, it works fine.
Problem is when I tried to add images in base64 format.
Attached the fiddle for this issue:
https://jsfiddle.net/9f7kb0ze/5/
Please check and let me know if it is an issue or I am doing something wrong.
Thanks.

**Comment by akshaymagapu** [comment]
@gitbrent any update here?

**Comment by gitbrent** [comment]
Hi @akshaymagapu 

Thanks for reporting this.

I've verified the issue has already been fixed in the upcoming 3.0 release.

**Comment by akshaymagapu** [comment]
@gitbrent  Thanks :)
