### ISSUE TITLE
Is native SVG support possible?

### ISSUE THREAD

**Issue by pandersen-uncharted** [gitbrent/PptxGenJS#582]
The current support for SVG appears to convert the SVG to a PNG before saving. Since PowerPoint supports SVG images natively could PptxGenJS insert SVG images into a slide without converting them to a PNG? This could break backwards compatibility but a flag on addImage() to convert or not would solve that.

**Comment by mmayer1** [comment]
see https://github.com/gitbrent/PptxGenJS/pull/528
