### ISSUE TITLE
Links in tables won't work on tables generated with autoPage

### ISSUE THREAD

**Issue by githuis** [gitbrent/PptxGenJS#583]
Hi I'm trying to create a rather large slideshow with some built-in navigation. Part of this means lots of tables with links to later slides for specific products. I've encountered an error that, when autoPage splits a table into separate slides, the links only work on the slide where the table starts.

Expected behaviour is that links work on every slide, autoPage or not.

I suspect it may have something to do with the fact that `createHyperlinkRels(arrRows, gObjPptx.slides[slideNum].rels);` (pptxgen.js line ~5345) is called before autoPaging, but I can't seem to fix it myself.

I've attached some demo code which results in the exact same issue. Also here is the pptx file generated by that code:  [Autopage_link_error.pptx](https://github.com/gitbrent/PptxGenJS/files/3524499/Autopage_link_error.pptx)

(Not) Working example:

    let genData = [];
    for (let index = 0; index < 30; index++) {
        genData.push({customer: "Customer-"+index, product: "Product-"+index, description: "Lorem ipsum dolor sit amet"});
    }
    let pptxtest = new PptxGenJS();
    let slideTest= pptxtest.addNewSlide();
    let tableRows = [];
    tableRows.push([ { text: "Customer" }, { text: "Solution" }, { text: "Description" }]);
    let i = 1;
    genData.forEach(ent => {
        tableRows.push([{ text: ent.customer}, { text: ent.product, options: {hyperlink: {slide: i.toString()}} }, { text: ent.description }]);
        i = i +1;
    });
    slideTest.addTable(tableRows, {autoPage: true, margin: 2});

    genData.forEach(ent => {
        let productSlide = pptxtest.addNewSlide();
        productSlide.addText(ent.customer +"\n"+ent.product+"\n"+ent.description);
    });

    pptxtest.save("Autopage_link_error.pptx");

**Comment by TobyNerd** [comment]
I am having the almost exact same issue, and have had to create a splitting function which splits tables upon reaching a set limit of maximum rows, in my case 6.

**Comment by gitbrent** [comment]
The `createHyperlinkRels` method is not completed on the new 3.0 typescript branch, so i'm presently unable to determine if this is already fixed (much of the codebase has been updated).

I'll test for this soon and provide an update.

**Comment by gitbrent** [comment]
Hi @githuis 

Thanks for reporting this issue and for the code.

The auto-paging link issue is fixed in the `3.0` codebase (see below).

If you need this fix ASAP, you may be able to utilize the code from the 3.0 branch as it's fully functional for tables. (See "Coming Soon" section of the README - many changes are still coming including breaking ones).

<img width="1603" alt="Screen Shot 2019-09-02 at 22 40 27" src="https://user-images.githubusercontent.com/7218970/64142743-f17f7880-cdd2-11e9-896b-5e5db8bc5a9f.png">

**Comment by githuis** [comment]
Hi @gitbrent 

Thanks for the response. I'll try to take a look some time soon 😃
