### ISSUE TITLE
Adding glow to a shape

### ISSUE THREAD

**Issue by thitemple** [gitbrent/PptxGenJS#584]
Is there a way to format a shape's glow? Like on the following image?

![image](https://user-images.githubusercontent.com/368734/63459509-a8b6df80-c422-11e9-9b21-313f0f14fa0a.png)

**Comment by gitbrent** [comment]
Hi @thitemple 

The Object API does not currently have support for `Glow`, so I've marked it as an enhancement.

Pull requests are always welcome. It looks similar to text outline as far as parameters go.

**Comment by thitemple** [comment]
I can work on this, should I do it on the current JS version or on the new 3.0?

**Comment by gitbrent** [comment]
Thanks, that'd be great.

In the `3.0-branch` please - it should be significantly easier to modify.

**Comment by gitbrent** [comment]
Hi @thitemple 

Glow has now been added via Pull #630 - target is v3.1.0, demo available in master branch.

<img width="1329" alt="Screen Shot 2020-01-18 at 00 05 58" src="https://user-images.githubusercontent.com/7218970/72659526-73d59700-3986-11ea-83d7-4fb20bf076ea.png">
