### ISSUE TITLE
How to debug Repair message? (PowerPoint found a problem with content in ... )

### ISSUE THREAD

**Issue by abarisic86** [gitbrent/PptxGenJS#588]
Is there any way of debugging what is wrong with the presentation? Like some online tool to verify the syntax of produced XML?

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by georgezouq** [comment]
@gitbrent  Hi I have same problem, open in MacOS Keynote is work, but open in windows PowerPoint 2019 have the repair message

**Comment by pimlottc-gov** [comment]
For me, what's caused that message more times than anything else is not defining enough colors for all the data series.

**Comment by akshaygoyal88** [comment]
For me its due to not defining color in speicifc hex color code
e.g. color: White is giving error color: FFFFFF Worked

**Comment by sckumar** [comment]
Auto paging + Multiline is causing the issue in my case.
