### ISSUE TITLE
Text option `fill` doesn't work when added as 'array of text objects'

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#59]
![capture](https://cloud.githubusercontent.com/assets/17859100/24045026/b5e73d02-0b43-11e7-9412-14d258c70ccf.JPG)
The above generates the output as follows:
![demo 3](https://cloud.githubusercontent.com/assets/17859100/24045106/f6e63d44-0b43-11e7-8be2-9624b464695d.jpg)

But moving margin and fill properties to individual items, 
![capture1](https://cloud.githubusercontent.com/assets/17859100/24045251/696432d6-0b44-11e7-9db2-4e923dd603c9.JPG)
does not reflect in output.
![demo 4](https://cloud.githubusercontent.com/assets/17859100/24045377/e43d78dc-0b44-11e7-900f-3adf60add797.jpg)

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

This is actually the expected behavior as `fill` is a textbox-level option, whereas something like `bold`, or `color`can be applied to individual pieces of text.

**Comment by sangramjagtap** [comment]
And what about margin to individual text item? (A paragraph level
tab/margin)

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

`addText()` creates a paragraph, then adds the individual text objects within that paragraph, so any margin has to applied at the addText-option level.
