### ISSUE TITLE
When i am creating production build i am getting this error

### ISSUE THREAD

**Issue by PriyankaNigotia6** [gitbrent/PptxGenJS#591]
ERROR in error TS5055: Cannot write file 'C:/Users/pnigotia/SM/dsc/src/ngApp/node_modules/pptxgenjs-angular/dist/pptxgen.colors.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file 'C:/Users/pnigotia/SM/dsc/src/ngApp/node_modules/pptxgenjs-angular/dist/pptxgen.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file 'C:/Users/pnigotia/SM/dsc/src/ngApp/node_modules/pptxgenjs-angular/dist/pptxgen.shapes.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.

**Comment by gitbrent** [comment]
[Closing due to age]
