### ISSUE TITLE
Pie Charts don't show decimal percentage

### ISSUE THREAD

**Issue by Alexiz-Padilla** [gitbrent/PptxGenJS#593]
Hi

I want to show decimals on my pie charts, and I don't need integer numbers, I tried used the property 'dataLabelFormatCode' but it does not work.

Can help me please?

I would greatly appreciate it, thank you.

**Comment by gitbrent** [comment]
Can you post your code and demonstrate the result you're looking for in a PowerPoint screencap?

**Comment by Alexiz-Padilla** [comment]
This is mi file pie.js on this create a pie chart:
 `
const PptxGenJS = require('pptxgenjs');
const colors = require('./colors');
const unitLabels = require('./unitLabels');

const pptx = new PptxGenJS();

function addPie(slide, chart, position, size) {
  const { x, y } = position;
  const { data, unit } = chart;
  const { w, h } = size;
  const targets = data.map(data => data.name);
  let title = `${chart.title} (${targets})`;
  if (unit === 'index') title = `${chart.title} (${targets} indexed against Base Target)`;
  const options = {
    x,
    y,
    w,
    h,
    chartColors: colors,
    showLegend: true,
    legendPos: 'r',
    showTitle: true,
    title,
    titleFontSize: 10,
  };

  slide.addChart(pptx.charts.PIE, data, options);

  slide.addText(unitLabels[unit], { x: x + (w - 0.7), y: y + 0.18, w: 0.7, fontSize: 10, bold: true, align: 'right' });
}

module.exports = addPie;
`

Data I send : `
[ { name: 'All Adults',
    targetIndex: 0,
    labels:
     [ 'None/ Don\'t know/ Refused',
       'Sunday Night Football',
       'Auto racing' ],
    values: [ 50.61, 42.39, 14.29 ] } ]
`

Exporter: 
![image](https://user-images.githubusercontent.com/43591705/65368051-435c3700-dbf8-11e9-936e-205427b24a6b.png)


I need a pie with decimal percentage values don't need proximations, the correct way would be:

- None/ Don't know/Refused: 47.2%
- Sunday Night Football: 39.5%
- Auto racing: 13.3%

**Comment by gitbrent** [comment]
Hi @Alexiz-Padilla 

What `dataLabelFormatCode` value are you using?  That should be the key to achieving the formatting you're looking for.

**Comment by Alexiz-Padilla** [comment]
I'm using `dataLabelFormatCode: ###.###` and `dataLabelFormatCode:  000.00`
But it does not work.

**Comment by Alexiz-Padilla** [comment]
I found the solution in [support.office.com](https://support.office.com/en-us/article/Number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68) 

They say `Currency, percentages, and scientific notation: "To display numbers as a percentage of 100 — for example, to display .08 as 8% or 2.8 as 280% — include the percent sign (%) in the number format." `

Por lo tanto, la propiedad sería así:
```dataLabelFormatCode: '##.##%' ```
