### ISSUE TITLE
placeholder missing from TextOptions interface

### ISSUE THREAD

**Issue by colmben** [gitbrent/PptxGenJS#595]
I'm not sure if you intend to release current master but just FYI that TextOptions is missing the placeholder option. I note that placeholder is actually not documented in the addText page, though it is shown in the placeholders example on the Master Slide page. It looks like they have made it into 3.0 as you have placeholder back in the interface. 

I would just emphasise the importance of being able to associate objects with a master placeholder. Doing that allows users to apply a design template to the created presentation and get the relevant design elements applied to the placeholders. Given that you are never going to go down the road of using a template as a basis for creating the presentation, having placeholders is the next best thing.

**Comment by gitbrent** [comment]
Fixed in v3.0
