### ISSUE TITLE
Custom polygon generation

### ISSUE THREAD

**Issue by hirenj** [gitbrent/PptxGenJS#597]
To generate a custom polygon shape, it looks like a minimal XML chunk would look a bit like this:

```
<p:sp>
	<p:nvSpPr>
		<p:cNvPr id="SOMEIDNUMBER" name="OBJECTNAME"/>
		<p:cNvSpPr/>
		<p:nvPr/>
	</p:nvSpPr>
	<p:spPr>
		<a:xfrm>
			<!-- x and y position of shape -->
			<a:off x="2917861" y="585627"/>
			<!-- width and height of shape -->
			<a:ext cx="2732926" cy="1705510"/>
		</a:xfrm>
		<a:custGeom>
			<a:avLst/>
			<a:gdLst/>
			<a:ahLst/>
			<a:cxnLst/>
			<a:pathLst>
				<a:path>
					<a:moveTo>
						<a:pt x="904126" y="0"/>
					</a:moveTo>
					<a:lnTo>
						<a:pt x="2732926" y="657546"/>
					</a:lnTo>
					<a:lnTo>
						<a:pt x="1952090" y="1705510"/>
					</a:lnTo>
					<a:lnTo>
						<a:pt x="297950" y="1664413"/>
					</a:lnTo>
					<a:lnTo>
						<a:pt x="0" y="708917"/>
					</a:lnTo>
					<a:lnTo>
						<a:pt x="904126" y="0"/>
					</a:lnTo>
					<a:close/>
				</a:path>
			</a:pathLst>
		</a:custGeom>
		<a:solidFill>
		<a:srgbClr val="FF0000"/>
		</a:solidFill>
	</p:spPr>
</p:sp>
```

There's also `arcTo`,`cubicBezTo` and `quadBezTo`. It seems like it would be possible to convert an SVG path definition to this path definition (if a width/height was passed along too). This is just enough to get a shape displayed but is missing definitions for shape handles etc.

`a:off` and `a:ext` can be minimised (`cx` and `cy` for `a:ext` set to 1, and `x`/`y` set to 0 for `a:off`) but that means that the point positions need to be absolute, and the bounding box on selection of the object is off (which is an ok artefact to have I think).

**Comment by gitbrent** [comment]
Implemented vai https://github.com/gitbrent/PptxGenJS/pull/872
