### ISSUE TITLE
i have installed new package 2.6.0 giving error 

### ISSUE THREAD

**Issue by PriyankaNigotia6** [gitbrent/PptxGenJS#598]
error TS2345: Argument of type '{ x: number; y: number; w: number; color: string; colW: number[]; border: { pt: string; color: st...' is not assignable to parameter of type 'TableFormatting'.
  Object literal may only specify known properties, and 'colW' does not exist in type 'TableFormatting'.

**Comment by gitbrent** [comment]
[Closing due to age]
