### ISSUE TITLE
save and exit cause error

### ISSUE THREAD

**Issue by uoiszero** [gitbrent/PptxGenJS#60]
```
pptx.save('sample', filename=>{
    console.log(filename);
    process.exit(0);
})
```

There is no pptx saved.
Maybe use callback at wrong time?
Thanks.

> Nodejs@6.10.0

**Comment by gitbrent** [comment]
The `process.exit(0)` is the issue.  If this line is removed, the sample.pptx file is created.

While there is a callback in use, the OS itself and the Node background filestream are still in flight and hard-exiting the process is killing the file generation.

The PptxGenJS code is passing the callback to `fs.writeFile()` which fires the callback upon completion, so this is the extent of what can be coded.

**Comment by uoiszero** [comment]
Thank you.
