### ISSUE TITLE
[HOW TO] Is there any way to load a ppt and show it in browser?

### ISSUE THREAD

**Issue by vishnu-dev** [gitbrent/PptxGenJS#601]
Is there a feature to load a .ppt or .pptx in PptxGenJS and to display it in browser? If no, could point me in the right direction?

**Comment by gitbrent** [comment]
That's what Office Online (O365) does.  Transforming an XML-based presentation into a compatible web page is no small feat.

I'm unsure if there are any such tools for free.

Please let me know if you find anything.

**Comment by vishnu-dev** [comment]
I have been researching for 5 days now and I have found nothing. I know that Office Online does that, but I want just a viewer not an editor. PDF is also somewhat similar to ppt in terms of complexity. But why is the opensource community ignoring PPT? Why can't we have something like PDF.js?

The only open source library that displays presentation, not .ppt or pptx but odp was ViewerJS. Even this doesn't have proper documentation or customizable code.

**Comment by QastanFIT** [comment]
Still nothing found for this problem. Previewing private pptx files seems like a hard thing. Did you find something @vishnu-dev?
