### ISSUE TITLE
Assigning id to table rows/cells

### ISSUE THREAD

**Issue by s0110s** [gitbrent/PptxGenJS#602]
Hi team,

Is there a way to assign identifier to table rows or cells?

Thank you.

**Comment by gitbrent** [comment]
Can you provide an example?

**Comment by stephanielsx** [comment]
For instance the following:
```
<table id="egTable">
    <tr id="123">
      <td id="123001">Last Name</th>
      <td>First Name</th>
      <td>Description</th>
    </tr>
    <tr id="456"></tr>
    <tr id="789"></tr>
</table>

pptx.addSlidesForTable( 'egTable' );
```

I am basically trying to use external libraries to read the content of the exported pptx file and I would very much want to be able to retrieve the ids assigned to the table rows and cells.

**Comment by gitbrent** [comment]
I'm confused. The library does not generate HTML tables, nor does the PPTX file contain HTML tables.

**Comment by s0110s** [comment]
Hi, sorry for the confusion. Let me show you an example in another way.

I have a table with 3 rows that I want to add to a slide.
I want to be able to assign an unique id to each of the rows as shown below, such that the xml data of the exported pptx file withhold the id attribute.

```
rows.push([
    { text:'1st', options:{id:'first_row', color:'ff0000'} }
]);

rows.push([
    { text:'2nd', options:{id:'second_row', color:'00ff00'} }
]);

rows.push([
    { text:'3rd', options:{id:'third_row', color:'0000ff'} }
]);

slide.addTable( rows, { x:0.5, y:1.0, w:9.0, color:'363636' } );
```

**Comment by gitbrent** [comment]
I'm not sure an `id` property is part of the Open Office XML standard...

Either way, this is highly specific to your use case so we wouldn't include this functionality as it's outside normal OOXML usage.

I'd suggest you fork the library and add a option to `addTable` to accept the `id` and then add a line of code to output it in the XML.
