### ISSUE TITLE
[Chart] LegendPos Suggestion

### ISSUE THREAD

**Issue by kwak914** [gitbrent/PptxGenJS#603]
Can you add more option such as 'bl', 'br' or 'tr' to the LegendPos attribute?

I found some code in pptgen.js code..
`if (['b', 'l', 'r', 't', 'tr'].indexOf(options.legendPos || '') < 0)
        options.legendPos = 'r';`

If it's true, ['b', 'l', 'r', 't', tr'] is only option for now...

**Comment by gitbrent** [comment]
Hi @kwak914 

Those 5 options are the only available options per MS spec
<img width="851" alt="Screen Shot 2019-10-07 at 21 48 37" src="https://user-images.githubusercontent.com/7218970/66363594-5d15b200-e94c-11e9-8bf3-d55d89f229d0.png">
