### ISSUE TITLE
addImage cover not preserving aspect ratio

### ISSUE THREAD

**Issue by argonaut76** [gitbrent/PptxGenJS#607]
I have an image that is 1920x1280 pixels. According to the docs, the following code should display it at 11x8.5 inches, cropped and centered:

```
slide.addImage({
    path: './images/binare-welt-001.jpg', 
    x:0, y:0, 
    w:11, h:8.5,
    sizing: { type:'cover', w:11, h:8.5 }
  });
```

However, the image shows up at the right size, but with the wrong aspect ratio (it's squished horizontally), so the crop and center isn't working.

**Comment by ReimaFrgos** [comment]
I'd expect that given those dimensions
1920 / 11 = 174.5454
1280 / 8.5 = 150.5882

To keep the aspect ratio you'd be looking at something like w:11, h:7.33

**Comment by gitbrent** [comment]
[Closing due to age]
