### ISSUE TITLE
Auto Paging does not include master template on additional slides

### ISSUE THREAD

**Issue by tb23911** [gitbrent/PptxGenJS#61]
When using gObjPptxMasters and auto paging with tables the new slides do not have the objects defined in the inMasters array of the original slide.

To give further context, when creating a new slide as follows:

```javascript
var slide = pptx.addNewSlide( pptx.masters.MASTER_SLIDE );
slide.addTable( arrRows, 
{ 
	slideMargin:  [ 1.2, 0.0, 1.18, 0.0 ], 
	x:0.5, 
	y:1.2, 
	colW:[5.0,0.55], 
	font_size:9, 
	margin:1, 
	border:{pt:'0.75', color:'E00000'}
	} 
);
```

If the number of rows exceed the available height and a new slide is created to hold the remaining rows the new slide does not include the objects defined in the MASTER_SLIDE.

**Comment by gitbrent** [comment]
Hi @tb23911 ,

Thanks for reporting this issue!

Slide masters and inline options are now used in subsequent slides.

The output looks weird though due to Issue #64 (over-paging when using some options) which I will be fixing next.
