### ISSUE TITLE
Generated PNG files can include SVG content.

### ISSUE THREAD

**Issue by pandersen-uncharted** [gitbrent/PptxGenJS#611]
This is a heisenbug for which I might have a fix.

First, the problem. I'm generating a slide with two base64 encoded SVG images. When I save the slide, very occasionally, one of the images will not display in PowerPoint. When I looked into the generated pptx file I found that the problem was that one of the PNG files incorrectly had the original SVG content in it.

Digging through the code I found that the problem starts in `addImageDefinition()` in STEP 4. Here a "rel" object is created with _isSvgPng_ set to **true** and the _data_ set to the SVG base64 data.

Later, in `callbackImgToDataURLDone()` (called after an SVG has been converted to a PNG) the code in `funcCallback` attempts to assign the PNG data to the data field of the appropriate "rel". It counts if any "rel"s have no data and if the count is zero, then `callbackImgToDataURLDone()` calls `doExportPresentation()`. Because `addImageDefinition()` has added the SVG data to the "rel"s the test for absent data fails and `doExportPresentation()` winds up being called each time a PNG is generated, in my case twice. It's just random at this point which zip file I get out of `doExportPresentation()`, whether I get one with incompletely resolved PNG images (that therefore have their data set to the original SVG data) or not.

My "fix" for this was to change:
```javascript
if ( !rel.data ) intEmpty++;
```
to
```javascript
if ( !rel.data || (rel.extn == 'png' && rel.data.indexOf("image/svg+xml") > -1 )) intEmpty++;
```
in `callbackImgToDataURLDone().funcCallback()`. This now properly detects unresolved PNG images and avoids calling `doExportPresentation()` until all PNG images are resolved.

**Comment by gitbrent** [comment]
Hi @pandersen-uncharted 

Please test your code using the [3.0-branch](https://github.com/gitbrent/PptxGenJS/tree/version-3.0).

Nearly all of the code you're referring to has been rewritten.

**Comment by pandersen-uncharted** [comment]
Is there documentation describing the differences between 2.x and 3.0? For example I'm finding `pptx.setLayout()` is undefined.

**Comment by gitbrent** [comment]
[Closing due to age]
