### ISSUE TITLE
online video on node.

### ISSUE THREAD

**Issue by JeffSkinn** [gitbrent/PptxGenJS#613]
When choosing add media, type: "online" link is not an option that can be set only onlineVideoLink. The program then checks if link is empty, and then doesn't continue if it is.

Change media option from onlineVideoLink to link or change link to onlineVideoOption in the addMedia function

**Comment by gitbrent** [comment]
Hi @JeffSkinn 

In the upcoming 3.0 release, the syntax is:

```javascript
slide1.addMedia({ x:9.4, y:4.0, w:3.00, h:2.25, type:'online', link:'https://www.youtube.com/embed/Dph6ynRVyUc' });
```

**Comment by gitbrent** [comment]
[Closing due to age]
