### ISSUE TITLE
Wrong coordinate value

### ISSUE THREAD

**Issue by dsmoter** [gitbrent/PptxGenJS#615]
Hi,

I try to add simple text component to a slide and the position on slide is different than options passed to method.

```
this.slide.addText("44%", {
  "x": 1.8437000000000001,
  "y": 2.8222,
  "w": 1.545,
  "align": "right",
  "fontSize": 51,
  "h": null,
  "color": "000000",
  "bodyProp": {
    "autoFit": false,
    "anchor": "ctr",
    "rot": null,
    "vert": null
  },
  "lineSpacing": null,
  "cx": 1.545,
  "lineIdx": 0
}
```

As you can see I set `y` coordinate to 2.8222 but on slide that element has `y` coordinate equal 2,52 inch.

Why?

**Comment by gitbrent** [comment]
Hi @dsmoter 

This is working correctly in the upcoming v3.0 branch.

<img width="1339" alt="Screen Shot 2019-10-30 at 23 49 19" src="https://user-images.githubusercontent.com/7218970/67919853-13497180-fb70-11e9-99a7-22ceac05dc0e.png">
