### ISSUE TITLE
⭐️ Need QA on upcoming TypeScript-based 3.0 version  ⭐️

### ISSUE THREAD

**Issue by gitbrent** [gitbrent/PptxGenJS#616]
Hi All,

Thanks for using this library!

Version 3.0 is coming soon and has been re-written from the ground up using TypeScript.

### HELP US TEST
Please download the [Version-3.0](https://github.com/gitbrent/PptxGenJS/tree/version-3.0) code and test it out if you can. 
- check the `./demos` folder for browser, Node and React demos, 
- or grab the latest builds of the min, es, or cjs versions from `./dist`

### WHATS NEW
- jQuery is gone! Now the only dependency is JSZip
- Brand-new TypeScript/ES6 Class codebase eliminated dozens of bugs and greatly increased stability
- Code is logically separated into 10+ files, making pull requests and maintenance easier
- Completely rewritten Table AutoPaging and HTML-to-PowerPoint methods - faster and much more accurate
- Save/Export:
- Promise-based export methods - no more callbacks
- Two new methods (Write and WriteFile) will replace `save()`
- Supports all types of output methods: ArrayBuffer, Blob, etc.

#### Added
- Ability to specify numbered list format [\#452](https://github.com/gitbrent/PptxGenJS/issue/452) ([mayvazyan](https://github.com/mayvazyan))
- New cat/val axis options: majorTickMark/minorTickMark [\#473](https://github.com/gitbrent/PptxGenJS/pull/473) ([RokasDie](https://github.com/RokasDie))
- Ability to set start number "startAt" for a bullet list of type numbered [\#554](https://github.com/gitbrent/PptxGenJS/issue/554) [\#555](https://github.com/gitbrent/PptxGenJS/pull/555) ([bj-mitchell](https://github.com/bj-mitchell))
#### Changed
- Fixed: Set proper MIME type for PPTX presentation [\#471](https://github.com/gitbrent/PptxGenJS/issue/471) ([StefanBrand](https://github.com/StefanBrand))
- Fixed: SVG images used to be generated by Node [\#515](https://github.com/gitbrent/PptxGenJS/issue/515) ([michaelcbrook](https://github.com/michaelcbrook))
- Fixed: SVG support has several issues [\#528](https://github.com/gitbrent/PptxGenJS/pull/528) ([RicardoNiepel](https://github.com/RicardoNiepel))
- Fixed: Downloading PPT in iOS using Safari does not work. File named as UNKNOWN. [\#540](https://github.com/gitbrent/PptxGenJS/issue/540) ([mustafagentrit](https://github.com/mustafagentrit))
- Fixed: Tables not being displayed after update [\#559](https://github.com/gitbrent/PptxGenJS/issue/559) ([emartz404](https://github.com/emartz404))
- Fixed: Exporting images corrupting file. [\#578](https://github.com/gitbrent/PptxGenJS/issue/578) ([joeberth](https://github.com/joeberth))
- Fixed: Multiple files getting downloaded if multiple base64 images are added. [\#581](https://github.com/gitbrent/PptxGenJS/issue/581) ([akshaymagapu](https://github.com/akshaymagapu))
- Fixed: Links in tables won't work on tables generated with autoPage [\#583](https://github.com/gitbrent/PptxGenJS/issue/583) ([githuis](https://github.com/githuis))
#### Removed
- Removed: jQuery is no longer required (!)

**Comment by gitbrent** [comment]
@ReimaFrgos - have you tried v3.0 yet?

**Comment by NateRadebaugh** [comment]
Is there a migration guide for this? On first try, I'm seeing `pttx.setLayout is not a function` error when running.

**Comment by gitbrent** [comment]
@NateRadebaugh 

Thanks for the feedback. You're right, a migration guide should be the very next thing. Other than the working demos included, there are no updated API docs...

I'll get started on a wiki page.

**Comment by ReimaFrgos** [comment]
@gitbrent finally got some time to play around with v 3.0 today. This is what I've experienced so far.

The obvious, as per Nate has to update the existing .setLayout and .save

**Question:** Now that pptx.layout is no longer a function, is it possible to user define specific layouts? One of my use cases is designed to be on US Letter / A4 paper size. This is a standard option in PPTX for for me, it may be as simple as the full list of default layouts being made available.

**Issue:** Line Chart is throwing an error when using `shadow:'none'`

**Issue:** `breakLine: false` no longer seems to work. Couldn't get it working on the demo generations either.

**Breaking Change?** for text boxes `align: 'middle'` no longer works and must use `align: 'center'`

**Breaking Change?** Previously you could specific a single value for colW in a table and all columns would be set to the same width. Any of my tables not passing in a full array with a value for each column now produce as a super skinny very tall table.


Some other problems I haven't been able to dig deep enough into yet:

1. My PPTX is generating needing repair every time. There's quite a few slides in the deck, so I need to go through and start disabling slides still so I can work out what specifically is triggering this.
2. I have two random base64 encoded images that are not displaying. Every other image using the same code seems to work fine without any other modification.

**Comment by ReimaFrgos** [comment]
@gitbrent got through some additional testing and tracked down where the last of my migration issues were coming from:
1. When you have charts and images on the same slide, it is duplicating relationship ID's. Sample output. 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId1" Target="/ppt/charts/chart1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart"/>
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image-2-1.png"/>
    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image-2-2.png"/>
    <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout8.xml"/>
    <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide" Target="../notesSlides/notesSlide2.xml"/>
</Relationships>
```
This appears to be the reason some of my images aren't showing, is that it is trying to embed the chart as an image.
2. My "repair file" alerts were being triggered for 2 reasons. The issue above with slides and charts on the same slide. The second is the breaking change I mentioned above with `colW`.m Either needed to remove this for each table, or convert it to an array.

Do you want me to raise separate tickets for each of the 3 outstanding issues (and breaking changes?)

**Comment by gitbrent** [comment]
@ReimaFrgos - thanks for the thorough testing! My QA skills are not my defining feature. :)

I'll work through what you've details above, don't worry about creating issues.

**Comment by gitbrent** [comment]
Hi @ReimaFrgos 

The only remaining issue you raised is the chart+image mangles rId's - it may've been fixed by another update along the way because i'm not able to reproduce it with the newest build of `version-3.0`:

<img width="1329" alt="Screen Shot 2019-12-24 at 17 47 19" src="https://user-images.githubusercontent.com/7218970/71426830-d7b1bc00-2675-11ea-951f-0e3c7ac2b49c.png">

**Comment by gitbrent** [comment]
Version 3.0.0 is finally released!
