### ISSUE TITLE
Uncaught TypeError: JSZip is not a constructor

### ISSUE THREAD

**Issue by I072742** [gitbrent/PptxGenJS#617]
Hi PptxGenJS Team,

          Good Morning. I am getting "Uncaught TypeError: JSZip is not a constructor" error, while calling "pptx.save('Sample Presentation');" 
           Can you please let me know, how to solve this? I have downloaded the files, added manually in the project folder and included their path in index.html file. I need to include these paths anywhere else?

Thanks,
Geetha Rani.

**Comment by gitbrent** [comment]
Hi @I072742 

Check the `PptxGenJS/demo` folder for working examples.

**Comment by I072742** [comment]
Hi Gitbrent,

         same issue. actually module is coming as undefined.. does anybody uses without node.js ..? I mean adding manually? I have added following lines in index.html..


<script src="ui/control/PptxGenJS/libs/jszip.min.js"></script>
<script src="ui/control/PptxGenJS/libs/promise.min.js"></script>
<script src="ui/control/PptxGenJS/libs/jquery.min.js"></script>
<script src="ui/control/PptxGenJS/dist/pptxgen.min.js"></script>

then loaded trying to execute the following code..

var pptx = new PptxGenJS(this);
		var slide = pptx.addNewSlide();
		slide.addText('Hello World', {x:1.5, y:1.5, fontSize:18, color:'363636'});
		pptx.save('Sample Presentation');

it is failing at pptx.save saying that "Uncaught TypeError: JSZip is not a constructor "..

can you please reply. is anything wrong here?

Thanks,
Geetha Rani.

**Comment by gitbrent** [comment]
Hi @I072742 

Your app must not be loading jszip correctly.  I'm not sure what else to tell you.  Please refer to the demo.

**Comment by gitbrent** [comment]
[Closing due to age]
