### ISSUE TITLE
Function to append slides to the existing PPT

### ISSUE THREAD

**Issue by RaghavendhraK** [gitbrent/PptxGenJS#619]
Hi,

Do we have a way so that to generate the large PPT without memory peaking?

In our project, we are creating PPT with 700 slides, in whcih has each slide has an image of 2M. i.e., it uses the memory of 1.4GB. On PPT save, memory goes to peak and the **Nodejs app** is getting killed.

Thus, if we have the support to append the slides to the existing PPT, then we can create the 10 slides at a time and can keep on appending the 10 slides to the existing file. i.e., we can avoid the memory peak and the app kill.

Pleaes do provide any suggestions/workaround to handle this scenario

Thanks,
Raghu

**Comment by RaghavendhraK** [comment]
Hi,

As a workaround for this, we did managed to generate the ppt by usiong stream by modifying at 2 places.  Could you plz spare a moment to check with the below pull request and make a small changes in the main branch, so that we can export the PPT without mem leak.

https://github.com/gitbrent/PptxGenJS/pull/623

Thanks,
Raghu

**Comment by gitbrent** [comment]
Version 3.0 is imminent and the code the PR touches has already been completely rewritten.

Try using the `version-3.0` branch and see how it works for this case.

**Comment by RaghavendhraK** [comment]
Hi,

I just had a look on the 3.0 branch, and it seems that, there also we are still using Buffer for images. That's why the memory leak. We do need to change it to stream.

Also while generating the Zip we need to pass the stream option, so that memory used will be minimal.

Note: Both of them are for Backend Nodejs Server only.

Thanks,
Raghu

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by fei0219** [comment]
Hey @RaghavendhraK  

Have you found a solution to this problem ? i'm currently stuck on this when I use a 300mb asset file or total amount of assets, the container memory goes nearly 2g and that is only one user.

**Comment by RaghavendhraK** [comment]
Hi @fei0219,

We have done some small changes according to our need. These are the changes https://github.com/gitbrent/PptxGenJS/pull/623. 
This is forked repository https://github.com/RaghavendhraK/PptxGenJS.
