### ISSUE TITLE
Table Header and Auto Paging

### ISSUE THREAD

**Issue by tb23911** [gitbrent/PptxGenJS#62]
This is more of a question than an issue:
I see that there is a section that handles table header rows but this doesn't seem to be documented in the readme. Looking at the code it seems that the way to do this is add addHeaderToEach: true and arrObjTabHeadRows: [row + opts] to the addTable call, is this correct?

**Comment by gitbrent** [comment]
Hi @tb23911 

Thanks for opening an Issue - i totally forgot to add this option to the README!

I've added it now and yes, when set to true it causes the table headers to repeat across each Slide.  The demos under `examples` had this as an option but it was not labeled as such, so i've added that now.
