### ISSUE TITLE
Unable to Add Table based on Text count

### ISSUE THREAD

**Issue by Ashok-SK** [gitbrent/PptxGenJS#626]
Kindly find the two files.
1. My Requirement
2.I have done this with PPT genJs.

Hi Team,
I need to set the table alignment based on the text added to the ppt. Could you please help me to come out from this...

Regards
Ashok

[Barbri - Affirmative Bank - PPT Output.pptx](https://github.com/gitbrent/PptxGenJS/files/3976715/Barbri.-.Affirmative.Bank.-.PPT.Output.pptx)
[Item Bank - 2019-12-18T104132.029.pptx](https://github.com/gitbrent/PptxGenJS/files/3976716/Item.Bank.-.2019-12-18T104132.029.pptx)

**Comment by 13ecg37** [comment]
`
    var i,j,k,m,n,a,b,c,d,e ;
    var z=data2.length;
    console.log("odata",z);

    for (i=1,j=0,k=0,m=0,n=0,a=0,b=0,c=0,d=0,e=0; 
        i<=z,k<data2.length,m<data3.length,n<itemBankQuestion.length,
        a<data5.length,b<data6.length,c<data7.length,d<data8.length,e<data9.length;
        i++,j++,k++,m++,n++,a++,b++,c++,d++,e++){
        //var slide = pptx.addNewSlide('MASTER_SLIDE');
       
        
      

      var question=itemBankQuestion[n];
      console.log("Question",question);
      var words = question.split(" ");
      console.log("Q-splice",words);
      var loopCount = 1;
      var numOfSentenceInPage = 215;
      if(words.length > numOfSentenceInPage)
        var loopCount = Math.ceil(words.length / numOfSentenceInPage);
        console.log("LoopCount",loopCount);

        var start = 0;
        var slideNum;
        var tabOpts = {x:0.2,y:4.5,h:1, w:'100%',lineWeight:0.5,align:'l',autoPage:true,fontSize:14,fontFace:'open sans', color:'363636',bkgd:'FFFFFF',colW:[1,8] };
        for( slideNum=1;slideNum<=loopCount;slideNum ++){

            //slide.addImage({path:Logo,x:0, y:0, align:'c', w:1.2, h:0.8});
            var sliceText = words.slice(start,start + numOfSentenceInPage).join(" ") + "\n";
            var sliceText1 =sliceText.concat("\nChoose your answer");
            var sliceText2=sliceText1


             
        var rows = [
          [{ text:'A', options:{ valign:'m', align:'c',fill:'FFFFFF', fontFace:'open sans',fontSize:14  } },
          { text:data5[a], options:{ valign:'m', align:'l',fill:'FFFFFF', fontFace:'open sans',fontSize:14 } }],

          [{ text:'B', options:{ valign:'m', align:'c',fill:'FFFFFF', fontFace:'open sans' , fontSize:14 } },
          { text:data6[b], options:{ valign:'m', align:'l', fill:'FFFFFF',fontFace:'open sans',fontSize:14 } }],

          [{ text:'C', options:{ valign:'m', align:'c',fill:'FFFFFF', fontFace:'open sans', fontSize:14 } },
          { text:data7[c], options:{ valign:'m', align:'l',fill:'FFFFFF', fontFace:'open sans',fontSize:14 } }],

          [{ text:'D', options:{ valign:'m', align:'c',fill:'FFFFFF', fontFace:'open sans',fontSize:14   } },
          { text:data8[d], options:{ valign:'m', align:'l',fill:'FFFFFF', fontFace:'open sans',fontSize:14 } }],

         /*  [{ text:'E', options:{ valign:'m', align:'c',fill:'FFFFFF', fontFace:'open sans',fontSize:14   } },
          { text:data9[e], options:{ valign:'m', align:'l',fill:'FFFFFF', fontFace:'open sans',fontSize:14 } }], */
    
      ];
 /*      <table id="tableId" style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td> 
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
  </tr>
</table> */

            console.log('sliceText',sliceText);
            var slide = pptx.addNewSlide('MASTER_SLIDE');
           // var slide1 = pptx.addNewSlide('MASTER_SLIDE');
            slide.addText(data2[k].concat(' ','/ ', data3[m],' ','#Q',i) , { x:-0.2, y:0, w:'100%', h:0.5, align:'r',fontFace:'open sans', color:'000000', bkgd:'ffefd5', fontSize:14 });
            slide.addText( sliceText2,/* slide.addTable(rows,tabOpts) */ { x:0.2,y:0.7,w:'97%',h:2,autoFit:true,valign:'top',fontSize:14,fontFace:'open sans', color:'363636'});
            slide.addText("Cont",{x:'88%', y:'95%',fontSize:10,fontFace:'open sans', });
            //start = start + numOfSentenceInPage;
           // slide.addTable( rows, { x:0.5, y:1.0, w:9.0, color:'363636' } );
            //slide.addTable( rows, { x:0.5, y:1.0, w:9.0, color:'363636' } );
          
            //slide1.addText(data2[k].concat(' ','/ ', data3[m],' ','#Q',i) , { x:-0.2, y:0, w:'100%', h:0.5, align:'r',fontFace:'open sans', color:'000000', bkgd:'ffefd5', fontSize:14 });
            //slide1.addText('Choose your answer:',  {x:0.2, y:0.5, w:'100%', h:0.9, align:'l', color:'000000', bkgd:'ffefd5', fontSize:16 });
             slide.addTable( rows, tabOpts );
            //slide1.addText("Hey",{x:1,y:5});
           // pptx.addSlidesForTable('tableId',{  addHeaderToEach:true,master:'MASTER_SLIDE',x:0.4, y:3.5});
        }
`

**Comment by gitbrent** [comment]
I'm not sure what you're asking for, but there is plenty of working examples under `./examples` including use of the "addSlidesForTable" feature.

**Comment by 13ecg37** [comment]
Hi Gitbrent,

Example : https://gitbrent.github.io/PptxGenJS/demo
Could you please tell us where to get the source codes for the above link examples...?

Thanks
Ashok

**Comment by gitbrent** [comment]
Sure.

It's the [`examples/pptxgenjs-demo.js`](https://github.com/gitbrent/PptxGenJS/blob/master/examples/pptxgenjs-demo.js) file.

**Comment by gitbrent** [comment]
[Closing due to age]
