### ISSUE TITLE
Return the height of any element 

### ISSUE THREAD

**Issue by Morozov90** [gitbrent/PptxGenJS#628]
Hi,
Thanks for the great library, it really works pretty well!
Can you return the height of any element ? This will be very helpful if we have for example table and text that should be placed under table. ( table can be different sizes) 
For now, I can't find any solution and I need to work with source code to get such info.

Do you have any ideas or did you try it before?

Thanks in advance.

**Comment by gitbrent** [comment]
Hi @Morozov90 

Thanks for the feedback.  

Theoretically, it's possible to determine an approximation, but PowerPoint is the ultimate determiner of the table size.  I'm not sure of the level of demand for this feature, so you may end up forking it for this feature. 

Check out the `version-3.0` branch - the new table generation code for auto-paging determines the height as it executes. You could pick up the size at the end of the method.

**Comment by gitbrent** [comment]
[Closing due to age]

**Comment by GauravAshara** [comment]
I have same thing to do with PPTXGenJs. I have two tables with dynamic number rows base on HTML tables. So I want to add table one after another. For that I need the first table height, So the second table will append with  Y(position) =  First Table Y + First Table Height.

Thaks In Advance
