### ISSUE TITLE
Unable to use Text and a Table in a single slide with PptxGenJs

### ISSUE THREAD

**Issue by thamazingone** [gitbrent/PptxGenJS#629]
Hello All,

I'm trying to generate a PPT using a custom text as Heading and a table from a HTML Page with PptxGenJS. However, I unable to add both of them on a single page with the below code. 

var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addText('This is Table Data');
pptx.addSlidesForTable('Table_Data');
pptx.save('Sample');

Consider I have below table with ID as 'Table_Data' 
Row	Last Name	First Name	Description
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst

I want the output as :- 

**This is the Table Data
Row	Last Name	First Name	Description
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst
1	GG	Ankit	L1 Application Analyst**

But with the code written, I get the table on one slide and the text on the other. Please help me add both of them in a single page.

**Comment by gitbrent** [comment]
Hi @thamazingone 

Check `./examples` or the [online demo](https://gitbrent.github.io/PptxGenJS/demo/) for several examples of table generation with a repeating text header.
