### ISSUE TITLE
Can we show the ppt created by this plugin on a html page

### ISSUE THREAD

**Issue by akhihiko** [gitbrent/PptxGenJS#63]

**Comment by gitbrent** [comment]
Hi @akhihiko 

I'd willing to bet there's some library that will display PowerPoint presentations in a webpage, but I'm not familiar with one off-hand.  As for PptxGenJS, it only creates PPTs.

**Comment by akhihiko** [comment]
Hi sir,

Thank you for replying. Instead of pushing the file to the browser using the "save" method. Is there a way you can save it on the server. Mainly using something like php. There is way to display the PPT if I can get it stored on the server.
