### ISSUE TITLE
Reuse image to reduce file size

### ISSUE THREAD

**Issue by kevinresol** [gitbrent/PptxGenJS#634]
When adding the same image multiple times, file size will grow accordingly. Is it possible to cache identical images?

**Comment by JohnnyKB** [comment]
How likely is this to be addressed in future versions?

**Comment by gitbrent** [comment]
There is no pull submitted and it's not high on my priority list at the present time.

**Comment by davolcu** [comment]
Any updates on this issue?

**Comment by sonvt-seta** [comment]
Any update on this. I have an issue with adding duplicate images. 
When I add the same image for every slice (For images with  1920x1024), the file size is large (6.7MB). But then, I open it with Microsoft PowerPoint and save it, and boom, the size reduces dramatically (720).

**Comment by gitbrent** [comment]
This is now done with Pull #1024
