### ISSUE TITLE
"Typescript definitions included"...

### ISSUE THREAD

**Issue by crazyx13th** [gitbrent/PptxGenJS#645]
Hi there,

thx for V3! But where are the TS Definitions @3.0.1 / npm?

![grafik](https://user-images.githubusercontent.com/8912561/72154090-ff13c300-33af-11ea-8980-0b54cd7fcfec.png)

maybe you should use a '.npmignore'? (npm-package too big?)

Greetings
crazyx13th

**Comment by crazyx13th** [comment]
ahh, ok, you had to add the folder `types` to `files` inside the `package.json`

**Comment by gitbrent** [comment]
@crazyx13th - yes, improper package.json configuration is to blame.

It'll be released with 3.1.0 soon.
