### ISSUE TITLE
Typescript Definition wrong

### ISSUE THREAD

**Issue by crazyx13th** [gitbrent/PptxGenJS#646]
Hi there,

`IObjectOptions` have `margin: Margin` but `ITextOpts` have `margin: number`

![grafik](https://user-images.githubusercontent.com/8912561/72155693-f2916980-33b3-11ea-99b9-a04ba01e3c9f.png)

thx!

Greetings
crazyx13th

**Comment by gitbrent** [comment]
Thanks @crazyx13th 

Fixed with Pull #647
