### ISSUE TITLE
error ' Object doesn't support property or method 'startsWith'' in IE 11

### ISSUE THREAD

**Issue by YakQin** [gitbrent/PptxGenJS#648]
Hello,

'startsWith' is ES 6 method but it is fund in the pptxgen.min.js file, due to this it is not working with IE 11, though I included promise.min.js

**Comment by gitbrent** [comment]
Thanks for reporting this @YakQin !

I've checked in a fix and will review it on an IE11 equipped PC tomorrow to look for further issues.

**Comment by YakQin** [comment]
Thanks a lot for the quick response. There are a lot of ES6  syntax  like 'endsWith', 'entries' etc. At the moment I will use the old versions.
Looking forward to the fix for IE 11 (though we don't like it)

**Comment by YakQin** [comment]
Thanks a lot, now it worked in IE 11, you might also need to update the CDN file : https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@master/dist/pptxgen.bundle.js

**Comment by gitbrent** [comment]
Thanks for the verification.

I'm getting the demo refs and other items ready for 3.1 - appreciate the reminder :)
