### ISSUE TITLE
Office2007's ppts ruins with \n

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#65]
@gitbrent, can you return the Office 2007's support, as it was before the "\n update". Almost all my ppts were ruined, where there is a lines with '\n' symbol :( 
![image](https://cloud.githubusercontent.com/assets/9961535/24151466/eb380306-0e59-11e7-99e8-eb1ae76955bb.png)
This method also ruins 2007 ppts
![image](https://cloud.githubusercontent.com/assets/9961535/24151627/5b08c350-0e5a-11e7-959c-1d18b71984ff.png)

**Comment by gitbrent** [comment]
Hi @itskun 

Yikes. If any recent changes impacted the output in PPT 2007, it was not intentional.  

So you're saying having "\n" characters in the text output causes multi slides to be created?

**Comment by itskun** [comment]
No, this cause error when opening and all slides with \n or few text lines displayed as the default slide
![image](https://cloud.githubusercontent.com/assets/9961535/24170820/24d4c1ba-0e93-11e7-938a-4d0aaaa77135.png)

`var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
// This works
	slide.addText('1st string 2nd String', { x: 1.0, y: 1.0, align: 'c' });
// Either of this makes slide crashed in power point 2007
	slide.addText('1st string\n 2nd String', { x: 1.0, y: 1.0, align: 'c' });
	slide.addText(
			[
				{ text:'1st string ', options:{  align:'c', breakLine:true } },
				{ text:'2nd String', options:{ align:'c' } }
			],
			{ x:0.5, y:0.5 }
		);
pptx.save('test');`

In power point 2010 looking good, but I need only 2007 :(
![image](https://cloud.githubusercontent.com/assets/9961535/24171091/1ebe33c8-0e94-11e7-8790-bee24afaa303.png)

**Comment by gitbrent** [comment]
Hi @itskun ,

How does using \r work?

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide(); 
slide.addText('1st string\r2nd String', { x: 1.0, y: 1.0, align: 'c' });
pptx.save('test');
```

**Comment by itskun** [comment]
\r works good! Changed all \n to \r. Thank you!
