### ISSUE TITLE
addChart and addImage in the same slide cause an error when trying to open the downloaded ppt

### ISSUE THREAD

**Issue by JuliaSheleva** [gitbrent/PptxGenJS#655]
Hello!

I have trying create a slide with both image and chart, but it cause an error  when trying to open the downloaded ppt. 
Could you help me, please?

PowerPoint version 2016
PptxGenJS version 3.0.1

Code sample is below:
 
```
const pptx = new PptxGenJS(); 
const slide = pptx.addSlide();

slide.addImage({ path:'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', x:4, y:1, w:6, h:4 });
const dataChartRadar = [
  {
    name  : 'Region 1',
    labels: ['May', 'June', 'July', 'August', 'September'],
    values: [26, 53, 100, 75, 41]
   }
];
slide.addChart( pptx.charts.RADAR, dataChartRadar, { x:0.5, y:0.6, w:4.0, h:2, radarStyle:'standard' } );
pptx.writeFile("example");
```

This is what is displayed when open ppt and what is on the slide:

<img width="435" alt="Screenshot 2020-01-23 at 09 25 03" src="https://user-images.githubusercontent.com/45160514/72962274-f619ed00-3dc4-11ea-93d7-1c4cd3ecc7ae.png">
<img width="1119" alt="Screenshot 2020-01-23 at 09 33 48" src="https://user-images.githubusercontent.com/45160514/72962276-f619ed00-3dc4-11ea-8c0d-af8c62372638.png">

Thank you in advance!

**Comment by gitbrent** [comment]
@JuliaSheleva - thanks for reporting this and for the clear details.

Issue is now resolved via new method to return relID on demand to all library methods insuring consistency in ID generation.

<img width="784" alt="Screen Shot 2020-01-29 at 21 56 22" src="https://user-images.githubusercontent.com/7218970/73420905-c0579580-42e9-11ea-9353-5eade008a1c4.png">
