### ISSUE TITLE
pptx.shapes not recognised by Typescript

### ISSUE THREAD

**Issue by luism-s** [gitbrent/PptxGenJS#656]
Hello

I'm trying to add shapes in a project with typescript, but the entity .shapes in pptx is not recognised.
This simple code
```
const pptSlide = pptx.addSlide(slide.title);
pptSlide.addShape(pptx.shapes.RECTANGLE, {});
```
results in:
```
any
Property 'shapes' does not exist on type 'PptxGenJS'.ts(2339)
```

I see the there's a collection of shapes (PowerPointShapes), but maybe this collection is not included in the types declaration?

**Comment by gitbrent** [comment]
@luism-s thanks for reporting this.

Neither "shapes" nor "charts" were being exported correctly.

This has now been fixed and will be out soon.

**Comment by abhinavek** [comment]
I am still facing this issue in version 3.12.0. Below are the error i am getting. i am using **angular version 8.2**

`847  export type Coord = number | `${number}%`
`
` error TS2339: Property 'shapes' does not exist on type 'PptxGenJS'.
` 
` error TS2559: Type 'string' has no properties in common with type 'ShapeLineProps'.`
