### ISSUE TITLE
Feature?? : JS-generated Hyperlinks that point to PPT Slides

### ISSUE THREAD

**Issue by njolee** [gitbrent/PptxGenJS#657]
Hi Brent,

The page at the link below shows how to (manually) insert a hyperlink into a slide that will transport the user to another slide in the same presentation

https://support.office.com/en-us/article/link-to-another-slide-in-the-same-presentation-7eb3f922-d3d5-4090-9892-76d8132b5cac

Does PptxGenJS provide a way to do generate/insert these kinds of hyperlinks (programmatically) into slides from Javascript?

Thanks,

Jabari

**Comment by gitbrent** [comment]
Yes, linking to a slide is supported.

[Docs/Sample Code](https://gitbrent.github.io/PptxGenJS/docs/api-text.html#text-examples)

```javascript
// EX: Hyperlink: Slide in Presentation
slide.addText(
    [{
        text: 'Slide #2',
        options: { hyperlink:{ slide:'2', tooltip:'Go to Summary Slide' } }
    }],
    { x:1.0, y:2.5, w:5, h:1 }
);
```

**Comment by njolee** [comment]
Very cool, I like it! Thanks so much Brent!

Have a good weekend!!

Jabari
