### ISSUE TITLE
addSlidesForTable does not recreate bullets

### ISSUE THREAD

**Issue by orpitadutta** [gitbrent/PptxGenJS#66]
<script type="text/javascript">
        function fnppt() {
           
            var pptx = new PptxGenJS();
            var tabOpts2 = { x: 0.5, y: 2.0, w: 9.0, font_size: 10 };
          
            pptx.addSlidesForTable('mydiv', tabOpts2)
            pptx.save();
        }

    </script>

<table id="mydiv">
        <tr>
            <td>
                <ul>
                    <li><b>Test for Bold</b></li>
                    <li>
                        Test:
                        <ul>
                            <li>Test</li>
                            <li>Test</li>
                            <li>Test</li>
                            <li>Test</li>
                        </ul>
                    </li>
                    <li>proposal</li>
                    <li>Reasons<br /></li>
                </ul>
            </td>
        </tr>

    </table>

<input type="button" value="Export to PPTX" onclick="fnppt()">

**Comment by yuz302** [comment]
Any updates on this one? I want to add bullet lists into a table cell. I added unordered list to <td> </td> but it doesn't seems to understand it as bullet lists.

**Comment by samirwarsi** [comment]
I found a workaround for this.

create table cell content something like this:

```
<table>
   <tr>
     <td>&bull;</td>
     <td>Test </td>
   </tr>
<table>
```

<table>
<tr>
<td>&bull;</td>
<td>Test </td>
</tr>
<table>

Exported PPTX properly shows Bullet in one cell and text in another.

Hope this helps.

**Comment by samirwarsi** [comment]
Or you can use bullet and text in a single cell like this:

`&bull;&#09;Sample Text`

&bull;&#09;Sample Text

`&#09; `- is html/ascii for 'tab' indent.

Might not be properly visible here but it works fine in exported pptx.

**Comment by gitbrent** [comment]
[Closing due to age]
