### ISSUE TITLE
Table border set to 'none' not working

### ISSUE THREAD

**Issue by TommyNT** [gitbrent/PptxGenJS#664]
I have a problem with borderless table. I have set `border: 'none'` but it's not working. When I set `border: { pt: 0 }` it works only in PowerPoint, but when I print document the border is visible on paper

**Comment by gitbrent** [comment]
Hi @TommyNT 

Thanks for the issue.  The docs were out of date and have been fixed now.

You'll need to use this syntax:
```javascript
slide.addTable(
  [[ {text:'no border'} ]],
  { x:1, y:1, border:{type:'none'}, colW:[2.5,0.5] }
);
```

There are working examples under /demos
