### ISSUE TITLE
firstSliceAngle (Pie, Doughnut) rotation

### ISSUE THREAD

**Issue by ghost** [gitbrent/PptxGenJS#666]
Please add feature for the ability to rotate Pie/Doughnut charts based on the First Slice Angle option.

```TypeScript
    // src/core-interfaces.ts & types/index.d.ts
...
    displayBlanksAs?: string
    fill?: string,
    firstSliceAngle? : number,
    hasArea?: boolean
...
```

```TypeScript
// src/gen-charts.ts
...
// 4: Close "SERIES"
    strXml += '  </c:ser>'
    strXml += `  <c:firstSliceAng val="${opts.firstSliceAngle || 0}"/>`
    ...
```

Thank you.

**Comment by gitbrent** [comment]
What are the possible values for `firstSliceAngle`? 0-360?
Any screencaps of what the results look like?
Does this apply to both 2D and 3D pie charts?

**Comment by HarveyDanger** [comment]
**Possible values**: 0-360.
**Applicable**: 2D, 3D Pie, Doughnut
**Not Applicable**: Composite [second plot] Pie Charts (pie with pie for sector; pie with column for sector)

**2D Pie Example of change**:
![image](https://user-images.githubusercontent.com/6269031/73904277-3f029300-48e7-11ea-9a75-864603ee439b.png)

**2D Pie - UI Option**:
![image](https://user-images.githubusercontent.com/6269031/73903980-4ffed480-48e6-11ea-8412-e63afcb23233.png)

**3D Pie - UI Option**:
![image](https://user-images.githubusercontent.com/6269031/73904038-80467300-48e6-11ea-8583-26e2185d86a5.png)

**Doughnut - UI Option**:
![image](https://user-images.githubusercontent.com/6269031/73904063-981df700-48e6-11ea-905d-0ab88d01c8aa.png)

**Does not depend on the number of series.**
