### ISSUE TITLE
Unable to pass  table ID in Html to powerPoint options

### ISSUE THREAD

**Issue by 13ecg37** [gitbrent/PptxGenJS#668]
### `Hi`  Below is my Code:  I am getting below error

pptxgen.es.js?8f74:1100 Uncaught Error: tableToSlides: Table ID "tabAutoPaging" does not exist!

Kindly help me to resolve this

      ppt = () => {
        var pptx = new PptxGenJS();
        pptx.defineLayout('LAYOUT_16x9');
        pptx.defineSlideMaster({
          title: 'MASTER_SLIDE',
          bkgd: 'F0F0F0',
          objects: [
    
            { 'rect': { x: 0.0, y: 0, w: '100%', h: 0.5, fill: 'FFFFFF' } },
            { 'image': { x:0, y:0,h:0.5, path:Logo } }
    
          ],
    
        });
 var slide = pptx.addNewSlide('MASTER_SLIDE');
<table id="tabAutoPaging" >
          <thead>
            <tr>
              <th data-pptx-min-width="0.6" style="width: 5%">Row</th>
              <th data-pptx-min-width="0.8" style="width:10%">Last Name</th>
              <th data-pptx-min-width="0.8" style="width:10%">First Name</th>
              <th data-pptx-width="8.5"     style="width:75%">Description</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>

 pptx.tableToSlides("tabAutoPaging");
}

**Comment by 13ecg37** [comment]
![image](https://user-images.githubusercontent.com/52811079/74087898-6491c700-4ab6-11ea-9242-efc99b7c6c09.png)

**Comment by gitbrent** [comment]
The `tableToSlides` argument is the `<table id="tabAutoPaging">` value.

It looks like you copied the demo code, which is fine, but you need to use the same `id` on your HTML table.

**Comment by 13ecg37** [comment]
I have passed the same id but its not working.

i have used the table  option inside the funtion but its not working.

Could you please help me to come out from this..?

Regards
Ashok

**Comment by gitbrent** [comment]
If you're generating the table, ensure it exists first.  Otherwise, you'll have to work on it.
