### ISSUE TITLE
Add text Overflow the slide

### ISSUE THREAD

**Issue by Ashok-SK** [gitbrent/PptxGenJS#670]
Hi Gitbrent,

What to do ...? if the text overflows the slide...

My questions is how to move to next slide if the text overflow on the same slide..?

Looking forward your response

Regards
Ashok

**Comment by gitbrent** [comment]
Hi @Ashok-SK 

The library doesn't support that feature.

**Comment by gitbrent** [comment]
[Closing due to age]
