### ISSUE TITLE
types error  'node_modules/pptxgenjs/types/index.d.ts'

### ISSUE THREAD

**Issue by Krishnakanth94** [gitbrent/PptxGenJS#672]
**node_modules/pptxgenjs/types/index.d.ts(1037,9): error TS1122: A tuple type element list cannot be empty.
node_modules/pptxgenjs/types/index.d.ts(1060,25): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/pptxgenjs/types/index.d.ts(1299,17): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/pptxgenjs/types/index.d.ts(1385,52): error TS1122: A tuple type element list cannot be empty.**

**Comment by gitbrent** [comment]
Where is this coming from, Webpack?

The library is built with TypeScript 3.3.1 and i'm not seeing any ts/tslint errors like this.

**Comment by abhishek19589** [comment]
Facing the same issue i have install  "npm install pptxgenjs --save"  in my angular 6 application and added demo in once file ng build --watch giving same error 


ERROR in node_modules/pptxgenjs/types/index.d.ts(1037,9): error TS1122: A tuple type element list cannot be empty.
node_modules/pptxgenjs/types/index.d.ts(1060,25): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/pptxgenjs/types/index.d.ts(1299,17): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/pptxgenjs/types/index.d.ts(1385,52): error TS1122: A tuple type element list cannot be empty.

**Comment by vincentproxistore** [comment]
I have a kind of similar issue here
I am using ng7 and typescript 3.2.4

ERROR in node_modules/pptxgenjs/types/index.d.ts(67,50): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
node_modules/pptxgenjs/types/index.d.ts(73,88): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

**Comment by gitbrent** [comment]
Thanks @Krishnakanth94 

This is now fixed in the master branch.

**Comment by Krishnakanth94** [comment]
Thank's @gitbrent .
