### ISSUE TITLE
typescript definitions Slide and ISlide

### ISSUE THREAD

**Issue by gytisgreitai** [gitbrent/PptxGenJS#673]
Considering the code:
```
import pptxgen from "pptxgenjs";
const pptx = new pptxgen();
const slide = pptx.addSlide();
```

now slide is of type `ISlide` and e.g. addText is defined as Function :

```
export interface ISlide {
        <....>
       addText: Function
       <....>
}
```

Thought he specific `Slide` class has a correct definition

```
addText(text: string | IText[], options?: ITextOpts): Slide
```

what I am doing right now is :

```
const coverSlide = pptx.addSlide() as any as PptxGenJS.Slide;
```

so any way to get type safety when using slide object?

**Comment by gitbrent** [comment]
Thanks @gytisgreitai 

This is now fixed.
