### ISSUE TITLE
slider.addTable with odd rows leads to the latest office application to ask for repair

### ISSUE THREAD

**Issue by zyzbroker** [gitbrent/PptxGenJS#675]
we are using pptx 3.3.0 to generate pptx. we add table into one of sliders. we found out that if we add odd number of rows and generate pptx. when we use lastest office app or goodle slider to open it, warning dialog show up and ask us to repair. Once clicked repair, the pptx is rendered properly inside the office or google slider. If we add even number of rows, this warning is not shown up.

**Comment by cihancelen** [comment]
Hi, i having this problem too.
How can i fix this problem?

**Comment by gitbrent** [comment]
@zyzbroker @cihancelen - the demo is loaded with tables that have an odd number of rows and opens fine in PPT desktop and online.

Please provide sample code and version (are you really using 3.3.0-beta?).

<img width="1601" alt="Screen Shot 2020-06-24 at 22 31 29" src="https://user-images.githubusercontent.com/7218970/85650443-324ec380-b66b-11ea-8c77-2df485a72d78.png">

**Comment by cihancelen** [comment]
@gitbrent Hi again, actually this is not exactly my problem, but it looks like. I use it in Angular 9. When I add a table, if the table is more than 3 lines, when I export it, it says that I need to repair the powerpoint.

**Comment by gitbrent** [comment]
@cihancelen - can you create a PPT with only a table of 3+ rows and attach it here?

**Comment by toinuma** [comment]
The same thing happened to me.

In my case it happens when I have a h(height) on the rows in percent.
Looking at the diff with the fixed one, the height with a decimal point was fixed to 0.

I manually fixed the decimal point to an integer, the fix message disappeared.
It may be a bug in PPTX itself, since it only happens when the number of rows is odd.

**Comment by cihancelen** [comment]
@toinuma thank u, i will try this solve.

**Comment by cihancelen** [comment]
> @cihancelen - can you create a PPT with only a table of 3+ rows and attach it here?

Hello I saw what you just wrote, sorry

[github_example.pptx](https://github.com/gitbrent/PptxGenJS/files/4858142/github_example.pptx)

**Comment by gitbrent** [comment]
Ah, that was it. Thanks!

There were areas of the code not immune to float issues when calculating `EMU` and `point` values - they have all been fixed by: #781
