### ISSUE TITLE
Add Slide Number formatting options

### ISSUE THREAD

**Issue by ZouhaierSebri** [gitbrent/PptxGenJS#68]
How to style a page number in slide ?

**Comment by gitbrent** [comment]
Hi @ZouhaierSebri ,

Thanks for opening an Issue.  There are presently no styling options for the Slide Number, but i'll get some added for the next release (font, size, and color).

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,
Thank you a lot .

**Comment by gitbrent** [comment]
Hi @ZouhaierSebri ,

Slide Number formatting options are now available and are included in the README.

`slide.slideNumber({ x:1.0, y:'90%', fontSize:32, fontFace:'Courier', color:'CF0101' });`

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,
Thank you for the good and quick feature adding.
It encourage me to use this framework and spport it 👍
