### ISSUE TITLE
Images not rendering on PPT when waiting for a promise before `.addImage()`

### ISSUE THREAD

**Issue by luism-s** [gitbrent/PptxGenJS#683]
Hello

I've run into a use case where I need to wait for promise before I add an image. It happens that if there is an `await` for a promise before the '.addImage()' call, the resulting PPT is not returning the slide images. I made an experiment with a simple function `(await (() => Promise.resolve())()` and even this renders no images. If I remove the promise function every image is rendered as expected.

My current version of pptxgenjs is 3.1.1, the latest release at the moment

This is a simple code snippet:

```
  const pptx: PptxGenJS = new PptxGenJS();

  const slides = [ ... ];

  slides.forEach((slide) => {
    const pptSlide = pptx.addSlide(slide.title);

    const widgets = [ ...slide.widgets ];

    widgets.forEach(async (widget) => {
      const pptWidget = { ... };
      const path = processImage(widget);

      await (() => Promise.resolve())();
      pptSlide.addImage({ ...pptWidget, path });
    });
  });
```

Any ideas? Thank you!

**Comment by gitbrent** [comment]
Why not run the loop beforehand, gather all your paths into `let myPaths:string[] = []` then loop over that and create all the pptx slides/images?

**Comment by luism-s** [comment]
Will give it a try and report back. Even then, it feels like a weird bug, that an empty promise break the images

**Comment by kokoagb** [comment]
Hey @luism-s , I suggest that instead of a `forEach` you use `map` which will return an array of promises. Then you can wait until all of them are resolved using `Promise.all`.

**Comment by luism-s** [comment]
> Hey @luism-s , I suggest that instead of a `forEach` you use `map` which will return an array of promises. Then you can wait until all of them are resolved using `Promise.all`.

This worked

Thank you!
