### ISSUE TITLE
How to add object like excel sheet in ppt

### ISSUE THREAD

**Issue by kshitijwalukar** [gitbrent/PptxGenJS#686]

**Comment by gitbrent** [comment]
?

**Comment by kshitijwalukar** [comment]
I want to add an excel sheet as a file in ppt
<img width="541" alt="Untitled" src="https://user-images.githubusercontent.com/34885899/75409347-7ab8d780-593e-11ea-9b71-e9799bd6f73f.png">

**Comment by gitbrent** [comment]
Not currently supported.
