### ISSUE TITLE
Need an Example file for HTML to PPT

### ISSUE THREAD

**Issue by kshitijwalukar** [gitbrent/PptxGenJS#688]

**Comment by gitbrent** [comment]
There's an online demo you can use:

### [https://gitbrent.github.io/PptxGenJS/demo/#html2pptx](https://gitbrent.github.io/PptxGenJS/demo/#html2pptx)

<img width="1535" alt="Screen Shot 2020-02-27 at 23 00 32" src="https://user-images.githubusercontent.com/7218970/75511821-ffded380-59b4-11ea-9969-448b4ecfd37c.png">
