### ISSUE TITLE
Doc: breaking 3.0 change, slide.back => slide.bkgd

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#690]
A small thing to add to the migration guide about the slide background colour

**Comment by gitbrent** [comment]
Fixed. Thanks @Slidemagic !

<img width="553" alt="Screen Shot 2020-02-27 at 22 56 58" src="https://user-images.githubusercontent.com/7218970/75511694-8cd55d00-59b4-11ea-8f36-982202db429d.png">
