### ISSUE TITLE
Wrong rotation results in triangle and line shapes

### ISSUE THREAD

**Issue by luism-s** [gitbrent/PptxGenJS#691]
Hello!

I'm trying to generate a slide with rotated shapes. All of them work as expected, except the triangle and line. It seems that when rendered, the containers respect the shapes width & height & rotation, however feels like these shapes are rotated with a different value.

The triangle feels like it's rotated in the opposite direction after a first rotation. For example, if contained in a rectangular container, it rotates naturally (90 degrees or whatever), but then the shape it self rotates back with the same value.

The line rotates in a weird way that I can't decode. When given 90 it rotates maybe 45, when given 45 it seems to rotate 90

Thanks!

Application slide

<img width="1221" alt="Screenshot 2020-03-01 at 23 30 03" src="https://user-images.githubusercontent.com/15066801/75635225-9eb53b00-5c14-11ea-9265-f9b3aaf6a06b.png">

Generated slide, rotation of 90 degrees.

<img width="1237" alt="Screenshot 2020-03-01 at 23 42 51" src="https://user-images.githubusercontent.com/15066801/75635446-64e53400-5c16-11ea-8583-4c41c75dc1d8.png">

Generated slide, rotation of 45

<img width="1248" alt="Screenshot 2020-03-01 at 23 35 55" src="https://user-images.githubusercontent.com/15066801/75635328-6a8e4a00-5c15-11ea-9b89-46c2c8cdeb9a.png">
 degrees.

**Comment by luism-s** [comment]
I came back to this and it seems to be working as expected. Probably because instead only adding rotation angles, I also use the modulus operator with 360

Like (userRotation + triangleRotation) % 360

**Comment by gitbrent** [comment]
@luism-s - thanks for the follow-up, i was hoping the rotation code wasn't really hosed. :)
