### ISSUE TITLE
how to get the data from excel sheet and make a table in ppt

### ISSUE THREAD

**Issue by kshitijwalukar** [gitbrent/PptxGenJS#693]

**Comment by Amitloh** [comment]
I also want to know about this

**Comment by gitbrent** [comment]
Hi @Amitloh @kshitijwalukar 

There is no direct way.

You can provide the data to PptxGenJS in 2 ways: 
* Create a data grid, or forEach into rows and use `addTable()`
* Create an HTML table and provide the table element ID to `tableToSlides()`

Demo of [tableToSlides](https://gitbrent.github.io/PptxGenJS/demo/#html2pptx)

API docs for [addTable](url)
