### ISSUE TITLE
HTML to Table adds random new lines

### ISSUE THREAD

**Issue by justinmcgrath95** [gitbrent/PptxGenJS#696]
Using pptx.tableToSlides() inserts new lines after seemingly random space characters. Even though there are no br tags within the HTML table, it behaves as if there are.

This can be seen in the demos as well. (https://gitbrent.github.io/PptxGenJS/demo/#html2pptx)

I am looking to upgrade to the latest version but I can't until this bug is fixed.

**Comment by chelseasaffold** [comment]
I am having this issue too. Were you able to resolve it? I do not have anything in the html that would cause a line break, yet it breaks after each word using pptx.tableToSlides. I attached screenshots of what the table looks like on the page and how it looks in the powerpoint.

This is my settings for html to table

`pptx.tableToSlides(element.table, {
            x: 0.4,
            y: 1.8,
            addHeaderToEach: true,
            newSlideStartY: 1.8,
            autoPageCharWeight: -1,
            autoPageLineWeight: -1,
            masterSlideName: "MASTER_PLAIN",
            addText: {text: report.name, options: {placeholder: 'title'}},
        });`

<img width="1032" alt="Screen Shot 2020-06-12 at 12 09 26 PM" src="https://user-images.githubusercontent.com/30847326/84523168-dd43a280-aca5-11ea-8f3b-f465f8d4b941.png">
<img width="893" alt="Screen Shot 2020-06-12 at 12 09 10 PM" src="https://user-images.githubusercontent.com/30847326/84523169-dddc3900-aca5-11ea-9fb9-0c688aacbe5e.png">

**Comment by gitbrent** [comment]
@chelseasaffold - by the looks of the resulting table, the columns are being set too small - even "%" and "change" were wrapped.

Is the table hidden or is the style returning tiny column sizes?

Note: You can specify parameters using `data` tags in HTML
### [API Docs and Examples](https://gitbrent.github.io/PptxGenJS/docs/html-to-powerpoint.html#html-to-powerpoint-table-options)

**Comment by jsvishal** [comment]
This issue is replicable in a normal table too. Word wrapped even if space available.
