### ISSUE TITLE
Allow select override of Master Slide background color/image

### ISSUE THREAD

**Issue by stevenljacobsen** [gitbrent/PptxGenJS#7]
I'd like to set the background color based on a value that is passed from my application. But it doesn't seem possible to pass it through the call to the master slide. Do you have any option for that? I'll need to do the same thing for background images.

**Comment by stevenljacobsen** [comment]
I worked around this by adding the image to each slide as I created it. But it seems like there should be a way to pass parameters to the master slide for not just backgrounds but any of the options that you may use in a master.

**Comment by gitbrent** [comment]
Give the newest check-in a try and let me know what you think.

I even created a new text case for both background color and image on the demo page.

**Comment by stevenljacobsen** [comment]
I just saw this. I'll have to reorganize my code a bit to try it. I'll give it a shot.

**Comment by prasademc** [comment]
Any update for this implementation

**Comment by gitbrent** [comment]
Hi @prasademc,

No, this feature is not implemented.

Unless you need to change the colors a lot, then creating a few colored masters is super easy:

```javascript
pptx.defineSlideMaster({ title: 'GREY_MASTER', bkgd: 'F1F1F1' });
pptx.defineSlideMaster({ title: 'RED_MASTER',  bkgd: 'FF0000' });
pptx.defineSlideMaster({ title: 'BLUE_MASTER', bkgd: '0000FF' });
```
