### ISSUE TITLE
Pie chart values for thin slices

### ISSUE THREAD

**Issue by psubrownie** [gitbrent/PptxGenJS#701]
When there is a thin slice of a pie and it attempts to put the label off to the side, it is drawing the line but not placing the value.  I don't mind not putting the value on the other slice but if the line is drawn the value should display.

![image](https://user-images.githubusercontent.com/2124762/77174050-d76b6600-6a96-11ea-9b6f-5f10900d25d7.png)

**Comment by gitbrent** [comment]
You'll need to experiment with the available pie chart options.  PowerPoint does al of its own layout, this library has no control over rendering like you've shown.
