### ISSUE TITLE
Live demo of current presentation / slides

### ISSUE THREAD

**Issue by sakstone** [gitbrent/PptxGenJS#702]
Hi,

is there a way to render a representation of a slide object as jpg/png/... in the users browser?

For example when I would like to have a live preview (see attachment) of the presentation before I download the .pptx file.

<img width="1589" alt="Bildschirmfoto 2020-03-25 um 13 14 23" src="https://user-images.githubusercontent.com/32909466/77535244-95796000-6e9a-11ea-9a44-4c6e7d56a8e2.png">

**Comment by gitbrent** [comment]
Hi @sakstone - no, such a feature does not exist.
