### ISSUE TITLE
catAxisTime options are not recognized

### ISSUE THREAD

**Issue by lucasflomuller** [gitbrent/PptxGenJS#705]
I receive this warning on my console:
![image](https://user-images.githubusercontent.com/32915144/78935015-56463400-7a82-11ea-83e4-e44b301009b0.png)

But my code is:
![image](https://user-images.githubusercontent.com/32915144/78935069-6e1db800-7a82-11ea-8acc-eb270b29cf1c.png)

Apparently the code on that part looks okay, but I investigated a lot and I don't know what's going on. I really needed these properties to be functional to get my expected result.

Any ideas of what it is?

**Comment by gitbrent** [comment]
@lucasflomuller - thanks so much for identifying and fixing this.

I've asked for a change on the pull request, otherwise, it looks good.
