### ISSUE TITLE
Stacked Area not working

### ISSUE THREAD

**Issue by phobos7000** [gitbrent/PptxGenJS#708]
Hello Ely,
First of all, I would like to tell you that your work on this library is very impressive. 
However, I'm trying to create a stacked area chart by setting "stacked" in "barGrouping" but nothing change.
May be I'm doing something wrong.
Please find below a example of code that I'm using for my test and a picture to illustrate my problem.

    var MONS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
		var arrDataTimeline2ser = [
			{
				name  : 'Actual Sales',
				labels: MONS,
				values: [1500, 4600, 5156, 3167, 8510, 8009, 6006, 7855, 12102, 12789, 10123, 15121]
			},
			{
				name  : 'Proj Sales',
				labels: MONS,
				values: [1000, 2600, 3456, 4567, 5010, 6009, 7006, 8855, 9102, 10789, 11123, 12121]
			}
		];
    

// Simple Slide
  let pptx = new PptxGenJS();
  let slide = pptx.addSlide();
  var optsChartLine2 = { x:7, y:0.6, w:'45%', h:3,
			chartColors: ['0088CC', '99FFCC'],
			chartColorsOpacity: 25,
			valAxisLabelRotate: 5,
			dataBorder: {pt:2, color:'FFFFFF'},
			showValue: false,
			fill: 'D1E1F1',
			barGrouping: 'stacked'
		};
  slide.addChart( pptx.charts.AREA, arrDataTimeline2ser, optsChartLine2 );
    

  pptx.writeFile();
![pptxgenjs_stacked_area_chart](https://user-images.githubusercontent.com/47020499/79029406-90075f80-7b94-11ea-8821-2a5ca23937da.png)

**Comment by pimlottc-gov** [comment]
Note that the change for stacked area charts (#333) hasn't been released yet. It should be in 3.8.0.

**Comment by gitbrent** [comment]
@pimlottc-gov is correct. This feature is now available with the recent v3.2.0 release.
