### ISSUE TITLE
catAxisLabelPos and valAxisLabelPos options are not working

### ISSUE THREAD

**Issue by cpf121** [gitbrent/PptxGenJS#709]
Hi team ,
I set the two options of `cataxislabelpos` and `valaxislabelpos`, but they didn't seem to work.Below is my code.

![pptgenjs](https://user-images.githubusercontent.com/31813563/79113441-7f810000-7db3-11ea-81eb-27d2ce652e73.png)
```
let dataChartAreaLine = [
	{
		name: "Actual Sales",
		labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
		values: [1500, 4600, 5156, 3167, 8510, 8009, 6006, 7855, 12102, 12789, 10123, 15121],
	},
	{
		name: "Projected Sales",
		labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
		values: [1000, 2600, 3456, 4567, 5010, 6009, 7006, 8855, 9102, 10789, 11123, 12121],
	},
];
slide.addChart("line", dataChartAreaLine, { x: 1, y: 1, w: 8, h: 4, catAxisLabelPos: "high", valAxisLabelPos: "high" });
```

**Comment by gitbrent** [comment]
Bug in code preventing user selection from being used:
https://github.com/gitbrent/PptxGenJS/blob/1f7c8a4686f2e4472448aad9758ebaae105f020b/src/gen-charts.ts#L1576

**Comment by cpf121** [comment]
Thank you.

**Comment by gitbrent** [comment]
Thanks @cpf121 

Fixed in upcoming v.3.4.0 release.

![Screen Shot 2021-01-02 at 22 00 41](https://user-images.githubusercontent.com/7218970/103471439-23497c00-4d46-11eb-847b-15c945483313.png)
