### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by alexbai31** [gitbrent/PptxGenJS#71]
Hi there, we've faced with the following bug: 
when sending the array with objects as the first parameter, where each object involves "text" and "options" attributes and herewith to the "options" attribute is assigned the object, which includes "bullet" parameter with any value, then after the .pptx is generated we get an error on opening the file.

Привет! Столкнулись со следующим багом:
в методе addText если первым аргументом посылать массив с объектами где каждый объект включает в себя атрибуты "text" и "options" и к атрибуту options присвоен объект включающий в себя параметр "bullet" с любим значением, после того как .pptx будет сгенерирован возникает ошибка при открытии файла.

**Comment by gitbrent** [comment]
Hi @alexbai31 ,

What version of PowerPoint are you using, and can i see the code?

**Comment by alexbai31** [comment]
PowerPoint 2010

The part of code, which is required:

var textOptions = { font_size: 9, font_face: 'Calibri', color: '000', align: 'l', bullet: true };
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_16x10');
var slide = pptx.addNewSlide();
slide.addText(
[
{ text: ltxt, options: textOptions }
],
{ x: 0, y: 0, w: 5, h: 2, margin: 0.1, fill: 'ffffff' }
);

There are several strings of the text divided with '\n' symbol in "ltxt"

**Comment by ZouhaierSebri** [comment]
It is the same as issue #64

**Comment by gitbrent** [comment]
Hi @alexbai31 ,

Thanks for reporting this.  The issue should be fixed in the latest codebase.

Please try again and let me know how it goes.
