### ISSUE TITLE
import/edit existing PPT?

### ISSUE THREAD

**Issue by Offbeatmammal** [gitbrent/PptxGenJS#712]
just curious if there is a roadmap to be able to open and edit items on an existing PPT - my specific scenario is that I'd like to be able to replace named text and picture objects in a source PPT via database lookups for specific sets of criteria.
a workaround might be to have a seperate parser that lists the contents of the existing template into a JSON format that could then be used to re-create the PPT 'fresh' just using PptxGenJS...

**Comment by gitbrent** [comment]
Hi @Offbeatmammal 

This library strictly produces Presentations. There is no item on the development roadmap to ingest existing documents.

**Comment by Offbeatmammal** [comment]
@gitbrent hopefully you'll see a comment on closed bugs...

to try and help with the effort, I've started work on [PPTXport](https://github.com/Offbeatmammal/PPTXport), and would love input from any others who might be able to make use of this.

You may have noticed that I've opened a couple of bugs/feature requests related to things that I've found getting this working, hopefully this helps to add some context ;)

**Comment by yuhonas** [comment]
Not sure if you're still looking/where you're at but I was looking for the exact same thing 2 3 years later and found this [docxtemplater](https://github.com/open-xml-templating/docxtemplater)
