### ISSUE TITLE
Enable JSZip compression

### ISSUE THREAD

**Issue by pimlottc-gov** [gitbrent/PptxGenJS#713]
We are using pptxgenjs to generate a fairly large deck (250+ slides) and our file size is starting to reach the limits of the mail server.  I was surprised to notice that the pptx as output does not use any compression.

Currently, our workaround is to manually open and resave the file from Powerpoint, which uses compression.  But it would great to have pptxgenjs do this for us.  JSZip does support the "deflate" compression algorithm.

If there might be performance concerns, this could be done as an optional setting; either a flag in pptgenjs like `enableCompression: true` or an `jszipOptions` argument that is passed on to JSZip.

**Comment by gitbrent** [comment]
The main export methods need to be updated to take options objects instead of method/export name to allow for a boolean 'compress' option, so i'm pushing to v3.5.0

branch 'zip-compression' created.

**Comment by gitbrent** [comment]
Thanks for the suggestion @pimlottc-gov 

This is complete and will be in v.3.5.0 (Pull #883)

```javascript
pptx.writeFile({ fileName: 'CompressDemo', compresion: true });
```
