### ISSUE TITLE
Multi colors for label?

### ISSUE THREAD

**Issue by mapapuche** [gitbrent/PptxGenJS#716]
Hello,

Is it possible to get multi color in data label ?

For example : 
    const chartBenchmarkConfig = {
      ...geometry,
      showPercent: true,
      valAxisMaxVal: max,
      valAxisMinVal: min,
      valGridLine: { size: 1, color: '000000', style: 'dot' },
      chartColors: colors,
      shadow: 'none',
      showValue: true,
      dataLabelColor: '000000',
      dataLabelPosition: 'outEnd',
      dataLabelFormatCode: '+0',
      gridLineColor: COLOR_AXIS,
      valAxisLabelColor: COLOR_AXIS,
      catAxisLabelColor: COLOR_AXIS,
      dataLabelFontBold: true,
      dataLabelFontSize: 14,
      valAxisMajorUnit: 0,
      barGapWidthPct: 1,
    };

In datalabel color i have '000000', there is a way to get multi color here ? I tried with ['000000', 'BEBEBEBE'] but not working because that does not accept array :/

Any idea ?

Thank for your help !

**Comment by ankon** [comment]
A label has a color, and then there is other colors for the lines etc. 
What do you expect here, i.e. whats 'multi colors?' Do you have a screenshot of the outcome you want?

**Comment by gitbrent** [comment]
Data label color is a singular value.

**Comment by adeelkhalid** [comment]
![image](https://user-images.githubusercontent.com/13808336/122521886-c8bf8600-d02e-11eb-8f5c-b79b82eddf87.png)

This is a must-required feature for me.
Can you please put all formatting variables in the chart data series? It would be a great help.

**Comment by adeelkhalid** [comment]
> Hello,
> 
> Is it possible to get multi color in data label ?
> 
> For example :
> const chartBenchmarkConfig = {
> ...geometry,
> showPercent: true,
> valAxisMaxVal: max,
> valAxisMinVal: min,
> valGridLine: { size: 1, color: '000000', style: 'dot' },
> chartColors: colors,
> shadow: 'none',
> showValue: true,
> dataLabelColor: '000000',
> dataLabelPosition: 'outEnd',
> dataLabelFormatCode: '+0',
> gridLineColor: COLOR_AXIS,
> valAxisLabelColor: COLOR_AXIS,
> catAxisLabelColor: COLOR_AXIS,
> dataLabelFontBold: true,
> dataLabelFontSize: 14,
> valAxisMajorUnit: 0,
> barGapWidthPct: 1,
> };
> 
> In datalabel color i have '000000', there is a way to get multi color here ? I tried with ['000000', 'BEBEBEBE'] but not working because that does not accept array :/
> 
> Any idea ?
> 
> Thank for your help !

https://github.com/gitbrent/PptxGenJS/issues/967#issuecomment-864213548
