### ISSUE TITLE
Bug: addTables API

### ISSUE THREAD

**Issue by Smithvinayakiya** [gitbrent/PptxGenJS#717]
Hi @gitbrent 
Please change newPageStartY to newSlideStartY in the documentation. newPageStartY doesn't work.

**Comment by gitbrent** [comment]
Thanks @Smithvinayakiya 

Documentation updated.

<img width="829" alt="Screen Shot 2020-05-23 at 23 17 36" src="https://user-images.githubusercontent.com/7218970/82745568-9cfa9f80-9d4b-11ea-8d08-90f9d93ed17a.png">
