### ISSUE TITLE
Bluebird warning when executing pptx.stream()

### ISSUE THREAD

**Issue by tkounenis** [gitbrent/PptxGenJS#719]
When pptx.stream() is executed, bluebird logs a warning:

> (node:10443) Warning: a promise was created in a handler at domain.js:137:15 but was not returned from it, see http://goo.gl/rRqMUw

This is because zip.generateAsync promise is not returned in this line:
https://github.com/gitbrent/PptxGenJS/blob/7654f1594a3204d913571fd75650e1990c6e75e4/src/pptxgen.ts#L526

When I add the return statement, the warning goes away.

**Comment by gitbrent** [comment]
Fixed with Pull #695
