### ISSUE TITLE
Errors when using webpack/Typescript

### ISSUE THREAD

**Issue by Vivihung** [gitbrent/PptxGenJS#72]
I hit 2 errors in my project where we use webpack/Typescript. 
(Note: I'm using the library in a web page)
The first error happened when building my project, 

```
ERROR in ./~/pptxgenjs/dist/pptxgen.js

Module not found: Error: Cannot resolve module 'fs' in c:\myproj\node_modules\pptxgenjs\dist
 @ ./~/pptxgenjs/dist/pptxgen.js 2536:10-23

ERROR in ./~/image-size/lib/index.js

Module not found: Error: Cannot resolve module 'fs' in c:\myproj\node_modules\image-size\lib
 @ ./~/image-size/lib/index.js 3:9-22

ERROR in ./~/image-size/lib/types/tiff.js

Module not found: Error: Cannot resolve module 'fs' in c:\myproj\node_modules\image-size\lib\types
 @ ./~/image-size/lib/types/tiff.js 6:9-22
```

By referring to [this post,](https://github.com/josephsavona/valuable/issues/9) I put the workaround in my webpack config
`node: {
        fs: "empty"
    }`

Then I hit another error when running my page in browser
`Uncaught (in promise) TypeError: callback is not a function
    at eval (eval at <anonymous> (main.js:8466), <anonymous>:193:104)`

It comes from this line of code in pptxgen.js
`zip.generateAsync({type:'nodebuffer'}).then(function(content){ fs.writeFile(strExportName, content, callback(strExportName)); });`

So, I comment it out as the following to bypass the error
```
/*
if ( NODEJS ) {
	zip.generateAsync({type:'nodebuffer'}).then(function(content){ fs.writeFile(strExportName, content, callback(strExportName)); });
}
else { */
	zip.generateAsync({type:'blob'}).then(function(content){ writeFileToBrowser(strExportName, content, callback); });
// }
```

Is there any way I can resolve the second error without changing PptxGenJS code?

**Comment by gitbrent** [comment]
Hi @Vivihung ,

Thanks for reporting this.  The callback issue affects Node.js as well as webpack.

Please try your build again with the newest codebase and let me know how it goes.

**Comment by Vivihung** [comment]
Thanks for the quick fix!
Could you please release 1.4.0 to npm so my project can consume it?

**Comment by gitbrent** [comment]
Hi @Vivihung ,

Version 1.4.0 has been released to NPM.

Please let me know if you have any further issues.

**Comment by HoangLong93** [comment]
Hi @gitbrent ,
 After updating to angular 6, I'm having 'Error: Cannot resolve module 'fs' in multiple file in the image-size and pptxgenjs modules.
 It seems like the new Angular 6 doesn't inject module fs anymore which might cause this problem. Is there a way to work around this?
 Thanks

**Comment by gitbrent** [comment]
Hi @HoangLong93 

What version of PptxgenJS are you using?

```javascript
PptxGenJS = require("pptxgenjs");
var pptx = new PptxGenJS();
console.log(pptx.version);
```

**Comment by akushylun** [comment]
Have the same issue as @HoangLong93 
Version - 2.1.0.

Mistakes:
1) Can't resolve 'fs'
2) Can't resolve 'path'
3) Can't resolve 'stream'

Will be great, if it is a work around.
Thanks.

**Comment by HoangLong93** [comment]
Hi @gitbrent ,
 Yes I'm using v2.1 also.

 Thanks

**Comment by gitbrent** [comment]
Okay, thanks for checking.

Version 2.2.0 has the newest Node-detection code that fixes these unresolved libraries.

It'll be released this weekend...

**Comment by HoangLong93** [comment]
Hi @gitbrent ,
 I just update to the new version 2.2.0, however I still see the same error with Angular 6. Can you have a look?

ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'fs'

ERROR in ./node_modules/image-size/lib/types/tiff.js
Module not found: Error: Can't resolve 'fs'

ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'path'

ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream'
Failed to compile.

 Thanks for your help

**Comment by HoangLong93** [comment]
@gitbrent , well that's unfortunate.
 Thanks for your effort and info. I'll try to find a way to work around it then.
 Best,

**Comment by gitbrent** [comment]
@HoangLong93 

Please let me know what you find - i'd like to be able to have the library work with Angular (and create some sort of guide).

**Comment by jcanaan88** [comment]
Hi. I think I'm having a relate issue. 

I ran npm install pptxgenjs, then I tried following the library integration example here:
https://gitbrent.github.io/PptxGenJS/docs/integration.html#angular-example

I just created a new TS file with just the example code in it. I import it into one of my component.ts files and try to call the generatePPT function, and I get the following messages:

ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib'
ERROR in ./node_modules/image-size/lib/types/tiff.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib\types'
ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib'
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\jszip\lib'

**Comment by jcanaan88** [comment]
Ok. I managed to get it to work.  Couple of things I did:

Module not found: Error: Can't resolve 'stream' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\jszip\lib'

in angular cli, I ran npm i stream.

To resolve 

ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib'
ERROR in ./node_modules/image-size/lib/types/tiff.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib\types'
ERROR in ./node_modules/image-size/lib/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\user\Documents\angularApps\playground\value-added-selling\node_modules\image-size\lib'
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js

Added the following to the image-size/package.json file

```
browser": {
    "fs": false,
    "path": false,
    "os": false
  }
```

To resolve the warning I received for not being able to find fs in pptxgenjs, I added the code above to the pptxgenjs/package.json file as well

To resolve the issue with "require," I followed these steps:
https://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require

Now the following seems to work as intended:

```
var PptxGenJS = require('pptxgenjs');
const pptx = new PptxGenJS();

pptx.setBrowser(true);

export function generatePPT() {
    const slide = pptx.addNewSlide();
    const opts = { x: 1.0, y: 1.0, font_size: 42, color: '00FF00' };
    slide.addText('Hello World!', opts);
    pptx.save();
}
```

**Comment by gitbrent** [comment]
Thanks @jcanaan88 .

I've added the `browser` element to the `package.json` and i've made several other changes to Node detection lately, so i'm hopeful this issue will improve shortly.
