### ISSUE TITLE
Sorry, PowerPoint can't read ^0 and Repair issue

### ISSUE THREAD

**Issue by chrisjaimes** [gitbrent/PptxGenJS#721]
Has anyone experienced this error with the library?

<img width="424" alt="Screen Shot 2020-04-27 at 11 01 33 PM" src="https://user-images.githubusercontent.com/45322800/80442575-349ad880-88db-11ea-8743-6eaadfb585c7.png">

I don't think is a format error cuz I am literally copying and pasting the following code

```
let pres = new PptxGenJS();

// 2. Add a Slide
let slide = pres.addSlide();

// 3. Add one or more objects (Tables, Shapes, Images, Text and Media) to the Slide
let textboxText = "Hello World from PptxGenJS!";
let textboxOpts = { x: 1, y: 1, color: "363636", fill: "f1f1f1", align: "center" };
slide.addText(textboxText, textboxOpts);

// 4. Save the Presentation
pres.writeFile("Sample Presentation.pptx");
```

any ideas? I'm on version 3.1.1 and PowerPoint is Version 16.33

**Comment by chrisjaimes** [comment]
alright, i fixed it. I think I had something wrong in my `bundle` file

**Comment by Shada-B** [comment]
Can you please share how you solved the issue? I'm having the same issue with a very important PPT file

**Comment by chrisjaimes** [comment]
@Shada-B sure. I was using the distribution files from the library by downloading the bundle release. My issue was that I was using the pptxgen.min.js file to import the library. But I needed to use pptxgen.bundle.js

**Comment by PENN73** [comment]
Can you please share how you solved the issue? I'm having the same issue with a very important PPT file
