### ISSUE TITLE
size/positioning doesn't match native PPT

### ISSUE THREAD

**Issue by Offbeatmammal** [gitbrent/PptxGenJS#723]
I have a sample source PowerPoint from which I am copying the size and position of sample objects.
When I run a PptxGenJS script to generate the output, there is a slight discrepancy in position/size of the objects

    let pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE'

    slide = pptx.addSlide();
    slide.addShape(pptx.ShapeType.hexagon,{x: 11.04,y: 3.36,w: 1.64,h: 1.43,rotate: 90, fill:{ type:'solid', color:'7F7F7F' }})
    slide.addShape(pptx.ShapeType.hexagon,{x: 12.52,y: 3.33,w: 1.64,h: 1.43,rotate: 90, fill:{ type:'solid', color:'000000' }})
    slide.addShape(pptx.ShapeType.hexagon,{x: 11.78,y: 2.08,w: 1.64,h: 1.43,rotate: 90, fill:{ type:'solid', color:'DE1D16' }})

  pptx.writeFile();Please see attached sample and output for an example
[test_orig.pptx](https://github.com/gitbrent/PptxGenJS/files/4556245/test_orig.pptx)
[Presenation.pptx](https://github.com/gitbrent/PptxGenJS/files/4556247/Presenation.pptx)

Is there anything I am doing wrong, perhaps a missed step?

Also, is there any way to support providing the x,y, width, and height as points so it's possible to use VBA to query positions in a template and use those values without conversion to inches (would that possibly help with this issue)?

**Comment by gitbrent** [comment]
Unable to reproduce in v3.2.0.

All 3 shapes' positions and sizes in PowerPoint match the input code above.
<img width="623" alt="Screen Shot 2020-05-23 at 23 11 42" src="https://user-images.githubusercontent.com/7218970/82745520-06c67980-9d4b-11ea-9746-961786e09db4.png">

<img width="613" alt="Screen Shot 2020-05-23 at 23 12 55" src="https://user-images.githubusercontent.com/7218970/82745523-0af29700-9d4b-11ea-8d09-6a8c15e66939.png">
