### ISSUE TITLE
[Feature Request] add name:'.....' to objects

### ISSUE THREAD

**Issue by Offbeatmammal** [gitbrent/PptxGenJS#724]
when creating an object the name always defaults to "object _n_" and allocates _n_ sequentially.

it would be a handy option to be able to override the default name with eg:

```javascript
slide.addShape(
  pptx.ShapeType.hexagon,
  {shape_name:'myHex01', x:0.33, y: 4.51, w: 1.6, h: 1.4, rotate: 270, fill:{ type:'solid', color:'DE1D16' }}
)
```

**Comment by gitbrent** [comment]
Feature added:

<img width="345" alt="Screen Shot 2020-06-28 at 12 46 13" src="https://user-images.githubusercontent.com/7218970/85954472-62cd8080-b93d-11ea-9094-71d9fdc55c9c.png">

```javascript
slide.addShape(
  pptx.shapes.RIGHT_TRIANGLE,
  { x: 0.4, y: 4.3, w: 6.0, h: 3.0, fill: { color: '0088CC' }, line: { color: '000000', width: 3 },
    shapeName:'First Right Triangle'
  });
```

<img width="612" alt="Screen Shot 2020-06-28 at 12 44 16" src="https://user-images.githubusercontent.com/7218970/85954459-37e32c80-b93d-11ea-9ad1-00c942832994.png">
