### ISSUE TITLE
[Feature Request] z-order support

### ISSUE THREAD

**Issue by Offbeatmammal** [gitbrent/PptxGenJS#728]
Is it possible to add explicit z-order support when adding objects to a slide? Sometimes it's not possible (easy) to create them in the correct visibility hierarchy so having an override would be very helpful

**Comment by gitbrent** [comment]
Not at this time. 

Request doesn't meet the majority-of-users threshold and re-ordering objects involves lots of code.

Suggest you create local variables, fill them in whatever order you want, then pass to PptxGenJS.

**Comment by Offbeatmammal** [comment]
@gitbrent agree with the closure, it actually forced me to solve the problem a better way - as I'm [re-creating slide decks based on a template](https://github.com/Offbeatmammal/PPTXport), for anyone hitting this issue instead of simply iterating over objects:
 `For Each ob In osl.Shapes` where osl is the iteration through the slides
I use

      For i = 1 To osl.Shapes.Count
      Set ob = osl.Shapes(i)
        
which gives me the collection in presentation order
