### ISSUE TITLE
PptxGenJS in applications like Outsystem? 

### ISSUE THREAD

**Issue by danielthelamb** [gitbrent/PptxGenJS#732]
For my job it uses outsystem a low code platform.
It allows running javascript and various other things and when I try to use PptxGenJs it gives me 

`[ErrorScreen] Module name "stream" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded`

does anyone know how I can fix this?

**Comment by gitbrent** [comment]
Sorry, I'm unable to assist with implementation problems across various systems.

If you figure it out, please follow-up so other users may benefit.
