### ISSUE TITLE
Dependency on jszip breaks ES6 Module support

### ISSUE THREAD

**Issue by amitmerin** [gitbrent/PptxGenJS#733]
`pptxgen` has a dependency on `jszip`, which does not support ES6 modules.

The first line of `pptxgenjs\dist\pptxgen.es.js` is
```
import * as JSZip from 'jszip';
```
But jszip uses `requires()` and fails with
```
Uncaught ReferenceError: require is not defined
```

**Comment by gitbrent** [comment]
I'm unsure what to advise. The library works with React/Angular, et al.

**Comment by phun-ky** [comment]
@gitbrent almost 3 years later, I also have this issue:

```
[!] Error: 'default' is not exported by node_modules/jszip/lib/index.js, imported by node_modules/pptxgenjs/dist/pptxgen.es.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/pptxgenjs/dist/pptxgen.es.js (2:7)
1: /* PptxGenJS 3.11.0 @ 2022-08-06T19:31:52.331Z */
2: import JSZip from 'jszip';
          ^

```

What do you use to bundle this? Could there be a required config?
