### ISSUE TITLE
PptxGenJS 'HTML to PowerPoint' feature and integration with Angular

### ISSUE THREAD

**Issue by robertsoaa** [gitbrent/PptxGenJS#734]
I am receiving an error when trying to use the PptxGenJS 'HTML to PowerPoint' feature with Angular and target an html table element by its ID (example: pptx.tableToSlides("myHtmlTableID"); ). I replaced "myHtmlTableID" with the appropriate Table ID. The error is: Cannot read property 'forEach' of undefined
   
    at getSlidesForTableRows (pptxgen.es.js:863)
    at genTableToSlides (pptxgen.es.js:1287)
    at PptxGenJS.push../node_modules/pptxgenjs/dist/pptxgen.es.js.PptxGenJS.tableToSlides (pptxgen.es.js:6438)

PptxGenJS 'HTML to PowerPoint' feature can see the Html Table, but it is having an issue somewhere else. I tried to execute the same code on a few different tables.
![HTML to PowerPoint Angular PxxtxGenJS Error](https://user-images.githubusercontent.com/36463308/81496716-a550d600-9287-11ea-88bd-3e6e1d4b6fc6.PNG)

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

**Comment by gitbrent** [comment]
You need to check the table - this error means the first row doesn't exist.

I've patched the code to check for rows going forward.

**Comment by robertsoaa** [comment]
Fyi, my tables include rows, first row, second row. etc. The problem was the PptxGenJS application explicity checks for the thead and tbody tags to determine the first rows. My tables only included rows with no thead element. It is arguably bad syntax / bad form, but html will render tables without the thead tag.
I added the thead element plus the patch for issue #734 and the table now renders in the pptx (although it drops much of the styling, but that's the next problem to solve).

Sent from Yahoo Mail on Android 
 
  On Sun, May 10, 2020 at 12:51, Brent Ely<notifications@github.com> wrote:   


You need to check the table - this error means the first row doesn't exist.

I've patched the code to check for rows going forward.
