### ISSUE TITLE
PptxGenJS slide.addTable Feature's Rows Property Error

### ISSUE THREAD

**Issue by robertsoaa** [gitbrent/PptxGenJS#735]
PptxGenJS returns an error when executing slide.addTable. The rows property of type string[] is not assignable to the parameter of type 'tableRow[]'. This error started with the patch for issue #734. 

![Argument of type string is not assignable to parameter of TableRow Error](https://user-images.githubusercontent.com/36463308/81572033-b45f8300-9370-11ea-8331-90256bf29665.PNG)

![Argument of type string is not assignable to parameter of TableRow Error2](https://user-images.githubusercontent.com/36463308/81572052-b9bccd80-9370-11ea-82b3-e04d4279c31a.PNG)

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

**Comment by gitbrent** [comment]
Thanks for reporting this @robertsoaa 

The type defs were not good to begin with, hence the rows issue.

Fixed now in master branch.

```typescript
  let rows = [];
  rows.push(["First", "Second", "Third", "Fourth"]);
  rows.push([{ text: "TODO" }, { text: "optionsChk", options: { fontFace: "Arial" } }]);
  slide1.addTable(rows, { x: 1, y: 1 });
  slide1.addTable([[{ text: "cell 1" }]], { x: 1, y: 1 });
```

<img width="1055" alt="Screen Shot 2020-05-13 at 23 24 47" src="https://user-images.githubusercontent.com/7218970/81892628-30c0b480-9571-11ea-80f4-6a0a792d64fd.png">
