### ISSUE TITLE
Is it possible to read from excel file and create chart and have reference to original  excel file?

### ISSUE THREAD

**Issue by Amitloh** [gitbrent/PptxGenJS#736]
I want to use this library and it looks great but Is it possible to read from excel file and create chart and have reference to excel? I do see read data and read excel but I need data coming from some original excel and then have user refer to it for verification when they click on read data inside ppt slide.

**Comment by gitbrent** [comment]
1: Use the great `XLSX` library to read in an Excel doc, grab the rows you want
2. Show it to a user on-screen
3. Use the `addChart()` method to create a Presentation with charts
