### ISSUE TITLE
is it possible to store this on one drive or server folder

### ISSUE THREAD

**Issue by Amitloh** [gitbrent/PptxGenJS#737]

**Comment by Offbeatmammal** [comment]
yes. I have a script generating reports which get saved to a OneDrive folder which is shared with the user who needs to see the powerpoint

**Comment by gitbrent** [comment]
Save it via `write()` or `stream()`, then send it off to OneDrive via graph API or any modern method.

### [API Docs](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html)
