### ISSUE TITLE
Cannot instatiate PptxGenJS

### ISSUE THREAD

**Issue by LandadelJr** [gitbrent/PptxGenJS#738]
I want to embed pptxgenjs in an extension for Qlik, but cannot get it to work. Here is what I tried:

```javascript
define(['require',
             ...
      './pptxGenJS/dist/pptxgen.bundle'
    ],
   ...
   try {
   var pptx = new PptxGenJS();
   var slide = pptx.addSlide();
  } catch(e) {
    alert(e);
  } 
```

I get the error: "TypeError: pptx.addSlide is not a function"

I also tried the following to make sure, path is working:

```javascript

   try {
   var pptx = require("./pptxGenJS/dist/pptxgen.bundle");
   alert(pptx.version);
  } catch(e) {
    alert(e);
  } 
```

At least path seems ok, because I get the Version 3.2.0 shown.

Since my Javascript knowledge is limited so far, I would appreciate any help.

**Comment by gitbrent** [comment]
The bundle is for browsers. Instead, try require-ing one of the other `/dist` builds.

**Comment by LandadelJr** [comment]
Unfortunatly that doesn't make a change. I thought bundle for browsers would be OK, since Qlik Sense is a browser front-end and creates html.
I had a look throught the Chrome developer tools and also get the following error:

```javascript

Uncaught ReferenceError: JSZip is not defined
    at pptxgen.bundle.js:2

```

Maybe that is also the reason, why pptxgen doesn't work properly.

**Comment by gitbrent** [comment]
Closing as this is an implementation question, not an issue.
