### ISSUE TITLE
Allow percent-based line spacing

### ISSUE THREAD

**Issue by idris** [gitbrent/PptxGenJS#739]
`<a:spcPts>` is hardcoded here:
https://github.com/gitbrent/PptxGenJS/blob/5c6195d196ae35ddd886f1dd7daa05aa84e013de/src/gen-xml.ts#L852

If you allow `lineSpacing` to be a string or number, we could allow a percent like `"120%"`, which would translate to `<a:spcPct val="${Math.round(percent) * 1000}"/>` (where `percent = 120`)

**Comment by gitbrent** [comment]
Hi @idris 

If PowerPoint's UI does not have an option for line spacing as a percent, I feel the library should be consistent and not provide an API either.

<img width="535" alt="Screen Shot 2020-05-16 at 22 04 09" src="https://user-images.githubusercontent.com/7218970/82134786-34e31100-97c1-11ea-8600-8099783007e7.png">
