### ISSUE TITLE
hyperlink and font_face  problem

### ISSUE THREAD

**Issue by ZouhaierSebri** [gitbrent/PptxGenJS#74]
Hi @gitbrent  when trying to add font_face my pptx in damaged

slide.addText(
 [
  { text:'Visit the ' },
  { text:'PptxGenJS Project', options:{ font_face:'Times',hyperlink:{ url:'https://github.com/gitbrent/pptxgenjs', tooltip:'Visit Homepage' } } },
  { text:' !' },
 ],
 { x:0.5, y:4.0, w:9, h:1, margin:0.5, fill:'F1F1F1', font_size:18 }
);

![image](https://cloud.githubusercontent.com/assets/19344990/24919789/ae90f76c-1edc-11e7-898b-3262e9c80143.png)

when i comment this code it works

startInfo += '<a:uFill>'+ genXmlColorSelection('0000FF') +'</a:uFill>';

why you add this code ?
To change color hyperlink is not possible actually by a text option it is a general properties

**Comment by gitbrent** [comment]
Hi @ZouhaierSebri ,

Thanks for reporting this.

I'd taken code from a newer version of PowerPoint and didn't know that it had deleterious effects on older versions!

I've removed this line now and presentations continue to work as they did before in newer versions, so let me know if it works for you as well now.

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,

It works like a charm.
Thank you for the fix.
