### ISSUE TITLE
Question: Contributing to documentation

### ISSUE THREAD

**Issue by thamara** [gitbrent/PptxGenJS#740]
I was wondering if there's a way of contributing to the documentation of this API. I hit the same issue in #725 and an updated documentation would be helpful.
Also, I feel there are some improvements in the way the shapes are documented, for example, listing the available options for shape, and I would to do contribute, if it's possble.

**Comment by gitbrent** [comment]
Olá @thamara 

Absolutely, any work you could do to improve documentation would be appreciated.

The docs are in the `gh-pages` branch and are built using [Docusaurus](https://docusaurus.io/).

Basically, make pull requests with any given .md file under `docs` (npm run build creates the HMTL documentation).

**Comment by thamara** [comment]
Great! I haven't notice the `gh-pages` branch. I'll try to do some work on that later and will send the PRs. :D
