### ISSUE TITLE
Add 0 as number to slide via "addText()" method.

### ISSUE THREAD

**Issue by roman1bondarenko** [gitbrent/PptxGenJS#745]
Hi.

> https://github.com/gitbrent/PptxGenJS/blob/3dd977b200113559abb1ef80e899ac13c9d26858/src/gen-objects.ts#L828

I use method 'addSlide()' from class Slide to print numbers on presentation and found issue with '0'
If you put 0 as type number, it wouldn't print into slide.
Cause it handle '0' as false in if condition and replace it to empty string - ''

**Comment by ankon** [comment]
But why wouldn't you just put in `'0'` as _text_?

**Comment by gitbrent** [comment]
Agree with @ankon - typing shows it accepts a string, also `TableCell` accepts strings as well. I'd rather be consistent and assert that the `text` property will be a string.

<img width="333" alt="Screen Shot 2020-05-23 at 22 48 19" src="https://user-images.githubusercontent.com/7218970/82745249-cca7a880-9d47-11ea-9ae4-79b3a1c93519.png">
