### ISSUE TITLE
Bubble chart catAxisMajorUnit not working

### ISSUE THREAD

**Issue by dscdngnw** [gitbrent/PptxGenJS#747]
No matter what I try, the category axis ticks don't change. On seeing the chart properties, after ppt is generated, i can see in the axis options that major unit is 0.5 and not 1 even after setting the below option

My Options for bubble chart is: 
```javascript
let optionsBubble = {
      x: 0.6771654,
      y: 2.16535,
      w: 7.0511811,
      h: 3.468504,
      catAxisMajorUnit: 1.0,
      catAxisMaxVal: 2,
      catAxisMinVal: 0,
      catGridLine: {
            style : 'dash'
      },
      valAxisMajorUnit: 1,
      valAxisMaxVal: 3,
      valAxisMinVal: 1,
      valGridLine: {
            style : 'dash'
      },
```

Screenshot: 
![image](https://user-images.githubusercontent.com/65522659/82355744-3f4f1600-9a20-11ea-9982-cba0a4869ffc.png)

**Comment by gitbrent** [comment]
Fixed via Pull #938
