### ISSUE TITLE
Issue links in release notes are broken

### ISSUE THREAD

**Issue by pimlottc-gov** [gitbrent/PptxGenJS#749]
In the v3.2.0 release notes, the links to the issues resolved are broken.
https://github.com/gitbrent/PptxGenJS/releases/tag/v3.2.0

e.g.

```
https://github.com/gitbrent/PptxGenJS/issue/349
```

should be

```
https://github.com/gitbrent/PptxGenJS/issues/349
```

Note that you can also just write e.g. `#349` and it will be auto-linked: #349

**Comment by gitbrent** [comment]
Thanks @pimlottc-gov !

I've been cut-n-pasting `issue` for many releases now and never noticed :(

**Comment by pimlottc-gov** [comment]
Thanks for fixing the changelog, is it also possible to fix the links in the github release tags?   Those are still broken, e.g. https://github.com/gitbrent/PptxGenJS/releases/tag/v3.2.0

**Comment by gitbrent** [comment]
Release notes updated.
