### ISSUE TITLE
Shape line Diagonal

### ISSUE THREAD

**Issue by vanekar** [gitbrent/PptxGenJS#75]
Hello

Thanks for the beautiful control, is there an option to draw a line diagonally.

Regards
Anwar

**Comment by ZouhaierSebri** [comment]
Hi @vanekar ,
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');

var slide = pptx.addNewSlide();

// Misc Shapes
slide.addShape(pptx.shapes.LINE,      { x:0, y:0, w:13.33, h:7.5, line:'FF0000'});

pptx.save('Demo-Shapes');

and you will get 

![image](https://cloud.githubusercontent.com/assets/19344990/24951531/a1a45a68-1f6c-11e7-8e2b-12b682a3f3b3.png)

**Comment by gitbrent** [comment]
I've added "Diagonal Line" to the README and the demo.

You can draw a box as shown above and plot a line between the corners, or draw an actual line and rotate it:

`slide.addShape(pptx.shapes.LINE, { x:0, y:0, w:5.0, h:0, line:'FF0000', rotate:45 });`
