### ISSUE TITLE
No able to set dataLabelPosition for Doughnut Chart using pptxgen library. Please help me in this

### ISSUE THREAD

**Issue by sagarloona4180** [gitbrent/PptxGenJS#750]
Hi Team,
I'm triying to put Doughnut Chart using pptxGen library . But i'm not able to set the datalabels position outwards the chart.

**Comment by ReimaFrgos** [comment]
@sagarloona4180 this is not a valid configuration for a Doughnut chart in PowerPoint. You would need to use a Pie chart instead to achieve the outside data labels.

If it is critical to be a Doughnut, you could replicate the look by placing a circle over the middle of the Pie Chart.
