### ISSUE TITLE
I want to merge my generated presentation into already existing presentation how we can do that?

### ISSUE THREAD

**Issue by kuldeept70** [gitbrent/PptxGenJS#753]

**Comment by Offbeatmammal** [comment]
AFAIK you'd have to regenerate the existing presentation inline as part of the same task.
For my particular usecase I'm building a powerpoint macro that lets me [export from Powerpoint to PptxGenJS commands](https://github.com/Offbeatmammal/PPTXport) to build, but right now it's very focussed on the objects/formatting we're using so there might be better solutions (I was hoping to find a javascript way to read the PPTX but not found a great solution yet, hence the clunky macro)

**Comment by gitbrent** [comment]
Sorry, this feature is listed in the README as a wont-implement.  

Creating Master slides is very simple.

**Comment by kuldeept70** [comment]
Thanks for the reply, but actually my problem was that I am creating presentation using pptxgenJS, now I want to insert few slides from another presentation into my presentation.Is this possible? @Offbeatmammal  your solution is interesting but I need some direct java script solution.Currently I am doing it by converting slide(that i want to insert) into image and then adding it into my current presentation.But I know it will not work if slide(that i want to insert) contains some audio or video.

**Comment by gitbrent** [comment]
Not using pptxgenjs. This library only generates presentations, it has no input/read/parsing functionality for existing files.

**Comment by jsvishal45** [comment]
Any other library that can work with PptxGenJS ?

**Comment by Vixtorine** [comment]
Hello, I'm currently working on a similar project, were you successful? I'm having trouble.

**Comment by kuldeept70** [comment]
Hey! I managed to do this using office api of Microsoft. Please check this https://learn.microsoft.com/en-us/office/dev/add-ins/reference/overview/powerpoint-add-ins-reference-overview
