### ISSUE TITLE
How to generate a combo chart with 100% stacked area

### ISSUE THREAD

**Issue by BattiniSantthosh** [gitbrent/PptxGenJS#754]
![image](https://user-images.githubusercontent.com/24696729/83016194-30c7b680-a03f-11ea-9394-fd78c1411412.png)

![image](https://user-images.githubusercontent.com/24696729/83016400-813f1400-a03f-11ea-89d4-315e47509700.png)

**Comment by gitbrent** [comment]
Sorry, I dont have any demo code for this particular chart request.
