### ISSUE TITLE
Interface 'IObjectOptions' cannot simultaneously extend types 'ITableCellOpts' and 'ITextOpts'.

### ISSUE THREAD

**Issue by robertsoaa** [gitbrent/PptxGenJS#756]
ERROR in node_modules/pptxgenjs/types/index.d.ts:941:19 - error TS2320: Interface 'IObjectOptions' cannot simultaneously extend types 'ITableCellOpts' and 'ITextOpts'.
  Named property 'bullet' of types 'ITableCellOpts' and 'ITextOpts' are not identical.

941  export interface IObjectOptions extends IShapeOptions, ITableCellOpts, ITextOpts {

**Comment by gitbrent** [comment]
Thanks @robertsoaa 

I just noticed this last night.

Fixed now.
