### ISSUE TITLE
hyperlink and tooltip property is not working?

### ISSUE THREAD

**Issue by kuldeept70** [gitbrent/PptxGenJS#758]
I used this parameter { text: file.viewName + " ", options: { color: '3361FF', fontSize: 18, paraSpaceAfter: 18, hyperlink: { rId: 1, url: file.webUrl, tooltip: 'Visit File' } } } in slide.addText() ,but tooltip and hyperlink is not working.

**Comment by CraigH2013** [comment]
Having the same issue. I also noticed in the documentation it said that the type of value to use was a string, I'm assuming that's just a documentation error.

**Comment by gitbrent** [comment]
Thanks @kuldeept70 

The type defs were incorrect.

Updated result:
<img width="237" alt="Screen Shot 2020-06-02 at 23 29 32" src="https://user-images.githubusercontent.com/7218970/83595927-f4a5c180-a528-11ea-880a-3f0d3b44beec.png">

Usage:
```javascript
slide.addText("Hyperlinks:", { x:0.5, y:6.0, w:'90%', h:0.3, margin:0.123, color:'0088CC' });
slide.addText(
    [{ text: 'Link with Tooltip', options: { hyperlink: { url: 'https://github.com/gitbrent/pptxgenjs', tooltip: 'Visit Homepage' } } }],
    { x:0.5, y:6.4, w:3, h:0.6, margin:10, fill:'F1F1F1', fontSize:14, align:'center' }
);
slide.addText(
    [{ text: 'Link without Tooltip', options: { hyperlink: { url: 'https://github.com/gitbrent' } } }],
    { x:5.0, y:6.4, w:3, h:0.6, margin:10, fill:'F1F1F1', fontSize:14, align:'center' }
);
slide.addText(
    [{ text: 'Link to Slide #4', options: { hyperlink: { slide: '4' } } }],
    { x:9.5, y:6.4, w:3, h:0.6, margin:10, fill:'F1F1F1', fontSize:14, align:'center' }
);
```

<img width="1316" alt="Screen Shot 2020-06-02 at 23 32 28" src="https://user-images.githubusercontent.com/7218970/83596089-5ebe6680-a529-11ea-8fbc-496302ddffb2.png">

**Comment by gitbrent** [comment]
@CraigH2013 - the demo includes 2 hyperlinks on the same slide as your example shows and has no issues. The corruption may be caused by other objects.

**Comment by kuldeept70** [comment]
Hi @gitbrent , How I can get these changes? will l these changes appear in next release or I can just upgrade my package to see the changes?

**Comment by gitbrent** [comment]
@kuldeept70 - grab the newest `index.d.ts` file from the types directory and replace whats in your node_modules pptxgenjs folder currently for an immediate fix.

**Comment by CraigH2013** [comment]
> @CraigH2013 - the demo includes 2 hyperlinks on the same slide as your example shows and has no issues. The corruption may be caused by other objects.

Multiple on the same slide, yes. But I said in the same cell within a table.

**Comment by gitbrent** [comment]
@CraigH2013 - Ah, got it. Please open a new issue and i'll look into it.
