### ISSUE TITLE
chart `gridLineColor` is not working?

### ISSUE THREAD

**Issue by sijmenvos** [gitbrent/PptxGenJS#759]
The `gridLineColor` option is documented [here](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html#bar-data-line) but doesn't seem to work. Or maybe I am missing something?

**Comment by gitbrent** [comment]
Please provide the code you're using, the resulting slide and expected result.

**Comment by sijmenvos** [comment]
From [demo.js](https://github.com/gitbrent/PptxGenJS/blob/cd10585ea88f38433d94c9bdb5a7060b41760b4b/demos/common/demos.js#L1380):
```javascript
// SLIDE 7: Tornado Chart --------------------------------------------------------------
	function slide7() {
		var slide = pptx.addSlide({sectionTitle:'Charts'});
		slide.addNotes('API Docs: https://gitbrent.github.io/PptxGenJS/docs/api-charts.html');
		slide.addTable( [ [{ text:'Tornado Chart - Grid and Axis Formatting', options:gOptsTextL },gOptsTextR] ], gOptsTabOpts );

		slide.addChart(
			pptx.charts.BAR,
			[
				{
					name: 'High',
					labels: ['London', 'Munich', 'Tokyo'],
					values: [.20, .32, .41]
				},
				{
					name: 'Low',
					labels: ['London', 'Munich', 'Tokyo'],
					values: [-0.11, -0.22, -0.29]
				}
			],
			{
				x:0.5, y:0.5, w:'90%', h:'90%',
				valAxisMaxVal: 1,
				barDir: 'bar',
				axisLabelFormatCode: '#%',
				gridLineColor: 'D8D8D8',
				axisLineColor: 'D8D8D8',
				catAxisLineShow: false,
				valAxisLineShow: false,
				barGrouping: 'stacked',
				catAxisLabelPos: 'low',
				valueBarColors: true,
				shadow: {type:'none'},
				chartColors: ['0077BF','4E9D2D','ECAA00','5FC4E3','DE4216','154384','7D666A','A3C961','EF907B','9BA0A3'],
				invertedColors: ['0065A2','428526','C99100','51A7C1','BD3813','123970','6A575A','8BAB52','CB7A69','84888B'],
				barGapWidthPct: 25,
				valAxisMajorUnit: 0.2
			}
		);
	}
```

The option `gridLineColor: 'D8D8D8',`. In the resulting powerpoint the grid line colors of the graphs always seem to be #888888.

[result.pptx](https://github.com/gitbrent/PptxGenJS/files/4723518/result.pptx)

[expected.pptx](https://github.com/gitbrent/PptxGenJS/files/4723519/expected.pptx)

**Comment by gitbrent** [comment]
Thanks @sijmenvos 

Both `gridLineColor` and `axisLineColor` should've been removed back with v3.0.0

Please use `valGridLine` instead - it includes options for the size & style of the grid as well.

Ex:
```
catGridLine: { color: 'D8D8D8', style: 'dash', size: 1 },
valGridLine: { color: 'cc6699', style: 'dash', size: 1 }
```

<img width="1204" alt="Screen Shot 2020-06-07 at 00 10 39" src="https://user-images.githubusercontent.com/7218970/83960870-72ccd580-a853-11ea-9b8f-c7ad275fc8c5.png">

**Comment by sijmenvos** [comment]
Awesome, thank you!
