### ISSUE TITLE
Can we add iframe?

### ISSUE THREAD

**Issue by praveenv64** [gitbrent/PptxGenJS#76]
This is real good working, I have tried with adding text and all other options and come to know we can't add iframe inside

Is this feature is going to come, if yes, could you please let me know when it will be - Or if we have some other options to do the same, Please help me

Thanks,
Praveen

**Comment by gitbrent** [comment]
Hi @praveenv64 ,

Thanks for the question.

From what I can tell, the only options for iFrames are 3rd party products as iFrames aren't a core PowerPoint feature.  Given that, I do not have plans to support them.
