### ISSUE TITLE
How to use dataLabelFormatCode ?

### ISSUE THREAD

**Issue by mapapuche** [gitbrent/PptxGenJS#760]
Hello,

i'm trying to use dataLabelFormatCode, but i have some trouble ...

I am trying to do this : " If number is positive, add a '+' in suffix and add a '$' in prefix.
I'm using this link to help me : https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68?ui=en-us&rs=en-us&ad=us

Here my code :
    const chartConfig = {
      ...geometry,
      dataLabelColor: secondaryColor.split('#')[1],
      dataLabelPosition: 'outEnd',
      dataLabelFormatCode: '+0\;\;\;$',
    };

The problem is the '+' is correctly displayed, but not the $

![image](https://user-images.githubusercontent.com/64193148/83857399-372ef000-a71b-11ea-9db6-e410905a96d8.png)

Can you help please :) ?

**Comment by ReimaFrgos** [comment]
I assume you mean you want to prefix with a + and suffix with a $ e.g. +83$?

You're formatting should just be: 
`dataLabelFormatCode: '+0$'`
If you want to show decimals you could use: 
`dataLabelFormatCode: '+0.00$'`

Note this doesn't apply any form of formatting for a negative number if you want to display one, but can be added in.

**Comment by gitbrent** [comment]
<img width="488" alt="Screen Shot 2020-06-28 at 12 15 06" src="https://user-images.githubusercontent.com/7218970/85953861-1c762280-b939-11ea-9b5b-c03e5a85d4aa.png">
