### ISSUE TITLE
Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

### ISSUE THREAD

**Issue by zhangjiayu139** [gitbrent/PptxGenJS#762]
error image:
![image](https://user-images.githubusercontent.com/30860538/83994383-da387180-a988-11ea-8c57-932e9f16cc49.png)

code:
![image](https://user-images.githubusercontent.com/30860538/83994422-fa683080-a988-11ea-8952-0cfee37acb05.png)

vue-cll framework project

**Comment by ankon** [comment]
Looks a bit odd that you have a 'mock XMLHTTPRequest' in the stack traces. Is this part of a unit test or such? Can you add more details on how you are running the code there? And, maybe paste the code as code, and not as image?

**Comment by zhangjiayu139** [comment]
OK,,,
In my project, I'm using AXIOS to request data

`<template>
  <basic-container>
    <el-button type="primary" size="small"
               @click="downloadPPT()">下载PPT</el-button>
  </basic-container>
</template>

<script>
export default {
  data() {
    return {
      
    }
  },
  methods: {
    downloadPPT(){
      var pptx = new PptxGenJS();
				pptx.layout = 'LAYOUT_WIDE';
				//=====================================模板===================================
				pptx.defineSlideMaster({
				  title: 'MASTER_SLIDE',
				  bkgd:  'FFFFFF',
				  objects: [
				    { 'text':  { text:'问题：', options:{ x:0.2, y:0.5, fontSize: 19} } },
				    { 'image': { x:10.1, y:0.04, w:2.8, h:0.7, path:'http://127.0.0.1:8848/PPTExport/demo/index.html' } },
					{ 'rect':  { x: 0.0, y:0.8, w:'100%', h:0.02, fill:'f3f309' } },
					{ 'text':  { text:'零件供应商：', options:{ x:0.3, y:0.9, fontSize: 11} } },
					{ 'rect':  { x: 1.3, y:0.94, w: 2, h:0.23, fill:'f3f309' } },
					{ 'text':  { text:'发布日期：', options:{ x:3.5, y:0.9, fontSize: 11} } },
					{ 'rect':  { x: 4.3, y:0.94, w: 2, h:0.23, fill:'f3f309' } },
					{ 'text':  { text:'问题数量：', options:{ x:0.3, y:1.2, fontSize: 11} } },
					{ 'rect':  { x: 1.1, y:1.24, w: 2, h:0.23, fill:'f3f309' } },
					{ 'text':  { text:'问题来源：', options:{ x:3.5, y:1.2, fontSize: 11} } },
					{ 'rect':  { x: 4.3, y:1.24, w: 2, h:0.23, fill:'f3f309' } },
					{ 'text':  { text:'问题描述：', options:{ x:0.3, y:1.5, fontSize: 11} } },
				// ===================================内容区域======================================
					{ 'placeholder': {
							options: { name:'aaa', type:'body', x:0.3, y:1.8, w:6.3, h:1.5, line:'f3f309', lineSize: 0.02, fontSize: 11 },
							text: '问题描述信息'
						}
					},
					{ 'text':  { text:'照片：', options:{ x:0.3, y:3.3, fontSize: 11} } },
					{ 'text':  { text:'阶段：', options:{ x:2.3, y:3.3, fontSize: 11} } },
					{ 'rect':  { x: 3.3, y:3.34, w: 2, h:0.23, fill:'f3f309' } },
					{ 'placeholder': {
							options: { name:'bbb', type:'body', x:0.3, y:3.6, w:6.3, h:2, line:'f3f309', lineSize: 0.02, fontSize: 11 },
							text: '照片信息'
						}
					},
					{ 'rect':  { x: 0.0, y:6, w:'100%', h:0.02, fill:'f3f309' } }
					
				  ]
				  // slideNumber: { x:0.3, y:'90%' }
				});
				
				var slide = pptx.addSlide('MASTER_SLIDE');
				slide.addText('How To Create PowerPoint Presentations with JavaScript', { x:0.5, y:3.7, fontSize:18, color: pptx.SchemeColor.text1 });
				slide.addText('啛啛喳喳错错错错错错错错错错错错错错错错错错错错错错错错错错啛啛喳喳错错错错错错错错错错错错错错错错错错错错错啛啛喳喳错错错错错错!', { placeholder:'aaa' });
				// ====================================添加图片========================
        slide.addImage({path: 'https://mp.baomidou.com/img/relationship-with-mybatis.png', placeholder:'bbb'})
				
				pptx.writeFile();
    }
  }
};
</script>

<style>
</style>
`

**Comment by zhangjiayu139** [comment]
github demo
[https://github.com/zhangjiayu139/jsPPT.git](url)

**Comment by ankon** [comment]
Without going through your code: There definitely is something here -- you're depending on and using mock.js, which appears in your stack traces and in your package.json:

https://github.com/zhangjiayu139/jsPPT/blob/aaac0bc2597bc3c1376133a2946174fb4e9fdb45/package.json#L20

To be clear: This is _not_ a problem with PptxGenJS, but rather with your own code.

**Comment by zhangjiayu139** [comment]
Thank you very much for your reply
