### ISSUE TITLE
Table layout ignores colW when colspans are specified.

### ISSUE THREAD

**Issue by pandersen-uncharted** [gitbrent/PptxGenJS#764]
If I have a 3 column table but the header row has a cell that spans two columns colW is ignored with the error:

`"addTable: mismatch: (colW.length != data.length) Therefore, defaulting to evenly distributed col widths."`

The simple fix is that rather than looking at the number of items in the row the code should be summing up the colspans of the items in the row.

Here's a jsFiddle example that demonstrates the problem. (I expect three columns, the first 2" wide and the other two 0.5" wide.)
```javascript
let pptx = new PptxGenJS();
$('small').before('<code class="d-block text-black-50 mb-3">(pptxgenjs version: ' + pptx.version + ')</code>');

// Simple Slide
window.doDemo = function do7cells() {
  let pptx = new PptxGenJS();
  let slide = pptx.addSlide();
  let cells = [];
  cells.push({
    text: 'Wide Column',
    options: {
      color: 000000,
      bold: true,
      align: 'center',
    }
  });
  cells.push({
    text: 'Spanning header',
    options: {
      color: 000000,
      bold: true,
      align: 'center',
      colspan: 2
    }
  });

  let rows = [];
  rows.push(cells);
  cells = [];

  cells.push({
    text: 'Row label (long)',
    options: {
      color: 000000,
    }
  });

  cells.push({
    text: '1',
    options: {
      color: 000000,
    }
  });

  cells.push({
    text: '2',
    options: {
      color: 000000,
    }
  });
  rows.push(cells);

  let tableOptions = {
    x: 0,
    y: 0,
    w: 3,
    h: 2,
    colW: [2.0, 0.5, 0.5]
  };

  slide.addTable(rows, tableOptions);

  pptx.writeFile();
}
```

And this is what I get:
<img width="375" alt="Screen Shot 2020-06-10 at 7 35 28 AM" src="https://user-images.githubusercontent.com/28305358/84263171-fc4b0480-aaec-11ea-9d45-ffb41b381af9.png">

**Comment by pandersen-uncharted** [comment]
BTW, I tried working around this by adding an extra, hopefully invisible, cell in the header row with a colspan of 0, but it was still shown.

**Comment by gitbrent** [comment]
What version are you using?

**Comment by pandersen-uncharted** [comment]
We're using 3.1.1 but the example above was built on your jsFiddle example which I believe is running 3.2.1.

**Comment by gitbrent** [comment]
Please try using the newest codebase (v3.3.0-beta) - i believe this issue has been resolved.
#651 #679

**Comment by pandersen-uncharted** [comment]
Is there any way to get this as an npm? Our build can't be easily changed to ingest PPTXGenJS any other way. Or is there a jsFiddle environment I could try?

**Comment by ReimaFrgos** [comment]
Can confirm this issue no longer exists in the current build. My local version 
`/* PptxGenJS 3.3.0-beta @ 2020-06-11T04:13:39.290Z */`
produces the table looking correct as expected.

**Comment by gitbrent** [comment]
@pandersen-uncharted - if you're unable to update the files under `/dist` in your current node_modules folder, then you'll have to wait for v3.3.0 to be released.
