### ISSUE TITLE
Setting dataLabelPosition to a line chart causes latest office application to ask for repair

### ISSUE THREAD

**Issue by artdomg** [gitbrent/PptxGenJS#768]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.1 ]

Please specify what version(s) of PowerPoint you are targeting: [16.37 (2020)]

### Expected / Desired Behavior / Question
*PPTX files should be able to open on Microsoft PowerPoint*

### Observed Behavior
When adding a line chart with dataLabelPosition set, Microsoft Office application asks to repair the file and fails to do it.

### Code sample
`
slide.addChart(
      ppt.ChartType.line,
      [
        {
          name: 'Foo',
          labels: ['bar'],
          values: [1]
        }
      ],
      {
        dataLabelPosition: 'bestFit'
      }
    );
`

**Comment by gitbrent** [comment]
There are lots of demo charts that utilize the `dataLabelPosition` option, so it's likely that 'bestFit' doesn't work well with Line Charts.

**Comment by ReimaFrgos** [comment]
bestFit isn't a valid label position for line charts:

![image](https://user-images.githubusercontent.com/14120424/84733242-4857e680-afd0-11ea-9d84-16a6c6a3dd42.png)

It's used for Pie and Doughnut charts

**Comment by gitbrent** [comment]
Fixed via Pull #938
