### ISSUE TITLE
Image with hyperlink

### ISSUE THREAD

**Issue by plopez7** [gitbrent/PptxGenJS#77]
Is posible to insert an image with hyperlink???

I ask that for insert an excel image [(example)](http://www.internetadvantage.es/wp-content/uploads/2013/02/excel.png) and add that a hyperlink to download an excel file previously uploaded.

Thanks in advance.

**Comment by gitbrent** [comment]
Hi @plopez7 ,

Thanks for the feature request.

Image hyperlinks are now available in the latest codebase.  I've also updated the documentation and provided an example in the demo page.

Example:
```
// Image with Hyperlink
slide.addImage({
  x:1.0, y:1.0, w:8.0, h:4.0,
  hyperlink:{ url:'https://github.com/gitbrent/pptxgenjs', tooltip:'Visit Homepage' },
  path:'images/chart_world_peace_near.png',
});
```

**Comment by plopez7** [comment]
Thanks a lot for this one.
