### ISSUE TITLE
Add background image individually for each slide

### ISSUE THREAD

**Issue by DonnaZukowskiPfizer** [gitbrent/PptxGenJS#778]
Hi there,

I know there are Master Slides but we actually need to just add a background image to the slide.

Can this be done?

Thank you,
Donna

**Comment by gitbrent** [comment]
@DonnaZukowskiPfizer 

Sure, use any background you'd like: either via base64 (`data`) or a link (`path`).

Master with link example:
```javascript
pptx.defineSlideMaster({
    title: 'BKGD_SLIDE',
    background: { path:'https://raw.githubusercontent.com/gitbrent/PptxGenJS/master/demos/common/images/starlabs_bkgd.jpg' },
})
```

Starting with v3.3.0, slide background:
```javascript
let slide1 = pptx.addSlide();
slide1.background = { path:'some.img' }
```
<img width="476" alt="Screen Shot 2020-06-23 at 21 00 10" src="https://user-images.githubusercontent.com/7218970/85488974-df0a4180-b594-11ea-97f3-dc1e22d1f997.png">
