### ISSUE TITLE
Recreating slides using "shrinkText" but positions/font-sizes don't match

### ISSUE THREAD

**Issue by DonnaZukowskiPfizer** [gitbrent/PptxGenJS#779]
Hi there,

Thank you for all your help and great tool!

I have to recreate slides from PowerPoint into this tool. I'm frustrated because the numbers for positioning and font sizes I'm seeing and using in PowerPoint don't line up correctly when I place the coordinates and sizes into your code.

I am going from the top-left for both. I'm off like by inches and the font in your code seems larger.

I have quite a bit to do. How can I accurately replicate the sizes/positioning from PowerPoint?

Thanks,
Donna

**Comment by gitbrent** [comment]
@DonnaZukowskiPfizer 

You'll have to be more specific. I reproduced my corporate template precisely...

Have you looked at `/demos`?

**Comment by DonnaZukowskiPfizer** [comment]
Hi there. Thank you for your quick response.

I make sure that I'm dealing with the same slide size (on-screen show (16:9), and viewing at 100% for both, the original and what the program generates.

It's the fonts. You have shrink text but there's no scaling? If I use "shrink test" and put in the original font-size 44px, the original is at 37 with 44 as the size, but the generated slide isn't.

It sounds confusing. I'm no PowerPoint expert but I had to remove "shrink text" from the generated slide and set it at 33 to make it look like the original.

Hope that makes sense.

Donna

**Comment by gitbrent** [comment]
Can you provide the code that produced your example?

**Comment by DonnaZukowskiPfizer** [comment]
Hi, sorry it took so long. Very busy. Thank you for keeping this open,

Here is the code of the above. One thing I noticed is that the text isn't shrinking to fit the box as well. This will be important.

```
    var agendaObjectiveOutcome = {
        h: 1.04,
        w: 7.17,
        x: 2.5,
        y: 0.12,
        valign: 'top',
        shrinkText: true,
        fontFace: 'Arial',
        //fontSize: 10,
        fontSize: 12,
        align: 'left',
        color: '000000',
        margin: [2.88, 5.76, 2.88, 5.76],
        isTextBox: true,
        lineSpacing: 14
    }

    var slideOverview = pptx.addNewSlide('AGENDA_OVERVIEW_SLIDE');
    slideOverview.addText(this.$t("label.agenda"), { x: .33, y: 0.27, w: 1.84, h: 0.69, fontSize: 30, bold: true, valign: 'top', align: 'left', fontFace: 'Arial', color: '012496' });
    slideOverview.addText(
        [
            { text:this.$t("label.meetingObjectivePurpose"), options:{ color:'0078d4', bold: true, paraSpaceBefore: 7 } },
            { text:this.agenda.objective.replace(/<(.|\n)*?>/g, ''), breakline:true },
            { text:this.$t("label.meetingExpectedOutcomes"), options:{ color:'0078d4', bold: true, paraSpaceBefore: 7 }, shrinkText:true },
            { text:this.agenda.outcome.replace(/<(.|\n)*?>/g, '')}
        ],
        agendaObjectiveOutcome
    );
```
The this.$t("label.meetingObjectivePurpose") you can substitute with just text. This is a translator as it has to go into different languages.

One last question....
For margin, you have it as CSS values which are top, right, bottom, left. But if I put in it in the margins this way, it's not the same. Can you please verify?

Thank you again for your speedy response and a great tool.

Donna

**Comment by ReimaFrgos** [comment]
@gitbrent this is working as coded, but there's some logic missing in PptxGenJS to calculate what size the text should scale to.

With the current implementation you have:
```
// F: NEW: Add autofit type tags
if (slideObject.options.shrinkText)
    bodyProperties += '<a:normAutofit fontScale="85000" lnSpcReduction="20000"/>'; // MS-PPT > Format shape > Text Options: "Shrink text on overflow"
```
This is hard coding the scale to 85%. When running the sample provided above into overflow it generates at 10pt instead of 12 point which is correct for 85% scaling. Run it at 20, it scales to 17. Also consistent with the 44 to 37 mentioned by @DonnaZukowskiPfizer 

Ideally for this to function properly you'd need to make fontScale="" a variable and calculate what that scale should be based on the size of the text box, how much text you're trying to enter, and what font size has been specified.

**Comment by gitbrent** [comment]
@ReimaFrgos - great catch! I added that line without ever realizing that the `fontScale` was hard-coded...

**Comment by DonnaZukowskiPfizer** [comment]
I there. For the above to scale, how do I implement that into my code?

Thanks,
Donna

**Comment by gitbrent** [comment]
@ReimaFrgos - this took way more time than i thought it would!!
- New `fit` option created using standard PPT values
- `autoFit` and `shrinkText` deprecated
- new demo page created
<img width="957" alt="Screen Shot 2020-07-13 at 21 35 44" src="https://user-images.githubusercontent.com/7218970/87504560-74e13b80-c62c-11ea-8b13-c996a2b2df15.png">

@DonnaZukowskiPfizer - long story short, see the note here:
<img width="1195" alt="Screen Shot 2020-07-14 at 23 37 11" src="https://user-images.githubusercontent.com/7218970/87504495-3ea3bc00-c62c-11ea-8dbc-dceb7d197747.png">

**Comment by kracas** [comment]
Hi,

Sorry for necromancing, but maybe you could add an option for the user to optionally provide fontScale and lnSpcReduction values? In many cases we can know these just by checking the values after PowerPoint calculates them. 
Could look something like this:
```
if (slideObject.options.fit) {
	if (slideObject.options.fit.type === 'none') bodyProperties += ''
	else if (slideObject.options.fit.type === 'shrink') bodyProperties += `<a:normAutofit${slideObject.options.fit.fontScale && ` fontScale="${}"`}${slideObject.options.fit.lnSpcReduction && ` lnSpcReduction="${slideObject.options.fit.lnSpcReduction}"`}/>`
	else if (slideObject.options.fit.type === 'resize') bodyProperties += '<a:spAutoFit/>'
}
```

**Comment by kracas** [comment]
Hi, 

Sorry for necromancing. Maybe you could give an option for the user to optionally provide the fontScale and lnSpcReduction values? It would be useful in cases when the user can calculate the scaling factor.
The code could looks something like this:
```
if (slideObject.options.fit) {
    if (slideObject.options.fit.type === 'none') bodyProperties += ''
    else if (slideObject.options.fit.type === 'shrink') bodyProperties += `<a:normAutofit${!!slideObject.options.fit.fontScale && ` ${slideObject.options.fit.fontScale}`}${!!slideObject.options.fit.lnSpcReduction && ` {slideObject.options.fit.lnSpcReduction}`}/>`
    else if (slideObject.options.fit.type === 'resize') bodyProperties += '<a:spAutoFit/>'
}
```
