### ISSUE TITLE
Can't override margin with 0

### ISSUE THREAD

**Issue by scottmtraver** [gitbrent/PptxGenJS#78]
https://github.com/gitbrent/PptxGenJS/blob/eefae75701f84976c900c5d8d50dd27ccdc79824/dist/pptxgen.js#L2477

One cannot override options margin with a 0 because it is JS 'falsey' and the 0.5 is the result of this line. I will fix it soon when I get the chance.

**Comment by gitbrent** [comment]
Hi @scottmtraver ,

Thanks for reporting this!

I've fixed the issue in both `addTable()` and `addSlidesForTable()`.
