### ISSUE TITLE
Inserting Images into Placeholders

### ISSUE THREAD

**Issue by ChrisHastieIW** [gitbrent/PptxGenJS#780]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.1]

Please specify what version(s) of PowerPoint you are targeting: [PowerPoint for Microsoft 365 MSO (16.0.12821.20328) 64bit]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am trying to insert images into placeholders and think I must have the syntax wrong, but cannot find an example in the docs. I have successfully leveraged placeholders for titles. May you please provide a code sample for inserting an image into a placeholder? I've included my attempt in the steps to reproduce.

### Observed Behavior
Instead of landing in the placeholder areas, the images all stack on top of each other in the top left corner, as if the placeholder cannot be found

### Steps to Reproduce
Add a placeholder using this code (I've removed surrounding code):
```js
{
    placeholder: {
      options: {
        name: "image1", type: "image",
        x: "4%",
        y: "12%",
        w: "92%",
        h: "38%"
      }
    }
  }
```
Try to populate the placeholder with an image:
```js
image = {dataURL = "data:image/png;base64,iVBORw0KGgo[...]", position = 1}

slide.addImage({ data: image.dataURL}, { placeholder: `image${image.position}` })
```

The following image shows both my placeholder, and the image sitting in the top left corner:
<img width="219" alt="2020-06-25_14h40_16" src="https://user-images.githubusercontent.com/47250945/85731593-8d77c900-b6f2-11ea-8a98-ab4729e8a0c7.png">

**Comment by ReimaFrgos** [comment]
@ChrisHastieIW Minor syntax issue. data and placeholder should be in the same object. Update this and you should be fine.
```
slide.addImage({ data: image.dataURL,  placeholder: `image${image.position}` })
```

**Comment by ChrisHastieIW** [comment]
Fantastic, thanks @ReimaFrgos!  I'll give it a try this week.

Cheers

**Comment by ChrisHastieIW** [comment]
Apologies for taking a bit longer to get back. Happy to confirm this works, thanks @ReimaFrgos

**Comment by gitbrent** [comment]
Thanks guys.
