### ISSUE TITLE
[BUG] DXA & EMU calculations are not safe

### ISSUE THREAD

**Issue by CroniD** [gitbrent/PptxGenJS#781]
Hi there,

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.1]

Please specify what version(s) of PowerPoint you are targeting: [2019 & 365]

### Expected / Desired Behavior / Question

Numbers are set in points or inchs, but they get re-calculated to DXA & EMU. Those two units must be integer values (as far as I can tell). In `gen-xml.ts` are a lot of places with unsafe calculation. E.g. https://github.com/gitbrent/PptxGenJS/blob/master/src/gen-xml.ts#L367 `w="${cellOpts.border[obj.idx].pt * ONEPT}"`. One must ensure that the resulting value is rounded to an integer correctly.

```javascript
w="${Math.round(cellOpts.border[obj.idx].pt * ONEPT)}
```
That should do the trick. :)

### Observed Behavior

I generate PPTX files by code, which involves calculations for x, y, width & height values, font sizes etc. Sometimes there are values with fractions, which are then problematic when PptxGenJS converts the values to DXA or EMU values, but without rounding the result to integer. MS PowerPoint then detects errors in the file and tries to correct them, but most of time in a way that destroys the content and layout.

### Steps to Reproduce

It's not easy to reproduce because of how floating-point calculation are handled in JS, but I hope one understands the issue here.

**Comment by gitbrent** [comment]
Thanks @CroniD - I just added this line a couple days ago totally forgot to round it :)

All ONEPT calculations are method-driven now.

**Comment by michaelcmelton** [comment]
@gitbrent Just downloaded v3.3-beta for use today, and I'm not sure that the EMU calculations for rowHeights on tables is updated properly. The EMUs are still set as a floating point decimal at a certain number of rows, throwing a corruption error on the file. If I'm missing something and the fix hasn't been published to dist/ yet, please let me know!

**Comment by gitbrent** [comment]
Can you be more specific about where floating point decimals are created?

**Comment by michaelcmelton** [comment]
Specifically, the only issues I've seen is on this line: https://github.com/gitbrent/PptxGenJS/blob/244194bf7e5353505b2e1b4cfcf8b9e76c83ad42/src/gen-xml.ts#L300

When specifying a height property on a table, the number of table rows may cause the intRowH variable to calculate out to any number of decimal points.

**Comment by gitbrent** [comment]
Thanks @michaelcmelton - i've updated the code to address this
