### ISSUE TITLE
Getting a new line even if space availabe in table cell.

### ISSUE THREAD

**Issue by jsvishal** [gitbrent/PptxGenJS#787]
The last row has one extra newline character even if this cell has 4 extra characters available.

Tried with margin:0 but no luck

If we press backspace. we get the data in one line
![image](https://user-images.githubusercontent.com/7326080/86036446-84bd2500-ba5b-11ea-9fcc-ff09ce6a8d13.png)

**Comment by gitbrent** [comment]
Please see `/demos` and the docs on using different line/char weights.

**Comment by chrisjaimes** [comment]
Having the same issue here! I tried `autoPageCharWeight` and `autoPageLineWeight` values but still getting line breaks on table cells

**Comment by Ciabas** [comment]
Any luck?
