### ISSUE TITLE
dataLabelPosition "t" in Bar chart is crashing ppt in latest MS office Power Point

### ISSUE THREAD

**Issue by jsvishal** [gitbrent/PptxGenJS#788]
dataLabelPosition with option "t" crashing MS office PPT.

Chart Type: BAR

### Category
- [ ] Enhancement
- [ ] Bug 

### Version
3.3.0
version(s) of PowerPoint we are targeting: [   latest MS office      ]

### Expected / Desired Behavior / Question
dataLabelPosition with option "t" crashing MS office PPT.

### Steps to Reproduce
dataLabelPosition with option "t" 
Chart Type: BAR

**Comment by ReimaFrgos** [comment]
`dataLabelPosition: "t"` is not supported by bar charts. "t" is for use with bubble charts.

Guessing what you are after is Outside End?
`dataLabelPosition: "outEnd"`

**Comment by gitbrent** [comment]
Fixed via Pull #938
