### ISSUE TITLE
Table outer Border support

### ISSUE THREAD

**Issue by jsvishal** [gitbrent/PptxGenJS#791]
How can i show OUTER border in a table along with cell border?
![image](https://user-images.githubusercontent.com/7326080/86540051-808f7c80-bf1f-11ea-98c2-b3db55e7ca14.png)

### Category
- [ ] Enhancement
- [ ] Bug
- [-] **Question**
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [       3.3.0  ]

Please specify what version(s) of PowerPoint you are targeting: [    latest     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*We should get the support of OUTER border in table*

### Observed Behavior
*Not able to add table border and cell border all together*

**Comment by ReimaFrgos** [comment]
You can set each individual border on a cell. Set your default border style for the table, then for the cells on the outside set the border at cell level.

**Comment by jsvishal** [comment]
This will be very tricky. We need to track corner cells for border

**Comment by ReimaFrgos** [comment]
I build most of my tables this way. 
Load all your data into an array first, and then run it through a loop that applies the options based on row, all middle rows, last row.

This handles identifying the corners and styling approproiately

**Comment by gitbrent** [comment]
There is no setting in PowerPoint for an overall table border, so you'll need to follow Reima's guidance and create them as needed.
