### ISSUE TITLE
how to assign a slide master to a section?

### ISSUE THREAD

**Issue by ghost** [gitbrent/PptxGenJS#797]
I was excited to see that Sections are supported. As I couldn't find any documentation on how they work, I was wondering how I assign a slide to a section, as well as applying a slide master, at the same time.

The only mention of sections is [here](https://github.com/gitbrent/PptxGenJS/issues/349), and from that I can get them working as such, however the slide is not using a slide master:

```
pptx.addSection({ title: 'Presentation' });]
slide = pptx.addSlide({sectionTitle:'Presentation'});
```

The following results in the slide master-formatted slide being added in a section called 'Default-1', _underneath_ the newly created 'Presentation' section (rather than within it).

```
pptx.addSection({ title: 'Presentation' });
slide = pptx.addSlide('Template'); //<<Template is the name of slide master with formatting
```

The following has the same effect:

```
pptx.addSection({ title: 'Presentation' });
slide = pptx.addSlide('Template', {sectionTitle:'Presentation'}); //<<Template is the name of slide master with formatting
```

Thanks for any guidance here.

**Comment by gitbrent** [comment]
Whoops!! Docs were never produced for this feature.

Fixed now!

### [Sections](https://gitbrent.github.io/PptxGenJS/docs/sections)
