### ISSUE TITLE
Tiny: 'catAxisMajorTickMark' missing in API documentation

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#799]
You can set it to 'out' or 'none' I think. https://gitbrent.github.io/PptxGenJS/docs/api-charts.html

**Comment by ReimaFrgos** [comment]
There are 4 valid options:
- cross = The tick mark will cross the axis
- in = the tick mark will be inside the plot area
- out = the tick mark will be outside the plot area
- none = there will be no tick mark

**Comment by gitbrent** [comment]
Thanks @Slidemagic - i'm updating the docs for v3.3.0 now, so i'll get this added.

FYI: The typescript defs that went out with 3.3.0 have it included and with the correct available options (thanks @ReimaFrgos )

<img width="601" alt="Screen Shot 2020-08-17 at 21 47 27" src="https://user-images.githubusercontent.com/7218970/90464656-6c6c9c80-e0d3-11ea-86e0-1604997debe4.png">

**Comment by gitbrent** [comment]
Whoops, this fell off the radar... docs are fixed now.
