### ISSUE TITLE
autopage and colspan

### ISSUE THREAD

**Issue by Szymon-dziewonski** [gitbrent/PptxGenJS#80]
Hello, I think this is a bug when in options table is autoPage: false then colspan doesn't work

example from demo plus autoPage option 

```
    var tabOpts1 = {
      autoPage: false,
      x: 0.5,
      y: 1.1,
      w: '90%',
      h: 2,
      fill: 'F5F5F5',
      color: '3D3D3D',
      font_size: 16,
      border: {pt: 4, color: 'FFFFFF'},
      align: 'c',
      valign: 'm'
    };
    var arrTabRows1 = [
      [{text: 'C1 -> D1', options: {colspan: 2, fill: '99FFCC'}}],
      ['D2', 'E2'],
      ['D3', 'E3']
    ];
    console.log(arrTabRows1)
    // NOTE: Follow HTML conventions for colspan/rowspan cells - cells spanned are left out of arrays - see above
    // The table above has 6 columns, but each of the 3 rows has 4-5 elements as colspan/rowspan replacing the missing ones
    // (e.g.: there are 5 elements in the first row, and 6 in the second)
    slide.addTable(arrTabRows1, tabOpts1);
```

Result
![image](https://cloud.githubusercontent.com/assets/2566152/25847995/be7f4984-34b8-11e7-8d99-e164499a4663.png)

Plugin cuts second row
Hope this helps

**Comment by gitbrent** [comment]
Hi @Szymon-dziewonski ,

Thanks for reporting this!

The logic used to determine total number of cols to iterate over was different in the paging function versus the non-paging functions, hence the disparity.

![screen shot 2017-05-17 at 21 43 15](https://cloud.githubusercontent.com/assets/7218970/26184334/e9c2d5f6-3b49-11e7-8390-cd98be278488.png)
