### ISSUE TITLE
dataLabelFormatCode appears to be getting overwritten in Pie and Donut charts

### ISSUE THREAD

**Issue by cronin4392** [gitbrent/PptxGenJS#803]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.1]

Please specify what version(s) of PowerPoint you are targeting: [N/A]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

The `dataLabelFormatCode` option is respected.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a suggestion or asking a question delete this section.*

`dataLabelFormatCode` is `"0%"` in Pie charts even when a custom `dataLabelFormatCode` option is passed.

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question delete this section.*

Set `dataLabelFormatCode` on a pie chart to `"##.#%"`

Thank you for your feedback!

**Comment by cronin4392** [comment]
Should be fixed by https://github.com/gitbrent/PptxGenJS/pull/802

**Comment by gitbrent** [comment]
Fixed via Pull #802 @cronin4392
