### ISSUE TITLE
Header Auto Incrementing Slides Generating

### ISSUE THREAD

**Issue by sajikuttan** [gitbrent/PptxGenJS#804]
Problem: 

According to my requirement in the slide header "Information Data (1/2)" this should be dynamic.

like for example I had created a JSON table and if the data in JSON exceeds the slide it will get print on another slide, then above header information should dynamically get build.

Example :  
             slide 1 (header) - Information Data (1/2)
             slide 2 (header) - Information Data (2/2)
             slide 3 (header) - Information Data (3/2)
            ...... and so on.

this is not possible as of now please check this issue and help me to sort out the problem

Thank you for reporting an issue, suggesting an enhancement, or asking a question.
We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Comment by gitbrent** [comment]
This is possible in v3.3.0 via `addTable()` `autoPageHeaderRows` option.

<img width="768" alt="Screen Shot 2020-08-17 at 21 43 56" src="https://user-images.githubusercontent.com/7218970/90464405-db95c100-e0d2-11ea-8bc8-c359e662c05e.png">


<img width="1602" alt="Screen Shot 2020-08-17 at 21 41 05" src="https://user-images.githubusercontent.com/7218970/90464246-8194fb80-e0d2-11ea-9264-5aaabdb6a296.png">
