### ISSUE TITLE
[ENHANCEMENT] Support soft-breaks in text formatting

### ISSUE THREAD

**Issue by memorsolutions** [gitbrent/PptxGenJS#805]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.3.0 latest master branch]

Please specify what version(s) of PowerPoint you are targeting: [2016 and up]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Currently there is no way to add text that uses a soft-break (i.e. using <Shitf-Ret> in PowerPoint) to add text on the next line without beginning a new paragraph (bullet, etc.). Desire a means to produce something like this:

- This is a bullet with a
  continuation line via soft-break

### Observed Behavior
Only hard-breaks are currently supported.

Suggested implementation is to add a a new option to TextOptions named "softBreakBefore". Setting this option will cause the addition of a "<a:br/>" element before the text run that gets created for the IText item.

I have a PR implementing this that I will submit.

**Comment by gitbrent** [comment]
This will be available in v3.5.0 thanks to @memorsolutions via Pull #806
