### ISSUE TITLE
Does not work on Firefox for Mac, no issues on Firefox for windows.

### ISSUE THREAD

**Issue by alexanderdevm** [gitbrent/PptxGenJS#81]
Does not work, as in firefox for mac does not download the ppt file.

**Comment by gitbrent** [comment]
Hi @alexanderdevm,

I'm not able to reproduce this: I downloaded Firefox, opened the local `pptxgenjs-demo.html` page, clicked the Basic Slide Demo button and a PowerPoint was opened in Keynote.

Do you see any output in the Console that would indicate the issue?

**Comment by alexanderdevm** [comment]
After upgrading firefox to the latest version 53 on my first Mac, the issue disappeared, and i was able to reproduce the issue on older version of Firefox on different Mac.

- First Mac,, Mac sierra 10.12.4, Firefox 53.0
- Second Mac,  Mac sierra 10.12.4 , Firefox 48.0.4

I have also tried local pptxgenjs-demo.html, and the page on your demo portal.

So it looks like unless your of Firefox 53 Mac, you will run into this issue.

**Comment by rwhitmore90** [comment]
I have noticed this on Firefox for windows version 44 and 46. No errors on the console but when I started to look through the save procedure I noticed the blob URL would begin with blob:null/. Could that be the issue?

As soon as I upgraded Firefox, issue disappeared. Unfortunately my client has either Firefox 46 or IE11. IE11 works for PptxGenJS but my requirements are to convert a d3 svg into a png and then place into a powerpoint file which does not work in IE11.

**Comment by gitbrent** [comment]
Hi @alexanderdevm @rwhitmore90,

Thanks for reporting this.

It looks like the element is being removed before Firefox can grab it, as seen in this [StackOverflow answer](http://stackoverflow.com/a/30708820/3027591).

I've added a delay before removing the element which should fix the issue.

Please try the using the latest code and let me know how it goes.

**Comment by rwhitmore90** [comment]
It fixed it for me, thank you!

**Comment by gitbrent** [comment]
Thanks guys!
