### ISSUE TITLE
[Enhancement] Support different underline style

### ISSUE THREAD

**Issue by wangfengming** [gitbrent/PptxGenJS#811]
Need to support different underline style

### Category
- [ x ] Enhancement

### Version

Please specify what version of the library you are using: [ 3.2.1 ]

Please specify what version(s) of PowerPoint you are targeting:  [ 16.39 (20071300) ]

### Expected / Desired Behavior / Question

![image](https://user-images.githubusercontent.com/11853824/88517628-b658ea00-d021-11ea-8451-957311e4cf37.png)

```typescript
{
underline?: boolean;
}
```
should change to
```typescript
enum UnderlineType = {
  single = 'sng',
  wave = 'wave',
  // ...
}
{
underline?: boolean | UnderlineType;
}
```

**Comment by gitbrent** [comment]
This is done via Pull #854 in v3.5.0
