### ISSUE TITLE
Does it  provide the excel data for the charts and also select which columns to display?

### ISSUE THREAD

**Issue by smurfs2549** [gitbrent/PptxGenJS#814]
Thank you for create this amazing library!

We want pick the top 15 and then combine the remainder into an "Other" section. But when we right click on a ppt chart and select "edit data in excel". we do not want to "destroy" this extra information. Is there  a way to provide the excel data for the charts or any other solutions?

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.6.0   ]

**Comment by gitbrent** [comment]
You may want to try v3.x as 2.x is pretty old, otherwise, no i just create the XLSX per the standard.
