### ISSUE TITLE
dataLabelPosition is not working in Multi Type Charts

### ISSUE THREAD

**Issue by Adt-SakshamSethi** [gitbrent/PptxGenJS#815]
### Category
- Bug

### Version

Please specify what version of the library you are using: [  Latest  ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

### Expected / Desired Behavior / Question
I am giving dataLabelPosition : 't' in Mutli type charts (Line chart + Bar chart).
Corrupted PPT is created.

### Steps to Reproduce
Add a multi type chart and add dataLabelPosition : 't' and after downloading the PPT when you open that PPt, it asks to repair the file.

Can you please provide urgent solution for the same ?

**Comment by ReimaFrgos** [comment]
't' is not a valid dataLabelPosition for a barChart. 
You can use it for the LineChart but should be: 'ctr','inBase', 'inEnd' for a Bar. It can also be 'outEnd' for a clustered bar.

**Comment by gitbrent** [comment]
Fixed via Pull #938
