### ISSUE TITLE
No option to add Table Header on each page when you use auto pagination while adding Table

### ISSUE THREAD

**Issue by adt-saksham** [gitbrent/PptxGenJS#816]
# Category 
- [ ] Enhancement

### Version

Please specify what version of the library you are using: [   Latest   ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

### Expected / Desired Behavior / Question
When you add a table in a slide and use **autoPage** in that, **there is no option to add header in each page.**

There should be an option to add headers to each page when using autopage in table.
**This will increase readability of table values and one can relate values to header easily.**

_**Urgent Requirement !!!**_

**Comment by gitbrent** [comment]
There is an option for this starting in v.3.3.0. 

See the /demo folder for working code.
