### ISSUE TITLE
There is no option to add a shape in table cells

### ISSUE THREAD

**Issue by adt-saksham** [gitbrent/PptxGenJS#817]
### Category
- [ ] Enhancement

### Version

Please specify what version of the library you are using: [   Latest    ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

### Expected / Desired Behavior / Question
I need to add a progress bar in one of my table cells, I can achieve that by adding shape(line) to table cell but there is no option in table to add shapes.

**Please provide an option to add shapes in a table cell this will provide more flexibility in using this library.**

_This has been raised by many, so please provide an urgent solution for the same._

**Comment by gitbrent** [comment]
You can place a circle on a table, but you cant "insert" it into a cell in PowerPoint table that i'm aware of.

**Comment by adt-saksham** [comment]
Can you provide some work around for adding progress bar instead of values in table cell ???

**Comment by adt-saksham** [comment]
> You can place a circle on a table, but you cant "insert" it into a cell in PowerPoint table that i'm aware of.

Can you provide some work around for adding progress bar instead of values in table cell ???
