### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by RahulSahib** [gitbrent/PptxGenJS#820]
My application uses html and js files for generating powerpoint presentation. I have referenced cdn paths in js file - 

<script src="https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@3.2.1/libs/jszip.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@3.2.1/dist/pptxgen.min.js"></script>

and sample code from site to generate ppt - 

var pptx = null;

    // Presentation 1:
    pptx = new PptxGenJS();
    pptx.addSlide().addText('Presentation 1', {x:1, y:1});
    pptx.writeFile('PptxGenJS-Presentation-1');
    
    // Presentation 2:
    pptx = new PptxGenJS();
    pptx.addSlide().addText('Presentation 2', {x:1, y:1});
    pptx.writeFile('PptxGenJS-Presentation-2');

But while opening ppt files that got downloaded, i am getting message to repair the file and when i click on repair, it is unable to repair.

Kindly help on this issue pls.

**Comment by gitbrent** [comment]
There is not nearly enough information here to debug. Please try the demo and see if that works for you.
