### ISSUE TITLE
slide.addText() with "line.pt" option does not work

### ISSUE THREAD

**Issue by npgeomap** [gitbrent/PptxGenJS#822]
Hi,
congrats great lib, just ran into small issue.

using: slide.addText() with option: "**option.line.pt: xx**" does not work, only "**option.lineSize: xx**" does the job. 
Documentation says: [Adding Text](https://gitbrent.github.io/PptxGenJS/docs/api-text.html)
Source Code says: [deprecated](https://github.com/gitbrent/PptxGenJS/blob/7eaf5760851848209fd6ef7ac4b27670c97cf0df/src/gen-objects.ts#L615)

thx
Christian

**Comment by gitbrent** [comment]
Hi @npgeomap 

You ran into this on the cusp of v3.3.0 being released.

Documentation is currently being updated, please consult type defs file for correct properties.

<img width="866" alt="Screen Shot 2020-08-17 at 21 29 10" src="https://user-images.githubusercontent.com/7218970/90463601-fbc48080-e0d0-11ea-8ece-74047b73992f.png">
