### ISSUE TITLE
Write HTML to PPT

### ISSUE THREAD

**Issue by ramtirthe** [gitbrent/PptxGenJS#825]
Can we write the existing rich text box HTML into the PPT with Bold, Italic, Underline, Bullets and Numbering feature.

We are using rich text box in SharePoint online to save the HTML formatted data, same formatting data need to write into the PPT. the format of writing PPT and HTML is different in PptxGenJS component. To extract HTML formatted data into the PPT format is getting difficult at the level of words( as like Bold, Italic, Underline etc.). 
We are looking for feature which can help us to write HTML formatting data into the PPT or else convert HTML formatting data into the PPT formating to support the writing into the PPT with existing format.

Can you please suggest on this.

**Comment by gitbrent** [comment]
There is no build-in method to perform this operation.

You'll need to parse the HTML and create the corresponding pptxgenjs objects.
