### ISSUE TITLE
Broken pptx has generated if used custom slide layout in v3.3.0

### ISSUE THREAD

**Issue by yhatt** [gitbrent/PptxGenJS#826]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: v3.3.0

Please specify what version(s) of PowerPoint you are targeting: PowerPoint 16.40, Keynote 10.1

### Expected

If used the custom slide layout defined through `defineLayout()`, the output pptx should show the slide with the correct size defined in layout.

### Observed Behavior

A broken pptx will be generated if used the custom slide layout in PptxGenJS v3.3.0.

PowerPoint will be trying to repair it but the result has different layout size. Keynote will show nothing.

### Steps to Reproduce

Run this script in Node.js and open `pptx.pptx`:

```js
const PptxGenJS = require('pptxgenjs')
const pptx = new PptxGenJS()

pptx.defineLayout({ name: 'A3', width: 16.5, height: 11.7 })

// console.dir(pptx.presLayout)
pptx.layout = 'A3'
// console.dir(pptx.presLayout)

pptx.addSlide()
pptx.writeFile('pptx.pptx')
```

#### Appendix

- This script works correctly with v3.2.1.
- v3.3.0 + built-in layout such as `LAYOUT_4x3` also will work.
- Workaround: Assign `width` and `height` to `pptx.presLayout` manually after assigning `layout`.

```js
pptx.layout = 'A3'
pptx.presLayout.width = pptx.presLayout._sizeW
pptx.presLayout.height = pptx.presLayout._sizeH
```

**Comment by gitbrent** [comment]
Thanks @yhatt - I thought there was a test case for `defineLayout()`, but I was mistaken.

Issue was due to lose type definitions not catching recent changes to SlideLayout props in 3.3.0
