### ISSUE TITLE
[BUG] lineSpacing option set to decimal triggers repair alert

### ISSUE THREAD

**Issue by ReimaFrgos** [gitbrent/PptxGenJS#827]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.3.0  ]

Please specify what version(s) of PowerPoint you are targeting: [ N/A ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Should be able to enter a decimal for lineSpacing, not just an integer.
If using fontSize 12 and you want 1.15 line spacing you need linespacing set to 13.8

### Observed Behavior
Entering decimal for the lineSpacing option triggers a repair warning. An integer works fine

### Steps to Reproduce
enter lineSpacing: 13.8 as an option

### Fix
Update
`strXmlLnSpc = "<a:lnSpc><a:spcPts val=\"" + textObj.options.lineSpacing + "00\"/></a:lnSpc>";
`
to 
`strXmlLnSpc = "<a:lnSpc><a:spcPts val=\"" + (textObj.options.lineSpacing * 100) + "\"/></a:lnSpc>";
`

**Comment by gitbrent** [comment]
Thanks @ReimaFrgos !
