### ISSUE TITLE
[BUG] The documentation for slideNumber doesn't match the implementation.

### ISSUE THREAD

**Issue by pandersen-uncharted** [gitbrent/PptxGenJS#828]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.3.0]

Please specify what version(s) of PowerPoint you are targeting: [PowerPoint for Mac Version 16.40]

### Observed Behavior
The documentation for slideNumber (https://gitbrent.github.io/PptxGenJS/docs/usage-slide-options.html) explains that `slideNumber` is a function. In the library it is actually implemented on the slide as a property with a getter and setter method that causes the slide number to be rendered to top left corner of a slide.

### Expected / Desired Behavior / Question
Can this be changed back to a function as described in the documentation so that the position and typeface of the slide number can be specified?

### Steps to Reproduce
Here's a fiddle that demonstrates the problem:
```javascript
let pptx = new PptxGenJS();
$('small').before('<code class="d-block text-black-50 mb-3">(pptxgenjs version: ' + pptx.version + ')</code>');

// Simple Slide
window.doDemo = function do7cells() {
  let pptx = new PptxGenJS();
  let slide = pptx.addSlide();
  slide.slideNumber({ x: 1.0, y: "90%" });
  pptx.writeFile();
}
```
Which when run produces the error:
`TypeError: slide.slideNumber is not a function. (In 'slide.slideNumber({ x: 1.0, y: "90%" })`

While the following doesn't produce an error, produces output, but doesn't allow placing the slideNumber.
```javascript
let pptx = new PptxGenJS();
$('small').before('<code class="d-block text-black-50 mb-3">(pptxgenjs version: ' + pptx.version + ')</code>');

// Simple Slide
window.doDemo = function do7cells() {
  let pptx = new PptxGenJS();
  let slide = pptx.addSlide();
  slide.slideNumber = 1;
  pptx.writeFile();
}
```

**Comment by pandersen-uncharted** [comment]
I've had a look at the demos and now I see how the slideNumbers property is used. So this is really just a documentation issue.

**Comment by gitbrent** [comment]
Thanks @pandersen-uncharted - docs have been updated
