### ISSUE TITLE
Can't create multiple presentations in node

### ISSUE THREAD

**Issue by daynedavis** [gitbrent/PptxGenJS#83]
I am requiring pptx via var pptx = require('pptxgenjs') within a function called by a route on my node server, but when I hit the endpoint multiple times slides are added to the same presentation (first time it returns a ppt with 4 slides, second time one with 8 slides). Changing module.exports to be PptxGenJs  in pptxgen.js and then requiring pptx = new (require('pptxgenjs'))() allowed me to get separate instances. Is this a bug or is there a way to get multiple instances in node without making that change?

**Comment by gerbendekker** [comment]
That would be nice, having the same issue here.
Needed to restart the electron app for each new pptx.
What I did is creating a new public function 'newFile' but don't know this is appropriate.
```
this.newFile = function newFile() {
    gObjPptx = {};
    gObjPptx.author = 'PptxGenJS';
    gObjPptx.company = 'PptxGenJS';
    gObjPptx.revision = '1';
    gObjPptx.subject = 'PptxGenJS Presentation';
    gObjPptx.title = 'PptxGenJS Presentation';
    gObjPptx.fileName = 'Presentation';
    gObjPptx.fileExtn = '.pptx';
    gObjPptx.pptLayout = LAYOUTS['LAYOUT_16x9'];
    gObjPptx.slides = [];
}
```

**Comment by gitbrent** [comment]
Hi @daynedavis @gerbendekker ,

Thanks for the question.

I've added a new section to the README that covers this very issue:
[Saving a Node.js Presentation](https://github.com/gitbrent/PptxGenJS#nodejs-1)

See also: Issue #38

**Comment by gerbendekker** [comment]
How does this cover the NodeJs usecase of above?
Can't 'new' the PptxGenJS class because it isn't exposed.
```JavaScript
var pptx = require("pptxgenjs");
```

**Comment by daynedavis** [comment]
@gitbrent like @gerbendekker said I'm not able use new in NodeJs since the class is not exposed.

**Comment by gitbrent** [comment]
Hi @daynedavis @gerbendekker,

Ack!  I spaced out and used the wrong code.  Sorry about that.

It should've been `pptx = require("pptxgenjs");` and i've corrected the README as well.

Does this work for you guys, or would a more formal method like `clearPresentation()` (something that would remove all the Slides from the current Presentation) be preferable?

**Comment by gerbendekker** [comment]
Now we are back where we started.
Let me write some more context about the issue in NodeJs:

**Problem**
```JavaScript
let pptx = require('pptxgenjs');
let slide1 = pptx.addNewSlide();
let slide2 = pptx.addNewSlide();

pptx = require('pptxgenjs');
// How many slides does pptx have?
```
The anser is 2, because `require('pptxgenjs')` returns the same (singleton) instance.

**Solution**
What I would expect in 'pptxgen.js' and described by @daynedavis: 
```JavaScript
module.exports = PptxGenJS;
```
Then we can write:
```JavaScript
let PptxGenJS = require('pptxgenjs');
let pptx = new PptxGenJS();
let slide1 = pptx.addNewSlide();
let slide2 = pptx.addNewSlide();

pptx = new PptxGenJS();
// Yeay a new instance.
```
But that is a breaking change.
For the development roadmap of version 2.0 I would advise to export the class instead of an instance.

Thinking forward...
What use case would `clearPresentation()` have in 2.0? I would use `new PptxGenJS()`.
But I can imaging a use case for `removeSlide()`.
My advise would be adding a `removeSlide(pageNumber)` to version 1 and we can iterate to clear the presentation.

**Comment by LiranBri** [comment]
Hello,
Is there a solution for this issue in the current version?

**Comment by LiranBri** [comment]
I fixed it in the current version by deleting the module from the cache before requiring again:
```javascript
  delete require.cache[require.resolve('pptxgenjs')]
  let pptx = require('pptxgenjs')
```

**Comment by labriola** [comment]
Here is a much cleaner work around:

var pptxgenjs = require('pptxgenjs');
var pptx = new pptxgenjs.constructor();
...
pptx.save(name);

const pptx2 = new pptxgenjs.constructor();
...
pptx2.save(name);

Using the constructor property of the function will let you build new objects at will.

**Comment by dtabolich** [comment]
Any news guys?

**Comment by gitbrent** [comment]
Hi @dtabolich,

Other than the newer posts above, no.  The factory method will be updated in 2.0 as it's a breaking change, until then work-arounds are all that's available. :-(

**Comment by labriola** [comment]
@gitbrent if I do a PR for a way to make this work that would be backwards compatible (non-breaking) would you be interested in reviewing? I have a strategy we can use

**Comment by gitbrent** [comment]
Hi All,

Work on 2.0 is underway and a fix for this issue is now checked into the codebase.  If any of you would care to demo it and provide feedback, i'd appreciate it. :-)

The `examples/node-demo.js` file now creates 2 separate Presentations to demo the new functionality.

**Comment by gitbrent** [comment]
Version 2.0.0 has been released and this issue is now fixed.

Thank you all for your feedback.
