### ISSUE TITLE
[typescript] - addSection missing return type

### ISSUE THREAD

**Issue by dylang** [gitbrent/PptxGenJS#833]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [master]

Please specify what version(s) of PowerPoint you are targeting: [n/a]

### Expected / Desired Behavior / Question

Expect to have a return type here: https://github.com/gitbrent/PptxGenJS/blob/master/types/index.d.ts#L87

### Observed Behavior

```
node_modules/pptxgenjs/types/index.d.ts:87:2 - error TS7010: 'addSection', 
which lacks return-type annotation, implicitly has an 'any' return type.

87  addSection(section: PptxGenJS.SectionProps)
    ~~~~~~~~~~

Found 1 error.
```

### Steps to Reproduce

Type check project with latest PptxGenJS as a depedency and `skipLibChecks: false`.

**Comment by gitbrent** [comment]
Thanks @dylang !

**Comment by praveenpuglia** [comment]
Is there a workaround for this that I can use while 3.4.0 is released?
