### ISSUE TITLE
Align property doesn't work in slide number object

### ISSUE THREAD

**Issue by ax2mx** [gitbrent/PptxGenJS#835]
Hi!

I've failed to align slide number to the right inside a `slideNumber` object. `center` alignment doesn't work either.
The only avaliable option is the default left alignment.

### Category
Bug

### Versions
PptxGenJS version: **3.3.1**
PowerPoint version: PowerPoint for Mac **16.40**

### Steps to Reproduce
Try to create new slide master with number aligned to the right inside slide number block:

```js
import pptxgen from "pptxgenjs";

pptx.defineSlideMaster({
  title: "Text Slide",
  slideNumber: {
    x: "90%",
    y: "10%",
    w: 0.5,
    align: "right",
    fontSize: 12,
    lineSpacing: 16
  }
});

slide = pptx.addSlide({ masterName: "Text Slide" });

pptx.writeFile("sample.pptx");
```

### Expected Behavior
Slide number aligned to the right inside `slideNumber` block.

### Result
`align` property has no effect on slide number alignment.

**Comment by hegelstad** [comment]
I also have the same issue:

![image](https://user-images.githubusercontent.com/6997343/91860491-06a01900-ec6c-11ea-88c4-85fe83ae3134.png)

![image](https://user-images.githubusercontent.com/6997343/91860504-0bfd6380-ec6c-11ea-8261-ad82b4bb34c2.png)

**Comment by gitbrent** [comment]
[DEV]: Possibly related to Issue #836 ? (`TextOpts` not being honored?)

**Comment by gitbrent** [comment]
Fixed, thanks for reporting this @ax2mx !
