### ISSUE TITLE
Margin doesn't work in slide number object 

### ISSUE THREAD

**Issue by ax2mx** [gitbrent/PptxGenJS#836]
Failed to set margin of `slideNumber` block to zero.

### Category
Bug

### Versions
PptxGenJS version: **3.3.1**
PowerPoint version: PowerPoint for Mac **16.40**

### Steps to Reproduce
Try to create new slide number block with zero margins:

```js
import pptxgen from "pptxgenjs";

pptx.defineSlideMaster({
  title: "Text Slide",
  slideNumber: {
    x: "90%",
    y: "10%",
    w: 0.5,
    margin: 0,
    fontSize: 12,
    lineSpacing: 16
  }
});

slide = pptx.addSlide({ masterName: "Text Slide" });

pptx.writeFile("sample.pptx");
```

### Expected Behavior
`slideNumber` block has zero margins.

### Result
`margin: 0` has no effect on slide number margin.

**Comment by gitbrent** [comment]
Fixed, thanks for reporting this @ax2mx !
