### ISSUE TITLE
dataLabelPosition option for Pie charts

### ISSUE THREAD

**Issue by kornarakis** [gitbrent/PptxGenJS#837]
### Category
- Enhancement

### Version

Please specify what version of the library you are using: [   3.3.1     ]

Please specify what version(s) of PowerPoint you are targeting: [   360    ]

### Expected / Desired Behavior / Question
When creating a Pie to have the `dataLabelPosition` option available like Powerpoint has, so we can position the labels for example outside the pie with `outEnd`.

**Comment by gitbrent** [comment]
The [Chart API docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html) show this as an optoin for bar charts, but it should work with pie charts according to what i see in the source code.

https://github.com/gitbrent/PptxGenJS/blob/506af72a7a0e2d8694ca012d374521d7d1c7de6c/src/gen-charts.ts#L1457

**Comment by calidatkoch** [comment]
@gitbrent  The line you mentioned has no effect. To work properly it should be replaced with:
strXml += "<c:dLblPos val=\"" + (opts.dataLabelPosition || 'inEnd') + "\"/>";

**Comment by gitbrent** [comment]
Fixed via Pull #938
