### ISSUE TITLE
Does anybody know why this number is used here - "4294967295"? Why not a simple value like "1"?

### ISSUE THREAD

**Issue by Kirill71** [gitbrent/PptxGenJS#838]
https://github.com/gitbrent/PptxGenJS/blob/506af72a7a0e2d8694ca012d374521d7d1c7de6c/dist/pptxgen.es.js#L1917

**Comment by koddistortion** [comment]
My guess would be, that this is the last possible index. 

Why the last?
It seems the index here is an unsigned 32bit number, starting at 0 and 4294967295 = 2³²-1 is the highest (last) representable number here.

Probably this is used to ensure, that no previous index is re-used or overwritten.

Just my 2 cents.

**Comment by Kirill71** [comment]
Thanks, @koddistortion, I know about the upper bound of unsigned int type, but I've checked it on real pptx files and behavior a bit different with idx='4294967295'  than, for example with idx='1' etc, and I'm trying to understand how does it work...

**Comment by gitbrent** [comment]
I’m unable to recall where the value is derived from off-hand. I may have simply mimicked what PowerPoint produced.

**Comment by Kirill71** [comment]
@gitbrent I've understood how to get this value in PP. For example, you have an inheritance chain: master slide placeholder with idx='1', slide layout placeholder with idx='1', and slide placeholder with idx='1'. if you remove the slide layout's placeholder the inheritance chain between the slide and the slide layout will be broken, but PP still has to inherit properties from parent entities in this case from the master slide, and it marks slide placeholder with idx='4294967295'. It's like a mark. If PP reads this value it inherits properties directly from the master slide, excludes the slide layout and it understands that placeholder which belongs to the slide layout has been removed.
