### ISSUE TITLE
Webpack Support

### ISSUE THREAD

**Issue by dylankerr-bis** [gitbrent/PptxGenJS#84]
Thanks for a great client-side solution for PPTX generation!

I had a lot of pain getting PptxGenJS to behave in a Webpack build, as a result of the Node.js detection: `var NODEJS = ( typeof module !== 'undefined' && module.exports );` This returns true in a Webpack environment, leading to incorrect behaviour.

It would be great if this check could be refined to behave correctly in Webpack (as many other modules have done), but in the meantime I thought I would share the wrapper module I used to work around this:

```
/* eslint no-unused-vars: 0 */
'use strict';

var src = require('raw!pptxgenjs');

// Construct the environment assumed by PptxGenJS.
var temp_$ = require('jquery');
var temp_JSZip = require('jszip');
module.exports = undefined;

var PptxGenJS = eval([
  'var $ = temp_$;',
  'var JSZip = temp_JSZip;',
  src,
  'PptxGenJS;' // `eval` returns the final expression.
].join('\n'));

module.exports = PptxGenJS;
```

There is probably a better way of doing this, but I couldn't find the right combination of `script-loader`, `imports-loader` and `exports-loader` to achieve what was needed.

**Comment by gitbrent** [comment]
Hi @dylankerr-bis ,

Thanks for the feedback!

Do you have an example library that handles WebPack and Node.js well?

**Comment by mpalmr** [comment]
@gitbrent I was just trying to use this library with Webpack and ran into a slew of issues. Would you be open to me contributing to this, and restructuring this project a little bit? Might require a major version number change but aside from making this a browser compatible module (able to use this with Webpack and what not), I could break up the source code into multiple files. An example of me implementing something like this can be found here: https://github.com/toish/chromatism/blob/refactor/

**Comment by dylankerr-bis** [comment]
@gitbrent Sorry for the delay in responding, but I've been struggling to think of a way to detect the environments sensibly and avoid dependencies on non-browser-compatible libraries like fs. It sounds like @mpalmr has some ideas around this.

**Comment by gitbrent** [comment]
Hi @mpalmr,

I'm not to the point of wanting to break the library into dozens of pieces at this point...

Webpack support is definitely something I'd like to work towards, so any guidance or patches that would help would be greatly appreciated.

**Comment by clubajax** [comment]
I think this is something that should be seriously considered. I can do my best to help.

The main benefit you will get from Webpack is using babel, mostly the multi-line template literals, which will helps so much with stringifying XML. You could also keep IE11 compatibility which I highly recommend - it's still a major browser. 

Also speaking from experience - if you have non-parsable code (such as fat arrow functions), you'll blow up IE, and the script would have to be conditionally loaded, which is a royal PITA in Webpack - so you would lose what you wanted to gain.

Most of all, you would get the opportunity to break the code into smaller, digestible pieces, which would be easier to work on. You said you're not ready to do that - I wonder why?

**Comment by clubajax** [comment]
Webpack can be unwieldy to work with - there is an alternative. My [BaseComponent](https://github.com/clubajax/BaseComponent) library instead uses Browserify and Grunt, along with Babel. Note also that libraries work better using the NodeJS style modules instead of ES6 modules.

Without having to conform to Webpack's sometimes oppressive rules, you could have more liberty with how you put the library together and expose it.

**Comment by philipthemagnificent** [comment]
I believe I found a fix

`var NODEJS = ( typeof module !== 'undefined' && module.exports );`

to

`module.exports = Object.prototype.toString.call(global.process) === '[object process]'`

Stolen from here.
https://www.npmjs.com/package/detect-node

**Comment by gitbrent** [comment]
(closing old issue - node detection is different now)
