### ISSUE TITLE
Chart Data Range

### ISSUE THREAD

**Issue by MJRuskin** [gitbrent/PptxGenJS#845]
Would it be possible to add support for selecting the range of the data for charts?

Doing this manually is easy (you change the range while editing the chart in excel), however, this is not possible with PptxGenJS currently.

#### Storing Additional Information

Often times the data will have too many categories/columns and it can be convenient to group the lower values into an "Other" category. This can be especially useful for Pie Charts and Stacked Bar Charts, where too many categories can limit readability.
However, doing so results in information being lost to the user - since they don't know the make-up of this "Other" category.

To resolve this, I would like to be able to include all the individual categories in the chart data (i.e. when editing the chart in excel), but not display them in the chart.
This would allow users easy access to the grouped data, so they can add additional info to their PPT if needed.

#### Data Label "Value From Cells"

_Although this would require additional features implemented (i.e. per label editing of data labels), it is related and requires the feature in this issue be implemented first._

When created a Stacked Bar Chart (i.e. horizontal "Stacked Column Chart"), it's difficult to add the sum totals to the end of the bars. However, there is an easy "hack" to resolve this.
It involves adding two additional dummy categories - one with a value of zero, and one with the totals.
The totals are not included in the chart's data range, but are instead used as the data label values by utilizing the "Value From Cells" feature in PPT.

[Here is a tutorial](https://peltiertech.com/add-stacked-bar-totals/) that I found which explains this use case.

**Comment by gitbrent** [comment]
I'm unsure about how to implement this or the interest level of the user base. Closing for now, not locking in case others have feedback.
