### ISSUE TITLE
JavaScript heap out of memory when asset total size too large

### ISSUE THREAD

**Issue by fei0219** [gitbrent/PptxGenJS#846]
### Category
 Question

### Version

3.3.1

### Expected / Desired Behavior / Question

Getting  `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` when the total asset size gets large even with `stream` method. is this intended behaviour ? anyway I can work around this other than increase the memory limit of my container ? also when i used a 300 mb image, the memory gets very high like 1.6 G during the .stream() 
in docker stats. 

### Observed Behavior
if I add many or single image/video that makes the total size greater than the docker container limit.  the .stream() will cause heap memory error. 

### Steps to Reproduce
if i set mem limit of container to 100m and upload an image or multiple asset with 250mb of size it will generate this error.

**Comment by gitbrent** [comment]
I'm not sure what can be done to address this.

**Comment by gitbrent** [comment]
There's a new `compression` option in `write` and `writeFile` that may help.
