### ISSUE TITLE
[BUG] PptxGenJS add chart show nothing

### ISSUE THREAD

**Issue by shinaBR2** [gitbrent/PptxGenJS#847]
### Category
- [x] Bug
- [ ] Enhancement
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [neither ^2.6.0 nor 3.3.1 work]

Please specify what version(s) of PowerPoint you are targeting: [Microsoft Powerpoint 2013 and Google Slides]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
My question has been posted [here](https://stackoverflow.com/questions/64039910/pptxgenjs-add-chart-show-nothing)

### Observed Behavior
Charts should be shown correctly

### Steps to Reproduce
- Install packages
- Copy code from official demo
- Run

Thank you for your feedback!

**Comment by shinaBR2** [comment]
Like the title.

My steps:

- Install PptxGenJS and import like normal npm package.
- Copy code from [official demo](https://github.com/gitbrent/PptxGenJS/blob/master/demos/common/demos.js): `slide.addChart( pptx.charts.BAR, arrDataRegions, optsChartBar1 );`
The result:

- Chart show nothing in exported slider.
- Open with Microsoft Powerpoint 2013, it shows some error similar to this question.
- [My codesanbox](https://codesandbox.io/s/pptxgenjs-chart-show-nothing-0tygp?file=/src/App.js) even worse, no file were downloaded.

**Comment by gitbrent** [comment]
I'm not sure what support I can lend. There are many examples in React and browser that create charts just fine...
