### ISSUE TITLE
Random line breaks in Table cells

### ISSUE THREAD

**Issue by chrisjaimes** [gitbrent/PptxGenJS#849]
I have seen a lot of issues opened due to random line breaks when using the `align` property in the `addText` function. However, I'm seeing this breaks in table rows after using `.addTable()`. I don't use `align` but `valign` for row data, and the content of the row is just regular text.

For example:
<img width="277" alt="Screen Shot 2020-10-07 at 9 33 08 AM" src="https://user-images.githubusercontent.com/45322800/95337717-24225d00-0880-11eb-8c81-87d39373f9c5.png">

Even though there is enough space on the cell, there is some text rendered on a separate line. Not sure if this happens randomly but all cells have simple text with no line break characters. Any ideas? 🙏 

I am using version v3.3.1

**Comment by chrisjaimes** [comment]
I forgot to mention that I also played around with weight values with `autoPageCharWeight` and `autoPageLineWeight` but one way or another some cells will keep adding line breaks

**Comment by gitbrent** [comment]
This is auto-paging attempting to wrap lines. Adjust the `autoPageCharWeight` and/or `autoPageLineWeight` properties to fine tune this for your implementation.

The table demo shows how adjusting these reflects in the export.

### [Table Demo](https://gitbrent.github.io/PptxGenJS/demo/#tables)
