### ISSUE TITLE
Uncaught (in promise) ERROR! Unable to load image (xhr.onerror):

### ISSUE THREAD

**Issue by ZornitsaSerbezova** [gitbrent/PptxGenJS#851]
Could you tell me why my image is not adding?
https://jsfiddle.net/1m84jw5d/3/

**Comment by mmarkelov** [comment]
@ZornitsaSerbezova I think this is because of CORS
<img width="452" alt="Screen Shot 2020-10-16 at 4 26 29 PM" src="https://user-images.githubusercontent.com/22371328/96264040-707e4300-0fcc-11eb-9e91-b505913b14d3.png">

**Comment by ZornitsaSerbezova** [comment]
@mmarkelov, thank you! I'll check that out.
