### ISSUE TITLE
Using scheme colors and fonts in chart axis labels, axis lines and series labels

### ISSUE THREAD

**Issue by robertedjones** [gitbrent/PptxGenJS#858]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.3.1 ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Is it be possible for chart axis line, chart labels, and chart axis labels to use the scheme colours and template fonts?

### Observed Behavior
PPT shows repair message or option is not available

**Comment by gitbrent** [comment]
Completed via Pull #938
