### ISSUE TITLE
[BUG] Need to repair presentation with line chart after download 2-type chart presentation

### ISSUE THREAD

**Issue by Extnow** [gitbrent/PptxGenJS#859]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Version of the library: [ pptxgenjs@3.3.1 ]
Version of PowerPoint: [ latest ]

### Expected / Desired Behavior / Question
Download 2 working presentation, PPTX files should be able to open on Microsoft PowerPoint

### Observed Behavior
- Download first presentation with 2-type charts (bar and line)
- Second presentation with line chart needs to be repair

### Steps to Reproduce
- Open codepen https://codepen.io/extnow/pen/pobLePw
- Save 2-type chart presentation (1)
- Save line chart presentation (2)
- Open line chart presentation

Thank you for your feedback!

**Comment by ReimaFrgos** [comment]
This is failing because you are adding the option:
`barDir: 'col',`
This is not a valid configuration for a line chart. Remove this and your second chart will generate fine.

**Comment by gitbrent** [comment]
Thanks @ReimaFrgos
