### ISSUE TITLE
[BUG] ESLINT Typescript throws error: types/index.d.ts(87,2): 'addSection' lacks return-type annotation

### ISSUE THREAD

**Issue by guillaumeprevost** [gitbrent/PptxGenJS#862]
### Category

- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.3.1]
Please specify what version(s) of PowerPoint you are targeting: [ANY]

### Expected / Desired Behavior / Question

No error or warning when linting testing or building my project.

### Observed Behavior

The linting (and therefore building) crashes with the following error :

```
ERROR in ...MYPROJECT.../node_modules/pptxgenjs/types/index.d.ts(87,2):
87:2 'addSection', which lacks return-type annotation, implicitly has an 'any' return type.
    85 |         * @example pptx.addSection({ title:'Charts' });
    86 |         */
  > 87 |        addSection(section: PptxGenJS.SectionProps)
       |        ^
    88 |        /**
    89 |         * Add a new Slide to Presentation
    90 |         * @param {AddSlideProps} options - slide options
```

### Steps to Reproduce
Use `@nuxtjs/eslint-config-typescript` to enforce ESLINT Typescript 
https://typescript.nuxtjs.org/guide/lint.html#configuration
then build the project

**Comment by gitbrent** [comment]
Thanks @guillaumeprevost 

Fixed in next release.

`addSection(section: PptxGenJS.SectionProps): void`
