### ISSUE TITLE
Autopage is set to false in case text is array in Table

### ISSUE THREAD

**Issue by jsvishal45** [gitbrent/PptxGenJS#863]
**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [*] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   Latest      ]

Please specify what version(s) of PowerPoint you are targeting: [     Latest    ]

### Expected / Desired Behavior / Question
*AutoPage option with Array Text fields not working*

### Observed Behavior
*Autopage is set to false in case text is array*

### Steps to Reproduce
*Create tabel . give cell value as [{text:1},{text:2}]* and make rows upto 20

### Submission Guidelines
https://github.com/gitbrent/PptxGenJS/blob/master/dist/pptxgen.es.js#L3750
            if (cell.text && Array.isArray(cell.text))
                opt.autoPage = false;

**Comment by gitbrent** [comment]
Disabling of auto-paging is done by design. Text objects can be too varied (font size 12, then font size 28, then back agian) and this makes it too complex for auto-paging.
