### ISSUE TITLE
[QUESTION] Is there a Hover/ToolTip option for Shapes/Table 

### ISSUE THREAD

**Issue by harishjss2002** [gitbrent/PptxGenJS#864]
### Category

- [ ] Question

We are trying to build multi dimension chart , so wanted to check if there is an api to add Hover/ToolTi/ScrrenTip option for Shapes/Table  which will help us adding another dimension .

Any suggestions on which meta data information in open office XML spec would be helpful

**Comment by gitbrent** [comment]
Aside from hyperlink tooltips, i'm unaware of such a feature in PowerPoint.

**Comment by harishjss2002** [comment]
Ok thanks, can be achieve this feature hyperlink tooltips using pptgenx library ?
