### ISSUE TITLE
[Question] Highcharts SVG to PPT Image 

### ISSUE THREAD

**Issue by sesmic** [gitbrent/PptxGenJS#865]
Hi,

I am trying to convert a HighChat based chat from SVG to Image and download a ppt.  The following code is what I am trying,

 var trendChart=$("#trendChart").highcharts();
 let svgString = trendChart.getSVG();
 let parser = new DOMParser(); 
 let svgElem = parser.parseFromString(svgString, "image/svg+xml").documentElement;
 let b64 = svgElem.toDataURL();

// 1. Create a new Presentation
let pres = new PptxGenJS();
// 2. Add a Slide
let slide = pres.addSlide();
// 3. Add highchart Image
slide.addImage({//base64 string goes here});
// 4. Save the Presentation
pres.writeFile("Sample Presentation.pptx");

I am getting the following error,

Uncaught (in promise) ERROR! Unable to load image (image.onerror): 

What can be missing here?

**Comment by gitbrent** [comment]
You cant just pass the base64 string as the argument. This is correct:
`slide.addImage({ x:7.87, y:1.1, w:1.0, h:1.0, data:svgElem });`

Please see /demos for more sample code.
