### ISSUE TITLE
[BUG] titleAlign have no effect

### ISSUE THREAD

**Issue by mapringg** [gitbrent/PptxGenJS#867]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.3.1     ]

Please specify what version(s) of PowerPoint you are targeting: [    Office 365    ]

### Expected / Desired Behavior / Question
titleAlign property on addChart method does not have any effect on the alignment of the chart title.

### Observed Behavior
I expect the chart title to be aligned correctly.

### Steps to Reproduce
Apply 'left', 'center', or 'right' value on the titleAlign property of a chart.

**Comment by gitbrent** [comment]
Unable to reproduce:

```javascript
slide.addChart( pptx.charts.PIE, dataChartPieLocs,
    {
        x:9.8, y:0.5, w:3.2, h:3.2, dataBorder:{pt:'1',color:'F1F1F1'},
        showLegend: true,
        legendPos: 't',
        legendFontSize: 14,
        showLeaderLines: true,
        showTitle: true,
        title: 'Right Title & Large Legend',
        titleAlign: 'right', // this works
        titlePos: {x: 0, y: 0}
    });
```

![Screen Shot 2020-12-24 at 00 17 59](https://user-images.githubusercontent.com/7218970/103066044-a9630700-457d-11eb-9e1e-a774ace35b4b.png)
