### ISSUE TITLE
Embedd an Excel Object inside PPT

### ISSUE THREAD

**Issue by Reachakhil** [gitbrent/PptxGenJS#868]
### Category
 Enhancement
 Question

### Version

Please specify what version of the library you are using: 3.3.1

Please specify what version(s) of PowerPoint you are targeting: office professional plus 2013

### Expected / Desired Behavior / Question
My requirement  includes adding an excel object generated inside the ppt slide and on click should open an excel object .

### Observed Behavior
Currenty does not support embedding excel worksheet object inside ppt

**Comment by gitbrent** [comment]
I'm not 100% certain what you're looking for, but the insertion of Excel objects is not currently supported nor is it slated for development.
