### ISSUE TITLE
typo in ts doc

### ISSUE THREAD

**Issue by jencii** [gitbrent/PptxGenJS#873]
in **ShapeLineProps**

    /**
     * @deprecated v3.3.0 - use `arrowTypeEnd`
     */
    lineTail?: 'none' | 'arrow' | 'diamond' | 'oval' | 'stealth' | 'triangle'

but there is no **arrowTypeEnd** property, just **endArrowType**

the same for lineHead/arrowTypeBegin/beginArrowType

**Comment by gitbrent** [comment]
Oops, you're correct. It should be `endArrowType`. Fixed in v3.4.0

Thanks @jencii !
