### ISSUE TITLE
Feature Request: Chart Logarithmic Scale

### ISSUE THREAD

**Issue by rkspx** [gitbrent/PptxGenJS#878]
First of all, Thank You for making this, PptxGenJs is such an awesome library

I'd like to request a feature for logarithmic scale in Bar Chart, i used to check  this options when working with large variation number, it would be really helping if PptxGenJs support this.

![issue](https://user-images.githubusercontent.com/9310368/103220368-ab98dd00-4952-11eb-9f6a-20ae4ce5376f.JPG)

**Comment by gitbrent** [comment]
Thanks for the feedback @rkspx ! 

Log scale is a great suggestion and will be in v.3.5.0

![Screen Shot 2021-02-25 at 20 28 19](https://user-images.githubusercontent.com/7218970/109248193-f72d0300-77aa-11eb-8280-cad588390df2.png)

**Comment by rkspx** [comment]
Great to hear it, Thank you!
