### ISSUE TITLE
TypeError: Cannot set property 'lIns' of undefined

### ISSUE THREAD

**Issue by CroniD** [gitbrent/PptxGenJS#879]
Hi there,

in https://github.com/gitbrent/PptxGenJS/blob/8d81999e1a09bb581a7d870e0e5727373f37a83a/src/gen-xml.ts#L415 is a check missing for ```slideItemObj.options._bodyProp```.

Best regards

**Comment by gitbrent** [comment]
A default is added when the object is instantiated in the `addTextDefinition()` method:
https://github.com/gitbrent/PptxGenJS/blob/ea85a79e07aa9b41cb10b065fba180a42ec41881/src/gen-objects.ts#L903

However, I agree that's a poor design.

A local check has been added:
![Screen Shot 2021-01-02 at 19 59 37](https://user-images.githubusercontent.com/7218970/103470232-6fd88b80-4d35-11eb-9ffb-423d5424313f.png)

Thanks @CroniD !
