### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by ada2805** [gitbrent/PptxGenJS#888]
Hello,

How can I do after writeFile to send the file by email?

I am using client browser, but on mobile writeFile does not work and I want to generate pptx and send it by email.

Thanks in advance!

**Comment by gitbrent** [comment]
Hi @ada2805 

Support for solutions like this is outside the scope of normal Issues.

Maybe stream it or choose `blob` as the type, then take that binary and attach it to an email...
