### ISSUE TITLE
Invalid XML when calling .addText() with empty array.

### ISSUE THREAD

**Issue by JimmyTheChimp** [gitbrent/PptxGenJS#89]
I'll try to nail down some more details when I get a chance, but basically something along the lines of the following code causes invalid XML to be generated and PowerPoint will require a "repair" operation to open the file. The file does not display correctly even when repaired.

```javascript
var dataDrivenTextArray = [];
slide.addText(dataDrivenTextArray,
  {
    x: 1,
    y: 1,
    w: 2,
    h: 0.5,
    valign: 'top'
  });
```

I've attached an example of the corrupted output.

[SummaryExport (61).pptx](https://github.com/gitbrent/PptxGenJS/files/1008646/SummaryExport.61.pptx)

**Comment by JimmyTheChimp** [comment]
Here's a fiddle for ya if it helps.
https://jsfiddle.net/JimmyTheChimp/Loo3rony/1/

**Comment by gitbrent** [comment]
Hi @JimmyTheChimp ,

Thanks for reporting this.

The library correctly handles empty arrays now.
