### ISSUE TITLE
The percentages in the charts are not visible.

### ISSUE THREAD

**Issue by cihancelen** [gitbrent/PptxGenJS#890]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ latest ]

Please specify what version(s) of PowerPoint you are targeting: [ Microsoft Powerpoint 2019 for Mac V 16.45 (21011103) ]

Hi, i updated pptxgenjs recently 2.5.0 to 3.4.0. I don't know if there was this problem before updating. My problem is percentage values is not show in charts. I look this link https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68?ui=en-us&rs=en-us&ad=us. But it dosen't happen in a any way.

My code:
![image](https://user-images.githubusercontent.com/23706015/105794729-a902c500-5f9c-11eb-9dc9-34d01e48a56a.png)

 Thank u.

**Comment by cihancelen** [comment]
When update code with percentage symbol.

![image](https://user-images.githubusercontent.com/23706015/105795293-a6549f80-5f9d-11eb-87cb-86ae1bddcc1b.png)

![image](https://user-images.githubusercontent.com/23706015/105795378-c84e2200-5f9d-11eb-8563-6c067c88361a.png)

**Comment by ReimaFrgos** [comment]
You need to divide you values by 100.

**Comment by cihancelen** [comment]
> You need to divide you values by 100.

Hi, my problem is solved thanks to your answer but my project is very dynamically structure and more calculation operation is not true. Please solve it problem.

Retry thanks.

**Comment by ReimaFrgos** [comment]
@cihancelen the problem is your values are not percentages. 100% as a number is 1, not 100. That is why you need to divide, or fix the number upstream
