### ISSUE TITLE
Provide a way to control bullet text margin

### ISSUE THREAD

**Issue by danielsiwiec** [gitbrent/PptxGenJS#892]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
3.4.0

### Expected / Desired Behavior / Question
It would be great to be able to control the space between the bullet and the text.

### Observed Behavior
It is currently not possible to control the space between the bullet and the text. The current space is pegged at 27 points.

![image](https://user-images.githubusercontent.com/1505227/106340813-e347bd00-624f-11eb-9078-0df3b83fa393.png)

![image](https://user-images.githubusercontent.com/1505227/106340841-f490c980-624f-11eb-899b-dc579f65bdc0.png)

**Comment by danielsiwiec** [comment]
A PR above takes care of this

**Comment by danielsiwiec** [comment]
@gitbrent would you accept this enhancement?

**Comment by gitbrent** [comment]
@danielsiwiec - isnt the space between the bullet and text, the `indent`?

https://github.com/gitbrent/PptxGenJS/blob/c7c36a1b9b6b2272f4ca60c3d1fe1605276c5d1b/types/index.d.ts#L1101

![Screen Shot 2021-02-03 at 21 05 40](https://user-images.githubusercontent.com/7218970/106839538-00bbc300-6664-11eb-9322-9b1d76fcc4fc.png)

**Comment by danielsiwiec** [comment]
@gitbrent you're absolutely right. I overlooked it
