### ISSUE TITLE
Small API documentation glitch: (line.width i.s.o line.pt when adding text) 

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#895]
Quick update needed in the API documentation for adding text, when you discuss the **line** property:

adds a border. Ex: line:{ pt:'2', color:'A9A9A9' }

should be

adds a border. Ex: line:{ width:'2', color:'A9A9A9' }

https://gitbrent.github.io/PptxGenJS/docs/api-text.html

**Comment by gitbrent** [comment]
Fixed! Thanks @Slidemagic
