### ISSUE TITLE
How to use multiple different layouts for different slides?

### ISSUE THREAD

**Issue by Sher-V** [gitbrent/PptxGenJS#896]
Is  there an opportunity to use different  layouts for every slide?
Seems like when you assign a new layout to  pres.layout its used for an each presentation slide.
I need to have different layout for an each slide.

**Comment by gitbrent** [comment]
Hi @Sher-V 

If you're referring to a "layout" as in the Presentation prop `layout` (the size of the slides), then no, you can't have different sized slides in a PPT.

If you mean layout as in the Home tab "Layout" items in the PowerPoint app, you predefine those layouts and use them on one or more slides with what we feature as [Master Slides](https://gitbrent.github.io/PptxGenJS/docs/masters.html).
