### ISSUE TITLE
Office js remove custom tags while inserting presentation created by PptxGenJS

### ISSUE THREAD

**Issue by mariselvanm** [gitbrent/PptxGenJS#899]
I am creating a presentation using `pptxgenjs` and get the data as a `base64` format.

While creating a chart I was adding some custom XML tags in every chart.xml under the charts folder. 

    chart.xml

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace
                xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"
                xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
                xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
                />
    <author>User</author>
    <c:chart>
        Other data's
    </c:chart>

`<aurhor>` is the custom tag.

If I download this pptx file using the below code and unzip it I can able to view the author tag.
   
    pptx.writeFile('PptxGenJS-Demo');

But If I am inserting it as a slide using the PowerPoint office API, save the file into the local disk and unzip and view the chart.xml file then the `author` tag was removed. Anyone let me know how to resolve this issue?

    pptx.write('base64').then(async function(data) {
    await PowerPoint.run(async function(context) {
      context.presentation.insertSlidesFromBase64(data);
      await context.sync();
    });
    }).catch(err=> {
       console.log(err)
    })

**Comment by gitbrent** [comment]
I'm unsure where in that process flow the `<author>` tag is removed.

Regardless, the library itself wouldn't be removing anything, so I'm guessing PowerPoint is removing them. Are you sure the `<author>` tag is part of the OOXML spec?

**Comment by gitbrent** [comment]
Closing due to age
