### ISSUE TITLE
How can customize pptx theme?

### ISSUE THREAD

**Issue by ielijose** [gitbrent/PptxGenJS#9]

**Comment by gitbrent** [comment]
Thanks for the question/feedback.

I've added a whole new section to the README that covers how theme/style/slide masters work and provided examples.

[https://github.com/gitbrent/PptxGenJS#master-slides-and-corporate-branding](https://github.com/gitbrent/PptxGenJS#master-slides-and-corporate-branding)

**Comment by gitbrent** [comment]
Closing issue as documentation of this feature is now complete.
