### ISSUE TITLE
hyperlink and XML entities issue

### ISSUE THREAD

**Issue by ZouhaierSebri** [gitbrent/PptxGenJS#90]
Hi @gitbrent 
i'm testing hyperlink both in image and text

```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
    slide .addText([
          {text: 'test A & B', options: {hyperlink: {url: 'https://github.com/gitbrent/pptxgenjs?a=1&b=2', tooltip: ' A&B'}}}
          ], {x: 0.62, y: 1, w: 5.3, h: 0.34, font_size: 14, color: '667184', bullet: {code: '27A2'}}
     );
pptx.save('testhyperlink');
```

![image](https://cloud.githubusercontent.com/assets/19344990/26257195/9926200c-3cb7-11e7-9dd3-171d07182ce4.png)

The problem is in & because when i change & by &amp;  the exemple works fine.

as a solution i propose to use decodeXmlEntities()  
line 2389 : change  
Target="'+ rel.Target+'"
BY 
Target="'+ decodeXmlEntities(rel.Target) +'"
line 1579 : change
tooltip="'+ (opts.hyperlink.tooltip ? opts.hyperlink.tooltip : '') +'"
BY
tooltip="'+ (opts.hyperlink.tooltip ? decodeXmlEntities(opts.hyperlink.tooltip) : '') +'"

**Comment by gitbrent** [comment]
Thanks @ZouhaierSebri !

I added decoding to both the text and the image hyperlink tooltips.

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent 
issue not fixed.
we need encoding for url

```
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
    slide .addText([
          {text: 'test A & B', options: {hyperlink: {url: 'https://github.com/gitbrent/pptxgenjs?a=1&b=2', tooltip: ' A&B'}}}
          ], {x: 0.62, y: 1, w: 5.3, h: 0.34, font_size: 14, color: '667184', bullet: {code: '27A2'}}
     );
pptx.save('testhyperlink');
```

not work due to "a=1&b=2" in url

**Comment by lejard-h** [comment]
still having the issue on hyperlink, version 2.4.0 and Powerpoint 2016

```
var pptx = new PptxGenJS();
	var slide = pptx.addNewSlide();
	var opts = { x:1.0, y:1.0, fontSize:42, color:'00FF00',
        hyperlink: { url: 'https://google.fr', tooltip: 'Google' }
  }
slide.addText('Hello World!', opts);
pptx.save();
```

**Comment by gitbrent** [comment]
Hi @lejard-h 

This code will indeed cause warnings on PPT startup.

You'll want to follow the example in the docs and use a complex text type instead (not a simple string with a global option)

**[Example](https://gitbrent.github.io/PptxGenJS/docs/api-text.html#text-examples)**

```
slide.addText(
    [{
        text: 'Hello world!',
        options: { hyperlink:{ url:'https://google.fr', tooltip:'Google' } }
    }],
    { x:1.0, y:1.0, fontSize:42, color:'00FF00' }
);
```

![screen shot 2018-11-08 at 22 07 35](https://user-images.githubusercontent.com/7218970/48242856-bd9a1900-e3a2-11e8-9fbc-b30f384c38ed.png)

**Comment by Tehnix** [comment]
Having the exact same issue as @ZouhaierSebri, in the newest version of the library (2.5.0). Can't place any `&` in the URLs.

**Comment by gitbrent** [comment]
@Tehnix - Please open a new issue for problems using "&" in a URL.
