### ISSUE TITLE
hyperlink URL having special chars like & isn't working

### ISSUE THREAD

**Issue by digvijay442** [gitbrent/PptxGenJS#901]
hyperlink URL having special chars like & isn't working- getting repair error.. 
(version-  PptxGenJS 3.3.1)

Please check with the below sample URL - 

https://www.google.com/search?q=nature&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjG1J-V8N7uAhUw6XMBHXAxCkQQ_AUoAXoECB8QAw&biw=1440&bih=732

**Comment by mmarkelov** [comment]
@gitbrent are you sure that this is related to url? I just tried your code and it is ok for me

**Comment by digvijay442** [comment]
Hi,

I checked, this is resolved in the new version.

thanks
