### ISSUE TITLE
[QUESTION] Is there any way to add title to the slides generated. Also any way to add alternate text to images. Are the PPTs generated through pptxgenjs accessibility complaint?

### ISSUE THREAD

**Issue by Ram4242** [gitbrent/PptxGenJS#903]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

**Questions**

- Is there any way to add title to the slides generated. 
- Also any way to add alternate text to images. 
- Are the PPTs generated through pptxgenjs accessibility complaint?

**Comment by gitbrent** [comment]
- Slides take the title of the title in the Title Placeholder, without one the default "Slide 1" etc is used
- The image API does not yet accept an alternate title (it default to the image name, ex: "New office.jpg"
- Yes, as far as i know
