### ISSUE TITLE
Data labels as Text for Values on Charts

### ISSUE THREAD

**Issue by rayishome** [gitbrent/PptxGenJS#906]
Believe the OpenXML api has a section to allow configuration of the Data Label for Values:  https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.charts.datalabel?view=openxml-2.8.1 

Recommended change to the data object: valueLabels: ["",...]

**Comment by gitbrent** [comment]
Please be more specific. Are you asking for a method to format the data labels, eg: "$0,00"?

**Comment by rayishome** [comment]
@gitbrent thanks for responding so quick... This use case is to alter the value and append text or replace it all together.  For example the value is 50% we would replace the value label with "50% neutral"  The bar would still use the 50% value to display but instead of showing 50% as a value label we would show the string value.

**Comment by gitbrent** [comment]
You're looking for the `dataLabelFormatCode` property ([docs](https://gitbrent.github.io/PptxGenJS/docs/api-charts.html))

A standard use-case is `dataLabelFormatCode: '#.0',` - i imagine you could use `dataLabelFormatCode: '#% neutral',`

[Microsoft format code docs](https://support.office.com/en-us/article/Number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68)

**Comment by rayishome** [comment]
@gitbrent tried that option, but without setting the string value for each value in the values array it would add "neutral" is added to each one.  To expand the use case.  "50% Neutral", "90% Partial", "25% Don't Care"

**Comment by ReimaFrgos** [comment]
You'll only be able to partially achieve this using the format code, as you would only be able to define 2 labels in this manner. Here's an example of the format code"
`[<0.3]0.0% "Don't Care";[>0.7]0.0% "Important";0.0%`

Alternatively, it would need a PR to enable an option to use the _Value from Cells_ setting for PPTX charts and store the appropriate data.

**Comment by rayishome** [comment]
@ReimaFrgos  @gitbrent Taking a look at the following PR that was abandoned it looks like someone had attempted to build a valueLabels (https://github.com/gitbrent/PptxGenJS/pull/727/files).  Will this approach work?  This branch also had some chart coloring changes which may have been problematic?

**Comment by gitbrent** [comment]
Closing due to age, doesn't meet 90/10 threshold for inclusion in codebase.
