### ISSUE TITLE
tooltip option not implemented for image hyperlink

### ISSUE THREAD

**Issue by ZouhaierSebri** [gitbrent/PptxGenJS#91]
Hi @gitbrent ,
for the given exemple in sandbox

```
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

// Image with hyperlink
slide.addImage({
  x:3.5, y:0.8, w:1.78, h:1.78,
  data:GIF_ANIM_FIRE,
  hyperlink:{ url:'https://github.com/gitbrent/pptxgenjs', tooltip:'Visit Homepage' }
});

pptx.save('PptxGenJS-Sandbox_'+getTimestamp());
```

![image](https://cloud.githubusercontent.com/assets/19344990/26259404/bdd32662-3cc0-11e7-9629-f439f33c49d4.png)

To fix the issue you can do ::

line 2212 ::
`					if ( slideObj.hyperlink ) strSlideXml += '<a:hlinkClick r:id="rId'+ slideObj.hyperlink.rId +'"/>';`

Changed by
`					if ( slideObj.hyperlink ) strSlideXml += '<a:hlinkClick r:id="rId'+ slideObj.hyperlink.rId +'" tooltip="'+ (slideObj.hyperlink.tooltip ? decodeXmlEntities(slideObj.hyperlink.tooltip) : '') +'"/>';`

**Comment by gitbrent** [comment]
Hi @ZouhaierSebri ,

Thanks for catching this!

**Comment by ZouhaierSebri** [comment]
Hi @gitbrent ,

tested OK.

thank you for the quick fix.
