### ISSUE TITLE
Get pptxgenjs Object from a existing PPTX file

### ISSUE THREAD

**Issue by mariselvanm** [gitbrent/PptxGenJS#912]
### Category
- [ ] Enhancement

I know it's a big change. But could give more benefit for users. If we give a pptxgen js object from an existing pptx base64 could be better for updating the existing file.

**Comment by gitbrent** [comment]
Thanks for the suggestion.

This library is solely designed to produce OOXML presentations. Ingesting existing documents will never be implemented.
