### ISSUE TITLE
Feature Request - East Asian Font Face

### ISSUE THREAD

**Issue by Infinite-Lop** [gitbrent/PptxGenJS#916]
Powerpoint supports multiple text font face. This is done by setting fonts' "east asian name", which specifies the font name used for Asian text. Could this feature be added to the "AddText" function?

Also, I believe the sole East Asian font is an easy fix, but there's more handy features to add into the library.

↓: This is a table of font object properties copied from 「PowerPoint's AppleScript Dictionary」. More support of these properties is definitely going to be Brilliant!

| Property                    | Access  | Type                                                    | Description                                                  |
| --------------------------- | ------- | ------------------------------------------------------- | ------------------------------------------------------------ |
| ASCII name                  | get/set | [text](typeref:///text)                                 | Returns or sets the font used for Latin text; characters with character codes from 0 through 127. |
| auto rotate numbers         | get/set | [boolean](typeref:///boolean)                           | Returns or sets a value that specifies whether the numbers in a numbered list should be rotated when the text is rotated. |
| base line offset            | get/set | [real](typeref:///real)                                 | Returns or sets a value specifying the horizontaol offset of the selected font. |
| bold                        | get/set | [boolean](typeref:///boolean)                           | Returns or sets a value specifying whether the font should be bold. |
| caps type                   | get/set | [MsoTextCaps](typeref:///MsoTextCaps)                   | Returns or sets a value specifying how the text should be capitalized. |
| east asian name             | get/set | [text](typeref:///text)                                 | Returns or sets the font name used for Asian text.           |
| embedable                   | get     | [boolean](typeref:///boolean)                           | Returns a value indicating whether the font can be embedded in a page. |
| embedded                    | get     | [boolean](typeref:///boolean)                           | Returns a value specifying whether the font is embedded in a page. |
| emboss                      | get/set | [boolean](typeref:///boolean)                           |                                                              |
| equalize character height   | get/set | [boolean](typeref:///boolean)                           | Returns or sets a value specifying whether the text should have the same horizontal height. |
| fill format                 | get     | [fill format](typeref:///fill format)                   | Returns a value specifying the fill formatting for text.     |
| font color                  | get/set | list of [integer](typeref:///integer)                   |                                                              |
| font color theme index      | get/set | [MsoThemeColorIndex](typeref:///MsoThemeColorIndex)     | Returns or sets the color for the specified font.            |
| font name                   | get/set | [text](typeref:///text)                                 | Returns or sets a value specifying the font to use for a selection. |
| font name other             | get/set | [text](typeref:///text)                                 | Returns or sets the font used for characters whose character set numbers are greater than 127. |
| font size                   | get/set | [real](typeref:///real)                                 |                                                              |
| glow format                 | get     | [glow format](typeref:///glow format)                   | Returns a value specifying the glow formatting of the text.  |
| highlight color             | get/set | list of [integer](typeref:///integer)                   | Returns or sets the text highlight color for object.         |
| highlight color theme index | get/set | [MsoThemeColorIndex](typeref:///MsoThemeColorIndex)     | Returns or sets the specified text highlight color for object. |
| italic                      | get/set | [boolean](typeref:///boolean)                           |                                                              |
| kerning                     | get/set | [real](typeref:///real)                                 | Returns or sets a value specifying the amount of spacing between text characters. |
| line format                 | get     | [line format](typeref:///line format)                   | Returns a value specifiying the line formatting of the text. |
| reflection format           | get     | [reflection format](typeref:///reflection format)       | Returns a value specifying the reflection formatting of the text. |
| shadow format               | get     | [shadow format](typeref:///shadow format)               | Returns the value specifying the type of shadow effect for the selection of text. |
| soft edge format            | get/set | [MsoSoftEdgeType](typeref:///MsoSoftEdgeType)           | Returns or sets a value specifying the soft edge fromatting of the text. |
| spacing                     | get/set | [real](typeref:///real)                                 | Returns or sets a value specifying the spacing between characters in a selection of text. |
| strike type                 | get/set | [MsoTextStrike](typeref:///MsoTextStrike)               | Returns or sets a value specifying the strike format used for a selection of text. |
| subscript                   | get/set | [boolean](typeref:///boolean)                           | Returns or sets a value specifying that the selected text should be displayed a subscript. |
| superscript                 | get/set | [boolean](typeref:///boolean)                           | Returns or sets a value specifying that the selected text should be displayed a superscript. |
| transparency                | get/set | [real](typeref:///real)                                 |                                                              |
| underline                   | get/set | [boolean](typeref:///boolean)                           |                                                              |
| underline color             | get/set | list of [integer](typeref:///integer)                   | Returns or sets the 24-bit color of the underline for the specified font object. |
| underline color theme index | get/set | [MsoThemeColorIndex](typeref:///MsoThemeColorIndex)     | Returns a value specifying the color of the underline for the selected text. |
| underline style             | get/set | [MsoTextUnderlineType](typeref:///MsoTextUnderlineType) | Returns or sets a value specifying the underline style for the selected text. |
| word art styles format      | get/set | [MsoPresetTextEffect](typeref:///MsoPresetTextEffect)   | Returns or sets a value specifying the text effect for the selected text. |

**Comment by Infinite-Lop** [comment]
Also I'm just a beginner, but I'm trying to advance into the code base     hope to contribute some code~

**Comment by gitbrent** [comment]
Hi @Infinite-Lop 

Most of these options are currently supported: [Text API](https://gitbrent.github.io/PptxGenJS/docs/api-text#text-options)

I would think you could use `fontFace` to specify any Asian font.

**Comment by gitbrent** [comment]
Closing due to age, lack of response and requested feature already exists AFAIK.
