### ISSUE TITLE
isNumbered not working

### ISSUE THREAD

**Issue by gretacodes** [gitbrent/PptxGenJS#918]
Hello,

I am currently working on generating a pptx presentation, however, I cannot seem to get the slide numbers working. I have used isNumbered as per the documentation but it's not returning any values.

I am using the latest version of the library.

Could you please provide advice on how I could potentially implement slide numbers? I can't hard code them in as the length of presentation can vary. This is a pretty urgent matter, any advice would be highly appreciated.

Thank you

**Comment by gitbrent** [comment]
Hi @gretacodes 

Here's the API docs for [Slide Numbers](https://gitbrent.github.io/PptxGenJS/docs/usage-slide-options#slide-numbers)

There are several working examples under [demos](https://github.com/gitbrent/PptxGenJS/tree/master/demos) as well
