### ISSUE TITLE
Table Height and append Object one after another 

### ISSUE THREAD

**Issue by GauravAshara** [gitbrent/PptxGenJS#919]
Hello PPTXGenJS Team, 

I am trying to add two tables one after another. Both tables having dynamic data, So the number of rows are  different each new version of slide. 
I use autoPage : true but still, I am facing two issues. 
1.AutoPage true break page but I didn't get next table Y position. 
2.How to append slide object base on previous object height? (Object means Table,Textbox )

Thanks in Advance.

**Comment by gitbrent** [comment]
Hi @GauravAshara 

Sorry, but there's no way to know exactly where a table ends. The code only guesses - PowerPoint is the final determiner.
