### ISSUE TITLE
Add Bullet level/indentation

### ISSUE THREAD

**Issue by zeroxx1986** [gitbrent/PptxGenJS#92]
I'd like to use multi-level bulleted lists, but I'm struggling to find out how it works :)

Example of what I'd like to achieve:

- Test
- Test 2
  - Test 3 one level deeper
  - Test 4 one level deeper
    - Test 5 again one level deeper - but this is optional - at least to me :)
- Test 6

Test and Test2 of course works via the `bullet` attribute, but I don't know how to achieve to have entries one level deeper. I've tried to have a tab (\t) character in front - seemed intuitive :) - but it didn't work.

Thanks for the support in advance!

**Comment by ZouhaierSebri** [comment]
hi @gitbrent ,

This option is named "Increase list level"/"Decrease list level"
I have a proposed solution to get this result
![image](https://cloud.githubusercontent.com/assets/19344990/26451646/dd57bd7a-4154-11e7-8a53-be4d6d1752ec.png)

`var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
var slide = pptx.addNewSlide();

slide.addText(
[
{ text:'Test', options:{bullet:true} },
{ text:'Test 3 one level deeper', options:{bullet:true,indentLevel:1} },
{ text:'Test 4 one level deeper', options:{bullet:true,indentLevel:1} },
{ text:'Test 5 again one level deeper - but this is optional - at least to me :)', options:{bullet:true,indentLevel:2} },
{ text:'Test1', options:{bullet:true} },        
{ text:'Test2', options:{bullet:true} },
 ],
{ x:0, y:2, w:'100%', h:'100%'}
);

pptx.save('PptxGenJS-Test_Bullet_level');`

Solution:  add new option to text named indentLevel
line :: 1468
paragraphPropXml += ' marL="'+(342900+ (inch2Emu(0.5)* (textObj.options.indentLevel? textObj.options.indentLevel: 0)))+'" indent="-342900"';

line 1481::
paragraphPropXml += ' marL="'+(342900+ (inch2Emu(0.5)* (textObj.options.indentLevel? textObj.options.indentLevel: 0)))+'" indent="-342900"';

line  1487 ::
paragraphPropXml += ' marL="'+(228600+ (inch2Emu(0.5)* (textObj.options.indentLevel? textObj.options.indentLevel: 0)))+'" indent="-228600"';


You can add the 0.5 used as global variable can be changed too

**Comment by gitbrent** [comment]
Hi @zeroxx1986 ,

The `indentLevel` option for bullets was recently added.  The demo file includes examples.
