### ISSUE TITLE
Table Height for auto page second slide and Table first row not having space,

### ISSUE THREAD

**Issue by GauravAshara** [gitbrent/PptxGenJS#925]
I studied source code PPTGenJS(Very well coded), I found 2 small issues. 
1. Table Height For Auto Page: 
Suppose our slide height is 7.5 and the table Y starts with 5.5. So Table has space 2.0 and table height will be 2.0. After  2.0 height fill by rows it will create a new slide. In the new slide, It creates a table at given y position but its take a height 2.0 even new slide having space of 7.5

I think there is improvement  in gen-tables.js's getSlidesForTableRows function, 

`
				
		if (tabOpts.verbose) console.log('emuSlideTabH (in) ...... = ' + (emuSlideTabH / EMU).toFixed(1))
		// D: RULE: Use margins for starting point after the initial Slide, not `opt.y` (ISSUE#43, ISSUE#47, ISSUE#48)
		if (tableRowSlides.length > 1 && typeof tabOpts.autoPageSlideStartY === 'number') {
			emuSlideTabH = tabOpts.h && typeof tabOpts.h === 'number' ? tabOpts.h : presLayout.height - inch2Emu(tabOpts.autoPageSlideStartY + arrInchMargins[2])
		} else if (tableRowSlides.length > 1 && typeof tabOpts.newSlideStartY === 'number') {
			// @deprecated v3.3.0
			emuSlideTabH = tabOpts.h && typeof tabOpts.h === 'number' ? tabOpts.h : presLayout.height - inch2Emu(tabOpts.newSlideStartY + arrInchMargins[2])
		} else if (tableRowSlides.length > 1 && typeof tabOpts.y === 'number') {
			emuSlideTabH = presLayout.height - inch2Emu((tabOpts.y / EMU < arrInchMargins[0] ? tabOpts.y / EMU : arrInchMargins[0]) + arrInchMargins[2])
			// Use whichever is greater: area between margins or the table H provided (dont shrink usable area - the whole point of over-riding X on paging is to *increarse* usable space)
			if (typeof tabOpts.h === 'number' && emuSlideTabH < tabOpts.h) emuSlideTabH = tabOpts.h
		} else if (typeof tabOpts.h === 'number' && typeof tabOpts.y === 'number')
			emuSlideTabH = tabOpts.h ? tabOpts.h : presLayout.height - inch2Emu((tabOpts.y / EMU || arrInchMargins[0]) + arrInchMargins[2])`
			
2. Table first row not having space: (Auto Page : True)
Let take the above slide height (7.5) when we start the new table 7.48. So, In this case, our slide max height was 7.5 bsothere is no space in slide. It will create a new slide but in the background first slide having no row.SSoWhen it will iterate tableRowSlides(getSlidesForTableRows function) and throw below error 

addTable: Array expected! EX: 'slide.addTable( [rows], {options} );' (https://gitbrent.github.io/PptxGenJS/docs/api-tables.html) 

These two are just suggestions from my end. 

Keep doing good work

**Comment by gitbrent** [comment]
Hi @GauravAshara 

Thanks for the feedback.

I have demo code that works correctly with your scenario above (see pptxgenjs/demos/), so i'd need a test case to investigate further.

**Comment by gitbrent** [comment]
Closing due to age.
