### ISSUE TITLE
Feature request - set line shape postion startX/startY endX/endY

### ISSUE THREAD

**Issue by calebcbaker** [gitbrent/PptxGenJS#926]
Unless I'm missing something, I don't see a way to position lines. It would be great if ShapeLineProps took a startX/startY and endX/endY to position the line pointing from something, to something.

**Comment by ReimaFrgos** [comment]
The end position is defined using the `h` and `w` options.
The following will you you a line that starts at 1,1 and ends at 2,2.
`slide.addShape(pptx.ShapeType.line, { x:1,y:1,h:1,w:1, line: { color: "FF0000", width: 1 } });`

**Comment by gitbrent** [comment]
@ReimaFrgos is correct

```typescript
slide.addShape(pptx.ShapeType.line, { x:1,y:1,h:2,w:2, line: { color: "FF0000", width: 1 } });
```

we're following PowerPoint standards by using x/y and w/h:
![Screen Shot 2021-04-11 at 22 19 20](https://user-images.githubusercontent.com/7218970/114336238-1c37c400-9b14-11eb-845f-5c909f82cf17.png)
