### ISSUE TITLE
`pptx.stream()`: Uncaught TypeError: Cannot read property 'compression' of undefined

### ISSUE THREAD

**Issue by arbourd** [gitbrent/PptxGenJS#932]
With 3.5.0, this sample code no longer works. It looks like the examples haven't been updated if the options with `compression` key are now required for `stream()` like they look to be for `writeFile()`:

```js
pptx.stream()
  .then((data) => {
    console.log(data);
  });
```

In a Fiddle (open the console/inspector):
https://jsfiddle.net/hztm8p6k/1/

Solution is to provide `compression` option:

```js
pptx.stream({compression: false})
  .then((data) => {
    console.log(data);
  });
```

Is this supposed to be required?

**Comment by gitbrent** [comment]
Thanks for reporting this @arbourd 

The addition of `WriteBaseProps` to the stream() method was not implemented correctly and caused this issue. Apparently the node stream test was skipped or the feedback not checked as well, so apologies for the poor Q&A.

The issue has been fixed and the type defs file updated as well.

As v3.6.0 has major demo changes, I dont want to create a v3.5.1 release with the current codebase. However, we are moving to monthly releases starting this cycle, so a fix will be shipped soon. If you'd like to patch your current install, you can check the 2 changes above.
