### ISSUE TITLE
addText Bullet not creating list properly 

### ISSUE THREAD

**Issue by GauravAshara** [gitbrent/PptxGenJS#939]
I am trying too add multiple bullet points Within bullet points I need to add some bold and italic text. When I tried to added it create the wrong bullet list 
slide.addText(
    [
        { text:'Demo1',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
  		{ text: 'Demo2',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
  		{ text: 'Same line bold ',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bold: true,bullet: false } },
  		{ text: 'Smae line with plaintext',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bullet: false } },
  		{ text: 'same line bold and italic',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,italic: true,bold: true,bullet: false  } },
  		{ text: 'Same line Extra bold text',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bold: true,bullet: false } },
  		{ text: 'same line ending demo2 ;',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bullet: false } },
  		{ text: 'Demo3 New bullet',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
  		{ text: 'Demo4 New bullet',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
  		{ text: 'Extra paragrapha',options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: true } }	
  ],
    { x: 1, y: 1.0, w: "80%", h: 1.4, color: "ABABAB", margin: 1 }
);
Above Code Result 

![WrongBulletList](https://user-images.githubusercontent.com/10428513/115398375-b4186a80-a204-11eb-822f-b66ed2b8e925.png)

As You can see that Demo1 first bullet point Demo2 second but in this bullet point there is text with bold and italics and 3rd bullet point not starting it club with the extra text of Demo2 buttlet point. 

Result expected from above code
![CorrectResult](https://user-images.githubusercontent.com/10428513/115398798-25f0b400-a205-11eb-8cd3-22fc3734aba1.png)

**Comment by ReimaFrgos** [comment]
@GauravAshara you need to set `breakLine: false` instead of `breakLine: true` when adding the Demo2 text. 

Code should be:
```
slide.addText(
[
{ text:'Demo1',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
{ text: 'Demo2',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bullet: true } },
{ text: 'Same line bold ',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bold: true,bullet: false } },
{ text: 'Smae line with plaintext',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bullet: false } },
{ text: 'same line bold and italic',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,italic: true,bold: true,bullet: false } },
{ text: 'Same line Extra bold text',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bold: true,bullet: false } },
{ text: 'same line ending demo2 ;',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: false,bullet: false } },
{ text: 'Demo3 New bullet',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
{ text: 'Demo4 New bullet',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },
{ text: 'Extra paragrapha',options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: true } }
],
{ x: 1, y: 1.0, w: "80%", h: 1.4, color: "ABABAB", margin: 1 }
);
```

Result:
![image](https://user-images.githubusercontent.com/14120424/115480901-0cd81980-a27e-11eb-8d4d-0cda338276d1.png)

**Comment by GauravAshara** [comment]
Yes that correct but when see  Demo3 New bullet must be the new bulleted point as it had below code 

{ text: 'Demo3 New bullet',options:{ fontSize: 12,color: '0d0d0d',align: 'left',breakLine: true,bullet: true } },

I did different experiments with breakline, it works weird sometimes it creates bullet point on Demo2 or sometimes create  bullet point on Demo3 but not at both at the same time.

**Comment by ReimaFrgos** [comment]
@GauravAshara you need to breakLine on the line before the bullet.

```
slide.addText(
[
{ text: 'Demo1 ', options:{ fontSize: 12,color: '0d0d0d', align: 'left', breakLine: true,bullet: true } },
{ text: 'Demo2 ', options:{ fontSize: 12,color: '0d0d0d', align: 'left', breakLine: false,bullet: true } },
{ text: 'Same line bold ',options:{ fontSize: 12,color: '0d0d0d', align: 'left', breakLine: false, bold: true, bullet: false } },
{ text: 'Same line with plaintext ', options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: false, bullet: false } },
{ text: 'Same line bold and italic ', options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: false, italic: true, bold: true, bullet: false } },
{ text: 'Same line Extra bold text ', options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: false, bold: true, bullet: false } },
{ text: 'Same line ending demo2; ', options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: true, bullet: false } },
{ text: 'Demo3 New bullet ',options:{ fontSize: 12, color: '0d0d0d',align: 'left', breakLine: true, bullet: true } },
{ text: 'Demo4 New bullet ',options:{ fontSize: 12, color: '0d0d0d',align: 'left', breakLine: true, bullet: true } },
{ text: 'Extra paragraph ',options:{ fontSize: 12, color: '0d0d0d', align: 'left', breakLine: true } }
],
{ x: 1, y: 1.0, w: "80%", h: 1.4, color: "ABABAB", margin: 1 }
);
```
Produces:
![image](https://user-images.githubusercontent.com/14120424/115510603-85f16400-a2b2-11eb-8851-9b5f968beb24.png)

**Comment by GauravAshara** [comment]
I did used same cod but it show me below output 

![image](https://user-images.githubusercontent.com/10428513/115539832-12078980-a2bb-11eb-90e8-707bd43d9fce.png)
My PPTGenJs version 3.5.0

**Comment by ReimaFrgos** [comment]
@GauravAshara 
This https://jsfiddle.net/ReimaFrgos/q69m0gcd/ works fine for me on V3.5.0

What app / version are you opening the file in? It works fine for me in PowerPoint and Keynote

**Comment by GauravAshara** [comment]
@ReimaFrgos  Thank You very for your help
I figure out an issue base on your jsfiddle, When I removed bullet:false from bold,italic and extra text object. It works perfectly. 
![image](https://user-images.githubusercontent.com/10428513/115658832-2c8f4080-a357-11eb-9fb0-68bfe4111206.png)

**Comment by Pomelo1213** [comment]
我也出现了同样的问题，上面 jsfiddle 中保存下来的 ppt 展示仍然是错的，我的版本是 4.0.0

**Comment by LindelGitGut** [comment]
Hi it seems that onlyoffice / libreoffice has problems with bulletPoints, if you open the File generated from js Fiddle in microsoft powerpoint it works as expected

**Comment by Pomelo1213** [comment]
> the

你是对的，我用 Microsoft PowerPoint 打开确实是好的。
