### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by vanekar** [gitbrent/PptxGenJS#94]
Hello Brent

I had requested help on an animation feature to make text fadin and appear 1 by 1, can you please help me the comment i accidently closed but i do require that feature.

Regards
Anwar

**Comment by vanekar** [comment]
Hi Brent,

Something like the macro below


Sub TestShapeAnimation()

With ActivePresentation.Slides(1)
    Dim shp1, shp2, shp3 As Shape
    ' This sets the initial shape, with which we will test the animation sequences.
    Set shp1 = .Shapes.AddShape(msoShape12pointStar, 20, 20, 100, 100)

    ' This creates the animations.
    .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectFadedSwivel, , msoAnimTriggerAfterPrevious
    .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectPathBounceRight, , msoAnimTriggerAfterPrevious
    .TimeLine.MainSequence.AddEffect shp1, msoAnimEffectSpin, , msoAnimTriggerAfterPrevious

    ' This acquires the animation... [i]
    shp1.PickupAnimation

    ' [i] ... and applies it to another shape.
    Set shp2 = .Shapes.AddShape(msoShapeHexagon, 100, 20, 100, 100)
    shp2.ApplyAnimation

    ' Another shape creation / animation application.
    Set shp3 = .Shapes.AddShape(msoShapeCloud, 180, 20, 100, 100)
    shp3.ApplyAnimation

End With

**Comment by gitbrent** [comment]
[Closing due to age]
