### ISSUE TITLE
[BUG] addNotes function adding notes as an array of objects, parsed as [object Object] in notes field

### ISSUE THREAD

**Issue by karlolsonuc** [gitbrent/PptxGenJS#941]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.5.0

Please specify what version(s) of PowerPoint you are targeting: Powerpoint Online, Google Slides (they show identical behavior)

### Expected / Desired Behavior
addNotes should result in text notes in the Notes field of the Powerpoint file.

### Observed Behavior
addNotes function with any string results in [object Object] in the note field in any reader I've tried it in.

### Steps to Reproduce
1. use addNotes function to add any string to a pptxgen presentation.
2. trigger save presentation
3. open in either Powerpoint Online or Google Slides (possibly in Powerpoint itself?)
4. note [object Object] in the field

Here is a slightly modified version of the demo fiddle which replicates this behavior: https://jsfiddle.net/zj5m21ba/0/

Here is another version of the demo fiddle that bypasses addNotes but successfully generates notes: https://jsfiddle.net/zj5m21ba/1/

**Comment by ReimaFrgos** [comment]
I noticed the same issue yesterday after updating. It looks like the function was updated as part of the addTextDefinition update that took place for 3.5.0. 

Updated function:

```
function addNotesDefinition(target, notes) {
    target._slideObjects.push({
        _type: SLIDE_OBJECT_TYPES.notes,
        text: [{ text: notes }],
    });
}
```

All the downstream code still seems to be expecting a string though, so reverting back to the following restores the previous behaviour:

```
function addNotesDefinition(target, notes) {
    target._slideObjects.push({
        _type: SLIDE_OBJECT_TYPES.notes,
        text: notes,
    });
}
```

**Comment by gitbrent** [comment]
Thanks @karlolsonuc and @ReimaFrgos

Whoops. I neglected to check Notes functionality before v.3.5.0 was released.

Fixed now:
![Screen Shot 2021-04-22 at 22 21 48](https://user-images.githubusercontent.com/7218970/115813874-a48e5280-a3b9-11eb-9e50-187ad70ce5d4.png)
