### ISSUE TITLE
Question: Is there any way to draw a bell curve shape?

### ISSUE THREAD

**Issue by gurdeep-sourcefuse** [gitbrent/PptxGenJS#946]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by gurdeep-sourcefuse** [comment]
Referenced video and image of the bell curve: https://www.youtube.com/watch?v=dysqb2vEkh0
![image](https://user-images.githubusercontent.com/78344911/116832524-c3b78c00-abd2-11eb-9ecf-44e66e19de54.png)

**Comment by gitbrent** [comment]
Hi @gurdeep-sourcefuse 

As the video shows, it's not a standard shape so it must be drawn manually.

An upcoming change will allow this: [Pull #872](https://github.com/gitbrent/PptxGenJS/pull/872)

**Comment by gitbrent** [comment]
Implemented via https://github.com/gitbrent/PptxGenJS/pull/872
