### ISSUE TITLE
Update/remove slides ?

### ISSUE THREAD

**Issue by hmendezm** [gitbrent/PptxGenJS#947]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. 

We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://gitbrent.github.io/PptxGenJS/docs/installation.html) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.4.0        ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

Hi guys, thanks for your work on this library. I have a couple of questions

1. Can I update the existing slide base on the index/slice name? I notice you have a private slice variable where you store the new slice and I am wondering if you have a method to update the existing Slide. In my case, the user updates the slice using a wizard and I need to keep updating the slide every time that s/he clicks update.
2. is it a way to remove the slide from the pptxGen object?

Best
H. Méndez

**Comment by gitbrent** [comment]
Hi @hmendezm 

Thanks for the feedback, hope you find the library useful.

In answer to your questions: no and no. You'll need to store the users configuration in variables until its time to generate the presentation. The API is not meant to be used in real-time as changes are made.
