### ISSUE TITLE
barDir is not working

### ISSUE THREAD

**Issue by Shankar000536** [gitbrent/PptxGenJS#95]
Hi,
slide.addChart( pptx.charts.BAR, dataChartBar,{barDir:'h'} );

Im using the above code. But its not working.

can you please help.

thanks,
shiva

**Comment by Shankar000536** [comment]
Is there any way to remove Gridlines in bar chart?

**Comment by Shankar000536** [comment]
Need Horizontal bar chart 
slide.addChart( pptx.charts.BAR, dataChartBar,{barDir:'h'} );
Its not working.

**Comment by gitbrent** [comment]
Hi @Shankar000536 ,

Thanks for letting me know about the `barDir` issue.

I'd written the README incorrectly, and have fixed it now.  The options should be `bar` (horiz) or `col` (vertical).

**Comment by gitbrent** [comment]
Other Questions:
* Using `path` to add remote images (images from a different server) is not currently supported.
* More Chart gridline and axis options are forthcoming
