### ISSUE TITLE
[QUESTION] Reuse off masterslides

### ISSUE THREAD

**Issue by ericlaaper** [gitbrent/PptxGenJS#956]
Reuse off  MasterSlides
First : Great Library and still getting better. 
I made more than 20 presentations with the library and make use off the MasterSlide function. Copying the masterslides over from one codebase  to the other. I am using Vue. 
Is there a way to make a central template file which I can import over and over In stead off copying from one code base to the other. Help is highly appreciated! Cheers, Eric

**Comment by gitbrent** [comment]
Hi @ericlaaper 

Thanks for the feedback.

I also share master slide defs across apps using a simple file (eg: 'SlideMasters.tsx') that contains all of the `pptx.defineSlideMaster()` method calls.

Are there any impediments to this? What kind of solution were you thinking of?

**Comment by ericlaaper** [comment]
Hi tnx for your reply? I am struggling with this. I tried the same approach with a separate Vue component and also with a Mixin but both are not working. The mixin is working before the component is created. Can you give me an example off the SlideMaster.tsx
Maybe I can figure something out. Tnx a lot. Cheers, Eric

**Comment by ericlaaper** [comment]
Got it working!!!
I made  a Mixin with a 2 dataobjects. Import the Mixin in the component. 
import defaultslide from "@/mixin/defaultslide";
 mixins: [defaultslide],
 
An in the methods I define the masterslides like
pres.defineSlideMaster(this.data);
pres.defineSlideMaster(this.data2);

This works fine! AS example I added the mixin

export default {
  data() {
    return {
      data: {
        title: "MASTER_SLIDE",
        bkgd: "FFFFFF",
        objects: [
          {
            text: {
              text: "-test master 1",
              options: {
                x: 0.6,
                y: 5.23,
                w: 6.5,
                fontFace: "Arial",
                fontSize: 6.8,
                charSpacing: 10,
                color: "9D968D",
                valign: "top",
              },
            },
          },
        ],
        slideNumber: {
          x: 0.42,
          y: 5.23,
          fontFace: "Arial",
          fontSize: 6.8,
          color: "9D968D",
        },
      },
      data2: {
        title: "MASTER_SLIDE2",
        bkgd: "FFFFFF",
        objects: [
          {
            text: {
              text: "- test master 2",
              options: {
                x: 0.6,
                y: 5.23,
                w: 6.5,
                fontFace: "Arial",
                fontSize: 6.8,
                charSpacing: 10,
                color: "9D968D",
                valign: "top",
              },
            },
          },
        ],
        slideNumber: {
          x: 0.42,
          y: 5.23,
          fontFace: "Arial",
          fontSize: 6.8,
          color: "9D968D",
        },
      }
    };
  },
}

**Comment by ericlaaper** [comment]
Thanks for your help!

**Comment by gitbrent** [comment]
Glad you've got the solution you needed!
