### ISSUE TITLE
How can I create Graph title with different font styles

### ISSUE THREAD

**Issue by voletiswaroop** [gitbrent/PptxGenJS#960]
Im using PptxGenJS to create PPTX files from scratch using reactJs. I need to create a graph title with different font styles.

Ex: **Hi** *Hello*

I tried using css or html tags to pass the information through respective PptxGenJS attributes but its not happening instead its printing html values.

```
Ex: 
let graphOptions = {
    title: "<b>Collections</b> <i>Posted</i>" 
}
```
Also how I add fontbold to valAxisTitle or catAxisTitle

**Comment by gitbrent** [comment]
Sorry, that's not supported as of now, only a single text string formatted as a whole is available.
