### ISSUE TITLE
SVG in node.js doesn't work

### ISSUE THREAD

**Issue by Evgenus** [gitbrent/PptxGenJS#963]
Hi.

I'm trying to build a presentation on the server-side (express) containing SVGs. 
Tried on versions 3.0, 3.3, 3.6 the result is the same. I've got an image inside of the presentation indicating an error. Also doesn't work in tests.  It is confusing because I see lots of issues fixed and also some remarks in comments and in the changelog.

![зображення](https://user-images.githubusercontent.com/379412/122028653-e8f40880-cdd4-11eb-8aa0-68b6efd43dc0.png)

![зображення](https://user-images.githubusercontent.com/379412/122028758-02955000-cdd5-11eb-8706-c67b3ee51891.png)

Can you please clarify if that function should work? Maybe I'm doing something wrong? Maybe missing some dependency? 

Will appreciate any reply.

**Comment by tjohannto** [comment]
Maybe this helps. It works for me like this:

```
function b64EncodeUnicode(str) {
return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function (match, p) {
	return String.fromCharCode(+("0x" + p));
}));
}
const serializer = new XMLSerializer()
, clone = node.cloneNode(!0) //node equals the svg html node
, xmlns = "http://www.w3.org/2000/xmlns/"
, xlinkns = "http://www.w3.org/1999/xlink"
, svgns = "http://www.w3.org/2000/svg";
clone.setAttributeNS(xmlns, "xmlns", svgns);
clone.setAttributeNS(xmlns, "xmlns:xlink", xlinkns);
const dataStr = 'data:image/svg+xml;base64,' + b64EncodeUnicode(serializer.serializeToString(clone));
```
The string created I can then use in imgOptions Object.

```
const imgOptions = {};
imgOptions.x = posX;
imgOptions.y = posY;
imgOptions.w = chartWidth;
imgOptions.h = chartHeight;
imgOptions.data = dataStr ;
```

I don't know what the demo does but this creates working Presentations with v 3.4.0

**Comment by gitbrent** [comment]
@Evgenus - i'm not seeing this issue, the node Image demo works fine.

Looking at the demo code, it refs 2 SVGs: a base64 one (which should always work) and a remove file:
`wikimedia_svg: { path: "https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@master/demos/common/images/lock-green.svg" }`

```javascript
// BOTTOM-RIGHT:
slide.addText("Type: SVG", { x: 9.5, y: 3.3, w: 4.0, h: 0.4, color: "0088CC" });
slide.addImage({ path: IMAGE_PATHS.wikimedia_svg.path, x: 9.5, y: 3.8, w: 2.0, h: 2.0 }); // TEST: `path`
slide.addImage({ data: SVG_BASE64, x: 11.1, y: 5.1, w: 1.5, h: 1.5 }); // TEST: `data`
```

Ensure your `demos` directly has all the modules files, etc.

```bash
=> node demo.js Image -local


--------------------==~==~==~==[ STARTING DEMO... ]==~==~==~==--------------------

* pptxgenjs ver: 3.7.0-beta-20210521-2050
* save location: /Users/brentely/GitHub/PptxGenJS/demos/node

--------------------==~==~==~==[ ...DEMO COMPLETE ]==~==~==~==--------------------


EX1 exported: PptxGenJS_Demo_Image_20210706193029030.pptx
```

![Screen Shot 2021-07-06 at 14 32 07](https://user-images.githubusercontent.com/7218970/124657592-517c5580-de68-11eb-82c7-742a1fef978e.png)

**Comment by haakenlid** [comment]
Can this issue be reopened? 

I've found the cause of this problem and opened a PR #1315 to fix it.

**Comment by haakenlid** [comment]
Steps to confirm that this is a bug in PpptxGenJS:
 
```bash
 cd demos/node
 npm install
 node demo.js Image
 unzip PptxGenJS_Demo_Image_<timestamp>.pptx 
```
In the folder `demos/node/ppt/media` you will find all images embedded in the demo pptx file
 
![image](https://github.com/gitbrent/PptxGenJS/assets/1686266/39c02ddd-26f5-4e48-8d7f-7949eb78524e)

The file `Image-1-7.png` looks fine, since it's really the same file as `Image-1-8.svg` only renamed.
The file `Image-1-9.png` is a real png created from the PptxGenJS placeholder IMG_BROKEN. This will be shown in LibreOffice Impress instead of `Image-1-10.svg`.

**Comment by caike-venngage** [comment]
hey @Evgenus were you able to make this work? node version doesn't work for me either. I'm using v3.12

**Comment by afishhhhh** [comment]
> Steps to confirm that this is a bug in PpptxGenJS:
> 
>  cd demos/node
>  npm install
>  node demo.js Image
>  unzip PptxGenJS_Demo_Image_<timestamp>.pptx 
> In the folder `demos/node/ppt/media` you will find all images embedded in the demo pptx file
> 
> ![image](https://github.com/gitbrent/PptxGenJS/assets/1686266/39c02ddd-26f5-4e48-8d7f-7949eb78524e)
> 
> The file `Image-1-7.png` looks fine, since it's really the same file as `Image-1-8.svg` only renamed. The file `Image-1-9.png` is a real png created from the PptxGenJS placeholder IMG_BROKEN. This will be shown in LibreOffice Impress instead of `Image-1-10.svg`.

same issue  @gitbrent
