### ISSUE TITLE
Background in master template broken by 3.6.0

### ISSUE THREAD

**Issue by viral-sh** [gitbrent/PptxGenJS#968]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v3.6.0 ]

Please specify what version(s) of PowerPoint you are targeting: [         ]

### Expected / Desired Behavior / Question
When we add "path" to the background property of a slide master, it should add the image at the path as background.

```.js
  pptx.defineSlideMaster({
    title: "mytitle",
    background: { fill: theme.background1, path: "../bg-image.jpeg" },
    ...
```

### Observed Behavior
Above worked till v3.5.0. But when we upgraded to v3.6.0 it's broken. It triggers repair PPT dialog and does not even add the image.

### Steps to Reproduce
- Create a master and add a background image to it via background.path property.
- Create a PPT and try to open it.
- Repair PPT dialog should trigger and background image should not be visible

**Comment by gitbrent** [comment]
Thanks @viral-sh 

The recent changes to the `background` prop allowed for more than one `<p:bg>` tag to be created in the `slideLayoutN.xml` files, which caused the warning.

The API now supports more than 1 background prop correctly.
