### ISSUE TITLE
Bullet:false property forcefully adds a line break to text

### ISSUE THREAD

**Issue by sangramjagtap** [gitbrent/PptxGenJS#97]
Hi @ZouhaierSebri , @gitbrent 

Exporting the following 2 codes to PPTX, leads to a different outputs

```
var pptx = new PptxGenJS(); 
pptx.setLayout('LAYOUT_WIDE'); 
var slide = pptx.addNewSlide(); 

slide.addText( [ 
{ text:'Hello ', options:{bold: true } }, 
{ text:'World ', options:**{bold: true }** }
], 
{ x:0, y:0, w:'100%', h:'100%'} 
); 
pptx.save('on same line');
```

![image](https://cloud.githubusercontent.com/assets/17859100/26577784/3073450c-454b-11e7-9c4e-200f14e72747.png)

--------------------------------------------------------------------------------------------------------------

```
var pptx = new PptxGenJS(); 
pptx.setLayout('LAYOUT_WIDE'); 
var slide = pptx.addNewSlide(); 

slide.addText( [ 
{ text:'Hello ', options:{bold: true } }, 
{ text:'World ', options:**{bold: true, bullet: false}** }
], 
{ x:0, y:0, w:'100%', h:'100%'} 
); 
pptx.save('on different lines');
```

![image](https://cloud.githubusercontent.com/assets/17859100/26577970/ce829bc6-454b-11e7-912f-c1c7c0fa028a.png)

---------------------------------------------------------------------------------------------------
In 2nd example, I added bullet: **false** property. Which leads to a forced line break.

**Comment by gitbrent** [comment]
Hi @sangramjagtap ,

Yes, that's done to preserve formatting, fix indentation, etc.  Is there so output you cannot achieve or what's the issue?

**Comment by ZouhaierSebri** [comment]
hi @gitbrent ,
bullet default value is false, but when we send it from option with false a line break is added.

**Comment by sangramjagtap** [comment]
Hi @gitbrent ,
Could you please make the required changes?

Thanks in advance!
