### ISSUE TITLE
invertedColors: not working any more

### ISSUE THREAD

**Issue by ericlaaper** [gitbrent/PptxGenJS#970]
HI, I have got a problem with the inverted colors in bar chart

Everything works except for this. In the past, same code worked perfect.
Underneath my code for the options off the graph

let optionsGraph = {
        x: 0.25,
        y: 0.85,
        w: 7,
        h: 4,
        barDir: "bar",
        barGrouping: "stacked",
        valGridLine: {
          color: "EFF0F1",
        },
       catAxisOrientation: "minMax",
        catAxisLabelColor: this.colors.colorB,
        catAxisTitleColor:this.colors.colorA,
        catAxisLabelFontFace: "Calibri",
        catAxisLabelFontSize: 14,
        catAxisLineShow: false,
        valAxisLabelFontColor: this.colors.colorA,
        valAxisLabelFontBold: false,
        catAxisLabelPos: 'low',
        dataLabelColor: this.colors.colorA,
        showValue: false,
        chartColors: [this.colors.colorC],
        invertedColors: [this.colors.colorD],
        titleColor: "red",
        titleFontFace: "Arial",
        titleFontSize: 24,
        valAxisMaxVal: 100,
        valAxisMinVal: -100, 

};
Then I add the chart by:

slide1.addChart(pptx.charts.BAR, arrayStatementA, optionsGraph);
the optiongraph is stating an error in my IDE  which removes when I remove InvertedColors form options.
removing the bracet from InvertedColors makes the error go away but it not makes InvertedColors working.

I also tried with just colornumber in stead off the variable same problem negative values have the same color as positive values.

**Comment by ericlaaper** [comment]
![Schermafbeelding 2021-06-27 om 22 08 23](https://user-images.githubusercontent.com/20456800/123558009-510efb00-d794-11eb-8786-13c668feb399.png)


this is the chart what is produced

**Comment by ericlaaper** [comment]
HI there, Any news on this?

**Comment by ReimaFrgos** [comment]
I'm assuming you were using version 3.3.1 or older since you mentioned it used to work.

As far as I can tell this was broken in 3.4.0 as part of PR #821

Pretty sure the fix is to change the last line here to > 0 so that you can have a single element array.

```
 if ((chartType === CHART_TYPE.BAR || chartType === CHART_TYPE.BAR3D) &&
data.length === 1 &&
opts.chartColors !== BARCHART_COLORS &&
opts.chartColors.length > 1) {
```

As an interim fix, you can just create an array with the same color twice:
```   
chartColors: ["ffff00","ffff00"],
invertedColors: ["00ff00","00ff00"],
```

**Comment by ericlaaper** [comment]
HI you are right, the older version was 3.3.1  
Great!! The Interim fix is working. Do I need to make the array content as much same colors as there are values or is 2 enough? 

Thanks a lot. 
Have a nice day!
Eric

**Comment by ReimaFrgos** [comment]
@ericlaaper two is enough assuming you want the same color for all positives and all negatives.

**Comment by leonyah** [comment]
I just hit the same problem.  

I believe proper fix is 


```
	if (
			(chartType === CHART_TYPE.BAR || chartType === CHART_TYPE.BAR3D) &&
			data.length === 1 &&
			**(
				(opts.chartColors && opts.chartColors !== BARCHART_COLORS && opts.chartColors.length > 1) ||
				(opts.invertedColors && opts.invertedColors.length)
			)**
	) {

```


There is a typescript Typescript definition problem too:
```
export interface IChartPropsBase {
 ...
 chartColors?: HexColor[]
  ...
  invertedColors?: **string**
}
```
invertedColors must also be of type "HexColor[]" not string

**Comment by leonyah** [comment]
I created a pull request with the fix, now allowing rendering of negative bars with invertedColor even if only one chartColor is specified.  https://github.com/gitbrent/PptxGenJS/pull/1004
I also fixed the Typescript definition of invertedColors to be an array
