### ISSUE TITLE
[QUESTION] Table Columns width text wrap 

### ISSUE THREAD

**Issue by GauravAshara** [gitbrent/PptxGenJS#977]
Hi PPTXGenJS Team, 

I face an issue with table columns width, when I set columns width with let say 1 inch. So that columns hold 20 length characters.

If column text having 2 capital letters at that there is no wrap text . 
If column text having 10 capital letters at that there is  wrap text (which is not detected by below logic) 
```javascript
function parseTextToLines(cell: TableCell, colWidth: number): string[] {
let CHAR = 2.2 + (cell.options && cell.options.autoPageCharWeight ? cell.options.autoPageCharWeight : 0) // Character Constant (An approximation of the Golden Ratio)
let CPL = (colWidth * EMU) / (((cell.options && cell.options.fontSize) || DEF_FONT_SIZE) / CHAR) // Chars-Per-Line
let arrLines = []
let strCurrLine = ''

// A: Allow a single space/whitespace as cell text (user-requested feature)
if (cell.text && cell.text.toString().trim().length === 0) return [' ']

// B: Remove leading/trailing spaces
let inStr = (cell.text || '').toString().trim()

// C: Build line array
inStr.split('\n').forEach(line => {
	line.split(' ').forEach(word => {
		if (strCurrLine.length + word.length + 1 < CPL) {
			strCurrLine += word + ' '
		} else {
			if (strCurrLine) arrLines.push(strCurrLine)
			strCurrLine = word + ' '
		}
	})

	// All words for this line have been exhausted, flush buffer to new line, clear line var
	if (strCurrLine) arrLines.push(strCurrLine.trim() + CRLF)
	strCurrLine = ''
})

// D: Remove trailing linebreak
arrLines[arrLines.length - 1] = arrLines[arrLines.length - 1].trim()

return arrLines
}
```

I tried autoPageCharWeight but it didn't help me with all cases. If there is a way to calculate line per character that will help.

**Comment by gitbrent** [comment]
The `autoPageCharWeight` and `autoPageLineWeight` properties are the only adjustment mechanisms.

There is no guaranteed way to calculate line height that i've ever seen. The jsPDF project uses a rather complex formula if you'd like to copy it.

**Comment by GauravAshara** [comment]
Thanks for your response. @gitbrent 
One Improvement, During debug I found column width not subtracting margin width.
