### ISSUE TITLE
titleAlign doesn't work in any chart

### ISSUE THREAD

**Issue by hhq365** [gitbrent/PptxGenJS#978]
It always display in center of the chart header

**Comment by gitbrent** [comment]
Cannot reproduce.

This works fine:
```javascript
	slide.addChart(pptx.charts.PIE, dataChartPieLocs, {
		x: 9.8,
		y: 0.5,
		w: 3.2,
		h: 3.2,
		dataBorder: { pt: "1", color: "F1F1F1" },
		showLegend: true,
		legendPos: "t",
		legendFontSize: 14,
		showLeaderLines: true,
		showTitle: true,
		title: "Right Title & Large Legend",
		titleAlign: "right",
		titlePos: { x: 0, y: 0 },
	});
```

![Screen Shot 2021-07-19 at 23 50 41](https://user-images.githubusercontent.com/7218970/126263761-55393e58-f04e-408c-9f9a-a712aa20172c.png)

**Comment by hhq365** [comment]
OK.I thought it means the title label position relative to chart.thanks

**Comment by gitbrent** [comment]
It sounds like you're looking for `legendPos` - where the legend is in reference to the chart itself.

[Chart API](https://gitbrent.github.io/PptxGenJS/docs/api-charts)
