### ISSUE TITLE
chart property "border" dont effect for outer border?

### ISSUE THREAD

**Issue by hhq365** [gitbrent/PptxGenJS#981]
![image](https://user-images.githubusercontent.com/6645976/125375021-db717480-e3ba-11eb-9936-1e5b545acab9.png)
I set the chart property border ,Then it take effect on the inner border.Can I set the border style of outer border in charts?
And the background has the same issue.

**Comment by gitbrent** [comment]
Issue #1015 fixes this as you can now use `fill` and `border` on either/or `plotArea` or `chartArea`

**Comment by gitbrent** [comment]
Issue #1015 fixes this as you can now use `fill` and `border` on either/or `plotArea` or `chartArea`
