### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by costaalvesgabriel** [gitbrent/PptxGenJS#982]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.6.0    ]

I have a problem with CORS

Uncaught (in promise) ERROR! Unable to load image (xhr.onerror):

Access to XMLHttpRequest at 'https://picviewer.umov.me/Pic/GetImage?id=294989539&token=2e842d8b477b964a8147df73d2b573a0' from origin 'https://analyticsdev.1uptech.com.br' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I´m using slide.addImage({ path: "https://picviewer.umov.me/Pic/GetImage?id=294989539&token=2e842d8b477b964a8147df73d2b573a0"});

Any suggestions on how to solve?

**Comment by gitbrent** [comment]
Sorry, CORS issues are outside of support scope.

**Comment by matt88120** [comment]
Have the same issue. Did you find a solution ?

**Comment by costaalvesgabriel** [comment]
> Have the same issue. Did you find a solution ?

Yes. I needed to convert image to base64.

slide.addImage({data: "data:image/gif;base64,R0lGODlhAQABAIABAP..." });
