### ISSUE TITLE
[BUG]Table layout broken with auto pagination and merged cells

### ISSUE THREAD

**Issue by Barrywww** [gitbrent/PptxGenJS#983]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

Not sure whether this is a bug, or a potential enhancement to be implemented in the future. Please correct me if so.

### Version

Please specify what version of the library you are using: [ v3.6.0 ]

Please specify what version(s) of PowerPoint you are targeting: [PowerPoint for Mac v16.50]

### Expected / Desired Behavior
Basically, we have a table with different columns of merged cells (like a tree structure).  We have some value that belongs to several types, which further belongs to several categories. As the following table shows.
![image](https://user-images.githubusercontent.com/36621849/125436675-9a661d91-afe8-4c96-a31e-34d47f04b16d.png)

When data overflows one page, the desired table on the next page should look like this table, which contains the remaining merged cells from the previous page.
![image](https://user-images.githubusercontent.com/36621849/125437390-4c9f76e7-4b6a-4656-984b-e94c67ecd22b.png)

### Observed Behavior
This is the observed behavior. It seems that when doing pagination, the library is only filling in the new table with solely the data from the previous row without tracing back further to the starting point where the merged cells are defined. (If I got it right, the merged cells are defined at the starting row of it.)
![image](https://user-images.githubusercontent.com/36621849/125436907-be6359f0-6405-4a55-be9d-5130ca18ba8d.png)

### Steps to Reproduce
Running the following code will reproduce the situation.
```
  let taboptions = { x: 0.6, y: 1.3, w: "90%", h: 3, rowH: 0.1, margin: 0, fontSize: 12, align: "center", valign: "middle", border: { pt: "1" }, autoPage: true };

  let testRows = [
    [
      {text: "Category 1", options: {rowspan: 20}},
      "test"
    ]
  ]
  for (let i=0; i<19; i++){
    testRows.push(["test"])
  }
  slide.addTable(testRows, taboptions)
```

**Comment by Barrywww** [comment]
Any updates on this issue? @gitbrent

**Comment by gitbrent** [comment]
Closing this as table auto-paging was completely rewritten in release 3.8.0

**Comment by tallajobmails** [comment]
Hi Brent,

I am facing same issue and we are using version "^3.9.0" . Any update on this?

Thank you 
~TK
