### ISSUE TITLE
Possible to change an existing presentation?

### ISSUE THREAD

**Issue by realtimecarsten** [gitbrent/PptxGenJS#99]
Is it possible to open an existing presentation and add slides to it?

I would like to use pptxgenjs, but need to generate presentations that follow the company rules.
Instead of recreating the company master (and I would have no idea if that is possible at all) it would be simpler to just use an existing empty presentation.

**Comment by gitbrent** [comment]
Hi @realtimecarsten ,

Ingesting a PPT is not something the library is capable of.

I also produce PowerPoints for a large corporation and it was pretty easy to reproduce our corporate  style using the [Master Slide](https://github.com/gitbrent/PptxGenJS#master-slides-and-corporate-branding) features provided.

Check out the `dist/pptxgen.masters.js` file and the `examples/pptxgenjs-demo.html` to see how to setup a similar style to what you've got now.
