### ISSUE TITLE
[QUESTION] Is there a way to customize bullet color 

### ISSUE THREAD

**Issue by matt88120** [gitbrent/PptxGenJS#992]
Hi,

Is there a way to customize the color of a bullet, regardless of the color of the text ?

### Version
Latest version

Thank you for your feedback!

**Comment by ReimaFrgos** [comment]
You can separate the bullet from the text using a non breaking space character that allows you to style. Something like this:
```
slide.addText(
	[
		{ text: "\u200B", options: { color: pptx.colors.ACCENT1, bullet: true, breakLine: false } },
		{ text: "This is my first bullet text", options: { } },
		{ text: "\u200B", options: { color: pptx.colors.ACCENT1, bullet: true, breakLine: false } },
		{ text: "This is my second bullet text", options: { } },
		{ text: "\u200B", options: { color: pptx.colors.ACCENT1, bullet: true, breakLine: false } },
		{ text: "This is my third bullet text", options: { } },
	],
		{ x: 1, y: 1, w: 5.75, h: 1.5, fontFace: "Arial", fontSize: 12, color:pptx.colors.TEXT1 }
);
```
Visually it will work, but it's not true bullet styling, so if you need to add additional bullet points to the output they revert to the default color

**Comment by gitbrent** [comment]
@matt88120 from what i can tell, Reima's answer is the way to do it.
