### ISSUE TITLE
Adding SVG with text creats broken letterspaceing 

### ISSUE THREAD

**Issue by kairichard** [gitbrent/PptxGenJS#995]
### Category
- [ ] Enhancement
- [x] Bug - not sure
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.4
Please specify what version(s) of PowerPoint you are targeting: Latest

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Observed Behavior
When adding an SVG to a slide the result has distorted fonts that are not pleasant to read. 
![Screenshot 2021-08-31 at 12 46 27](https://user-images.githubusercontent.com/35398/131489946-ef837ffa-cb8b-4bd2-aba1-6b8256544f78.png)

Using the convert to shape the functionality of PowerPoint seems to fix the problem, but that is undesired because I want to automate the entire generation of slides.

![Screenshot 2021-08-31 at 12 46 34](https://user-images.githubusercontent.com/35398/131490377-6ae7a46a-10e4-4ec4-85e4-ac71462a7fbe.png)

![Screenshot 2021-08-31 at 12 46 41](https://user-images.githubusercontent.com/35398/131490389-8515563e-c84e-4dc4-badb-f713c2217b56.png)

### Expected / Desired Behavior / Question

I would expect the font to be rendered correctly, without the need to manually convert them to a shape. 

### Steps to Reproduce
Sadly I currently don't have an isolated example that reproduces this behavior. I will try to get that in later.

Thanks 🙏

**Comment by gitbrent** [comment]
@kairichard - I don't control any of these properties, i merely pass the SVG code to the XML tags that comprise the PowerPoint document... perhaps PPT is using other fonts or some similar behavior.
