### ISSUE TITLE
Add justify option to Text align options

### ISSUE THREAD

**Issue by salievn** [gitbrent/PptxGenJS#998]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: 3.6.0
Please specify what version(s) of PowerPoint you are targeting: >2016

### Expected
The last and previous version of the API reference for Text state that **align** option has 3 differents values **left** or **center** or **right**. 

The enhancement is to add the justify way to format text block as a fourth possibility.

**Comment by gitbrent** [comment]
Hi @salievn 

```javascript
export enum AlignH {
	'left' = 'left',
	'center' = 'center',
	'right' = 'right',
	'justify' = 'justify',
}
```

Alignment options are specified via `TextBaseProps.align` which allows the `AlignH` enum shown above.

Justify already exists as an option and works correctly.
